PhasicFlow: geometricRegion< GeomType > Class Template Reference
geometricRegion< GeomType > Class Template Reference
Public Types
using GeometryType = GeomType
Public Member Functions
TypeInfoTemplateNV11 ("geometricRegion", GeomType)
geometricRegion (const dictionary &dict)
~geometricRegion ()=default
bool isInside (const realx3 &p) const
realx3 peek () const
const auto & minPoint () const
const auto & maxPoint () const
bool read (const dictionary &dict)
bool write (dictionary &dict) const
Private Attributes
GeomType geom_
realx3 minPoint_
realx3 maxPoint_
uniformRandomReal random_
Static Private Attributes
static constexpr uint32 maxTries_ = 100
Detailed Description
template<typename GeomType>
class pFlow::geometricRegion< GeomType >
Definition at line 33 of file geometricRegion.hpp.
Member Typedef Documentation
GeometryType
using GeometryType = GeomType
Definition at line 37 of file geometricRegion.hpp.
Constructor & Destructor Documentation
geometricRegion()
geometricRegion (const dictionary & dict) explicit
Definition at line 22 of file geometricRegion.cpp.
References geometricRegion< GeomType >::geom_, geometricRegion< GeomType >::maxPoint_, and geometricRegion< GeomType >::minPoint_.
~geometricRegion()
~geometricRegion () default
Member Function Documentation
TypeInfoTemplateNV11()
TypeInfoTemplateNV11 ("geometricRegion< GeomType >" , GeomType)
isInside()
bool isInside (const realx3 & p) const inline
Definition at line 32 of file geometricRegion.cpp.
peek()
pFlow::realx3 peek inline
Definition at line 39 of file geometricRegion.cpp.
References pFlow::endl(), fatalErrorInFunction, and fatalExit.
minPoint()
const auto& minPoint () const inline
Definition at line 65 of file geometricRegion.hpp.
References geometricRegion< GeomType >::minPoint_.
Referenced by PeakableRegion< GeomType >::minPoint().
maxPoint()
const auto& maxPoint () const inline
Definition at line 70 of file geometricRegion.hpp.
References geometricRegion< GeomType >::maxPoint_.
Referenced by PeakableRegion< GeomType >::maxPoint().
read()
bool read (const dictionary & dict)
Definition at line 57 of file geometricRegion.cpp.
write()
bool write (dictionary & dict) const
Definition at line 64 of file geometricRegion.cpp.
Member Data Documentation
geom_
GeomType geom_ private
Definition at line 41 of file geometricRegion.hpp.
Referenced by geometricRegion< GeomType >::geometricRegion().
minPoint_
realx3 minPoint_ private
Definition at line 43 of file geometricRegion.hpp.
Referenced by geometricRegion< GeomType >::geometricRegion(), and geometricRegion< GeomType >::minPoint().
maxPoint_
realx3 maxPoint_ private
Definition at line 45 of file geometricRegion.hpp.
Referenced by geometricRegion< GeomType >::geometricRegion(), and geometricRegion< GeomType >::maxPoint().
random_
uniformRandomReal random_ mutable private
Definition at line 47 of file geometricRegion.hpp.
maxTries_
constexpr uint32 maxTries_ = 100 static constexpr private
Definition at line 49 of file geometricRegion.hpp.
The documentation for this class was generated from the following files:
src/phasicFlow/structuredData/peakableRegion/geometricRegion/geometricRegion.hpp
src/phasicFlow/structuredData/peakableRegion/geometricRegion/geometricRegion.cpp