PhasicFlow: boundaryReflective Class Reference
boundaryReflective Class Reference
Public Member Functions
TypeInfo ("boundary<reflective>")
boundaryReflective (const dictionary &dict, const plane &bplane, internalPoints &internal, boundaryList &bndrs, uint32 thisIndex)
~boundaryReflective () override=default
add_vCtor (boundaryBase, boundaryReflective, dictionary)
bool beforeIteration (uint32 step, const timeInfo &ti, bool updateIter, bool iterBeforeUpdate, bool &callAgain) final
bool iterate (const timeInfo &ti) final
bool afterIteration (const timeInfo &ti) final
Public Member Functions inherited from boundaryBase
uint32 markInNegativeSide (const word &name, uint32Vector_D &markedIndices) const
TypeInfo ("boundaryBase")
boundaryBase (const dictionary &dict, const plane &bplane, internalPoints &internal, boundaryList &bndrs, uint32 thisIndex)
boundaryBase (const boundaryBase &)=delete
boundaryBase & operator= (const boundaryBase &)=delete
boundaryBase (boundaryBase &&)=default
boundaryBase & operator= (boundaryBase &&)=default
~boundaryBase () override=default
create_vCtor (boundaryBase, dictionary,(const dictionary &dict, const plane &bplane, internalPoints &internal, boundaryList &bndrs, uint32 thisIndex),(dict, bplane, internal, bndrs, thisIndex))
real neighborLengthIntoInternal () const
The length from boundary plane into the domain where beyond that distance internal points exist.
virtual real neighborLength () const
The distance length from boundary plane where neighbor particles still exist in that distance.
virtual realx3 boundaryExtensionLength () const
The extention length (in vector form) for the boundary as required by each boundary type.
bool performBoundarytUpdate () const
Is this iter the right time for updating bounday list.
bool iterBeforeBoundaryUpdate () const
const word & type () const
const word & name () const
bool empty () const
auto size () const
auto capacity () const
int neighborProcessorNo () const
int thisProcessorNo () const
bool isBoundaryMaster () const
uint32 thisBoundaryIndex () const
uint32 mirrorBoundaryIndex () const
const internalPoints & internal () const
internalPoints & internal ()
const pointStructure & pStruct () const
const Time & time () const
const auto & indexList () const
const auto & indexListHost () const
boundaryBase & mirrorBoundary ()
const boundaryBase & mirrorBoundary () const
const plane & boundaryPlane () const
the actual boundary plane of this boundary
virtual realx3 displacementVectroToMirror () const
displacement vector that transfers points
to a distance that is equal to the distance between this plane and the mirror plane, the vector points from this plane to mirror plane
pointFieldAccessType thisPoints () const
virtual uint32 neighborProcSize () const
Return number of points in the neighbor processor boundary.
virtual realx3Vector_D & neighborProcPoints ()
Return a reference to point positions in the neighbor processor boundary.
virtual const realx3Vector_D & neighborProcPoints () const
Return a const reference to point positions in the neighbor processor boundary.
virtual uint32 numToTransfer () const
virtual uint32 numToRecieve () const
Public Member Functions inherited from subscriber
subscriber (const word &name)
subscriber (const subscriber &)
Copy constructor, only copies the name, not the list.
subscriber (subscriber &&)
Move constructor, moves the name and the list, also change the subriber of the object in the list
subscriber & operator= (const subscriber &)
Copy assignemnt, only assign the name, do not assign the list.
subscriber & operator= (subscriber &&)
Move assignment, move assign name and list, also change the subcriber of the object in the list
virtual ~subscriber ()
virtual bool subscribe (message msg, observer *obsevr) const
virtual bool unsubscribe (observer *obsevr) const
bool notify (uint32 iter, real t, real dt, const message msg, const anyList &varList)
bool notify (const timeInfo &ti, const message msg, const anyList &varList)
const word & subscriberName () const
Private Attributes
real restitution_ = 0.95
word velocityName_ {"velocity"}
word diameterName_ {"diameter"}
Additional Inherited Members
Public Types inherited from boundaryBase
using pointFieldAccessType = deviceScatteredFieldAccess< realx3 >
Static Public Member Functions inherited from boundaryBase
static uniquePtr< boundaryBase > create (const dictionary &dict, const plane &bplane, internalPoints &internal, boundaryList &bndrs, uint32 thisIndex)
Protected Member Functions inherited from boundaryBase
virtual void setSize (uint32 newSize)
Set the size of indexList.
void setUpdateTime (bool val)
void setNewIndices (const uint32Vector_D &newIndices)
bool appendNewIndices (const uint32Vector_D &newIndices)
bool removeIndices (uint32 numRemove, const uint32Vector_D &removeMask)
bool setRemoveKeepIndices (const uint32Vector_D &removeIndices, const uint32Vector_D &keepIndices)
bool transferPointsToMirror (uint32 numTransfer, const uint32Vector_D &transferMask, uint32 transferBoundaryIndex, realx3 transferVector)
void unSyncLists ()
void syncLists () const
virtual bool updataBoundaryData (int step)
Update this boundary data in two steps (1 and 2).
virtual bool transferData (uint32 iter, int step, bool &callAgain)
This method is called when a transfer of data is to be performed between processors (in afterIteration).
Detailed Description
Definition at line 29 of file boundaryReflective.hpp.
Constructor & Destructor Documentation
boundaryReflective()
boundaryReflective (const dictionary & dict, const plane & bplane, internalPoints & internal, boundaryList & bndrs, uint32 thisIndex)
Definition at line 26 of file boundaryReflective.cpp.
References dictionary::getValOrSet().
~boundaryReflective()
~boundaryReflective () override default
Member Function Documentation
TypeInfo()
TypeInfo ("boundary<reflective>")
add_vCtor()
add_vCtor (boundaryBase , boundaryReflective , dictionary)
beforeIteration()
bool beforeIteration (uint32 step, const timeInfo & ti, bool updateIter, bool iterBeforeUpdate, bool & callAgain) final virtual
Reimplemented from boundaryBase.
Definition at line 48 of file boundaryReflective.cpp.
References boundaryBase::beforeIteration().
iterate()
bool iterate (const timeInfo & ti) final virtual
Implements boundaryBase.
Definition at line 61 of file boundaryReflective.cpp.
afterIteration()
bool afterIteration (const timeInfo & ti) final virtual
Implements boundaryBase.
Definition at line 69 of file boundaryReflective.cpp.
References pointField< T, MemorySpace >::BoundaryField(), internalField< T, MemorySpace >::deviceViewAll(), VectorSingle< T, MemorySpace >::deviceViewAll(), dot(), pFlow::exclusiveScan(), VectorSingle< T, MemorySpace >::fill(), and LAMBDA_HD.
Member Data Documentation
restitution_
real restitution_ = 0.95 private
Definition at line 35 of file boundaryReflective.hpp.
velocityName_
word velocityName_ {"velocity"} private
Definition at line 37 of file boundaryReflective.hpp.
diameterName_
word diameterName_ {"diameter"} private
Definition at line 39 of file boundaryReflective.hpp.
The documentation for this class was generated from the following files:
src/phasicFlow/structuredData/boundaries/boundaryReflective/boundaryReflective.hpp
src/phasicFlow/structuredData/boundaries/boundaryReflective/boundaryReflective.cpp