PhasicFlow: conveyorBelt Class Reference
conveyorBelt Class Reference
conveyor belt model for a wall
Public Member Functions
TypeInfoNV ("conveyorBelt")
FUNCTION_HD conveyorBelt ()=default
FUNCTION_H conveyorBelt (const dictionary &dict)
FUNCTION_HD conveyorBelt (const conveyorBelt &)=default
conveyorBelt & operator= (const conveyorBelt &)=default
INLINE_FUNCTION_HD void setTime (real t)
INLINE_FUNCTION_HD realx3 linVelocityPoint (const realx3 &) const
INLINE_FUNCTION_HD realx3 transferPoint (const realx3 &p, real) const
FUNCTION_H bool read (const dictionary &dict)
FUNCTION_H bool write (dictionary &dict) const
FUNCTION_H bool read (iIstream &is)
FUNCTION_H bool write (iOstream &os) const
Private Attributes
realx3 tangentVelocity_ {0, 0, 0}
Detailed Description
conveyor belt model for a wall
Definition at line 40 of file conveyorBelt.hpp.
Constructor & Destructor Documentation
conveyorBelt() [1/3]
FUNCTION_HD conveyorBelt () default
conveyorBelt() [2/3]
FUNCTION_H conveyorBelt (const dictionary & dict) explicit
Definition at line 26 of file conveyorBelt.cpp.
References pFlow::endl(), fatalErrorInFunction, fatalExit, dictionary::globalName(), and conveyorBelt::read().
conveyorBelt() [3/3]
FUNCTION_HD conveyorBelt (const conveyorBelt &) default
Member Function Documentation
TypeInfoNV()
TypeInfoNV ("conveyorBelt")
operator=()
conveyorBelt& operator= (const conveyorBelt &) default
setTime()
INLINE_FUNCTION_HD void setTime (real t) inline
Definition at line 63 of file conveyorBelt.hpp.
linVelocityPoint()
INLINE_FUNCTION_HD realx3 linVelocityPoint (const realx3 &) const inline
Definition at line 67 of file conveyorBelt.hpp.
References conveyorBelt::tangentVelocity_.
transferPoint()
INLINE_FUNCTION_HD realx3 transferPoint (const realx3 & p, real) const inline
Definition at line 73 of file conveyorBelt.hpp.
read() [1/2]
FUNCTION_H bool read (const dictionary & dict)
Definition at line 37 of file conveyorBelt.cpp.
References dictionary::getVal().
Referenced by conveyorBelt::conveyorBelt().
write() [1/2]
FUNCTION_H bool write (dictionary & dict) const
Definition at line 46 of file conveyorBelt.cpp.
References dictionary::add(), pFlow::endl(), fatalErrorInFunction, and dictionary::globalName().
read() [2/2]
FUNCTION_H bool read (iIstream & is)
Definition at line 58 of file conveyorBelt.cpp.
References notImplementedFunction.
write() [2/2]
FUNCTION_H bool write (iOstream & os) const
Definition at line 66 of file conveyorBelt.cpp.
References iOstream::writeWordEntry().
Member Data Documentation
tangentVelocity_
realx3 tangentVelocity_ {0, 0, 0} private
Definition at line 44 of file conveyorBelt.hpp.
Referenced by conveyorBelt::linVelocityPoint().
The documentation for this class was generated from the following files:
src/MotionModel/entities/conveyorBelt/conveyorBelt.hpp
src/MotionModel/entities/conveyorBelt/conveyorBelt.cpp