PhasicFlow: MotionModel< Model, Component > Class Template Reference
MotionModel< Model, Component > Class Template Reference
Motion model abstract class (CRTP) for all the motion models.
Classes
class ModelInterface
Motion model class to be passed to computational units/kernels for transfing points and returning velocities at various positions.
Public Types
using ModelType = Model
using ModelComponent = Component
using ComponentVector_D = VectorSingle< ModelComponent >
Public Member Functions
MotionModel ()
Empty.
MotionModel (const MotionModel &)=default
Copy constructor.
MotionModel (MotionModel &&)=default
Move constructor.
MotionModel & operator= (const MotionModel &)=default
Copy assignment.
MotionModel & operator= (MotionModel &&)=default
No move assignment.
~MotionModel ()=default
Destructor.
bool nameToIndex (const word &name, uint32 &idx) const
name of the compoenent to index of the component
bool indexToName (uint32 idx, word &name) const
Component index to motion component name.
const wordList & componentNames () const
Return a const reference to the list of compoenent names.
bool isMoving () const
Is the wall assocciated to this motion component moving?
bool move (uint32 iter, real t, real dt)
Move the component itself.
auto getModelInterface (uint32 iter, real t, real dt) const
Obtain an object to model interface.
Protected Member Functions
auto & getModel ()
obtain a reference to the actual motion model
const auto & getModel () const
Obtain a const reference to the actual motion model.
auto impl_noneComponent () const
Return a none object for the motion model.
bool impl_nameToIndex (const word &name, uint32 &idx) const
Name of the compoenent to index of the component.
bool impl_indexToName (uint32 i, word &name) const
Component index to motion component name.
const wordList & impl_componentNames () const
const reference to the list of component names
auto impl_getModelInterface (uint32 iter, real t, real dt) const
Return model interface.
bool impl_readDictionary (const dictionary &dict)
Read from dictionary.
bool impl_writeDictionary (dictionary &dict) const
Write to dictionary.
Private Attributes
friend ModelType
uint32 numComponents_ = 0
Number of axes components.
ComponentVector_D motionComponents_
Vector to store motion components.
wordList componentNames_
Names of compoenents.
Detailed Description
template<typename Model, typename Component>
class pFlow::MotionModel< Model, Component >
Motion model abstract class (CRTP) for all the motion models.
Definition at line 39 of file MotionModel.hpp.
Member Typedef Documentation
ModelType
using ModelType = Model
Definition at line 43 of file MotionModel.hpp.
ModelComponent
using ModelComponent = Component
Definition at line 45 of file MotionModel.hpp.
ComponentVector_D
using ComponentVector_D = VectorSingle<ModelComponent>
Definition at line 47 of file MotionModel.hpp.
Constructor & Destructor Documentation
MotionModel() [1/3]
MotionModel
Empty.
Definition at line 144 of file MotionModel.cpp.
MotionModel() [2/3]
MotionModel (const MotionModel< Model, Component > &) default
Copy constructor.
MotionModel() [3/3]
MotionModel (MotionModel< Model, Component > &&) default
Move constructor.
~MotionModel()
~MotionModel () default
Destructor.
Member Function Documentation
getModel() [1/2]
auto& getModel () inline protected
obtain a reference to the actual motion model
Definition at line 130 of file MotionModel.hpp.
Referenced by MotionModel< rotatingAxisMotion, rotatingAxis >::componentNames(), MotionModel< rotatingAxisMotion, rotatingAxis >::getModelInterface(), MotionModel< rotatingAxisMotion, rotatingAxis >::impl_getModelInterface(), MotionModel< rotatingAxisMotion, rotatingAxis >::indexToName(), MotionModel< rotatingAxisMotion, rotatingAxis >::isMoving(), MotionModel< rotatingAxisMotion, rotatingAxis >::move(), and MotionModel< rotatingAxisMotion, rotatingAxis >::nameToIndex().
getModel() [2/2]
const auto& getModel () const inline protected
Obtain a const reference to the actual motion model.
Definition at line 137 of file MotionModel.hpp.
impl_noneComponent()
auto impl_noneComponent () const inline protected
Return a none object for the motion model.
Definition at line 144 of file MotionModel.hpp.
impl_nameToIndex()
bool impl_nameToIndex (const word & name, uint32 & idx) const inline protected
Name of the compoenent to index of the component.
Definition at line 24 of file MotionModel.cpp.
impl_indexToName()
bool impl_indexToName (uint32 i, word & name) const inline protected
Component index to motion component name.
Definition at line 40 of file MotionModel.cpp.
impl_componentNames()
const wordList& impl_componentNames () const inline protected
const reference to the list of component names
Definition at line 157 of file MotionModel.hpp.
impl_getModelInterface()
auto impl_getModelInterface (uint32 iter, real t, real dt) const inline protected
Return model interface.
Definition at line 163 of file MotionModel.hpp.
impl_readDictionary()
bool impl_readDictionary (const dictionary & dict) inline protected
Read from dictionary.
Definition at line 56 of file MotionModel.cpp.
impl_writeDictionary()
bool impl_writeDictionary (dictionary & dict) const inline protected
Write to dictionary.
Definition at line 113 of file MotionModel.cpp.
operator=() [1/2]
MotionModel& operator= (const MotionModel< Model, Component > &) default
Copy assignment.
operator=() [2/2]
MotionModel& operator= (MotionModel< Model, Component > &&) default
No move assignment.
nameToIndex()
bool nameToIndex (const word & name, uint32 & idx) const inline
name of the compoenent to index of the component
Definition at line 203 of file MotionModel.hpp.
indexToName()
bool indexToName (uint32 idx, word & name) const inline
Component index to motion component name.
Definition at line 209 of file MotionModel.hpp.
componentNames()
const wordList& componentNames () const inline
Return a const reference to the list of compoenent names.
Returns
Definition at line 216 of file MotionModel.hpp.
isMoving()
bool isMoving () const inline
Is the wall assocciated to this motion component moving?
Definition at line 222 of file MotionModel.hpp.
move()
bool move (uint32 iter, real t, real dt) inline
Move the component itself.
Definition at line 228 of file MotionModel.hpp.
getModelInterface()
auto getModelInterface (uint32 iter, real t, real dt) const inline
Obtain an object to model interface.
Definition at line 234 of file MotionModel.hpp.
Member Data Documentation
ModelType
friend ModelType private
Definition at line 115 of file MotionModel.hpp.
numComponents_
uint32 numComponents_ = 0 private
Number of axes components.
Definition at line 118 of file MotionModel.hpp.
Referenced by MotionModel< rotatingAxisMotion, rotatingAxis >::impl_getModelInterface().
motionComponents_
ComponentVector_D motionComponents_ private
Vector to store motion components.
Definition at line 121 of file MotionModel.hpp.
Referenced by MotionModel< rotatingAxisMotion, rotatingAxis >::impl_getModelInterface().
componentNames_
wordList componentNames_ private
Names of compoenents.
Definition at line 124 of file MotionModel.hpp.
Referenced by MotionModel< rotatingAxisMotion, rotatingAxis >::impl_componentNames().
The documentation for this class was generated from the following files:
src/MotionModel/MotionModel/MotionModel.hpp
src/MotionModel/MotionModel/MotionModel.cpp