PhasicFlow: mapperNBS::CellIterator Class Reference
mapperNBS::CellIterator Class Reference
Public Member Functions
CellIterator (const HeadType &head, const NextType &next)
INLINE_FUNCTION_HD int32x3 numCells () const
INLINE_FUNCTION_HD uint32 start (int32 i, int32 j, int32 k) const
INLINE_FUNCTION_HD uint32 getNext (uint32 n) const
INLINE_FUNCTION_HD uint32 next (uint32 n) const
Static Public Attributes
static constexpr uint32 NoPos = 0xFFFFFFFF
Private Attributes
HeadType head_
NextType next_
Detailed Description
Definition at line 45 of file mapperNBS.hpp.
Constructor & Destructor Documentation
CellIterator()
CellIterator (const HeadType & head, const NextType & next) inline
Definition at line 54 of file mapperNBS.hpp.
Member Function Documentation
numCells()
INLINE_FUNCTION_HD int32x3 numCells () const inline
Definition at line 63 of file mapperNBS.hpp.
References mapperNBS::CellIterator::head_.
Referenced by pFlow::NBSLevel0Kernels::findPairsCount().
start()
INLINE_FUNCTION_HD uint32 start (int32 i, int32 j, int32 k) const inline
Definition at line 67 of file mapperNBS.hpp.
References mapperNBS::CellIterator::head_.
Referenced by cellsWallLevel0::findPairsElementRangeCount().
getNext()
INLINE_FUNCTION_HD uint32 getNext (uint32 n) const inline
Definition at line 71 of file mapperNBS.hpp.
References n, mapperNBS::CellIterator::next_, and mapperNBS::CellIterator::NoPos.
next()
INLINE_FUNCTION_HD uint32 next (uint32 n) const inline
Definition at line 76 of file mapperNBS.hpp.
References n, and mapperNBS::CellIterator::next_.
Referenced by cellsWallLevel0::findPairsElementRangeCount().
Member Data Documentation
head_
HeadType head_ private
Definition at line 48 of file mapperNBS.hpp.
Referenced by mapperNBS::CellIterator::numCells(), and mapperNBS::CellIterator::start().
next_
NextType next_ private
Definition at line 50 of file mapperNBS.hpp.
Referenced by mapperNBS::CellIterator::getNext(), and mapperNBS::CellIterator::next().
NoPos
constexpr uint32 NoPos = 0xFFFFFFFF static constexpr
Definition at line 60 of file mapperNBS.hpp.
Referenced by cellsWallLevel0::findPairsElementRangeCount(), and mapperNBS::CellIterator::getNext().
The documentation for this class was generated from the following file:
src/Interaction/contactSearch/methods/cellBased/NBS/mapperNBS.hpp