PhasicFlow: wallBoundaryContactSearch Class Reference
wallBoundaryContactSearch Class Reference
Public Types
using execution_space = csExecutionSpace
using memory_space = typename execution_space::memory_space
using iBoxType = iBox< int32 >
Public Member Functions
TypeInfoNV ("wallBoundaryContactSearch")
INLINE_FUNCTION_HD wallBoundaryContactSearch ()=default
FUNCTION_H wallBoundaryContactSearch (real cellExtent, uint32 numPoints, uint32 numElements, const ViewType1D< realx3, memory_space > &points, const ViewType1D< uint32x3, memory_space > &vertices, const ViewType1D< realx3, memory_space > &normals)
INLINE_FUNCTION_HD uint32 numElements () const
bool build (const cells &searchBox, const realx3 &transferVec)
bool broadSearch (csPairContainerType &pairs, const cells &searchCells, const deviceScatteredFieldAccess< realx3 > &thisPoints, const deviceScatteredFieldAccess< real > &thisDiams, const deviceScatteredFieldAccess< realx3 > &mirrorPoints, const deviceScatteredFieldAccess< real > &mirroDiams, const realx3 &transferVec, real sizeRatio)
uint32 findPairsElementRangeCount (csPairContainerType &pairs, const cells &searchCells, const deviceScatteredFieldAccess< realx3 > &pPoints, const deviceScatteredFieldAccess< real > &pDiams, const realx3 &transferVec, uint baseTriIndex)
Private Member Functions
FUNCTION_H void allocateArrays ()
Private Attributes
real cellExtent_ = 0.5
uint32 numElements_ = 0
uint32 numPoints_ = 0
ViewType1D< uint32x3, memory_space > vertices_
ViewType1D< realx3, memory_space > points_
ViewType1D< realx3, memory_space > normals_
ViewType1D< iBoxType, memory_space > elementBox_
ViewType1D< uint8, memory_space > validBox_
Detailed Description
Definition at line 36 of file wallBoundaryContactSearch.hpp.
Member Typedef Documentation
execution_space
using execution_space = csExecutionSpace
Definition at line 40 of file wallBoundaryContactSearch.hpp.
memory_space
using memory_space = typename execution_space::memory_space
Definition at line 42 of file wallBoundaryContactSearch.hpp.
iBoxType
using iBoxType = iBox<int32>
Definition at line 44 of file wallBoundaryContactSearch.hpp.
Constructor & Destructor Documentation
wallBoundaryContactSearch() [1/2]
INLINE_FUNCTION_HD wallBoundaryContactSearch () default
wallBoundaryContactSearch() [2/2]
wallBoundaryContactSearch (real cellExtent, uint32 numPoints, uint32 numElements, const ViewType1D< realx3, memory_space > & points, const ViewType1D< uint32x3, memory_space > & vertices, const ViewType1D< realx3, memory_space > & normals)
Definition at line 5 of file wallBoundaryContactSearch.cpp.
Member Function Documentation
allocateArrays()
FUNCTION_H void allocateArrays () inline private
Definition at line 73 of file wallBoundaryContactSearch.hpp.
References wallBoundaryContactSearch::elementBox_, wallBoundaryContactSearch::numElements_, pFlow::reallocNoInit(), and wallBoundaryContactSearch::validBox_.
TypeInfoNV()
TypeInfoNV ("wallBoundaryContactSearch")
numElements()
INLINE_FUNCTION_HD uint32 numElements () const inline
Definition at line 98 of file wallBoundaryContactSearch.hpp.
References wallBoundaryContactSearch::numElements_.
build()
bool build (const cells & searchBox, const realx3 & transferVec)
Definition at line 24 of file wallBoundaryContactSearch.cpp.
References wallBoundaryContactSearch::cellExtent_, CLASS_LAMBDA_HD, wallBoundaryContactSearch::elementBox_, cells::extendBox(), wallBoundaryContactSearch::numElements_, cells::pointIndex(), wallBoundaryContactSearch::points_, wallBoundaryContactSearch::validBox_, and wallBoundaryContactSearch::vertices_.
broadSearch()
bool broadSearch (csPairContainerType & pairs, const cells & searchCells, const deviceScatteredFieldAccess< realx3 > & thisPoints, const deviceScatteredFieldAccess< real > & thisDiams, const deviceScatteredFieldAccess< realx3 > & mirrorPoints, const deviceScatteredFieldAccess< real > & mirroDiams, const realx3 & transferVec, real sizeRatio)
Definition at line 50 of file wallBoundaryContactSearch.cpp.
References pFlow::BASE_MIRROR_WALL_INDEX, unsortedPairs< executionSpace, idType >::capacity(), END_INFO, unsortedPairs< executionSpace, idType >::increaseCapacityBy(), INFORMATION, and pFlow::max().
findPairsElementRangeCount()
pFlow::uint32 findPairsElementRangeCount (csPairContainerType & pairs, const cells & searchCells, const deviceScatteredFieldAccess< realx3 > & pPoints, const deviceScatteredFieldAccess< real > & pDiams, const realx3 & transferVec, uint baseTriIndex)
Definition at line 102 of file wallBoundaryContactSearch.cpp.
References scatteredFieldAccess< T, MemorySpace >::empty(), LAMBDA_HD, cells::pointIndexInDomain(), and scatteredFieldAccess< T, MemorySpace >::size().
Member Data Documentation
cellExtent_
real cellExtent_ = 0.5 private
Definition at line 49 of file wallBoundaryContactSearch.hpp.
Referenced by wallBoundaryContactSearch::build().
numElements_
uint32 numElements_ = 0 private
Definition at line 52 of file wallBoundaryContactSearch.hpp.
Referenced by wallBoundaryContactSearch::allocateArrays(), wallBoundaryContactSearch::build(), and wallBoundaryContactSearch::numElements().
numPoints_
uint32 numPoints_ = 0 private
Definition at line 55 of file wallBoundaryContactSearch.hpp.
vertices_
ViewType1D<uint32x3, memory_space> vertices_ private
Definition at line 58 of file wallBoundaryContactSearch.hpp.
Referenced by wallBoundaryContactSearch::build().
points_
ViewType1D<realx3, memory_space> points_ private
Definition at line 61 of file wallBoundaryContactSearch.hpp.
Referenced by wallBoundaryContactSearch::build().
normals_
ViewType1D<realx3, memory_space> normals_ private
Definition at line 64 of file wallBoundaryContactSearch.hpp.
elementBox_
ViewType1D<iBoxType, memory_space> elementBox_ private
Definition at line 67 of file wallBoundaryContactSearch.hpp.
Referenced by wallBoundaryContactSearch::allocateArrays(), and wallBoundaryContactSearch::build().
validBox_
ViewType1D<uint8, memory_space> validBox_ private
Definition at line 69 of file wallBoundaryContactSearch.hpp.
Referenced by wallBoundaryContactSearch::allocateArrays(), and wallBoundaryContactSearch::build().
The documentation for this class was generated from the following files:
src/Interaction/contactSearch/boundaries/periodicBoundaryContactSearch/wallBoundaryContactSearch.hpp
src/Interaction/contactSearch/boundaries/periodicBoundaryContactSearch/wallBoundaryContactSearch.cpp