PhasicFlow: repository Class Reference
repository Class Reference
Public Member Functions
TypeInfo ("repository")
repository (const word &name, const fileSystem &localPath, repository *owner=nullptr)
repository (const repository &)=delete
repository & operator= (const repository &)=delete
virtual ~repository ()
word name () const
virtual fileSystem localPath () const
virtual fileSystem path () const
const repository * owner () const
repository * owner ()
const repository & thisRepository () const
repository & thisRepository ()
bool addToRepository (repository *rep)
add repository to this repository return false if the name already exists
bool removeFromRepository (repository *rep)
remove rep from the list of repositories
bool addToRepository (IOobject *io)
add IOobject to this repository
bool removeFromRepository (IOobject *io)
remove rep from the list of repositories
repository * releaseOwner (bool fromOwner=false)
virtual bool isIncluded (const word &objName) const
virtual bool isExcluded (const word &objName) const
bool lookupObjectName (const word &nm) const
word lookupObjectTypeName (const word &nm) const
bool globalLookupObjectName (const word &nm, bool downward=false) const
bool lookupRepositoryName (const word &nm) const
bool lookupName (const word nm) const
size_t numObjects () const
size_t numRepositories () const
virtual size_t outFilePrecision () const
template<typename T >
T & lookupObject (const word &name)
return a ref to the underlaying data in the object
template<typename T >
const T & lookupObject (const word &name) const
return a const ref to the underlaying data in the object
repository & lookupRepository (const word &name)
wordList objectNames () const
wordList repositoryNames () const
virtual bool outFileBinary () const
virtual bool write (bool verbose=false) const
template<typename Type1 >
pFlow::word reportTypeError (IOobject &object) const
Private Member Functions
template<typename Type1 >
word reportTypeError (IOobject &object) const
Static Private Member Functions
template<typename Type >
static bool checkForObjectType (IOobject &object)
Private Attributes
word name_
fileSystem localPath_
repository * owner_
wordMap< IOobject * > objects_
wordMap< repository * > repositories_
Detailed Description
Definition at line 34 of file repository.hpp.
Constructor & Destructor Documentation
repository() [1/2]
repository (const word & name, const fileSystem & localPath, repository * owner = nullptr)
Definition at line 25 of file repository.cpp.
References repository::addToRepository().
repository() [2/2]
repository (const repository &) delete
~repository()
~repository () virtual
Definition at line 42 of file repository.cpp.
References repository::objects_, repository::owner_, repository::removeFromRepository(), and repository::repositories_.
Member Function Documentation
reportTypeError() [1/2]
word reportTypeError (IOobject & object) const private
checkForObjectType()
bool checkForObjectType (IOobject & object) static private
Definition at line 34 of file repositoryTemplates.cpp.
TypeInfo()
TypeInfo ("repository")
operator=()
repository& operator= (const repository &) delete
name()
pFlow::word name () const
Definition at line 60 of file repository.cpp.
Referenced by repository::addToRepository(), readFromTimeFolder::createUniformPointField_H(), IOobject::IOobject(), readFromTimeFolder::readPointField_D(), readFromTimeFolder::readPointField_H(), repository::removeFromRepository(), repository::reportTypeError(), and setFieldEntry::setPointFieldSelected().
localPath()
pFlow::fileSystem localPath () const virtual
Reimplemented in Time.
Definition at line 65 of file repository.cpp.
path()
pFlow::fileSystem path () const virtual
Definition at line 70 of file repository.cpp.
References fileSystem::path().
Referenced by pFlow::PFtoVTK::convertTimeFolderPointFields(), pFlow::PFtoVTK::convertTimeFolderPointFieldsSelected(), pFlow::TSFtoVTK::convertTimeFolderTriSurfaceFields(), interaction::create(), geometry::create(), and readFromTimeFolder::path().
owner() [1/2]
pFlow::repository * owner () const
Definition at line 82 of file repository.cpp.
Referenced by repository::globalLookupObjectName().
owner() [2/2]
repository* owner ()
thisRepository() [1/2]
pFlow::repository & thisRepository () const
Definition at line 92 of file repository.cpp.
thisRepository() [2/2]
repository& thisRepository ()
addToRepository() [1/2]
bool addToRepository (repository * rep)
add repository to this repository return false if the name already exists
Definition at line 102 of file repository.cpp.
References repository::name(), and warningInFunction.
Referenced by IOobject::IOobject(), and repository::repository().
removeFromRepository() [1/2]
bool removeFromRepository (repository * rep)
remove rep from the list of repositories
Definition at line 118 of file repository.cpp.
References repository::name().
Referenced by IOobject::releaseOwner(), repository::releaseOwner(), IOobject::~IOobject(), and repository::~repository().
addToRepository() [2/2]
bool addToRepository (IOobject * io)
add IOobject to this repository
Definition at line 142 of file repository.cpp.
References objectFile::name(), and warningInFunction.
removeFromRepository() [2/2]
bool removeFromRepository (IOobject * io)
remove rep from the list of repositories
Definition at line 124 of file repository.cpp.
References objectFile::name().
releaseOwner()
pFlow::repository * releaseOwner (bool fromOwner = false)
Definition at line 131 of file repository.cpp.
References repository::removeFromRepository().
isIncluded()
virtual bool isIncluded (const word & objName) const inline virtual
Reimplemented in systemControl.
Definition at line 120 of file repository.hpp.
References repository::isIncluded(), and repository::owner_.
Referenced by repository::isIncluded().
isExcluded()
virtual bool isExcluded (const word & objName) const inline virtual
Reimplemented in systemControl.
Definition at line 128 of file repository.hpp.
References repository::isExcluded(), and repository::owner_.
Referenced by repository::isExcluded().
lookupObjectName()
bool lookupObjectName (const word & nm) const
Definition at line 157 of file repository.cpp.
Referenced by readFromTimeFolder::checkForPointStructure(), pFlow::selectedFieldVals(), and setFieldEntry::setPointFieldSelected().
lookupObjectTypeName()
pFlow::word lookupObjectTypeName (const word & nm) const
Definition at line 163 of file repository.cpp.
References pFlow::endl(), fatalErrorInFunction, and fatalExit.
Referenced by pFlow::selectedFieldVals(), and setFieldEntry::setPointFieldSelected().
globalLookupObjectName()
bool globalLookupObjectName (const word & nm, bool downward = false) const
Definition at line 181 of file repository.cpp.
References repository::globalLookupObjectName(), and repository::owner().
Referenced by repository::globalLookupObjectName().
lookupRepositoryName()
bool lookupRepositoryName (const word & nm) const
Definition at line 217 of file repository.cpp.
lookupName()
bool lookupName (const word nm) const
Definition at line 222 of file repository.cpp.
numObjects()
size_t numObjects () const
Definition at line 229 of file repository.cpp.
numRepositories()
size_t numRepositories () const
Definition at line 234 of file repository.cpp.
outFilePrecision()
virtual size_t outFilePrecision () const inline virtual
Reimplemented in systemControl.
Definition at line 160 of file repository.hpp.
References repository::outFilePrecision(), and repository::owner_.
Referenced by repository::outFilePrecision().
lookupObject() [1/2]
T & lookupObject (const word & name)
return a ref to the underlaying data in the object
Definition at line 40 of file repositoryTemplates.cpp.
References pFlow::endl(), fatalErrorInFunction, and fatalExit.
Referenced by readFromTimeFolder::createUniformPointField_H(), readFromTimeFolder::readPointField_D(), readFromTimeFolder::readPointField_H(), pFlow::selectedFieldVals(), and setFieldEntry::setPointFieldSelected().
lookupObject() [2/2]
const T & lookupObject (const word & name) const
return a const ref to the underlaying data in the object
Definition at line 70 of file repositoryTemplates.cpp.
References pFlow::endl(), fatalErrorInFunction, and fatalExit.
lookupRepository()
pFlow::repository & lookupRepository (const word & name)
Definition at line 239 of file repository.cpp.
References pFlow::endl(), fatalErrorInFunction, and fatalExit.
objectNames()
pFlow::wordList objectNames () const
Definition at line 256 of file repository.cpp.
repositoryNames()
pFlow::wordList repositoryNames () const
Definition at line 266 of file repository.cpp.
outFileBinary()
virtual bool outFileBinary () const inline virtual
Reimplemented in Time.
Definition at line 190 of file repository.hpp.
References repository::outFileBinary(), and repository::owner_.
Referenced by repository::outFileBinary().
write()
bool write (bool verbose = false) const virtual
Reimplemented in Time.
Definition at line 278 of file repository.cpp.
References END_REPORT, pFlow::endl(), fatalErrorInFunction, and REPORT.
Referenced by Time::write().
reportTypeError() [2/2]
pFlow::word reportTypeError (IOobject & object) const
Definition at line 23 of file repositoryTemplates.cpp.
References repository::name().
Member Data Documentation
name_
word name_ private
Definition at line 39 of file repository.hpp.
localPath_
fileSystem localPath_ private
Definition at line 42 of file repository.hpp.
owner_
repository* owner_ private
Definition at line 45 of file repository.hpp.
Referenced by repository::isExcluded(), repository::isIncluded(), repository::outFileBinary(), repository::outFilePrecision(), and repository::~repository().
objects_
wordMap<IOobject*> objects_ private
Definition at line 48 of file repository.hpp.
Referenced by repository::~repository().
repositories_
wordMap<repository*> repositories_ private
Definition at line 52 of file repository.hpp.
Referenced by repository::~repository().
The documentation for this class was generated from the following files:
src/phasicFlow/repository/repository/repository.hpp
src/phasicFlow/repository/repository/repository.cpp
src/phasicFlow/repository/repository/repositoryTemplates.cpp