PhasicFlow: property Class Reference
property Class Reference
property holds the pure properties of materials.
Public Member Functions
TypeInfo ("property")
Type info.
property (const word &fileName, repository *owner=nullptr)
property (const word &fileName, const fileSystem &dir)
property (const word &fileName, const wordVector &materials, const realVector &densities, repository *owner=nullptr)
property (const property &)=default
Default copy.
property (property &&)=default
Default move.
property & operator= (const property &)=default
Default copy assignment.
property & operator= (property &&)=default
Default move assignment.
~property () override=default
Default destructor.
auto numMaterials () const
Return number of materials.
const auto & materials () const
Return list of material names.
const auto & densities () const
Return the list of densities.
const word & material (uint32 i) const
Return the material name of material i.
bool material (uint32 i, word &name) const
Get the name of material i.
real density (uint32 i) const
Return density of material i.
bool density (uint32 i, real &rho) const
Get the density of material i.
bool nameToIndex (const word &name, uint32 &idx) const
Get the name of material in index idx Return true, if the name found, otherwise false.
Public Member Functions inherited from fileDictionary
TypeInfo ("fileDictionary")
fileDictionary (const objectFile &of, repository *owner=nullptr)
construct an empty dictionary with keyword and make it global/fileDictionary
fileDictionary (const word &keyword, const fileSystem &file)
construct a dictionary with name and read it from file
fileDictionary (const objectFile &objf, const dictionary &dict, repository *owner=nullptr)
bool read (iIstream &is, const IOPattern &iop) override
read from stream
bool write (iOstream &os, const IOPattern &iop) const override
write to stream
bool read (iIstream &is) override
read from stream
bool write (iOstream &os) const override
write to stream
Public Member Functions inherited from IOobject
virtual word typeName () const =0
IOobject (const objectFile &objf, const IOPattern &iop, repository *owner)
~IOobject () override
IOobject (const IOobject &src)=delete
IOobject (IOobject &&src)=delete
const IOPattern & ioPattern () const
const repository * owner () const override
repository * owner ()
repository * releaseOwner (bool fromOwner=false)
bool isIncluded (const word &objName) const override
bool isExcluded (const word &objName) const override
bool readObject (bool rdHdr=true)
bool writeObject () const
bool readObject (iIstream &is, bool rdHdr=true)
bool writeObject (iOstream &os) const
Public Member Functions inherited from IOfileHeader
IOfileHeader (const objectFile &objf)
const word & objectName () const
const word & objectType () const
fileSystem path () const
bool outFileBinary () const
bool inFileBinary () const
bool headerOk (bool silent=false)
bool implyRead () const
Imply read.
bool implyWrite () const
Imply write.
bool fileExist () const
Check if file exists.
bool readIfPresent () const
Check read if present.
bool writeHeader () const
Check if the header should be written to file True: on master + implyWrite + readWriteHeader = true False: otherwise.
bool writeHeader (iOstream &os, const word &typeName, bool forceWrite=false) const
Write the header to the file , typeName comes from caller.
bool writeHeader (iOstream &os, bool forceWrite=false) const
Write the header to the file, typeName comes from the one read from file.
bool readHeader () const
Check if header should be read from file.
bool readHeader (iIstream &is, bool silent=false)
Read the header in the file.
bool writeBanner (iOstream &os) const
write the banner
bool writeSeparator (iOstream &os) const
wirte a separator line
Public Member Functions inherited from objectFile
objectFile (const word &name)
objectFile (const word &name, const fileSystem &localPath, const readFlag &rf=readFlag::READ_NEVER, const writeFlag &wf=writeFlag::WRITE_NEVER, bool rwHeader=true)
objectFile (const objectFile &src)=default
objectFile (objectFile &&src)=default
objectFile & operator= (const objectFile &rhs)=default
objectFile & operator= (objectFile &&rhs)=default
virtual ~objectFile ()=default
virtual const word & name () const
virtual const fileSystem & localPath () const
readFlag rFlag () const
writeFlag wFlag () const
bool isReadAlways () const
bool isReadNever () const
bool isReadIfPresent () const
bool isWriteAlways () const
bool isWriteNever () const
bool readWriteHeader () const
Public Member Functions inherited from dictionary
TypeInfo ("dictionary")
dictionary (const word &keyword, bool global)
construct an empty dictionary with keyword and make it global/fileDictionary (if true)
dictionary (const word &keyword, const fileSystem &file)
construct a dictionary with name and read it from file
dictionary ()
cunstructs a null dictionary
dictionary (const word &keyword)
construct an empty dictionary with keyword
dictionary (const word &keyword, const dictionary &parDict)
cunstruct an empty dictionary with keyword and parDict
dictionary (const word &keyword, const dictionary &parDict, iIstream &is)
cunstruct a dictionary with keyword and parDict and from stream
dictionary (const word &keyword, const dictionary &parDict, const dictionary &dict)
copy construct with keyword and new parrent dict discard the keyword and parDict of dict
dictionary (const dictionary &)
copy construct as default behavior entries_ are copied smoothly.
dictionary (const dictionary &src, bool global)
dictionary & operator= (const dictionary &rhs)
assignment preserve name of this dictionary only entries are transfered with ownership
virtual dictionary * dictPtr ()
pointer to this dictionary
virtual const dictionary * dictPtr () const
pointer to this dictionary
virtual bool isDictionary () const
if this is a dictionary
virtual word globalName () const
global name of entry, separated with dots
virtual const dictionary & parrentDict () const
const ref to parrent dictionary
virtual dictionary & dict ()
ref to this dictionary, if it is a dictionary
virtual const dictionary & dict () const
const ref to this dictionary, if it is a dictionary
virtual bool isFileDict () const
if dictionary is file dictionary, return false
bool addPtr (const word &keyword, uniquePtr< iEntry > &etry, bool warning=true)
add a pointer entry (dictionary/dataEntry) replaces this entry with existing one and issue a warning
bool add (const word &keyword, const float &v)
add a float dataEntry
bool add (const word &keyword, const double &v)
add a double dataEntry
bool add (const word &keyword, const word &v)
add a word dataEntry
bool add (const word &keyword, const int64 &v)
add a int64 dataEntry
bool add (const word &keyword, const int32 &v)
add a int32 dataEntry
bool add (const word &keyword, const int8 &v)
add a int8 dataEntry
bool add (const word &keyword, const uint64 &v)
add a uint64 dataEntry
bool add (const word &keyword, const uint32 &v)
add a uint32 dataEntry
bool add (const word &keyword, const uint8 &v)
add a uint8 dataEntry
bool addDict (const word &keyword, const dictionary &dict)
add a dictionary with the specifiedd keyword, if it exists, replace it.
template<typename T >
bool add (const word &keyword, const T &v)
add a dataEntry of type T
template<typename T >
bool addOrKeep (const word &keyword, const T &v)
template<typename T >
bool addOrReplace (const word &keyword, const T &v)
void clear ()
dictionary * subDictPtr (const word &keyword)
pointer to a subdictionary fatalExit if not found
dictionary & subDict (const word &keyword)
ref to a subdictioanry fatalExit if not found
const dictionary & subDict (const word &keyword) const
const ref to a subdictioanry fatalExit if not found
dataEntry * dataEntryPtr (const word &keyword)
pointer to a dataEntry fatalExit if not found/not a dataEntry
dataEntry & dataEntryRef (const word &keyword)
ref to a subdictioanry fatalExit if not found/not a dataEntry
const dataEntry & dataEntryRef (const word &keyword) const
const ref to a subdictioanry fatalExit if not found/not a dataEntry
dictionary & subDictOrCreate (const word &keyword)
search for a sub-dict with keyword create a new sub-dict if not found and return a ref to it fatalExit if fails
template<typename T >
T getVal (const word &keyword) const
get the value of data entry
template<typename T >
T getValMax (const word &keyword, const T &maxVal) const
get the value of data entry and return max(value, maxVal)
template<typename T >
T getValMin (const word &keyword, const T &minVal) const
get the value of data entry and return min(value, minVal)
template<typename T >
T getValOrSet (const word &keyword, const T &setVal) const
get the value of data entry or if not found, set the value to setVal
template<typename T >
T getValOrSetMax (const word &keyword, const T &setMaxVal) const
get the value of data entry anf return max(setMaxVal, value) if not found, set the value to setMaxVal
template<typename T >
T getValOrSetMin (const word &keyword, const T &setMinVal) const
get the value of data entry anf return max(setMinVal, value) if not found, set the value to setMinVal
size_t numEntries () const
return number of entris in this dictionary
size_t numDataEntries () const
return number of non-nullptr dataEntries
size_t numDictionaries () const
return number of non-nullptr dictionaries
wordList allKeywords () const
return all keywords (non-nullptr) in this dictionary
wordList dataEntryKeywords () const
return a list of all dataEntries (non-nullptr) keywords
wordList dictionaryKeywords () const
return a list of all dictionary (non-null) keywords
bool containsDictionay (const word &name) const
check if a sub-dictionary exists
bool containsDataEntry (const word &name) const
check if a data entry exist
virtual uniquePtr< iEntry > clone () const
clone polymorphic object (here dictionary)
virtual iEntry * clonePtr () const
clone the object
virtual uniquePtr< iEntry > clone (const dictionary &parDict) const
clone the polymorhpic object with parDict as the new parrent dictionary
virtual iEntry * clonePtr (const dictionary &parDict) const
clone the object and change its ownership to parDict
bool read (iIstream &is) override
read from stream
bool write (iOstream &os) const override
write to stream
Public Member Functions inherited from iEntry
TypeInfo ("iEntry")
Type info.
iEntry ()
empty constructor
iEntry (const word &key)
construct with a keyword
virtual ~iEntry ()
destructor
virtual const word & keyword () const
return keyword
virtual word & keyword ()
return keyword
virtual word name () const
name/keyword of entry
Private Member Functions
bool readDictionary ()
read from dict
bool writeDictionary ()
write to dict
bool makeNameIndex ()
creates a mapp
Private Attributes
wordVector materials_
list of name of materials
realVector densities_
list of density of materials
wordHashMap< uint32 > nameIndex_
rapid mapping from name to index
uint32 numMaterials_ = 0
number of materials
Additional Inherited Members
Public Types inherited from objectFile
enum readFlag { READ_ALWAYS, READ_NEVER, READ_IF_PRESENT }
enum writeFlag { WRITE_ALWAYS, WRITE_NEVER }
Static Public Member Functions inherited from iEntry
static bool readKeyword (iIstream &is, word &keyword, token &tok)
read a keyword from stream
static bool createEntry (dictionary &parDict, iIstream &is, bool hasBlockToken=false)
create an entry (dataEntry or dictionary) from stream
Static Public Attributes inherited from dictionary
static dictionary nullDict
Protected Member Functions inherited from IOfileHeader
uniquePtr< iFstream > inStream () const
uniquePtr< oFstream > outStream () const
uniquePtr< oFstream > dummyOutStream () const
Protected Member Functions inherited from dictionary
iEntry * findEntry (const word &keyword)
find an entry based on keyword return nullptr if not found
iEntry * findEntry (const word &keyword) const
find and entry based on keyword return nullptr if not found
template<typename T >
bool readDataEntry (const word &keyword, T &val) const
reads a dataEntry with keyword from dictionary
bool readDictionary (iIstream &is)
read dictionary from stream - without keyword
bool writeDictionary (iOstream &os, bool withBlock=true) const
write dictionary to stream - with keyword
Protected Member Functions inherited from iEntry
bool writeKeyword (iOstream &os) const
Protected Attributes inherited from IOfileHeader
word objectName_
word objectType_
word fileFormat_ = "ASCII"
file format read from file
Protected Attributes inherited from dictionary
word name_
global name of dictionary, separated with dots
wordOrderedMapPtr< iEntry > entries_
all the entries (data and dictionary) of the current dictionary
List< iEntry * > orderedEntries_
entries in order of insertion
const dictionary & parDict_
ref to parrent dictionary
bool isGlobal_ = false
Protected Attributes inherited from iEntry
word keyword_
Detailed Description
property holds the pure properties of materials.
This class holds a list of all materials name and their densities that are used in the simulation: for walls and particles.
Definition at line 37 of file property.hpp.
Constructor & Destructor Documentation
property() [1/5]
property (const word & fileName, repository * owner = nullptr) explicit
Definition at line 122 of file property.cpp.
References pFlow::endl(), fatalErrorInFunction, and fatalExit.
property() [2/5]
property (const word & fileName, const fileSystem & dir)
Definition at line 155 of file property.cpp.
References pFlow::endl(), fatalErrorInFunction, and fatalExit.
property() [3/5]
property (const word & fileName, const wordVector & materials, const realVector & densities, repository * owner = nullptr)
Definition at line 86 of file property.cpp.
References fatalErrorInFunction, and fatalExit.
property() [4/5]
property (const property &) default
Default copy.
property() [5/5]
property (property &&) default
Default move.
~property()
~property () override default
Default destructor.
Member Function Documentation
readDictionary()
bool readDictionary () private
read from dict
Definition at line 24 of file property.cpp.
References property::densities_, pFlow::endl(), fatalErrorInFunction, dictionary::globalName(), property::materials_, and Vector< T, Allocator >::size().
writeDictionary()
bool writeDictionary () private
write to dict
Definition at line 43 of file property.cpp.
References pFlow::endl(), and fatalErrorInFunction.
makeNameIndex()
bool makeNameIndex () private
creates a mapp
Definition at line 63 of file property.cpp.
References fatalErrorInFunction.
TypeInfo()
TypeInfo ("property")
Type info.
operator=() [1/2]
property& operator= (const property &) default
Default copy assignment.
operator=() [2/2]
property& operator= (property &&) default
Default move assignment.
numMaterials()
auto numMaterials () const inline
Return number of materials.
Definition at line 111 of file property.hpp.
References property::numMaterials_.
Referenced by shape::propIdValid().
materials()
const auto& materials () const inline
Return list of material names.
Definition at line 117 of file property.hpp.
References property::materials_.
Referenced by geometry::createPropertyId().
densities()
const auto& densities () const inline
Return the list of densities.
Definition at line 122 of file property.hpp.
References property::densities_.
material() [1/2]
const word& material (uint32 i) const inline
Return the material name of material i.
Definition at line 127 of file property.hpp.
References property::materials_.
Referenced by property::material().
material() [2/2]
bool material (uint32 i, word & name) const inline
Get the name of material i.
Return true, if i is in the range and otherwise false
Definition at line 134 of file property.hpp.
References property::material(), iEntry::name(), and property::numMaterials_.
density() [1/2]
real density (uint32 i) const inline
Return density of material i.
Definition at line 149 of file property.hpp.
References property::densities_.
Referenced by property::density(), and shape::indexToDensity().
density() [2/2]
bool density (uint32 i, real & rho) const inline
Get the density of material i.
Return true, if i is in the range and otherwise false
Definition at line 156 of file property.hpp.
References property::density(), and property::numMaterials_.
nameToIndex()
bool nameToIndex (const word & name, uint32 & idx) const inline
Get the name of material in index idx Return true, if the name found, otherwise false.
Definition at line 172 of file property.hpp.
References iEntry::name(), and property::nameIndex_.
Referenced by geometry::createPropertyId(), and shape::findPropertyIds().
Member Data Documentation
materials_
wordVector materials_ private
list of name of materials
Definition at line 46 of file property.hpp.
Referenced by property::material(), property::materials(), and property::readDictionary().
densities_
realVector densities_ private
list of density of materials
Definition at line 49 of file property.hpp.
Referenced by property::densities(), property::density(), and property::readDictionary().
nameIndex_
wordHashMap<uint32> nameIndex_ private
rapid mapping from name to index
Definition at line 52 of file property.hpp.
Referenced by property::nameToIndex().
numMaterials_
uint32 numMaterials_ = 0 private
number of materials
Definition at line 56 of file property.hpp.
Referenced by property::density(), property::material(), and property::numMaterials().
The documentation for this class was generated from the following files:
src/Property/property.hpp
src/Property/property.cpp