PhasicFlow: AdamsBashforth3 Class Reference
AdamsBashforth3 Class Reference
Third order Adams-Bashforth integration method for solving ODE.
Public Member Functions
TypeInfo ("AdamsBashforth3")
AdamsBashforth3 (const word &baseName, repository &owner, const pointStructure &pStruct, const word &method)
Construct from components.
uniquePtr< integration > clone () const override
Polymorphic copy/cloning.
virtual ~AdamsBashforth3 ()=default
Destructor.
add_vCtor (integration, AdamsBashforth3, word)
Add this to the virtual constructor table.
bool predict (real UNUSED(dt), realx3Vector_D &UNUSED(y), realx3Vector_D &UNUSED(dy)) override
bool correct (real dt, realx3Vector_D &y, realx3Vector_D &dy) override
Correction/main integration step.
bool setInitialVals (const int32IndexContainer &newIndices, const realx3Vector &y) override
Set the initial values for new indices.
bool needSetInitialVals () const override
Check if the method requires any set initial vals.
bool intAll (real dt, realx3Vector_D &y, realx3Vector_D &dy, range activeRng)
Integrate on all points in the active range.
template<typename activeFunctor >
bool intRange (real dt, realx3Vector_D &y, realx3Vector_D &dy, activeFunctor activeP)
Integrate on active points in the active range.
Public Member Functions inherited from integration
TypeInfo ("integration")
Type info.
integration (const word &baseName, repository &owner, const pointStructure &pStruct, const word &method)
Construct from components.
integration (const integration &)=default
Copy constructor.
integration (integration &&)=default
Move constructor.
integration & operator= (const integration &)=default
Copy assignment.
integration & operator= (integration &&)=default
Move assignment.
virtual ~integration ()=default
Destructor.
create_vCtor (integration, word,(const word &baseName, repository &owner, const pointStructure &pStruct, const word &method),(baseName, owner, pStruct, method))
Add a virtual constructor.
const auto & pStruct () const
Const ref to pointStructure.
const word & baseName () const
Base name.
repository & owner ()
Ref to the owner repository.
virtual bool predict (real dt, realx3Vector_D &y, realx3Vector_D &dy)=0
Prediction step in integration.
Protected Types
using rpIntegration = Kokkos::RangePolicy< DefaultExecutionSpace, Kokkos::Schedule< Kokkos::Static >, Kokkos::IndexType< int32 > >
Range policy for integration kernel.
Protected Attributes
pointField< VectorSingle, AB3History > & history_
Integration history.
Protected Attributes inherited from integration
repository & owner_
The owner repository that all fields are storred in.
const word baseName_
The base name for integration.
const pointStructure & pStruct_
A reference to pointStructure.
Additional Inherited Members
Static Public Member Functions inherited from integration
static uniquePtr< integration > create (const word &baseName, repository &owner, const pointStructure &pStruct, const word &method)
Create the polymorphic object based on inputs.
Detailed Description
Third order Adams-Bashforth integration method for solving ODE.
This is a one-step integration method and does not have prediction step.
Definition at line 73 of file AdamsBashforth3.hpp.
Member Typedef Documentation
rpIntegration
using rpIntegration = Kokkos::RangePolicy< DefaultExecutionSpace, Kokkos::Schedule<Kokkos::Static>, Kokkos::IndexType<int32> > protected
Range policy for integration kernel.
Definition at line 87 of file AdamsBashforth3.hpp.
Constructor & Destructor Documentation
AdamsBashforth3()
AdamsBashforth3 (const word & baseName, repository & owner, const pointStructure & pStruct, const word & method)
Construct from components.
Definition at line 26 of file AdamsBashforth3.cpp.
References pFlow::zero3.
~AdamsBashforth3()
virtual ~AdamsBashforth3 () virtual default
Destructor.
Member Function Documentation
TypeInfo()
TypeInfo ("AdamsBashforth3")
clone()
uniquePtr<integration> clone () const inline override virtual
Polymorphic copy/cloning.
Implements integration.
Definition at line 103 of file AdamsBashforth3.hpp.
add_vCtor()
add_vCtor (integration , AdamsBashforth3 , word)
Add this to the virtual constructor table.
predict()
bool predict (real UNUSEDdt, realx3Vector_D & UNUSEDy, realx3Vector_D & UNUSEDdy) override
Definition at line 49 of file AdamsBashforth3.cpp.
correct()
bool correct (real dt, realx3Vector_D & y, realx3Vector_D & dy) override virtual
Correction/main integration step.
Implements integration.
Definition at line 60 of file AdamsBashforth3.cpp.
References pStruct.
setInitialVals()
bool setInitialVals (const int32IndexContainer & newIndices, const realx3Vector & y) override virtual
Set the initial values for new indices.
Implements integration.
Definition at line 79 of file AdamsBashforth3.cpp.
needSetInitialVals()
bool needSetInitialVals () const inline override virtual
Check if the method requires any set initial vals.
Implements integration.
Definition at line 133 of file AdamsBashforth3.hpp.
intAll()
bool intAll (real dt, realx3Vector_D & y, realx3Vector_D & dy, range activeRng)
Integrate on all points in the active range.
Definition at line 86 of file AdamsBashforth3.cpp.
References VectorSingle< T, MemorySpace >::deviceVectorAll(), and LAMBDA_HD.
intRange()
bool intRange (real dt, realx3Vector_D & y, realx3Vector_D & dy, activeFunctor activeP)
Integrate on active points in the active range.
Definition at line 157 of file AdamsBashforth3.hpp.
References pointField< VectorField, T, MemorySpace >::activeRange(), VectorSingle< T, MemorySpace >::deviceVectorAll(), and LAMBDA_HD.
Member Data Documentation
history_
pointField<VectorSingle,AB3History>& history_ protected
Integration history.
Definition at line 80 of file AdamsBashforth3.hpp.
The documentation for this class was generated from the following files:
src/Integration/AdamsBashforth3/AdamsBashforth3.hpp
src/Integration/AdamsBashforth3/AdamsBashforth3.cpp