PhasicFlow: periodicBoundaryField< T, MemorySpace > Class Template Reference
periodicBoundaryField< T, MemorySpace > Class Template Reference
Public Types
using periodicBoundaryFieldType = periodicBoundaryField< T, MemorySpace >
using BoundaryFieldType = boundaryField< T, MemorySpace >
using InternalFieldType = typename BoundaryFieldType::InternalFieldType
using memory_space = typename BoundaryFieldType::memory_space
using execution_space = typename BoundaryFieldType::execution_space
Public Types inherited from boundaryField< T, void >
using BoundaryFieldType = boundaryField< T, void >
using InternalFieldType = internalField< T, void >
using memory_space = typename InternalFieldType::memory_space
using execution_space = typename InternalFieldType::execution_space
using FieldAccessType = scatteredFieldAccess< T, memory_space >
using ProcVectorType = VectorSingle< T, void >
Public Member Functions
TypeInfoTemplate211 ("boundaryField","periodic", T, memory_space::name())
periodicBoundaryField (const boundaryBase &boundary, const pointStructure &pStruct, InternalFieldType &internal)
add_vCtor (BoundaryFieldType, periodicBoundaryFieldType, boundaryBase)
bool hearChanges (real t, real dt, uint32 iter, const message &msg, const anyList &varList) override
Public Member Functions inherited from boundaryField< T, void >
TypeInfoTemplate211 ("boundaryField","none", T, memory_space::name())
boundaryField (const boundaryBase &boundary, const pointStructure &pStruct, InternalFieldType &internal)
create_vCtor (boundaryField, boundaryBase,(const boundaryBase &boundary, const pointStructure &pStruct, InternalFieldType &internal),(boundary, pStruct, internal))
add_vCtor (BoundaryFieldType, BoundaryFieldType, boundaryBase)
bool hearChanges (real t, real dt, uint32 iter, const message &msg, const anyList &varList) override
InternalFieldType & internal ()
const InternalFieldType & internal () const
word fieldName () const
word name () const
FieldAccessType thisField () const
FieldAccessType mirrorField () const
virtual ProcVectorType & neighborProcField ()
virtual const ProcVectorType & neighborProcField () const
virtual void fill (const T &val)
Public Member Functions inherited from generalBoundary
TypeInfo ("generalBoundary")
generalBoundary (const boundaryBase &boundary, const pointStructure &pStruct, const word &dataType, const word &option)
~generalBoundary () override=default
uint32 thisBoundaryIndex () const
uint32 mirrorBoundaryindex () const
auto size () const
auto capacity () const
auto neighborProcSize () const
int neighborProcessorNo () const
int thisProcessorNo () const
const auto & boundary () const
const auto & indexList () const
const auto & mirrorBoundary () const
const word & boundaryName () const
const word & type () const
const auto & pStruct () const
bool isBoundaryMaster () const
const Time & time () const
Public Member Functions inherited from observer
observer (message msg)
observer (const subscriber *subscrbr, message msg)
virtual ~observer ()
void subscribe (const subscriber *subscrbr, message msg)
observer & addEvent (message::EVENT event)
bool subscribed () const
void addToSubscriber (const subscriber *subscrbr, message msg)
bool addToSubscriber (const subscriber &subscriber)
Additional Inherited Members
Static Public Member Functions inherited from boundaryField< T, void >
static uniquePtr< boundaryField > create (const boundaryBase &boundary, const pointStructure &pStruct, InternalFieldType &internal)
Static Public Member Functions inherited from observer
static constexpr auto numEvents ()
Detailed Description
template<class T, class MemorySpace = void>
class pFlow::periodicBoundaryField< T, MemorySpace >
Definition at line 29 of file periodicBoundaryField.hpp.
Member Typedef Documentation
periodicBoundaryFieldType
using periodicBoundaryFieldType = periodicBoundaryField<T, MemorySpace>
Definition at line 35 of file periodicBoundaryField.hpp.
BoundaryFieldType
using BoundaryFieldType = boundaryField<T, MemorySpace>
Definition at line 37 of file periodicBoundaryField.hpp.
InternalFieldType
using InternalFieldType = typename BoundaryFieldType::InternalFieldType
Definition at line 39 of file periodicBoundaryField.hpp.
memory_space
using memory_space = typename BoundaryFieldType::memory_space
Definition at line 41 of file periodicBoundaryField.hpp.
execution_space
using execution_space = typename BoundaryFieldType::execution_space
Definition at line 43 of file periodicBoundaryField.hpp.
Constructor & Destructor Documentation
periodicBoundaryField()
periodicBoundaryField (const boundaryBase & boundary, const pointStructure & pStruct, InternalFieldType & internal)
Definition at line 22 of file periodicBoundaryField.cpp.
References observer::addEvent().
Member Function Documentation
TypeInfoTemplate211()
TypeInfoTemplate211 ("boundaryField" , "periodic" , T , memory_space::name())
add_vCtor()
add_vCtor (BoundaryFieldType , periodicBoundaryFieldType , boundaryBase)
hearChanges()
bool hearChanges (real t, real dt, uint32 iter, const message & msg, const anyList & varList) inline override virtual
Implements observer.
Definition at line 66 of file periodicBoundaryField.hpp.
References message::BNDR_APPEND, message::BNDR_TRANSFER, message::equivalentTo(), and boundaryField< T, MemorySpace >::hearChanges().
The documentation for this class was generated from the following files:
src/phasicFlow/containers/pointField/boundaryField/periodicBoundaryField/periodicBoundaryField.hpp
src/phasicFlow/containers/pointField/boundaryField/periodicBoundaryField/periodicBoundaryField.cpp