PhasicFlow: boundaryGrainParticles Class Reference
boundaryGrainParticles Class Reference
Public Member Functions
TypeInfo ("boundaryGrainParticles<none>")
type info
boundaryGrainParticles (const boundaryBase &boundary, grainParticles &prtcls)
create_vCtor (boundaryGrainParticles, boundaryBase,(const boundaryBase &boundary, grainParticles &prtcls),(boundary, prtcls))
add_vCtor (boundaryGrainParticles, boundaryGrainParticles, boundaryBase)
grainParticles & Particles ()
const grainParticles & Particles () const
bool hearChanges (real t, real dt, uint32 iter, const message &msg, const anyList &varList) override
virtual bool acceleration (const timeInfo &ti, const realx3 &g)
Public Member Functions inherited from generalBoundary
TypeInfo ("generalBoundary")
generalBoundary (const boundaryBase &boundary, const pointStructure &pStruct, const word &dataType, const word &option)
~generalBoundary () override=default
uint32 thisBoundaryIndex () const
uint32 mirrorBoundaryindex () const
auto size () const
auto capacity () const
auto neighborProcSize () const
int neighborProcessorNo () const
int thisProcessorNo () const
const auto & boundary () const
const auto & indexList () const
const auto & mirrorBoundary () const
const word & boundaryName () const
const word & type () const
const auto & pStruct () const
bool isBoundaryMaster () const
const Time & time () const
Public Member Functions inherited from observer
observer (message msg)
observer (const subscriber *subscrbr, message msg)
virtual ~observer ()
void subscribe (const subscriber *subscrbr, message msg)
observer & addEvent (message::EVENT event)
bool subscribed () const
void addToSubscriber (const subscriber *subscrbr, message msg)
bool addToSubscriber (const subscriber &subscriber)
Static Public Member Functions
static uniquePtr< boundaryGrainParticles > create (const boundaryBase &boundary, grainParticles &prtcls)
Static Public Member Functions inherited from observer
static constexpr auto numEvents ()
Private Attributes
grainParticles & particles_
Detailed Description
Definition at line 15 of file boundaryGrainParticles.hpp.
Constructor & Destructor Documentation
boundaryGrainParticles()
boundaryGrainParticles (const boundaryBase & boundary, grainParticles & prtcls)
Definition at line 6 of file boundaryGrainParticles.cpp.
Member Function Documentation
TypeInfo()
TypeInfo ("boundaryGrainParticles<none>")
type info
create_vCtor()
create_vCtor (boundaryGrainParticles , boundaryBase , (const boundaryBase &boundary, grainParticles &prtcls) , (boundary, prtcls))
add_vCtor()
add_vCtor (boundaryGrainParticles , boundaryGrainParticles , boundaryBase)
Particles() [1/2]
const pFlow::grainParticles & Particles ()
Definition at line 17 of file boundaryGrainParticles.cpp.
Particles() [2/2]
const grainParticles& Particles () const
hearChanges()
bool hearChanges (real t, real dt, uint32 iter, const message & msg, const anyList & varList) inline override virtual
Implements observer.
Definition at line 52 of file boundaryGrainParticles.hpp.
acceleration()
virtual bool acceleration (const timeInfo & ti, const realx3 & g) inline virtual
Definition at line 63 of file boundaryGrainParticles.hpp.
create()
pFlow::uniquePtr< pFlow::boundaryGrainParticles > create (const boundaryBase & boundary, grainParticles & prtcls) static
Definition at line 27 of file boundaryGrainParticles.cpp.
References pFlow::angleBracketsNames2(), pFlow::endl(), fatalError, fatalExit, Green_Text, boundaryBase::name(), pFlow::pFlowProcessors(), pFlow::pOutput, pFlow::printKeys(), iOstream::space(), and boundaryBase::type().
Referenced by boundaryGrainParticlesList::boundaryGrainParticlesList().
Member Data Documentation
particles_
grainParticles& particles_ private
Definition at line 20 of file boundaryGrainParticles.hpp.
The documentation for this class was generated from the following files:
src/Particles/GrainParticles/boundaryGrainParticles.hpp
src/Particles/GrainParticles/boundaryGrainParticles.cpp