PhasicFlow: vtkFile Class Reference
vtkFile Class Reference
Public Member Functions
vtkFile (const fileSystem dir, const word &bName, real time, bool bnry, bool append=false)
virtual ~vtkFile ()=default
oFstream & operator() ()
operator bool () const
bool operator! () const
bool binary () const
virtual fileSystem fileName () const
Protected Member Functions
bool openStream (bool wHeader)
virtual bool writeHeader ()
Protected Attributes
uniquePtr< oFstream > oStream_ = nullptr
bool binary_ = false
bool append_ =false
real time_ = 0.0
fileSystem dirPath_
word baseName_
Detailed Description
Definition at line 33 of file vtkFile.hpp.
Constructor & Destructor Documentation
vtkFile()
vtkFile (const fileSystem dir, const word & bName, real time, bool bnry, bool append = false)
Definition at line 54 of file vtkFile.cpp.
References pFlow::endl(), fatalErrorInFunction, and fatalExit.
~vtkFile()
virtual ~vtkFile () virtual default
Member Function Documentation
openStream()
bool openStream (bool wHeader) protected
Definition at line 24 of file vtkFile.cpp.
References vtkFile::append_, vtkFile::binary_, vtkFile::fileName(), vtkFile::oStream_, and vtkFile::writeHeader().
Referenced by vtkFile::operator()().
writeHeader()
virtual bool writeHeader () protected virtual
Referenced by vtkFile::openStream().
operator()()
oFstream& operator() () inline
Definition at line 64 of file vtkFile.hpp.
References vtkFile::append_, pFlow::endl(), fatalErrorInFunction, fatalExit, vtkFile::fileName(), vtkFile::openStream(), and vtkFile::oStream_.
operator bool()
operator bool () const inline explicit
Definition at line 78 of file vtkFile.hpp.
References vtkFile::oStream_.
operator!()
bool operator! () const inline
Definition at line 85 of file vtkFile.hpp.
References vtkFile::oStream_.
binary()
bool binary () const inline
Definition at line 94 of file vtkFile.hpp.
References vtkFile::binary_.
fileName()
pFlow::fileSystem fileName () const virtual
Definition at line 79 of file vtkFile.cpp.
References pFlow::int322Word().
Referenced by pFlow::TSFtoVTK::convertRealx3TypetriSurfaceFieldSeparate(), pFlow::PFtoVTK::convertTimeFolderPointFields(), pFlow::PFtoVTK::convertTimeFolderPointFieldsSelected(), pFlow::TSFtoVTK::convertTimeFolderTriSurfaceFieldsSeparate(), pFlow::TSFtoVTK::convertTimeFolderTriSurfaceFieldsSingle(), vtkFile::openStream(), and vtkFile::operator()().
Member Data Documentation
oStream_
uniquePtr<oFstream> oStream_ = nullptr protected
Definition at line 37 of file vtkFile.hpp.
Referenced by vtkFile::openStream(), vtkFile::operator bool(), vtkFile::operator!(), and vtkFile::operator()().
binary_
bool binary_ = false protected
Definition at line 39 of file vtkFile.hpp.
Referenced by vtkFile::binary(), and vtkFile::openStream().
append_
bool append_ =false protected
Definition at line 41 of file vtkFile.hpp.
Referenced by vtkFile::openStream(), and vtkFile::operator()().
time_
real time_ = 0.0 protected
Definition at line 43 of file vtkFile.hpp.
dirPath_
fileSystem dirPath_ protected
Definition at line 45 of file vtkFile.hpp.
baseName_
word baseName_ protected
Definition at line 47 of file vtkFile.hpp.
The documentation for this class was generated from the following files:
utilities/Utilities/vtkFile/vtkFile.hpp
utilities/Utilities/vtkFile/vtkFile.cpp