PhasicFlow: periodicBoundarySphereInteraction< contactForceModel, geometryMotionModel > Class Template Reference
periodicBoundarySphereInteraction< contactForceModel, geometryMotionModel > Class Template Reference
Public Types
using PBSInteractionType = periodicBoundarySphereInteraction< contactForceModel, geometryMotionModel >
using BSInteractionType = boundarySphereInteraction< contactForceModel, geometryMotionModel >
using GeometryMotionModel = typename BSInteractionType::GeometryMotionModel
using ContactForceModel = typename BSInteractionType::ContactForceModel
using MotionModel = typename geometryMotionModel::MotionModel
using ModelStorage = typename ContactForceModel::contactForceStorage
using IdType = typename BSInteractionType::IdType
using IndexType = typename BSInteractionType::IndexType
using ContactListType = typename BSInteractionType::ContactListType
Public Types inherited from boundarySphereInteraction< contactForceModel, geometryMotionModel >
using BoundarySphereInteractionType = boundarySphereInteraction< contactForceModel, geometryMotionModel >
using GeometryMotionModel = geometryMotionModel
using ContactForceModel = contactForceModel
using MotionModel = typename geometryMotionModel::MotionModel
using ModelStorage = typename ContactForceModel::contactForceStorage
using IdType = uint32
using IndexType = uint32
using ContactListType = sortedContactList< ModelStorage, DefaultExecutionSpace, IdType >
Public Member Functions
TypeInfoTemplate22 ("boundarySphereInteraction", "periodic", ContactForceModel, MotionModel)
periodicBoundarySphereInteraction (const boundaryBase &boundary, const sphereParticles &sphPrtcls, const GeometryMotionModel &geomMotion)
add_vCtor (BSInteractionType, PBSInteractionType, boundaryBase)
~periodicBoundarySphereInteraction () override=default
bool sphereSphereInteraction (real dt, const ContactForceModel &cfModel, uint32 step) override
Public Member Functions inherited from boundarySphereInteraction< contactForceModel, geometryMotionModel >
TypeInfoTemplate12 ("boundarySphereInteraction", ContactForceModel, MotionModel)
boundarySphereInteraction (const boundaryBase &boundary, const sphereParticles &sphPrtcls, const GeometryMotionModel &geomMotion)
create_vCtor (BoundarySphereInteractionType, boundaryBase,(const boundaryBase &boundary, const sphereParticles &sphPrtcls, const GeometryMotionModel &geomMotion),(boundary, sphPrtcls, geomMotion))
add_vCtor (BoundarySphereInteractionType, BoundarySphereInteractionType, boundaryBase)
~boundarySphereInteraction () override=default
const auto & sphParticles () const
const auto & geometryMotion () const
ContactListType & ppPairs ()
const ContactListType & ppPairs () const
ContactListType & pwPairs ()
const ContactListType & pwPairs () const
bool ppPairsAllocated () const
bool pwPairsAllocated () const
bool hearChanges (real t, real dt, uint32 iter, const message &msg, const anyList &varList) override
Public Member Functions inherited from generalBoundary
TypeInfo ("generalBoundary")
generalBoundary (const boundaryBase &boundary, const pointStructure &pStruct, const word &dataType, const word &option)
~generalBoundary () override=default
uint32 thisBoundaryIndex () const
uint32 mirrorBoundaryindex () const
auto size () const
auto capacity () const
auto neighborProcSize () const
int neighborProcessorNo () const
int thisProcessorNo () const
const auto & boundary () const
const auto & indexList () const
const auto & mirrorBoundary () const
const word & boundaryName () const
const word & type () const
const auto & pStruct () const
bool isBoundaryMaster () const
const Time & time () const
Public Member Functions inherited from observer
observer (message msg)
observer (const subscriber *subscrbr, message msg)
virtual ~observer ()
void subscribe (const subscriber *subscrbr, message msg)
observer & addEvent (message::EVENT event)
bool subscribed () const
void addToSubscriber (const subscriber *subscrbr, message msg)
bool addToSubscriber (const subscriber &subscriber)
Private Attributes
realx3 transferVec_
bool masterInteraction_
Additional Inherited Members
Static Public Member Functions inherited from boundarySphereInteraction< contactForceModel, geometryMotionModel >
static uniquePtr< BoundarySphereInteractionType > create (const boundaryBase &boundary, const sphereParticles &sphPrtcls, const GeometryMotionModel &geomMotion)
Static Public Member Functions inherited from observer
static constexpr auto numEvents ()
Protected Member Functions inherited from boundarySphereInteraction< contactForceModel, geometryMotionModel >
void allocatePPPairs ()
void allocatePWPairs ()
Detailed Description
template<typename contactForceModel, typename geometryMotionModel>
class pFlow::periodicBoundarySphereInteraction< contactForceModel, geometryMotionModel >
Definition at line 30 of file periodicBoundarySphereInteraction.hpp.
Member Typedef Documentation
PBSInteractionType
using PBSInteractionType = periodicBoundarySphereInteraction<contactForceModel,geometryMotionModel>
Definition at line 37 of file periodicBoundarySphereInteraction.hpp.
BSInteractionType
using BSInteractionType = boundarySphereInteraction<contactForceModel, geometryMotionModel>
Definition at line 40 of file periodicBoundarySphereInteraction.hpp.
GeometryMotionModel
using GeometryMotionModel = typename BSInteractionType::GeometryMotionModel
Definition at line 42 of file periodicBoundarySphereInteraction.hpp.
ContactForceModel
using ContactForceModel = typename BSInteractionType::ContactForceModel
Definition at line 44 of file periodicBoundarySphereInteraction.hpp.
MotionModel
using MotionModel = typename geometryMotionModel::MotionModel
Definition at line 46 of file periodicBoundarySphereInteraction.hpp.
ModelStorage
using ModelStorage = typename ContactForceModel::contactForceStorage
Definition at line 48 of file periodicBoundarySphereInteraction.hpp.
IdType
using IdType = typename BSInteractionType::IdType
Definition at line 50 of file periodicBoundarySphereInteraction.hpp.
IndexType
using IndexType = typename BSInteractionType::IndexType
Definition at line 52 of file periodicBoundarySphereInteraction.hpp.
ContactListType
using ContactListType = typename BSInteractionType::ContactListType
Definition at line 54 of file periodicBoundarySphereInteraction.hpp.
Constructor & Destructor Documentation
periodicBoundarySphereInteraction()
periodicBoundarySphereInteraction (const boundaryBase & boundary, const sphereParticles & sphPrtcls, const GeometryMotionModel & geomMotion)
Definition at line 24 of file periodicBoundarySphereInteraction.cpp.
References boundarySphereInteraction< contactForceModel, geometryMotionModel >::allocatePPPairs(), boundarySphereInteraction< contactForceModel, geometryMotionModel >::allocatePWPairs(), generalBoundary::boundary(), and periodicBoundarySphereInteraction< contactForceModel, geometryMotionModel >::masterInteraction_.
~periodicBoundarySphereInteraction()
~periodicBoundarySphereInteraction () override default
Member Function Documentation
TypeInfoTemplate22()
TypeInfoTemplate22 ("boundarySphereInteraction" , "periodic" , ContactForceModel , MotionModel)
add_vCtor()
add_vCtor (BSInteractionType , PBSInteractionType , boundaryBase)
sphereSphereInteraction()
bool sphereSphereInteraction (real dt, const ContactForceModel & cfModel, uint32 step) override virtual
Reimplemented from boundarySphereInteraction< contactForceModel, geometryMotionModel >.
Definition at line 46 of file periodicBoundarySphereInteraction.cpp.
References pFlow::periodicBoundarySIKernels::sphereSphereInteraction(), and sphParticles.
Member Data Documentation
transferVec_
realx3 transferVec_ private
Definition at line 58 of file periodicBoundarySphereInteraction.hpp.
masterInteraction_
bool masterInteraction_ private
Definition at line 60 of file periodicBoundarySphereInteraction.hpp.
Referenced by periodicBoundarySphereInteraction< contactForceModel, geometryMotionModel >::periodicBoundarySphereInteraction().
The documentation for this class was generated from the following files:
src/Interaction/sphereInteraction/boundaries/periodicBoundarySphereInteraction/periodicBoundarySphereInteraction.hpp
src/Interaction/sphereInteraction/boundaries/periodicBoundarySphereInteraction/periodicBoundarySphereInteraction.cpp