PhasicFlow: zAxis Class Reference
zAxis Class Reference
Public Member Functions
zAxis (const realx3 &lp1, const realx3 &lp2)
real length () const
realx3 transferToZ (const realx3 &p) const
realx3 transferBackZ (const realx3 &p) const
Private Types
using ArrayType = array2D< real, 3uL, 3uL >
Private Member Functions
void makeTransMatrix (const realx3 &v)
Private Attributes
realx3 p1_
the origin of the transformed coord
realx3 p2_
the direction vector of rotated coordinates
ArrayType rotMat_
transformation matrix to rotate original coordinates to rotated coordinates
ArrayType invRotMat_
rotation matrix to rotate back from rotated coordinates to the original axis
Detailed Description
Definition at line 38 of file zAxis.hpp.
Member Typedef Documentation
ArrayType
using ArrayType = array2D<real,3uL,3uL> private
Definition at line 43 of file zAxis.hpp.
Constructor & Destructor Documentation
zAxis()
zAxis (const realx3 & lp1, const realx3 & lp2)
Definition at line 25 of file zAxis.cpp.
References pFlow::endl(), pFlow::equal(), fatalErrorInFunction, fatalExit, and zAxis::makeTransMatrix().
Member Function Documentation
makeTransMatrix()
void makeTransMatrix (const realx3 & v) private
Definition at line 61 of file zAxis.cpp.
References pFlow::abs(), cross(), dot(), normalize(), pFlow::smallValue, and pFlow::transpose().
Referenced by zAxis::zAxis().
length()
real length () const inline
Definition at line 66 of file zAxis.hpp.
References length(), zAxis::p1_, and zAxis::p2_.
Referenced by cylinderWall::createCylinder().
transferToZ()
pFlow::realx3 transferToZ (const realx3 & p) const
Definition at line 39 of file zAxis.cpp.
References pFlow::MatMul().
transferBackZ()
pFlow::realx3 transferBackZ (const realx3 & p) const
Definition at line 50 of file zAxis.cpp.
References pFlow::MatMul(), triple< T >::x(), triple< T >::y(), and triple< T >::z().
Referenced by cylinder::calculateParams(), and cylinderWall::createCylinder().
Member Data Documentation
p1_
realx3 p1_ private
the origin of the transformed coord
Definition at line 46 of file zAxis.hpp.
Referenced by zAxis::length().
p2_
realx3 p2_ private
the direction vector of rotated coordinates
Definition at line 49 of file zAxis.hpp.
Referenced by zAxis::length().
rotMat_
ArrayType rotMat_ private
transformation matrix to rotate original coordinates to rotated coordinates
Definition at line 53 of file zAxis.hpp.
invRotMat_
ArrayType invRotMat_ private
rotation matrix to rotate back from rotated coordinates to the original axis
Definition at line 57 of file zAxis.hpp.
The documentation for this class was generated from the following files:
src/phasicFlow/structuredData/zAxis/zAxis.hpp
src/phasicFlow/structuredData/zAxis/zAxis.cpp