PhasicFlow: uniformRandomUint32 Class Reference
uniformRandomUint32 Class Reference
Public Member Functions
TypeInfoNV ("uniform")
uniformRandomUint32 (uint32 min, uint32 max)
~uniformRandomUint32 ()=default
uint32 randomNumber ()
triple< uint32 > randomNumber3 ()
triple< uint32 > operator() ()
Protected Attributes
std::mt19937_64 engineGen_
std::uniform_int_distribution< uint32 > distrbution_
Detailed Description
Definition at line 32 of file uniformRandomUint32.hpp.
Constructor & Destructor Documentation
uniformRandomUint32()
uniformRandomUint32 (uint32 min, uint32 max) inline explicit
Definition at line 45 of file uniformRandomUint32.hpp.
~uniformRandomUint32()
~uniformRandomUint32 () default
Member Function Documentation
TypeInfoNV()
TypeInfoNV ("uniform")
randomNumber()
uint32 randomNumber () inline
Definition at line 53 of file uniformRandomUint32.hpp.
References uniformRandomUint32::distrbution_, and uniformRandomUint32::engineGen_.
Referenced by uniformRandomUint32::randomNumber3(), and selectorRandomPoints::selectAllPointsInRange().
randomNumber3()
triple<uint32> randomNumber3 () inline
Definition at line 58 of file uniformRandomUint32.hpp.
References uniformRandomUint32::randomNumber().
Referenced by uniformRandomUint32::operator()().
operator()()
triple<uint32> operator() () inline
Definition at line 68 of file uniformRandomUint32.hpp.
References uniformRandomUint32::randomNumber3().
Member Data Documentation
engineGen_
std::mt19937_64 engineGen_ protected
Definition at line 36 of file uniformRandomUint32.hpp.
Referenced by uniformRandomUint32::randomNumber().
distrbution_
std::uniform_int_distribution<uint32> distrbution_ protected
Definition at line 38 of file uniformRandomUint32.hpp.
Referenced by uniformRandomUint32::randomNumber().
The documentation for this class was generated from the following file:
src/phasicFlow/random/randomInt32/uniformRandomUint32.hpp