PhasicFlow: baseTimeControl Class Reference
baseTimeControl Class Reference
Public Member Functions
baseTimeControl (const dictionary &dict, const word &intervalPrefix="", real defStartTime=0.0)
baseTimeControl (int32 start, int32 end, int32 stride, const word &intervalPrefix="")
bool isTimeStep () const
bool timeEvent (uint32 iter, real t, real dt) const
bool isInRange (uint32 iter, real t, real dt) const
real startTime () const
real endTime () const
real rInterval () const
int32 startIter () const
int32 endIter () const
int32 iInterval () const
bool write (dictionary &dict) const
Private Attributes
bool isTimeStep_
int32StridedRagne iRange_
realStridedRange rRange_
const word intervalPrefix_
Detailed Description
Definition at line 29 of file baseTimeControl.hpp.
Constructor & Destructor Documentation
baseTimeControl() [1/2]
baseTimeControl (const dictionary & dict, const word & intervalPrefix = "", real defStartTime = 0.0)
Definition at line 25 of file baseTimeControl.cpp.
References pFlow::endl(), fatalErrorInFunction, fatalExit, dictionary::getVal(), dictionary::getValOrSet(), dictionary::globalName(), pFlow::largestPosInt32, and pFlow::largeValue.
baseTimeControl() [2/2]
baseTimeControl (int32 start, int32 end, int32 stride, const word & intervalPrefix = "")
Definition at line 68 of file baseTimeControl.cpp.
Member Function Documentation
isTimeStep()
bool isTimeStep () const inline
Definition at line 56 of file baseTimeControl.hpp.
References baseTimeControl::isTimeStep_.
timeEvent()
bool timeEvent (uint32 iter, real t, real dt) const
Definition at line 78 of file baseTimeControl.cpp.
Referenced by insertionRegion::insertionTime(), and pointSorting::sortTime().
isInRange()
bool isInRange (uint32 iter, real t, real dt) const
Definition at line 92 of file baseTimeControl.cpp.
startTime()
pFlow::real startTime () const
Definition at line 105 of file baseTimeControl.cpp.
References pFlow::endl(), fatalErrorInFunction, and fatalExit.
endTime()
pFlow::real endTime () const
Definition at line 118 of file baseTimeControl.cpp.
References pFlow::endl(), fatalErrorInFunction, and fatalExit.
rInterval()
pFlow::real rInterval () const
Definition at line 131 of file baseTimeControl.cpp.
References pFlow::endl(), fatalErrorInFunction, and fatalExit.
startIter()
pFlow::int32 startIter () const
Definition at line 143 of file baseTimeControl.cpp.
References pFlow::endl(), fatalErrorInFunction, and fatalExit.
endIter()
pFlow::int32 endIter () const
Definition at line 155 of file baseTimeControl.cpp.
References pFlow::endl(), fatalErrorInFunction, and fatalExit.
iInterval()
pFlow::int32 iInterval () const
Definition at line 167 of file baseTimeControl.cpp.
References pFlow::endl(), fatalErrorInFunction, and fatalExit.
write()
bool write (dictionary & dict) const
Definition at line 179 of file baseTimeControl.cpp.
References dictionary::add().
Member Data Documentation
isTimeStep_
bool isTimeStep_ private
Definition at line 33 of file baseTimeControl.hpp.
Referenced by baseTimeControl::isTimeStep().
iRange_
int32StridedRagne iRange_ private
Definition at line 35 of file baseTimeControl.hpp.
rRange_
realStridedRange rRange_ private
Definition at line 37 of file baseTimeControl.hpp.
intervalPrefix_
const word intervalPrefix_ private
Definition at line 39 of file baseTimeControl.hpp.
The documentation for this class was generated from the following files:
src/phasicFlow/repository/Time/baseTimeControl.hpp
src/phasicFlow/repository/Time/baseTimeControl.cpp