PhasicFlow: Logical Class Reference
Logical Class Reference
Holds a bool value and converts strings to bool.
Public Member Functions
word typeName () const
Logical ()=default
Default constructor.
Logical (bool s)
Construct from bool.
Logical (const word &l)
Construct from word.
Logical (const char *ch)
Construct from char string.
Logical (const Logical &)=default
Copy.
Logical (Logical &&)=default
Move.
Logical & operator= (const Logical &)=default
Copy assignment.
Logical & operator= (Logical &&)=default
Move assignment.
Logical & operator= (const bool &b)
Assignment with bool.
bool operator() () const
() operator, return bool value
operator bool () const
Return bool value.
Logical operator! () const
Not operator.
bool read (iIstream &is)
bool write (iOstream &os) const
Static Public Member Functions
static word TYPENAME ()
Type info.
static bool evaluteWord (const word &l, bool &b, int &yesNoSet)
Private Member Functions
Logical (bool s, int yns)
Construct from bool and set number.
Private Attributes
bool s_ = false
bool value
int yesNoSet_ = 0
Set numbe of of Yes or No.
Static Private Attributes
static const word YesNo__ [4][2]
Set of Yes or Nos.
Detailed Description
Holds a bool value and converts strings to bool.
Definition at line 39 of file Logical.hpp.
Constructor & Destructor Documentation
Logical() [1/7]
Logical (bool s, int yns) inline explicit private
Construct from bool and set number.
Definition at line 56 of file Logical.hpp.
Logical() [2/7]
Logical () inline default
Default constructor.
Referenced by Logical::operator!().
Logical() [3/7]
Logical (bool s) inline explicit
Construct from bool.
Definition at line 81 of file Logical.hpp.
Logical() [4/7]
Logical (const word & l)
Construct from word.
Definition at line 26 of file Logical.cpp.
References pFlow::endl(), Logical::evaluteWord(), fatalErrorInFunction, fatalExit, Logical::s_, and Logical::yesNoSet_.
Logical() [5/7]
Logical (const char * ch)
Construct from char string.
Definition at line 35 of file Logical.cpp.
Logical() [6/7]
Logical (const Logical &) default
Copy.
Logical() [7/7]
Logical (Logical &&) default
Move.
Member Function Documentation
TYPENAME()
static word TYPENAME () inline static
Type info.
Definition at line 65 of file Logical.hpp.
Referenced by Logical::typeName().
typeName()
word typeName () const inline
Definition at line 70 of file Logical.hpp.
References Logical::TYPENAME().
operator=() [1/3]
Logical& operator= (const Logical &) default
Copy assignment.
operator=() [2/3]
Logical& operator= (Logical &&) default
Move assignment.
operator=() [3/3]
Logical& operator= (const bool & b) inline
Assignment with bool.
Definition at line 105 of file Logical.hpp.
References Logical::s_, and Logical::yesNoSet_.
operator()()
bool operator() () const inline
() operator, return bool value
Definition at line 115 of file Logical.hpp.
References Logical::s_.
operator bool()
operator bool () const inline explicit
Return bool value.
Definition at line 121 of file Logical.hpp.
References Logical::s_.
operator!()
Logical operator! () const inline
Not operator.
Definition at line 127 of file Logical.hpp.
References Logical::Logical(), Logical::s_, and Logical::yesNoSet_.
read()
bool read (iIstream & is)
Definition at line 65 of file Logical.cpp.
References token::good(), ioErrorInFile, token::isString(), token::isWord(), IOstream::lineNumber(), IOstream::name(), IOstream::setBad(), token::stringToken(), and token::wordToken().
Referenced by pFlow::operator>>().
write()
bool write (iOstream & os) const
Definition at line 97 of file Logical.cpp.
References IOstream::check(), and FUNCTION_NAME.
Referenced by pFlow::operator<<().
evaluteWord()
bool evaluteWord (const word & l, bool & b, int & yesNoSet) static
Definition at line 41 of file Logical.cpp.
References pFlow::toUpper().
Referenced by Logical::Logical().
Member Data Documentation
s_
bool s_ = false private
bool value
Definition at line 44 of file Logical.hpp.
Referenced by Logical::Logical(), Logical::operator bool(), Logical::operator!(), Logical::operator()(), and Logical::operator=().
yesNoSet_
int yesNoSet_ = 0 private
Set numbe of of Yes or No.
Definition at line 47 of file Logical.hpp.
Referenced by Logical::Logical(), Logical::operator!(), and Logical::operator=().
YesNo__
const word YesNo__[4][2] inline static private
Initial value:
= { { "Yes", "No" },
                                               { "on", "off" },
                                               { "true", "false" },
                                               { "Ok", "No" } }
Set of Yes or Nos.
Definition at line 50 of file Logical.hpp.
The documentation for this class was generated from the following files:
src/phasicFlow/types/basicTypes/Logical.hpp
src/phasicFlow/types/basicTypes/Logical.cpp