PhasicFlow: List< T > Class Template Reference
List< T > Class Template Reference
Public Types
using ListType = List< T >
using listType = std::list< T, std::allocator< T > >
using iterator = typename listType::iterator
using const_iterator = typename listType::const_iterator
using reference = typename listType::reference
using const_reference = typename listType::const_reference
using initList = typename std::initializer_list< T >
using valueType = T
Public Member Functions
TypeInfoTemplateNV11 ("List", T)
List ()
List (size_t len)
List (size_t len, const T &value)
List (initList lst)
List (const List &src)=default
List (List &&mv)=default
ListType & operator= (const ListType &rhs)=default
ListType & operator= (ListType &&rhs)=default
uniquePtr< ListType > clone () const
ListType * clonePtr () const
~List ()
int32 countElement (const T &elm) const
size_t size () const
auto pos (size_t i, bool noError=false)
const auto pos (size_t i, bool noError=false) const
T & operator[] (size_t i)
const T & operator[] (size_t i) const
const_iterator find (const T &val) const
iterator find (const T &val)
int32 findi (const T &val) const
bool search (const T &val) const
void set (size_t i, const T &val)
void set (size_t i, T &&val)
bool writeList (iOstream &os) const
bool readList (iIstream &is)
bool read (iIstream &is)
bool write (iOstream &os) const
Static Protected Member Functions
static size_t getListStride (const size_t &len)
Detailed Description
template<typename T>
class pFlow::List< T >
Definition at line 39 of file List.hpp.
Member Typedef Documentation
ListType
using ListType = List<T>
Definition at line 46 of file List.hpp.
listType
using listType = std::list<T,std::allocator<T> >
Definition at line 48 of file List.hpp.
iterator
using iterator = typename listType::iterator
Definition at line 50 of file List.hpp.
const_iterator
using const_iterator = typename listType::const_iterator
Definition at line 52 of file List.hpp.
reference
using reference = typename listType::reference
Definition at line 54 of file List.hpp.
const_reference
using const_reference = typename listType::const_reference
Definition at line 56 of file List.hpp.
initList
using initList = typename std::initializer_list<T>
Definition at line 58 of file List.hpp.
valueType
using valueType = T
Definition at line 60 of file List.hpp.
Constructor & Destructor Documentation
List() [1/6]
List () inline
Definition at line 89 of file List.hpp.
List() [2/6]
List (size_t len) inline
Definition at line 93 of file List.hpp.
List() [3/6]
List (size_t len, const T & value) inline
Definition at line 99 of file List.hpp.
List() [4/6]
List (initList< T > lst) inline
Definition at line 105 of file List.hpp.
List() [5/6]
List (const List< T > & src) default
List() [6/6]
List (List< T > && mv) default
~List()
~List () inline
Definition at line 136 of file List.hpp.
Member Function Documentation
getListStride()
static size_t getListStride (const size_t & len) inline static protected
Definition at line 66 of file List.hpp.
TypeInfoTemplateNV11()
TypeInfoTemplateNV11 ("List< T >" , T)
operator=() [1/2]
ListType& operator= (const ListType & rhs) default
operator=() [2/2]
ListType& operator= (ListType && rhs) default
clone()
uniquePtr<ListType> clone () const inline
Definition at line 126 of file List.hpp.
clonePtr()
ListType* clonePtr () const inline
Definition at line 130 of file List.hpp.
countElement()
pFlow::int32 countElement (const T & elm) const inline
Definition at line 74 of file ListI.hpp.
size()
size_t size inline
Definition at line 82 of file ListI.hpp.
Referenced by fileSeries::addTimeFile(), positionOrdered::findAxisIndex(), multiTriSurface::numSurfaces(), and anyList::size().
pos() [1/2]
auto pos (size_t i, bool noError = false)
Definition at line 23 of file ListI.hpp.
Referenced by anyList::getObject(), and anyList::getObjectPtr().
pos() [2/2]
const auto pos (size_t i, bool noError = false) const
Definition at line 48 of file ListI.hpp.
operator[]() [1/2]
T & operator[] (size_t i) inline
Definition at line 89 of file ListI.hpp.
operator[]() [2/2]
const T & operator[] (size_t i) const inline
Definition at line 98 of file ListI.hpp.
find() [1/2]
pFlow::List< T >::const_iterator find (const T & val) const inline
Definition at line 108 of file ListI.hpp.
Referenced by Timers::removeFromList().
find() [2/2]
pFlow::List< T >::iterator find (const T & val) inline
Definition at line 117 of file ListI.hpp.
findi()
pFlow::int32 findi (const T & val) const
Definition at line 125 of file ListI.hpp.
Referenced by anyList::getObject(), and multiRotatingAxisMotion::nameToIndex().
search()
bool search (const T & val) const
Definition at line 134 of file ListI.hpp.
set() [1/2]
void set (size_t i, const T & val) inline
Definition at line 144 of file ListI.hpp.
set() [2/2]
void set (size_t i, T && val) inline
Definition at line 151 of file ListI.hpp.
writeList()
bool writeList (iOstream & os) const inline
Definition at line 160 of file ListI.hpp.
Referenced by List< std::any >::write().
readList()
bool readList (iIstream & is) inline
Definition at line 194 of file ListI.hpp.
Referenced by List< std::any >::read().
read()
bool read (iIstream & is) inline
Definition at line 196 of file List.hpp.
write()
bool write (iOstream & os) const inline
Definition at line 201 of file List.hpp.
The documentation for this class was generated from the following files:
src/phasicFlow/containers/List/List/List.hpp
src/phasicFlow/containers/List/List/ListI.hpp