PhasicFlow: iTstream Class Reference
iTstream Class Reference
Input token stream.
Public Member Functions
iTstream (const word &streamName)
construct with a name
iTstream (const word &streamName, const tokenList &tList)
construct with name and copy
iTstream (const word &streamName, tokenList &&tList)
construct with name and move
iTstream (const iTstream &)=default
copy construct
iTstream (iTstream &&)=default
move construct
iTstream & operator= (const iTstream &)=default
copy assignment
iTstream & operator= (iTstream &&)=default
move assignment
void operator= (const tokenList &tList)
copy assignment from tokenList
void operator= (tokenList &&tList)
move assignment from tokenList
virtual ~iTstream ()=default
Destructor.
virtual const word & name () const
Return the name of the stream.
virtual word & name ()
Return non-const access to the name of the stream.
virtual iIstream & read (token &t) override
Return next token from stream.
virtual iIstream & read (char &c) override
Read a character.
virtual iIstream & read (word &str) override
Read a word.
virtual iIstream & readString (word &str) override
Read a string.
virtual iIstream & read (int64 &) override
Read a int64.
virtual iIstream & read (int32 &) override
Read a int32.
virtual iIstream & read (int8 &) override
Read a int8.
virtual iIstream & read (uint64 &) override
Read a uint64.
virtual iIstream & read (uint32 &) override
Read a uint32.
virtual iIstream & read (uint8 &) override
Read a uint8.
virtual iIstream & read (float &) override
Read a floatScalar.
virtual iIstream & read (double &) override
Read a doubleScalar.
iIstream & read (char *buffer, std::streamsize count) override
Write a block of binray data.
virtual void rewind () override
Rewind the stream so that it may be read again.
void seek (size_t pos) override
size_t tell () override
Return current position indicator.
virtual void reset ()
reset the iTstream and make the stream empty
const tokenList & tokens () const
const access to token list
size_t size () const
size
size_t numTokens () const
size
void appendTokens (const tokenList &tList)
append a list of tokens to the end of tokens
void appendToken (const token &t)
append token to the end of token and rewind the stream
ios_base::fmtflags flags () const
Return flags of output stream.
ios_base::fmtflags flags (const ios_base::fmtflags)
Set flags of stream.
Public Member Functions inherited from iIstream
iIstream ()
default
iIstream (writeFormat wf)
iIstream (const iIstream &)=default
Copy construct.
virtual ~iIstream ()=default
Destructor.
void putBack (const token &tok)
Put back token Only a single put back is permitted.
bool getBack (token &tok)
Get the put back token if there is one and return true.
bool peekBack (token &tok)
Peek at the put back token without removing it.
void resetPutBack ()
reset the put back token;
virtual size_t findBinaryBlockStart ()
It seek for a character sequence that indicates the start of a binary block char sequence is 255 255 255 0
virtual bool findToken (const word &w)
search for all tokesn and find the first word token tbat matchs w
virtual bool findTokenResume (const word &w)
search for all tokesn after the current file position and find the first word token tbat matchs w
virtual bool findTokenSilent (const word &w, int32 limitLine=100)
search for all tokesn and find the first word token that matchs
virtual bool findTokenResumeSilent (const word &w, int32 limitLine=100)
search for all tokesn after the current file position and find the first word token tbat matchs w
virtual bool findTokenAndNext (const word &w, word &nextW, bool checkEndStatement=true)
search for all tokens and find the first word token and also next word token chekck if it is eneded with end statement ;
virtual bool findTokenAndNextSilent (const word &w, word &nextW, int32 limitLine=100)
template<typename T >
bool findKeywordAndVal (const word &keyword, T &val, bool checkEndStatement=true)
find a pair of keyword and data terminated by ; keyword data; return false if keyword does not exist or reading fails.
template<typename T >
T lookupData (const word &keyword)
lookup for keyword and data; fatalExit if fails
template<typename T >
T lookupDataOrSet (const word &keyword, const T &setVal)
lookup for keyword and data; set to setVal if lookup fails.
template<typename T >
bool nextData (const word &keyword, T &data)
read the data next to keword keyword data; check the keyword is correct or not
bool readBegin (const char *funcName)
Begin read of data chunk, starts with '('.
bool readEnd (const char *funcName)
End read of data chunk, ends with ')' return true or FatalIOError.
bool readBeginSquare (const char *funcName)
Begin read of data chunk, starts with '('.
bool readEndSquare (const char *funcName)
Begin read of data chunk, starts with '('.
char readBeginList (const char *funcName)
Begin read of list data, starts with '(' or '{' return starting delimiter or FatalIOError.
char readEndList (const char *funcName)
End read of list data, ends with ')' or '}' return closing delimiter or FatalIOError.
char readEndStatement (const char *funcName)
End statement character ;.
iIstream & operator() () const
Public Member Functions inherited from IOstream
IOstream ()
Default.
IOstream (writeFormat wF)
Construct and set write format.
IOstream (const IOstream &)=default
Copy.
virtual ~IOstream ()=default
Destructor.
virtual bool check (const char *operation) const
Check IOstream status for given operation.
bool fatalCheck (const char *operation) const
Check IOstream status for given operation.
bool opened () const
Return true if stream has been opened.
bool closed () const
Return true if stream is closed.
bool isBinary () const
Return true if stream format is binray.
bool good () const
Return true if next operation might succeed.
bool eof () const
Return true if end of input seen.
bool fail () const
Return true if next operation will fail.
bool bad () const
Return true if stream is corrupted.
operator bool () const
Return true if the stream has not failed.
bool operator! () const
Return true if the stream has failed.
int32 lineNumber () const
Const access to the current stream line number.
int32 & lineNumber ()
Non-const access to the current stream line number.
int32 lineNumber (const int32 num)
Set the stream line number return the previous value.
void setEof ()
Set stream to have reached eof.
void setFail ()
Set stream to have failed.
void setBad ()
Set stream to be bad.
ios_base::fmtflags setf (const ios_base::fmtflags f)
Set flags of stream.
ios_base::fmtflags setf (const ios_base::fmtflags f, const ios_base::fmtflags mask)
Set flags of given field of stream.
void unsetf (const ios_base::fmtflags f)
Unset flags of stream.
Protected Member Functions
bool isLastToken ()
check if end of list is reached
void setFirstToken ()
rewind the stream
void validate ()
check for valid tokens in the tokenList
Protected Member Functions inherited from IOstream
void setOpened ()
Set stream opened.
void setClosed ()
Set stream closed.
void setState (ios_base::iostate state)
Set stream state.
void setWriteFormat (writeFormat wF)
void setGood ()
Set stream to be good.
Protected Attributes
word name_
name of the stream
tokenList tokenList_
list of tokens in this stream
tokenList::iterator currentToken_
current token
Protected Attributes inherited from IOstream
streamAccess openClosed_
Is stream open or closed.
writeFormat writeFormat_ = ASCII
write format
ios_base::iostate ioState_
state
int32 lineNumber_
The file line.
Additional Inherited Members
Public Types inherited from IOstream
enum streamAccess : char { CLOSED = 0, OPENED }
enum writeFormat : char { ASCII = 0, BINARY }
Static Public Member Functions inherited from IOstream
static unsigned int defaultPrecision ()
Return the default precision.
static unsigned int defaultPrecision (unsigned int prec)
Reset the default precision return the previous value.
Static Public Attributes inherited from IOstream
static unsigned int precision_ = 6
Default precision, only works for ASCII.
Static Protected Attributes inherited from IOstream
static word staticName_
Name for any generic stream - normally treat as readonly.
Detailed Description
Input token stream.
It is based on OpenFOAM stream, with some modifications/simplifications to be tailored to our needs.
Definition at line 27 of file iTstream.hpp.
Constructor & Destructor Documentation
iTstream() [1/5]
iTstream (const word & streamName)
construct with a name
Definition at line 32 of file iTstream.cpp.
iTstream() [2/5]
iTstream (const word & streamName, const tokenList & tList)
construct with name and copy
Definition at line 47 of file iTstream.cpp.
iTstream() [3/5]
iTstream (const word & streamName, tokenList && tList)
construct with name and move
Definition at line 65 of file iTstream.cpp.
iTstream() [4/5]
iTstream (const iTstream &) default
copy construct
iTstream() [5/5]
iTstream (iTstream &&) default
move construct
~iTstream()
virtual ~iTstream () virtual default
Destructor.
Member Function Documentation
isLastToken()
bool isLastToken () protected
check if end of list is reached
Definition at line 6 of file iTstream.cpp.
References iTstream::currentToken_, and iTstream::tokenList_.
setFirstToken()
void setFirstToken () protected
rewind the stream
Definition at line 11 of file iTstream.cpp.
validate()
void validate () protected
check for valid tokens in the tokenList
Definition at line 16 of file iTstream.cpp.
References pFlow::validTokenForStream().
operator=() [1/4]
iTstream& operator= (const iTstream &) default
copy assignment
operator=() [2/4]
iTstream& operator= (iTstream &&) default
move assignment
operator=() [3/4]
void operator= (const tokenList & tList)
copy assignment from tokenList
Definition at line 84 of file iTstream.cpp.
operator=() [4/4]
void operator= (tokenList && tList)
move assignment from tokenList
Definition at line 92 of file iTstream.cpp.
name() [1/2]
pFlow::word & name () const virtual
Return the name of the stream.
Reimplemented from IOstream.
Definition at line 99 of file iTstream.cpp.
name() [2/2]
virtual word& name () virtual
Return non-const access to the name of the stream.
Reimplemented from IOstream.
read() [1/12]
pFlow::iIstream & read (token & t) override virtual
Return next token from stream.
Implements iIstream.
Definition at line 111 of file iTstream.cpp.
References fatalErrorInFunction, fatalExit, iIstream::getBack(), token::lineNumber(), and token::reset().
Referenced by twoPartEntry::twoPartEntry().
read() [2/12]
pFlow::iIstream & read (char & c) override virtual
Read a character.
Implements iIstream.
Definition at line 168 of file iTstream.cpp.
References CONSUME_PARAM, fatalExit, and notImplementedFunction.
read() [3/12]
pFlow::iIstream & read (word & str) override virtual
Read a word.
Implements iIstream.
Definition at line 180 of file iTstream.cpp.
References CONSUME_PARAM, fatalExit, and notImplementedFunction.
readString()
pFlow::iIstream & readString (word & str) override virtual
Read a string.
Implements iIstream.
Definition at line 192 of file iTstream.cpp.
References CONSUME_PARAM, fatalExit, and notImplementedFunction.
read() [4/12]
pFlow::iIstream & read (int64 & val) override virtual
Read a int64.
Implements iIstream.
Definition at line 204 of file iTstream.cpp.
References CONSUME_PARAM, fatalExit, and notImplementedFunction.
read() [5/12]
pFlow::iIstream & read (int32 & val) override virtual
Read a int32.
Implements iIstream.
Definition at line 215 of file iTstream.cpp.
References CONSUME_PARAM, fatalExit, and notImplementedFunction.
read() [6/12]
pFlow::iIstream & read (int8 & val) override virtual
Read a int8.
Implements iIstream.
Definition at line 227 of file iTstream.cpp.
References CONSUME_PARAM, fatalExit, and notImplementedFunction.
read() [7/12]
pFlow::iIstream & read (uint64 & val) override virtual
Read a uint64.
Implements iIstream.
Definition at line 238 of file iTstream.cpp.
References CONSUME_PARAM, fatalExit, and notImplementedFunction.
read() [8/12]
pFlow::iIstream & read (uint32 & val) override virtual
Read a uint32.
Implements iIstream.
Definition at line 249 of file iTstream.cpp.
References CONSUME_PARAM, fatalExit, and notImplementedFunction.
read() [9/12]
pFlow::iIstream & read (uint8 & val) override virtual
Read a uint8.
Implements iIstream.
Definition at line 260 of file iTstream.cpp.
References CONSUME_PARAM, fatalExit, and notImplementedFunction.
read() [10/12]
pFlow::iIstream & read (float & val) override virtual
Read a floatScalar.
Implements iIstream.
Definition at line 272 of file iTstream.cpp.
References CONSUME_PARAM, fatalExit, and notImplementedFunction.
read() [11/12]
pFlow::iIstream & read (double & val) override virtual
Read a doubleScalar.
Implements iIstream.
Definition at line 284 of file iTstream.cpp.
References CONSUME_PARAM, fatalExit, and notImplementedFunction.
read() [12/12]
pFlow::iIstream & read (char * buffer, std::streamsize count) override virtual
Write a block of binray data.
Implements iIstream.
Definition at line 296 of file iTstream.cpp.
References notImplementedFunction.
rewind()
void rewind () override virtual
Rewind the stream so that it may be read again.
Implements iIstream.
Definition at line 305 of file iTstream.cpp.
References iIstream::resetPutBack().
Referenced by twoPartEntry::secondPartVal(), and dataEntry::stream().
seek()
void seek (size_t pos) override virtual
Implements iIstream.
Definition at line 312 of file iTstream.cpp.
References notImplementedFunction.
tell()
size_t tell () override virtual
Return current position indicator.
Implements iIstream.
Definition at line 325 of file iTstream.cpp.
References notImplementedFunction.
reset()
void reset () virtual
reset the iTstream and make the stream empty
Definition at line 317 of file iTstream.cpp.
References iIstream::resetPutBack().
tokens()
const pFlow::tokenList & tokens () const
const access to token list
Definition at line 331 of file iTstream.cpp.
Referenced by dataEntry::dataEntry().
size()
size_t size () const
size
Definition at line 336 of file iTstream.cpp.
Referenced by pFlow::isTwoPartEntry().
numTokens()
size_t numTokens () const
size
Definition at line 341 of file iTstream.cpp.
appendTokens()
void appendTokens (const tokenList & tList)
append a list of tokens to the end of tokens
Definition at line 347 of file iTstream.cpp.
References pFlow::validTokenForStream().
appendToken()
void appendToken (const token & t)
append token to the end of token and rewind the stream
Definition at line 360 of file iTstream.cpp.
References pFlow::validTokenForStream().
flags() [1/2]
ios_base::fmtflags flags () const inline virtual
Return flags of output stream.
Implements IOstream.
Definition at line 159 of file iTstream.hpp.
flags() [2/2]
ios_base::fmtflags flags (const ios_base::fmtflags) inline virtual
Set flags of stream.
Implements IOstream.
Definition at line 165 of file iTstream.hpp.
Member Data Documentation
name_
word name_ protected
name of the stream
Definition at line 34 of file iTstream.hpp.
tokenList_
tokenList tokenList_ protected
list of tokens in this stream
Definition at line 37 of file iTstream.hpp.
Referenced by iTstream::isLastToken().
currentToken_
tokenList::iterator currentToken_ protected
current token
Definition at line 40 of file iTstream.hpp.
Referenced by iTstream::isLastToken().
The documentation for this class was generated from the following files:
src/phasicFlow/streams/TStream/iTstream.hpp
src/phasicFlow/streams/TStream/iTstream.cpp