PhasicFlow: periodicBoundaryContactSearch Class Reference
periodicBoundaryContactSearch Class Reference
Public Member Functions
TypeInfo ("boundaryContactSearch<regular,periodic>") periodicBoundaryContactSearch(const dictionary &dict
~periodicBoundaryContactSearch () override=default
add_vCtor (boundaryContactSearch, periodicBoundaryContactSearch, boundaryBase)
bool broadSearch (uint32 iter, real t, real dt, csPairContainerType &ppPairs, csPairContainerType &pwPairs, bool force=false) override
Public Member Functions inherited from boundaryContactSearch
TypeInfo ("boundaryContactSearch<none>")
boundaryContactSearch (const dictionary &dict, const boundaryBase &boundary, const contactSearch &cSearch)
create_vCtor (boundaryContactSearch, boundaryBase,(const dictionary &dict, const boundaryBase &boundary, const contactSearch &cSearch),(dict, boundary, cSearch))
add_vCtor (boundaryContactSearch, boundaryContactSearch, boundaryBase)
const contactSearch & cSearch () const
bool hearChanges (real t, real dt, uint32 iter, const message &msg, const anyList &varList) override
Public Member Functions inherited from generalBoundary
TypeInfo ("generalBoundary")
generalBoundary (const boundaryBase &boundary, const pointStructure &pStruct, const word &dataType, const word &option)
~generalBoundary () override=default
uint32 thisBoundaryIndex () const
uint32 mirrorBoundaryindex () const
auto size () const
auto capacity () const
auto neighborProcSize () const
int neighborProcessorNo () const
int thisProcessorNo () const
const auto & boundary () const
const auto & indexList () const
const auto & mirrorBoundary () const
const word & boundaryName () const
const word & type () const
const auto & pStruct () const
bool isBoundaryMaster () const
const Time & time () const
Public Member Functions inherited from observer
observer (message msg)
observer (const subscriber *subscrbr, message msg)
virtual ~observer ()
void subscribe (const subscriber *subscrbr, message msg)
observer & addEvent (message::EVENT event)
bool subscribed () const
void addToSubscriber (const subscriber *subscrbr, message msg)
bool addToSubscriber (const subscriber &subscriber)
Public Attributes
const boundaryBase & boundary
const boundaryBase const contactSearch & cSearch
Private Member Functions
void setSearchBox ()
Private Attributes
box searchBox_
realx3 transferVec_
uint32 thisIndex_
uint32 mirrorIndex_
uniquePtr< ppwBndryContactSearch > ppContactSearch_ = nullptr
uniquePtr< wallBoundaryContactSearch > pwContactSearch_ = nullptr
const realPointField_D & diameter_
bool masterSearch_ = false
Additional Inherited Members
Static Public Member Functions inherited from boundaryContactSearch
static uniquePtr< boundaryContactSearch > create (const dictionary &dict, const boundaryBase &boundary, const contactSearch &cSearch)
Static Public Member Functions inherited from observer
static constexpr auto numEvents ()
Detailed Description
Definition at line 33 of file periodicBoundaryContactSearch.hpp.
Constructor & Destructor Documentation
~periodicBoundaryContactSearch()
~periodicBoundaryContactSearch () override default
Member Function Documentation
setSearchBox()
void setSearchBox () private
Definition at line 28 of file periodicBoundaryContactSearch.cpp.
References periodicBoundaryContactSearch::boundary, boundaryBase::boundaryPlane(), boundaryBase::mirrorBoundary(), boundaryBase::neighborLength(), infinitePlane::normal(), generalBoundary::pStruct(), and periodicBoundaryContactSearch::searchBox_.
TypeInfo()
TypeInfo ("boundaryContactSearch<regular,periodic>") const &
add_vCtor()
add_vCtor (boundaryContactSearch , periodicBoundaryContactSearch , boundaryBase)
broadSearch()
bool broadSearch (uint32 iter, real t, real dt, csPairContainerType & ppPairs, csPairContainerType & pwPairs, bool force = false) override virtual
Reimplemented from boundaryContactSearch.
Definition at line 87 of file periodicBoundaryContactSearch.cpp.
References boundaryBase::thisPoints().
Member Data Documentation
searchBox_
box searchBox_ private
Definition at line 37 of file periodicBoundaryContactSearch.hpp.
Referenced by periodicBoundaryContactSearch::setSearchBox().
transferVec_
realx3 transferVec_ private
Definition at line 39 of file periodicBoundaryContactSearch.hpp.
thisIndex_
uint32 thisIndex_ private
Definition at line 41 of file periodicBoundaryContactSearch.hpp.
mirrorIndex_
uint32 mirrorIndex_ private
Definition at line 43 of file periodicBoundaryContactSearch.hpp.
ppContactSearch_
uniquePtr<ppwBndryContactSearch> ppContactSearch_ = nullptr private
Definition at line 45 of file periodicBoundaryContactSearch.hpp.
pwContactSearch_
uniquePtr<wallBoundaryContactSearch> pwContactSearch_ = nullptr private
Definition at line 47 of file periodicBoundaryContactSearch.hpp.
diameter_
const realPointField_D& diameter_ private
Definition at line 49 of file periodicBoundaryContactSearch.hpp.
masterSearch_
bool masterSearch_ = false private
Definition at line 51 of file periodicBoundaryContactSearch.hpp.
boundary
const boundaryBase& boundary
Definition at line 60 of file periodicBoundaryContactSearch.hpp.
Referenced by periodicBoundaryContactSearch::setSearchBox().
cSearch
const boundaryBase const contactSearch& cSearch
Definition at line 61 of file periodicBoundaryContactSearch.hpp.
The documentation for this class was generated from the following files:
src/Interaction/contactSearch/boundaries/periodicBoundaryContactSearch/periodicBoundaryContactSearch.hpp
src/Interaction/contactSearch/boundaries/periodicBoundaryContactSearch/periodicBoundaryContactSearch.cpp