PhasicFlow: boundaryField< T, MemorySpace > Class Template Reference
boundaryField< T, MemorySpace > Class Template Reference
Public Types
using BoundaryFieldType = boundaryField< T, MemorySpace >
using InternalFieldType = internalField< T, MemorySpace >
using memory_space = typename InternalFieldType::memory_space
using execution_space = typename InternalFieldType::execution_space
using FieldAccessType = scatteredFieldAccess< T, memory_space >
using ProcVectorType = VectorSingle< T, MemorySpace >
Public Member Functions
TypeInfoTemplate211 ("boundaryField","none", T, memory_space::name())
boundaryField (const boundaryBase &boundary, const pointStructure &pStruct, InternalFieldType &internal)
create_vCtor (boundaryField, boundaryBase,(const boundaryBase &boundary, const pointStructure &pStruct, InternalFieldType &internal),(boundary, pStruct, internal))
add_vCtor (BoundaryFieldType, BoundaryFieldType, boundaryBase)
bool hearChanges (real t, real dt, uint32 iter, const message &msg, const anyList &varList) override
InternalFieldType & internal ()
const InternalFieldType & internal () const
word fieldName () const
word name () const
FieldAccessType thisField () const
FieldAccessType mirrorField () const
virtual ProcVectorType & neighborProcField ()
virtual const ProcVectorType & neighborProcField () const
virtual void fill (const T &val)
Public Member Functions inherited from generalBoundary
TypeInfo ("generalBoundary")
generalBoundary (const boundaryBase &boundary, const pointStructure &pStruct, const word &dataType, const word &option)
~generalBoundary () override=default
uint32 thisBoundaryIndex () const
uint32 mirrorBoundaryindex () const
auto size () const
auto capacity () const
auto neighborProcSize () const
int neighborProcessorNo () const
int thisProcessorNo () const
const auto & boundary () const
const auto & indexList () const
const auto & mirrorBoundary () const
const word & boundaryName () const
const word & type () const
const auto & pStruct () const
bool isBoundaryMaster () const
const Time & time () const
Public Member Functions inherited from observer
observer (message msg)
observer (const subscriber *subscrbr, message msg)
virtual ~observer ()
void subscribe (const subscriber *subscrbr, message msg)
observer & addEvent (message::EVENT event)
bool subscribed () const
void addToSubscriber (const subscriber *subscrbr, message msg)
bool addToSubscriber (const subscriber &subscriber)
Static Public Member Functions
static uniquePtr< boundaryField > create (const boundaryBase &boundary, const pointStructure &pStruct, InternalFieldType &internal)
Static Public Member Functions inherited from observer
static constexpr auto numEvents ()
Private Member Functions
virtual bool updateBoundary (int step, DataDirection direction)
Private Attributes
InternalFieldType & internal_
a ref to the internal field
Friends
class boundaryFieldList< T, MemorySpace >
friend et al.
Detailed Description
template<class T, class MemorySpace = void>
class pFlow::boundaryField< T, MemorySpace >
Definition at line 42 of file boundaryField.hpp.
Member Typedef Documentation
BoundaryFieldType
using BoundaryFieldType = boundaryField<T, MemorySpace>
Definition at line 48 of file boundaryField.hpp.
InternalFieldType
using InternalFieldType = internalField<T, MemorySpace>
Definition at line 50 of file boundaryField.hpp.
memory_space
using memory_space = typename InternalFieldType::memory_space
Definition at line 52 of file boundaryField.hpp.
execution_space
using execution_space = typename InternalFieldType::execution_space
Definition at line 54 of file boundaryField.hpp.
FieldAccessType
using FieldAccessType = scatteredFieldAccess<T, memory_space>
Definition at line 56 of file boundaryField.hpp.
ProcVectorType
using ProcVectorType = VectorSingle<T,MemorySpace>
Definition at line 58 of file boundaryField.hpp.
Constructor & Destructor Documentation
boundaryField()
boundaryField (const boundaryBase & boundary, const pointStructure & pStruct, InternalFieldType & internal)
Definition at line 23 of file boundaryField.cpp.
Member Function Documentation
updateBoundary()
virtual bool updateBoundary (int step, DataDirection direction) inline private virtual
Definition at line 69 of file boundaryField.hpp.
TypeInfoTemplate211()
TypeInfoTemplate211 ("boundaryField< T, MemorySpace >" , "none" , T , memory_space::name())
create_vCtor()
create_vCtor (boundaryField< T, MemorySpace > , boundaryBase , (const boundaryBase &boundary, const pointStructure &pStruct, InternalFieldType &internal) , (boundary, pStruct, internal))
add_vCtor()
add_vCtor (BoundaryFieldType , BoundaryFieldType , boundaryBase)
hearChanges()
bool hearChanges (real t, real dt, uint32 iter, const message & msg, const anyList & varList) inline override virtual
Implements observer.
Definition at line 104 of file boundaryField.hpp.
Referenced by exitBoundaryField< T, MemorySpace >::hearChanges(), reflectiveBoundaryField< T, MemorySpace >::hearChanges(), and periodicBoundaryField< T, MemorySpace >::hearChanges().
internal() [1/2]
InternalFieldType& internal () inline
Definition at line 125 of file boundaryField.hpp.
internal() [2/2]
const InternalFieldType& internal () const inline
Definition at line 131 of file boundaryField.hpp.
fieldName()
word fieldName () const inline
Definition at line 136 of file boundaryField.hpp.
Referenced by boundaryField< T, void >::name().
name()
word name () const inline
Definition at line 141 of file boundaryField.hpp.
thisField()
FieldAccessType thisField () const inline
Definition at line 146 of file boundaryField.hpp.
mirrorField()
FieldAccessType mirrorField () const inline
Definition at line 160 of file boundaryField.hpp.
neighborProcField() [1/2]
const pFlow::boundaryField< T, MemorySpace >::ProcVectorType & neighborProcField virtual
Definition at line 41 of file boundaryField.cpp.
neighborProcField() [2/2]
virtual const ProcVectorType& neighborProcField () const virtual
fill()
virtual void fill (const T & val) inline virtual
Definition at line 182 of file boundaryField.hpp.
create()
pFlow::uniquePtr< pFlow::boundaryField< T, MemorySpace > > create (const boundaryBase & boundary, const pointStructure & pStruct, InternalFieldType & internal) static
Definition at line 62 of file boundaryField.cpp.
Referenced by boundaryFieldList< VectorField, realx3, void >::boundaryFieldList().
Friends And Related Function Documentation
boundaryFieldList< T, MemorySpace >
friend class boundaryFieldList< T, MemorySpace > friend
friend et al.
Definition at line 63 of file boundaryField.hpp.
Member Data Documentation
internal_
InternalFieldType& internal_ private
a ref to the internal field
Definition at line 66 of file boundaryField.hpp.
Referenced by boundaryField< T, void >::fieldName(), boundaryField< T, void >::internal(), boundaryField< T, void >::mirrorField(), and boundaryField< T, void >::thisField().
The documentation for this class was generated from the following files:
src/phasicFlow/containers/pointField/boundaryField/boundaryField/boundaryField.hpp
src/phasicFlow/containers/pointField/boundaryField/boundaryField/boundaryField.cpp