PhasicFlow: boundarySphereInteraction< contactForceModel, geometryMotionModel > Class Template Reference
boundarySphereInteraction< contactForceModel, geometryMotionModel > Class Template Reference
Public Types
using BoundarySphereInteractionType = boundarySphereInteraction< contactForceModel, geometryMotionModel >
using GeometryMotionModel = geometryMotionModel
using ContactForceModel = contactForceModel
using MotionModel = typename geometryMotionModel::MotionModel
using ModelStorage = typename ContactForceModel::contactForceStorage
using IdType = uint32
using IndexType = uint32
using ContactListType = sortedContactList< ModelStorage, DefaultExecutionSpace, IdType >
Public Member Functions
TypeInfoTemplate12 ("boundarySphereInteraction", ContactForceModel, MotionModel)
boundarySphereInteraction (const boundaryBase &boundary, const sphereParticles &sphPrtcls, const GeometryMotionModel &geomMotion)
create_vCtor (BoundarySphereInteractionType, boundaryBase,(const boundaryBase &boundary, const sphereParticles &sphPrtcls, const GeometryMotionModel &geomMotion),(boundary, sphPrtcls, geomMotion))
add_vCtor (BoundarySphereInteractionType, BoundarySphereInteractionType, boundaryBase)
~boundarySphereInteraction () override=default
const auto & sphParticles () const
const auto & geometryMotion () const
ContactListType & ppPairs ()
const ContactListType & ppPairs () const
ContactListType & pwPairs ()
const ContactListType & pwPairs () const
bool ppPairsAllocated () const
bool pwPairsAllocated () const
virtual bool sphereSphereInteraction (real dt, const ContactForceModel &cfModel, uint32 step)
bool hearChanges (real t, real dt, uint32 iter, const message &msg, const anyList &varList) override
Public Member Functions inherited from generalBoundary
TypeInfo ("generalBoundary")
generalBoundary (const boundaryBase &boundary, const pointStructure &pStruct, const word &dataType, const word &option)
~generalBoundary () override=default
uint32 thisBoundaryIndex () const
uint32 mirrorBoundaryindex () const
auto size () const
auto capacity () const
auto neighborProcSize () const
int neighborProcessorNo () const
int thisProcessorNo () const
const auto & boundary () const
const auto & indexList () const
const auto & mirrorBoundary () const
const word & boundaryName () const
const word & type () const
const auto & pStruct () const
bool isBoundaryMaster () const
const Time & time () const
Public Member Functions inherited from observer
observer (message msg)
observer (const subscriber *subscrbr, message msg)
virtual ~observer ()
void subscribe (const subscriber *subscrbr, message msg)
observer & addEvent (message::EVENT event)
bool subscribed () const
void addToSubscriber (const subscriber *subscrbr, message msg)
bool addToSubscriber (const subscriber &subscriber)
Static Public Member Functions
static uniquePtr< BoundarySphereInteractionType > create (const boundaryBase &boundary, const sphereParticles &sphPrtcls, const GeometryMotionModel &geomMotion)
Static Public Member Functions inherited from observer
static constexpr auto numEvents ()
Protected Member Functions
void allocatePPPairs ()
void allocatePWPairs ()
Private Attributes
const GeometryMotionModel & geometryMotion_
const sphereParticles & sphParticles_
const reference to sphere particles
uniquePtr< ContactListType > ppPairs_ = nullptr
uniquePtr< ContactListType > pwPairs_ = nullptr
Detailed Description
template<typename contactForceModel, typename geometryMotionModel>
class pFlow::boundarySphereInteraction< contactForceModel, geometryMotionModel >
Definition at line 32 of file boundarySphereInteraction.hpp.
Member Typedef Documentation
BoundarySphereInteractionType
using BoundarySphereInteractionType = boundarySphereInteraction<contactForceModel, geometryMotionModel>
Definition at line 39 of file boundarySphereInteraction.hpp.
GeometryMotionModel
using GeometryMotionModel = geometryMotionModel
Definition at line 41 of file boundarySphereInteraction.hpp.
ContactForceModel
using ContactForceModel = contactForceModel
Definition at line 43 of file boundarySphereInteraction.hpp.
MotionModel
using MotionModel = typename geometryMotionModel::MotionModel
Definition at line 45 of file boundarySphereInteraction.hpp.
ModelStorage
using ModelStorage = typename ContactForceModel::contactForceStorage
Definition at line 47 of file boundarySphereInteraction.hpp.
IdType
using IdType = uint32
Definition at line 49 of file boundarySphereInteraction.hpp.
IndexType
using IndexType = uint32
Definition at line 51 of file boundarySphereInteraction.hpp.
ContactListType
using ContactListType = sortedContactList<ModelStorage, DefaultExecutionSpace, IdType>
Definition at line 54 of file boundarySphereInteraction.hpp.
Constructor & Destructor Documentation
boundarySphereInteraction()
boundarySphereInteraction (const boundaryBase & boundary, const sphereParticles & sphPrtcls, const GeometryMotionModel & geomMotion)
Definition at line 38 of file boundarySphereInteraction.cpp.
~boundarySphereInteraction()
~boundarySphereInteraction () override default
Member Function Documentation
allocatePPPairs()
void allocatePPPairs protected
Definition at line 23 of file boundarySphereInteraction.cpp.
Referenced by periodicBoundarySphereInteraction< contactForceModel, geometryMotionModel >::periodicBoundarySphereInteraction().
allocatePWPairs()
void allocatePWPairs protected
Definition at line 30 of file boundarySphereInteraction.cpp.
Referenced by periodicBoundarySphereInteraction< contactForceModel, geometryMotionModel >::periodicBoundarySphereInteraction().
TypeInfoTemplate12()
TypeInfoTemplate12 ("boundarySphereInteraction< contactForceModel, geometryMotionModel >" , ContactForceModel , MotionModel)
create_vCtor()
create_vCtor (BoundarySphereInteractionType , boundaryBase , (const boundaryBase &boundary, const sphereParticles &sphPrtcls, const GeometryMotionModel &geomMotion) , (boundary, sphPrtcls, geomMotion))
add_vCtor()
add_vCtor (BoundarySphereInteractionType , BoundarySphereInteractionType , boundaryBase)
sphParticles()
const auto& sphParticles () const inline
Definition at line 103 of file boundarySphereInteraction.hpp.
References boundarySphereInteraction< contactForceModel, geometryMotionModel >::sphParticles_.
geometryMotion()
const auto& geometryMotion () const inline
Definition at line 108 of file boundarySphereInteraction.hpp.
References boundarySphereInteraction< contactForceModel, geometryMotionModel >::geometryMotion_.
ppPairs() [1/2]
ContactListType& ppPairs () inline
Definition at line 113 of file boundarySphereInteraction.hpp.
References boundarySphereInteraction< contactForceModel, geometryMotionModel >::ppPairs_.
ppPairs() [2/2]
const ContactListType& ppPairs () const inline
Definition at line 118 of file boundarySphereInteraction.hpp.
References boundarySphereInteraction< contactForceModel, geometryMotionModel >::ppPairs_.
pwPairs() [1/2]
ContactListType& pwPairs () inline
Definition at line 123 of file boundarySphereInteraction.hpp.
References boundarySphereInteraction< contactForceModel, geometryMotionModel >::pwPairs_.
pwPairs() [2/2]
const ContactListType& pwPairs () const inline
Definition at line 128 of file boundarySphereInteraction.hpp.
References boundarySphereInteraction< contactForceModel, geometryMotionModel >::pwPairs_.
ppPairsAllocated()
bool ppPairsAllocated () const inline
Definition at line 133 of file boundarySphereInteraction.hpp.
References boundarySphereInteraction< contactForceModel, geometryMotionModel >::ppPairs_.
pwPairsAllocated()
bool pwPairsAllocated () const inline
Definition at line 139 of file boundarySphereInteraction.hpp.
References boundarySphereInteraction< contactForceModel, geometryMotionModel >::pwPairs_.
sphereSphereInteraction()
virtual bool sphereSphereInteraction (real dt, const ContactForceModel & cfModel, uint32 step) inline virtual
Reimplemented in periodicBoundarySphereInteraction< contactForceModel, geometryMotionModel >.
Definition at line 146 of file boundarySphereInteraction.hpp.
hearChanges()
bool hearChanges (real t, real dt, uint32 iter, const message & msg, const anyList & varList) inline override virtual
Implements observer.
Definition at line 158 of file boundarySphereInteraction.hpp.
References generalBoundary::boundaryName(), pFlow::endl(), pFlow::pOutput, and generalBoundary::type().
create()
pFlow::uniquePtr< pFlow::boundarySphereInteraction< cFM, gMM > > create (const boundaryBase & boundary, const sphereParticles & sphPrtcls, const GeometryMotionModel & geomMotion) static
Definition at line 50 of file boundarySphereInteraction.cpp.
References pFlow::angleBracketsNames2(), pFlow::angleBracketsNames3(), END_REPORT, fatalError, fatalExit, Green_Text, boundaryBase::name(), pFlow::pOutput, pFlow::printKeys(), iOstream::space(), and boundaryBase::type().
Member Data Documentation
geometryMotion_
const GeometryMotionModel& geometryMotion_ private
Definition at line 58 of file boundarySphereInteraction.hpp.
Referenced by boundarySphereInteraction< contactForceModel, geometryMotionModel >::geometryMotion().
sphParticles_
const sphereParticles& sphParticles_ private
const reference to sphere particles
Definition at line 61 of file boundarySphereInteraction.hpp.
Referenced by boundarySphereInteraction< contactForceModel, geometryMotionModel >::sphParticles().
ppPairs_
uniquePtr<ContactListType> ppPairs_ = nullptr private
Definition at line 63 of file boundarySphereInteraction.hpp.
Referenced by boundarySphereInteraction< contactForceModel, geometryMotionModel >::ppPairs(), and boundarySphereInteraction< contactForceModel, geometryMotionModel >::ppPairsAllocated().
pwPairs_
uniquePtr<ContactListType> pwPairs_ = nullptr private
Definition at line 65 of file boundarySphereInteraction.hpp.
Referenced by boundarySphereInteraction< contactForceModel, geometryMotionModel >::pwPairs(), and boundarySphereInteraction< contactForceModel, geometryMotionModel >::pwPairsAllocated().
The documentation for this class was generated from the following files:
src/Interaction/sphereInteraction/boundaries/boundarySphereInteraction/boundarySphereInteraction.hpp
src/Interaction/sphereInteraction/boundaries/boundarySphereInteraction/boundarySphereInteraction.cpp