PhasicFlow: pointRectCell Class Reference
pointRectCell Class Reference
Public Types
using mapType = mapperNBS< DefaultHostExecutionSpace >
using memory_space = typename mapType::memory_space
Public Member Functions
pointRectCell (const dictionary &dictMesh, const pointStructure &pStruct, repository &rep)
const auto & mesh () const
auto & processedRepository ()
void mapPOints ()
auto getCellIterator () const
int32 nPointInCell (int32 i, int32 j, int32 k) const
Protected Attributes
repository & processedRepository_
rectangleMesh & mesh_
const pointStructure & pStruct_
ViewType1D< realx3, memory_space > pointPosition_
mapType map_
int32RectMeshField_H nPointInCell_
Detailed Description
Definition at line 32 of file pointRectCell.hpp.
Member Typedef Documentation
mapType
using mapType = mapperNBS<DefaultHostExecutionSpace>
Definition at line 36 of file pointRectCell.hpp.
memory_space
using memory_space = typename mapType::memory_space
Definition at line 38 of file pointRectCell.hpp.
Constructor & Destructor Documentation
pointRectCell()
pointRectCell (const dictionary & dictMesh, const pointStructure & pStruct, repository & rep) inline
Definition at line 57 of file pointRectCell.hpp.
References pointRectCell::mapPOints().
Member Function Documentation
mesh()
const auto& mesh () const inline
Definition at line 91 of file pointRectCell.hpp.
References pointRectCell::mesh_.
Referenced by processField::mesh(), pFlow::sumMaksOp(), and pFlow::sumOp().
processedRepository()
auto& processedRepository () inline
Definition at line 96 of file pointRectCell.hpp.
References pointRectCell::processedRepository_.
Referenced by processField::processedRepository().
mapPOints()
void mapPOints () inline
Definition at line 101 of file pointRectCell.hpp.
References pointStructure::activePointsMaskH(), pointStructure::activeRange(), mapperNBS< executionSpace >::buildCheckInDomain(), mapperNBS< executionSpace >::getCellIterator(), pointRectCell::map_, n, pointRectCell::nPointInCell_, cells< indexType >::nx(), cells< indexType >::ny(), cells< indexType >::nz(), and pointRectCell::pStruct_.
Referenced by pointRectCell::pointRectCell().
getCellIterator()
auto getCellIterator () const inline
Definition at line 134 of file pointRectCell.hpp.
References mapperNBS< executionSpace >::getCellIterator(), and pointRectCell::map_.
Referenced by pFlow::sumMaksOp(), and pFlow::sumOp().
nPointInCell()
int32 nPointInCell (int32 i, int32 j, int32 k) const inline
Definition at line 139 of file pointRectCell.hpp.
References pointRectCell::nPointInCell_.
Member Data Documentation
processedRepository_
repository& processedRepository_ protected
Definition at line 42 of file pointRectCell.hpp.
Referenced by pointRectCell::processedRepository().
mesh_
rectangleMesh& mesh_ protected
Definition at line 44 of file pointRectCell.hpp.
Referenced by pointRectCell::mesh().
pStruct_
const pointStructure& pStruct_ protected
Definition at line 47 of file pointRectCell.hpp.
Referenced by pointRectCell::mapPOints().
pointPosition_
ViewType1D<realx3, memory_space> pointPosition_ protected
Definition at line 49 of file pointRectCell.hpp.
map_
mapType map_ protected
Definition at line 51 of file pointRectCell.hpp.
Referenced by pointRectCell::getCellIterator(), and pointRectCell::mapPOints().
nPointInCell_
int32RectMeshField_H nPointInCell_ protected
Definition at line 53 of file pointRectCell.hpp.
Referenced by pointRectCell::mapPOints(), and pointRectCell::nPointInCell().
The documentation for this class was generated from the following file:
utilities/postprocessPhasicFlow/pointRectCell.hpp