PhasicFlow: grainShape Class Reference
grainShape Class Reference
Public Member Functions
TypeInfo ("shape<grain>")
grainShape (const word &fileName, repository *owner, const property &prop)
~grainShape () override=default
real maxBoundingSphere () const override
real minBoundingSphere () const override
bool boundingDiameter (uint32 index, real &bDiam) const override
real boundingDiameter (uint32 index) const override
realVector boundingDiameter () const override
real coarseGrainFactor (uint32 index) const
realVector coarseGrainFactor () const
real orginalDiameter (uint32 index) const
realVector orginalDiameter () const
bool mass (uint32 index, real &m) const override
real mass (uint32 index) const override
realVector mass () const override
realVector density () const override
bool Inertia (uint32 index, real &I) const override
real Inertia (uint32 index) const override
realVector Inertia () const override
bool Inertia_xx (uint32 index, real &Ixx) const override
real Inertial_xx (uint32 index) const override
bool Inertia_yy (uint32 index, real &Iyy) const override
real Inertial_yy (uint32 index) const override
bool Inertia_zz (uint32 index, real &Izz) const override
real Inertial_zz (uint32 index) const override
Public Member Functions inherited from shape
TypeInfo ("shape")
shape (const word &fileName, repository *owner, const property &prop)
~shape () override=default
const auto & properties () const
const wordVector & materialNames () const
const auto & shapePropertyIds () const
bool shapeNameToPropId (const word &name, int8 &propId) const
bool propIdValid (uint32 propId) const
bool indexToDensity (uint32 index, real &rho) const
real indexToDensity (uint32 index) const
uint32 propertyId (uint32 index) const
Public Member Functions inherited from baseShapeNames
TypeInfo ("baseShapeNames")
baseShapeNames (const word &fileName, repository *owner)
~baseShapeNames () override=default
const wordVector & shapeNames () const
wordList shapeNameList () const
const auto & hashes () const
size_t numShapes () const
bool shapeNameToIndex (const word &name, uint32 &index) const
bool indexToShapeName (uint32 i, word &name) const
bool hashToIndex (const size_t &hs, uint32 &idx)
bool indexValid (uint32 index) const
bool write (iOstream &os) const override
write to stream
bool write (iOstream &os, const IOPattern &iop) const override
write to stream
Public Member Functions inherited from fileDictionary
TypeInfo ("fileDictionary")
fileDictionary (const objectFile &of, repository *owner=nullptr)
construct an empty dictionary with keyword and make it global/fileDictionary
fileDictionary (const word &keyword, const fileSystem &file)
construct a dictionary with name and read it from file
fileDictionary (const objectFile &objf, const dictionary &dict, repository *owner=nullptr)
bool read (iIstream &is, const IOPattern &iop) override
read from stream
bool write (iOstream &os, const IOPattern &iop) const override
write to stream
bool read (iIstream &is) override
read from stream
bool write (iOstream &os) const override
write to stream
Public Member Functions inherited from IOobject
virtual word typeName () const =0
IOobject (const objectFile &objf, const IOPattern &iop, repository *owner)
~IOobject () override
IOobject (const IOobject &src)=delete
IOobject (IOobject &&src)=delete
const IOPattern & ioPattern () const
const repository * owner () const override
repository * owner ()
repository * releaseOwner (bool fromOwner=false)
bool isIncluded (const word &objName) const override
bool isExcluded (const word &objName) const override
bool readObject (bool rdHdr=true)
bool writeObject () const
bool readObject (iIstream &is, bool rdHdr=true)
bool writeObject (iOstream &os) const
Public Member Functions inherited from IOfileHeader
IOfileHeader (const objectFile &objf)
const word & objectName () const
const word & objectType () const
fileSystem path () const
bool outFileBinary () const
bool inFileBinary () const
bool headerOk (bool silent=false)
bool implyRead () const
Imply read.
bool implyWrite () const
Imply write.
bool fileExist () const
Check if file exists.
bool readIfPresent () const
Check read if present.
bool writeHeader () const
Check if the header should be written to file True: on master + implyWrite + readWriteHeader = true False: otherwise.
bool writeHeader (iOstream &os, const word &typeName, bool forceWrite=false) const
Write the header to the file , typeName comes from caller.
bool writeHeader (iOstream &os, bool forceWrite=false) const
Write the header to the file, typeName comes from the one read from file.
bool readHeader () const
Check if header should be read from file.
bool readHeader (iIstream &is, bool silent=false)
Read the header in the file.
bool writeBanner (iOstream &os) const
write the banner
bool writeSeparator (iOstream &os) const
wirte a separator line
Public Member Functions inherited from objectFile
objectFile (const word &name)
objectFile (const word &name, const fileSystem &localPath, const readFlag &rf=readFlag::READ_NEVER, const writeFlag &wf=writeFlag::WRITE_NEVER, bool rwHeader=true)
objectFile (const objectFile &src)=default
objectFile (objectFile &&src)=default
objectFile & operator= (const objectFile &rhs)=default
objectFile & operator= (objectFile &&rhs)=default
virtual ~objectFile ()=default
virtual const word & name () const
virtual const fileSystem & localPath () const
readFlag rFlag () const
writeFlag wFlag () const
bool isReadAlways () const
bool isReadNever () const
bool isReadIfPresent () const
bool isWriteAlways () const
bool isWriteNever () const
bool readWriteHeader () const
Public Member Functions inherited from dictionary
TypeInfo ("dictionary")
dictionary (const word &keyword, bool global)
construct an empty dictionary with keyword and make it global/fileDictionary (if true)
dictionary (const word &keyword, const fileSystem &file)
construct a dictionary with name and read it from file
dictionary ()
cunstructs a null dictionary
dictionary (const word &keyword)
construct an empty dictionary with keyword
dictionary (const word &keyword, const dictionary &parDict)
cunstruct an empty dictionary with keyword and parDict
dictionary (const word &keyword, const dictionary &parDict, iIstream &is)
cunstruct a dictionary with keyword and parDict and from stream
dictionary (const word &keyword, const dictionary &parDict, const dictionary &dict)
copy construct with keyword and new parrent dict discard the keyword and parDict of dict
dictionary (const dictionary &)
copy construct as default behavior entries_ are copied smoothly.
dictionary (const dictionary &src, bool global)
dictionary & operator= (const dictionary &rhs)
assignment preserve name of this dictionary only entries are transfered with ownership
virtual dictionary * dictPtr ()
pointer to this dictionary
virtual const dictionary * dictPtr () const
pointer to this dictionary
virtual bool isDictionary () const
if this is a dictionary
virtual word globalName () const
global name of entry, separated with dots
virtual const dictionary & parrentDict () const
const ref to parrent dictionary
virtual dictionary & dict ()
ref to this dictionary, if it is a dictionary
virtual const dictionary & dict () const
const ref to this dictionary, if it is a dictionary
virtual bool isFileDict () const
if dictionary is file dictionary, return false
bool addPtr (const word &keyword, uniquePtr< iEntry > &etry, bool warning=true)
add a pointer entry (dictionary/dataEntry) replaces this entry with existing one and issue a warning
bool add (const word &keyword, const float &v)
add a float dataEntry
bool add (const word &keyword, const double &v)
add a double dataEntry
bool add (const word &keyword, const word &v)
add a word dataEntry
bool add (const word &keyword, const int64 &v)
add a int64 dataEntry
bool add (const word &keyword, const int32 &v)
add a int32 dataEntry
bool add (const word &keyword, const int8 &v)
add a int8 dataEntry
bool add (const word &keyword, const uint64 &v)
add a uint64 dataEntry
bool add (const word &keyword, const uint32 &v)
add a uint32 dataEntry
bool add (const word &keyword, const uint8 &v)
add a uint8 dataEntry
bool addDict (const word &keyword, const dictionary &dict)
add a dictionary with the specifiedd keyword, if it exists, replace it.
template<typename T >
bool add (const word &keyword, const T &v)
add a dataEntry of type T
template<typename T >
bool addOrKeep (const word &keyword, const T &v)
template<typename T >
bool addOrReplace (const word &keyword, const T &v)
void clear ()
dictionary * subDictPtr (const word &keyword)
pointer to a subdictionary fatalExit if not found
dictionary & subDict (const word &keyword)
ref to a subdictioanry fatalExit if not found
const dictionary & subDict (const word &keyword) const
const ref to a subdictioanry fatalExit if not found
dataEntry * dataEntryPtr (const word &keyword)
pointer to a dataEntry fatalExit if not found/not a dataEntry
dataEntry & dataEntryRef (const word &keyword)
ref to a subdictioanry fatalExit if not found/not a dataEntry
const dataEntry & dataEntryRef (const word &keyword) const
const ref to a subdictioanry fatalExit if not found/not a dataEntry
dictionary & subDictOrCreate (const word &keyword)
search for a sub-dict with keyword create a new sub-dict if not found and return a ref to it fatalExit if fails
template<typename T >
T getVal (const word &keyword) const
get the value of data entry
template<typename T >
T getValMax (const word &keyword, const T &maxVal) const
get the value of data entry and return max(value, maxVal)
template<typename T >
T getValMin (const word &keyword, const T &minVal) const
get the value of data entry and return min(value, minVal)
template<typename T >
T getValOrSet (const word &keyword, const T &setVal) const
get the value of data entry or if not found, set the value to setVal
template<typename T >
T getValOrSetMax (const word &keyword, const T &setMaxVal) const
get the value of data entry anf return max(setMaxVal, value) if not found, set the value to setMaxVal
template<typename T >
T getValOrSetMin (const word &keyword, const T &setMinVal) const
get the value of data entry anf return max(setMinVal, value) if not found, set the value to setMinVal
size_t numEntries () const
return number of entris in this dictionary
size_t numDataEntries () const
return number of non-nullptr dataEntries
size_t numDictionaries () const
return number of non-nullptr dictionaries
wordList allKeywords () const
return all keywords (non-nullptr) in this dictionary
wordList dataEntryKeywords () const
return a list of all dataEntries (non-nullptr) keywords
wordList dictionaryKeywords () const
return a list of all dictionary (non-null) keywords
bool containsDictionay (const word &name) const
check if a sub-dictionary exists
bool containsDataEntry (const word &name) const
check if a data entry exist
virtual uniquePtr< iEntry > clone () const
clone polymorphic object (here dictionary)
virtual iEntry * clonePtr () const
clone the object
virtual uniquePtr< iEntry > clone (const dictionary &parDict) const
clone the polymorhpic object with parDict as the new parrent dictionary
virtual iEntry * clonePtr (const dictionary &parDict) const
clone the object and change its ownership to parDict
bool read (iIstream &is) override
read from stream
bool write (iOstream &os) const override
write to stream
Public Member Functions inherited from iEntry
TypeInfo ("iEntry")
Type info.
iEntry ()
empty constructor
iEntry (const word &key)
construct with a keyword
virtual ~iEntry ()
destructor
virtual const word & keyword () const
return keyword
virtual word & keyword ()
return keyword
virtual word name () const
name/keyword of entry
Protected Member Functions
bool writeToDict (dictionary &dict) const override
Protected Member Functions inherited from shape
bool writeToDict (dictionary &dict) const override
Protected Member Functions inherited from IOfileHeader
uniquePtr< iFstream > inStream () const
uniquePtr< oFstream > outStream () const
uniquePtr< oFstream > dummyOutStream () const
Protected Member Functions inherited from dictionary
iEntry * findEntry (const word &keyword)
find an entry based on keyword return nullptr if not found
iEntry * findEntry (const word &keyword) const
find and entry based on keyword return nullptr if not found
template<typename T >
bool readDataEntry (const word &keyword, T &val) const
reads a dataEntry with keyword from dictionary
bool readDictionary (iIstream &is)
read dictionary from stream - without keyword
bool writeDictionary (iOstream &os, bool withBlock=true) const
write dictionary to stream - with keyword
Protected Member Functions inherited from iEntry
bool writeKeyword (iOstream &os) const
Private Member Functions
bool readFromDictionary3 ()
Private Attributes
realVector grainDiameters_
realVector sphereDiameters_
realVector coarseGrainFactor_
Additional Inherited Members
Public Types inherited from objectFile
enum readFlag { READ_ALWAYS, READ_NEVER, READ_IF_PRESENT }
enum writeFlag { WRITE_ALWAYS, WRITE_NEVER }
Static Public Member Functions inherited from iEntry
static bool readKeyword (iIstream &is, word &keyword, token &tok)
read a keyword from stream
static bool createEntry (dictionary &parDict, iIstream &is, bool hasBlockToken=false)
create an entry (dataEntry or dictionary) from stream
Static Public Attributes inherited from dictionary
static dictionary nullDict
Protected Attributes inherited from IOfileHeader
word objectName_
word objectType_
word fileFormat_ = "ASCII"
file format read from file
Protected Attributes inherited from dictionary
word name_
global name of dictionary, separated with dots
wordOrderedMapPtr< iEntry > entries_
all the entries (data and dictionary) of the current dictionary
List< iEntry * > orderedEntries_
entries in order of insertion
const dictionary & parDict_
ref to parrent dictionary
bool isGlobal_ = false
Protected Attributes inherited from iEntry
word keyword_
Detailed Description
Definition at line 29 of file grainShape.hpp.
Constructor & Destructor Documentation
grainShape()
grainShape (const word & fileName, repository * owner, const property & prop)
Definition at line 60 of file grainShape.cpp.
References fatalErrorInFunction, and fatalExit.
~grainShape()
~grainShape () override default
Member Function Documentation
readFromDictionary3()
bool readFromDictionary3 () private
Definition at line 24 of file grainShape.cpp.
References grainShape::coarseGrainFactor_, pFlow::endl(), fatalErrorInFunction, dictionary::globalName(), grainShape::grainDiameters_, baseShapeNames::numShapes(), Vector< T, Allocator >::size(), and grainShape::sphereDiameters_.
writeToDict()
bool writeToDict (dictionary & dict) const override protected virtual
Reimplemented from baseShapeNames.
Definition at line 51 of file grainShape.cpp.
References shape::writeToDict().
TypeInfo()
TypeInfo ("shape<grain>")
maxBoundingSphere()
pFlow::real maxBoundingSphere () const override virtual
Implements shape.
Definition at line 76 of file grainShape.cpp.
References pFlow::max().
minBoundingSphere()
pFlow::real minBoundingSphere () const override virtual
Implements shape.
Definition at line 81 of file grainShape.cpp.
References pFlow::min().
boundingDiameter() [1/3]
bool boundingDiameter (uint32 index, real & bDiam) const override virtual
Implements shape.
Definition at line 86 of file grainShape.cpp.
Referenced by grainParticles::initializeParticles().
boundingDiameter() [2/3]
pFlow::real boundingDiameter (uint32 index) const override virtual
Implements shape.
Definition at line 96 of file grainShape.cpp.
References pFlow::endl(), fatalErrorInFunction, and fatalExit.
boundingDiameter() [3/3]
pFlow::realVector boundingDiameter () const override virtual
Implements shape.
Definition at line 108 of file grainShape.cpp.
coarseGrainFactor() [1/2]
pFlow::real coarseGrainFactor (uint32 index) const
Definition at line 113 of file grainShape.cpp.
References pFlow::endl(), fatalErrorInFunction, and fatalExit.
Referenced by grainParticles::initializeParticles().
coarseGrainFactor() [2/2]
pFlow::realVector coarseGrainFactor () const
Definition at line 126 of file grainShape.cpp.
orginalDiameter() [1/2]
pFlow::real orginalDiameter (uint32 index) const
Definition at line 131 of file grainShape.cpp.
References pFlow::endl(), fatalErrorInFunction, and fatalExit.
orginalDiameter() [2/2]
pFlow::realVector orginalDiameter () const
Definition at line 145 of file grainShape.cpp.
mass() [1/3]
bool mass (uint32 index, real & m) const override virtual
Implements shape.
Definition at line 150 of file grainShape.cpp.
References m, pFlow::Pi, and pFlow::pow().
Referenced by grainParticles::initializeParticles().
mass() [2/3]
pFlow::real mass (uint32 index) const override virtual
Implements shape.
Definition at line 162 of file grainShape.cpp.
References pFlow::endl(), fatalErrorInFunction, fatalExit, and m.
mass() [3/3]
pFlow::realVector mass () const override virtual
Implements shape.
Definition at line 173 of file grainShape.cpp.
References pFlow::Pi, and pFlow::pow().
density()
pFlow::realVector density () const override virtual
Implements shape.
Definition at line 178 of file grainShape.cpp.
References ForAll.
Inertia() [1/3]
bool Inertia (uint32 index, real & I) const override virtual
Implements shape.
Definition at line 189 of file grainShape.cpp.
References pFlow::pow().
Referenced by grainParticles::initializeParticles().
Inertia() [2/3]
pFlow::real Inertia (uint32 index) const override virtual
Implements shape.
Definition at line 199 of file grainShape.cpp.
References fatalExit.
Inertia() [3/3]
pFlow::realVector Inertia () const override virtual
Implements shape.
Definition at line 209 of file grainShape.cpp.
References pFlow::pow().
Inertia_xx()
bool Inertia_xx (uint32 index, real & Ixx) const override virtual
Implements shape.
Definition at line 214 of file grainShape.cpp.
Inertial_xx()
pFlow::real Inertial_xx (uint32 index) const override virtual
Implements shape.
Definition at line 219 of file grainShape.cpp.
Inertia_yy()
bool Inertia_yy (uint32 index, real & Iyy) const override virtual
Implements shape.
Definition at line 224 of file grainShape.cpp.
Inertial_yy()
pFlow::real Inertial_yy (uint32 index) const override virtual
Implements shape.
Definition at line 229 of file grainShape.cpp.
Inertia_zz()
bool Inertia_zz (uint32 index, real & Izz) const override virtual
Implements shape.
Definition at line 234 of file grainShape.cpp.
Inertial_zz()
pFlow::real Inertial_zz (uint32 index) const override virtual
Implements shape.
Definition at line 239 of file grainShape.cpp.
Member Data Documentation
grainDiameters_
realVector grainDiameters_ private
Definition at line 36 of file grainShape.hpp.
Referenced by grainShape::readFromDictionary3().
sphereDiameters_
realVector sphereDiameters_ private
Definition at line 37 of file grainShape.hpp.
Referenced by grainShape::readFromDictionary3().
coarseGrainFactor_
realVector coarseGrainFactor_ private
Definition at line 38 of file grainShape.hpp.
Referenced by grainShape::readFromDictionary3().
The documentation for this class was generated from the following files:
src/Particles/GrainParticles/grainShape/grainShape.hpp
src/Particles/GrainParticles/grainShape/grainShape.cpp