PhasicFlow: Ostream Class Reference
Ostream Class Reference
Public Member Functions
Ostream (std::ostream &os, const word &streamName, writeFormat wf=ASCII)
Ostream (const Ostream &)=delete
void operator= (const Ostream &)=delete
virtual const word & name () const
Return the name of the stream.
virtual word & name ()
Return non-const access to the name of the stream.
virtual ios_base::fmtflags flags () const
Return flags of stream.
bool write (const token &tok) override
Write Functions.
iOstream & write (const char c) override
Write character.
iOstream & write (const char *str) override
Write character string.
iOstream & write (const word &str) override
Write word.
iOstream & writeQuoted (const word &str, const bool quoted=true) override
Write std::string surrounded by quotes.
iOstream & write (const int64 val) override
Write int64.
iOstream & write (const int32 val) override
Write int32.
iOstream & write (const label val) override
Write label.
iOstream & write (const uint32 val) override
Write uint32.
iOstream & write (const uint16 val) override
Write uint16.
iOstream & write (const float val) override
Write float.
iOstream & write (const double val) override
Write double.
iOstream & write (const char *binaryData, std::streamsize count) override
Write a block of binray data.
void indent () override
Add indentation characters.
ios_base::fmtflags flags (const ios_base::fmtflags f) override
Set flags of stream.
void flush () override
Flush stream.
void endl () override
Add newline and flush stream.
char fill () const override
Get padding character.
char fill (const char fillch) override
Set padding character for formatted field up to field width.
int width () const override
Get width of output field.
int width (const int w) override
Set width of output field (and return old width)
int precision () const override
Get precision of output field.
int precision (const int p) override
Set precision of output field (and return old precision)
virtual std::ostream & stdStream ()
virtual const std::ostream & stdStream () const
Public Member Functions inherited from iOstream
iOstream ()
Default.
iOstream (writeFormat wF)
Construct from writeFormat.
iOstream (const iOstream &)=default
Copy construct.
virtual ~iOstream ()=default
Destructor.
unsigned short indentSize () const
Return indent level.
unsigned short & indentSize ()
Access to indent size.
unsigned short indentLevel () const
Return indent level.
unsigned short & indentLevel ()
Access to indent level.
void incrIndent ()
Increment the indent level.
void decrIndent ()
Decrement the indent level.
virtual iOstream & beginBlock (const word &kw)
Write begin block group with a name Increments indentation, adds newline.
virtual iOstream & beginBlock ()
Write begin block group without a name Increments indentation, adds newline.
virtual iOstream & endBlock ()
Write end block group Decrements indentation, adds newline.
virtual iOstream & beginList ()
Write begin list "(".
virtual iOstream & beginList (const word &kw)
Write begin list with keyword "kw (".
virtual iOstream & endList ()
Write end list ")".
virtual iOstream & beginSquare ()
Write begin list "[".
virtual iOstream & beginSquare (const word &kw)
Write begin list with keyword "kw [".
virtual iOstream & endSquare ()
Write end list "]".
virtual iOstream & endEntry ()
Write end entry (';') followed by newline.
virtual iOstream & newLine ()
Write a newLine to stream.
virtual iOstream & space (int32 n=1)
Write space to stream.
virtual iOstream & writeWordKeyword (const word &kw)
Write the keyword followed by an appropriate indentation.
template<class T >
iOstream & writeWordEntry (const word &key, const T &value)
Write a keyword/value entry.
iOstream & operator() () const
Return a non-const reference to const iOstream Needed for write functions where the stream argument is temporary: e.g.
Public Member Functions inherited from IOstream
IOstream ()
Default.
IOstream (writeFormat wF)
Construct and set write format.
IOstream (const IOstream &)=default
Copy.
virtual ~IOstream ()=default
Destructor.
virtual bool check (const char *operation) const
Check IOstream status for given operation.
bool fatalCheck (const char *operation) const
Check IOstream status for given operation.
bool opened () const
Return true if stream has been opened.
bool closed () const
Return true if stream is closed.
bool isBinary () const
Return true if stream format is binray.
bool good () const
Return true if next operation might succeed.
bool eof () const
Return true if end of input seen.
bool fail () const
Return true if next operation will fail.
bool bad () const
Return true if stream is corrupted.
operator bool () const
Return true if the stream has not failed.
bool operator! () const
Return true if the stream has failed.
int32 lineNumber () const
Const access to the current stream line number.
int32 & lineNumber ()
Non-const access to the current stream line number.
int32 lineNumber (const int32 num)
Set the stream line number return the previous value.
void setEof ()
Set stream to have reached eof.
void setFail ()
Set stream to have failed.
void setBad ()
Set stream to be bad.
ios_base::fmtflags setf (const ios_base::fmtflags f)
Set flags of stream.
ios_base::fmtflags setf (const ios_base::fmtflags f, const ios_base::fmtflags mask)
Set flags of given field of stream.
void unsetf (const ios_base::fmtflags f)
Unset flags of stream.
Private Attributes
word name_
std::ostream & os_
Additional Inherited Members
Public Types inherited from IOstream
enum streamAccess : char { CLOSED = 0, OPENED }
enum writeFormat : char { ASCII = 0, BINARY }
Static Public Member Functions inherited from IOstream
static unsigned int defaultPrecision ()
Return the default precision.
static unsigned int defaultPrecision (unsigned int prec)
Reset the default precision return the previous value.
Static Public Attributes inherited from IOstream
static unsigned int precision_ = 6
Default precision, only works for ASCII.
Protected Member Functions inherited from IOstream
void setOpened ()
Set stream opened.
void setClosed ()
Set stream closed.
void setState (ios_base::iostate state)
Set stream state.
void setWriteFormat (writeFormat wF)
void setGood ()
Set stream to be good.
Protected Attributes inherited from iOstream
unsigned short indentSize_ = 4
Number of spaces per indent level.
unsigned short indentLevel_ = 0
Current indent level.
Protected Attributes inherited from IOstream
streamAccess openClosed_
Is stream open or closed.
writeFormat writeFormat_ = ASCII
write format
ios_base::iostate ioState_
state
int32 lineNumber_
The file line.
Static Protected Attributes inherited from iOstream
static constexpr const unsigned short entryIndentation_ = 16
Indentation of the entry from the start of the keyword.
Static Protected Attributes inherited from IOstream
static word staticName_
Name for any generic stream - normally treat as readonly.
Detailed Description
Definition at line 35 of file Ostream.hpp.
Constructor & Destructor Documentation
Ostream() [1/2]
Ostream (std::ostream & os, const word & streamName, writeFormat wf = ASCII)
Definition at line 29 of file Ostream.cpp.
Ostream() [2/2]
Ostream (const Ostream &) delete
Member Function Documentation
operator=()
void operator= (const Ostream &) delete
name() [1/2]
virtual const word& name () const inline virtual
Return the name of the stream.
Reimplemented from IOstream.
Definition at line 61 of file Ostream.hpp.
References Ostream::name_.
name() [2/2]
virtual word& name () inline virtual
Return non-const access to the name of the stream.
Reimplemented from IOstream.
Definition at line 67 of file Ostream.hpp.
References Ostream::name_.
flags() [1/2]
std::ios_base::fmtflags flags () const virtual
Return flags of stream.
Implements IOstream.
Definition at line 281 of file Ostream.cpp.
write() [1/12]
bool write (const token & tok) override virtual
Write Functions.
Write token to stream or otherwise handle it. return false if the token type was not handled by this method
Implements iOstream.
Definition at line 53 of file Ostream.cpp.
References token::type(), token::wordToken(), and Ostream::writeQuoted().
write() [2/12]
pFlow::iOstream & write (const char c) override virtual
Write character.
Implements iOstream.
Definition at line 80 of file Ostream.cpp.
References token::NL.
write() [3/12]
pFlow::iOstream & write (const char * str) override virtual
Write character string.
Implements iOstream.
Definition at line 92 of file Ostream.cpp.
References pFlow::countChar(), and token::NL.
write() [4/12]
pFlow::iOstream & write (const word & str) override virtual
Write word.
Implements iOstream.
Definition at line 101 of file Ostream.cpp.
writeQuoted()
pFlow::iOstream & writeQuoted (const word & str, const bool quoted = true) override virtual
Write std::string surrounded by quotes.
Optional write without quotes.
Implements iOstream.
Definition at line 110 of file Ostream.cpp.
References token::BEGIN_STRING, pFlow::countChar(), token::END_STRING, and token::NL.
Referenced by Ostream::write().
write() [5/12]
pFlow::iOstream & write (const int64 val) override virtual
Write int64.
Implements iOstream.
Definition at line 169 of file Ostream.cpp.
write() [6/12]
pFlow::iOstream & write (const int32 val) override virtual
Write int32.
Implements iOstream.
Definition at line 177 of file Ostream.cpp.
write() [7/12]
pFlow::iOstream & write (const label val) override virtual
Write label.
Implements iOstream.
Definition at line 198 of file Ostream.cpp.
write() [8/12]
pFlow::iOstream & write (const uint32 val) override virtual
Write uint32.
Implements iOstream.
Definition at line 205 of file Ostream.cpp.
write() [9/12]
pFlow::iOstream & write (const uint16 val) override virtual
Write uint16.
Implements iOstream.
Definition at line 212 of file Ostream.cpp.
write() [10/12]
pFlow::iOstream & write (const float val) override virtual
Write float.
Implements iOstream.
Definition at line 219 of file Ostream.cpp.
write() [11/12]
pFlow::iOstream & write (const double val) override virtual
Write double.
Implements iOstream.
Definition at line 227 of file Ostream.cpp.
write() [12/12]
pFlow::iOstream & write (const char * binaryData, std::streamsize count) override virtual
Write a block of binray data.
Implements iOstream.
Definition at line 235 of file Ostream.cpp.
References token::BEGIN_LIST, pFlow::count(), token::END_LIST, fatalErrorInFunction, and fatalExit.
indent()
void indent () override virtual
Add indentation characters.
Implements iOstream.
Definition at line 259 of file Ostream.cpp.
flags() [2/2]
std::ios_base::fmtflags flags (const ios_base::fmtflags f) override virtual
Set flags of stream.
Implements IOstream.
Definition at line 287 of file Ostream.cpp.
flush()
void flush () override virtual
Flush stream.
Implements iOstream.
Definition at line 268 of file Ostream.cpp.
endl()
void endl () override virtual
Add newline and flush stream.
Implements iOstream.
Definition at line 274 of file Ostream.cpp.
fill() [1/2]
char fill () const override virtual
Get padding character.
Implements iOstream.
Definition at line 295 of file Ostream.cpp.
fill() [2/2]
char fill (const char fillch) override virtual
Set padding character for formatted field up to field width.
Implements iOstream.
Definition at line 301 of file Ostream.cpp.
width() [1/2]
int width () const override virtual
Get width of output field.
Implements iOstream.
Definition at line 307 of file Ostream.cpp.
width() [2/2]
int width (const int w) override virtual
Set width of output field (and return old width)
Implements iOstream.
Definition at line 313 of file Ostream.cpp.
precision() [1/2]
int precision () const override virtual
Get precision of output field.
Implements iOstream.
Definition at line 319 of file Ostream.cpp.
Referenced by stlFile::write().
precision() [2/2]
int precision (const int p) override virtual
Set precision of output field (and return old precision)
Implements iOstream.
Definition at line 325 of file Ostream.cpp.
stdStream() [1/2]
virtual std::ostream& stdStream () inline virtual
Definition at line 151 of file Ostream.hpp.
References Ostream::os_.
stdStream() [2/2]
virtual const std::ostream& stdStream () const inline virtual
Definition at line 157 of file Ostream.hpp.
References Ostream::os_.
Member Data Documentation
name_
word name_ private
Definition at line 40 of file Ostream.hpp.
Referenced by Ostream::name().
os_
std::ostream& os_ private
Definition at line 42 of file Ostream.hpp.
Referenced by Ostream::stdStream().
The documentation for this class was generated from the following files:
src/phasicFlow/streams/Stream/Ostream.hpp
src/phasicFlow/streams/Stream/Ostream.cpp