PhasicFlow: normalRolling< contactForceModel > Class Template Reference
normalRolling< contactForceModel > Class Template Reference
Public Types
using contactForceStorage = typename contactForceModel::contactForceStorage
Public Member Functions
bool readNormalDict (const dictionary &dict)
TypeInfoNV (word("normal<"+contactForceModel::TYPENAME()+">"))
normalRolling (int32 nMaterial, const ViewType1D< real > &rho, const dictionary &dict)
INLINE_FUNCTION_HD void rollingFriction (const real dt, const int32 i, const int32 j, const int32 propId_i, const int32 propId_j, const real Ri, const real Rj, const realx3 &wi, const realx3 &wj, const realx3 &Nij, const realx3 &FCn, realx3 &Mri, realx3 &Mrj) const
Public Attributes
realSymArray_D mur_
Detailed Description
template<typename contactForceModel>
class pFlow::cfModels::normalRolling< contactForceModel >
Definition at line 29 of file normalRolling.hpp.
Member Typedef Documentation
contactForceStorage
using contactForceStorage = typename contactForceModel::contactForceStorage
Definition at line 36 of file normalRolling.hpp.
Constructor & Destructor Documentation
normalRolling()
normalRolling (int32 nMaterial, const ViewType1D< real > & rho, const dictionary & dict) inline
Definition at line 64 of file normalRolling.hpp.
References fatalExit, and normalRolling< contactForceModel >::readNormalDict().
Member Function Documentation
readNormalDict()
bool readNormalDict (const dictionary & dict) inline
Definition at line 41 of file normalRolling.hpp.
References symArray< T, MemorySpace >::assign(), fatalErrorInFunction, symArray< real >::getN(), dictionary::getVal(), and normalRolling< contactForceModel >::mur_.
Referenced by normalRolling< contactForceModel >::normalRolling().
TypeInfoNV()
TypeInfoNV (word("normal<"+contactForceModel::TYPENAME()+">"))
rollingFriction()
INLINE_FUNCTION_HD void rollingFriction (const real dt, const int32 i, const int32 j, const int32 propId_i, const int32 propId_j, const real Ri, const real Rj, const realx3 & wi, const realx3 & wj, const realx3 & Nij, const realx3 & FCn, realx3 & Mri, realx3 & Mrj) const inline
Definition at line 77 of file normalRolling.hpp.
References pFlow::equal(), length(), and normalRolling< contactForceModel >::mur_.
Member Data Documentation
mur_
realSymArray_D mur_
Definition at line 39 of file normalRolling.hpp.
Referenced by normalRolling< contactForceModel >::readNormalDict(), and normalRolling< contactForceModel >::rollingFriction().
The documentation for this class was generated from the following file:
src/Interaction/Models/rolling/normalRolling.hpp