PhasicFlow: readFromTimeFolder Class Reference
readFromTimeFolder Class Reference
Public Member Functions
readFromTimeFolder (repository &rep)
auto path () const
auto & db ()
std::pair< bool, IOfileHeader > fieldExists (word fieldName) const
bool pointFieldFileGetType (word fieldName, word &typeName) const
template<typename T >
bool pointFieldGetType (word &typeName) const
template<typename T >
bool pointFieldGetCheckType (word const &fieldName, word &typeName) const
template<typename T >
uniquePtr< pointField_H< T > > createUniformPointField_H (word const &name, T value, bool regRep=true)
template<typename T >
uniquePtr< pointField_H< T > > readPointField_H (word const &name)
template<typename T >
uniquePtr< pointField_D< T > > readPointField_D (word const &name)
Protected Member Functions
bool checkForPointStructure () const
Protected Attributes
repository & repository_
Detailed Description
Definition at line 31 of file readFromTimeFolder.hpp.
Constructor & Destructor Documentation
readFromTimeFolder()
readFromTimeFolder (repository & rep) explicit
Definition at line 23 of file readFromTimeFolder.cpp.
Member Function Documentation
checkForPointStructure()
bool checkForPointStructure () const inline protected
Definition at line 37 of file readFromTimeFolder.hpp.
References repository::lookupObjectName(), pFlow::pointStructureFile__, and readFromTimeFolder::repository_.
Referenced by readFromTimeFolder::createUniformPointField_H(), readFromTimeFolder::readPointField_D(), and readFromTimeFolder::readPointField_H().
path()
auto path () const inline
Definition at line 47 of file readFromTimeFolder.hpp.
References repository::path(), and readFromTimeFolder::repository_.
db()
auto& db () inline
Definition at line 52 of file readFromTimeFolder.hpp.
References readFromTimeFolder::repository_.
Referenced by countField::timeFolderRepository(), and processField::timeFolderRepository().
fieldExists()
std::pair< bool, pFlow::IOfileHeader > fieldExists (word fieldName) const
Definition at line 30 of file readFromTimeFolder.cpp.
References IOfileHeader::headerOk(), objectFile::READ_ALWAYS, and objectFile::WRITE_NEVER.
pointFieldFileGetType()
bool pointFieldFileGetType (word fieldName, word & typeName) const
Definition at line 43 of file readFromTimeFolder.cpp.
References pFlow::endl(), fatalErrorInFunction, fatalExit, and pFlow::utilities::pointFieldGetType().
Referenced by readFromTimeFolder::pointFieldGetCheckType().
pointFieldGetType()
bool pointFieldGetType (word & typeName) const inline
Definition at line 65 of file readFromTimeFolder.hpp.
References pFlow::endl(), fatalErrorInFunction, and pFlow::utilities::pointFieldGetType().
pointFieldGetCheckType()
bool pointFieldGetCheckType (word const & fieldName, word & typeName) const inline
Definition at line 84 of file readFromTimeFolder.hpp.
References fatalExit, and readFromTimeFolder::pointFieldFileGetType().
createUniformPointField_H()
uniquePtr<pointField_H<T> > createUniformPointField_H (word const & name, T value, bool regRep = true) inline
Definition at line 116 of file readFromTimeFolder.hpp.
References readFromTimeFolder::checkForPointStructure(), pFlow::endl(), fatalErrorInFunction, fatalExit, repository::lookupObject(), repository::name(), pFlow::pointStructureFile__, pStruct, objectFile::READ_NEVER, readFromTimeFolder::repository_, and objectFile::WRITE_NEVER.
readPointField_H()
uniquePtr<pointField_H<T> > readPointField_H (word const & name) inline
Definition at line 167 of file readFromTimeFolder.hpp.
References readFromTimeFolder::checkForPointStructure(), pFlow::endl(), fatalErrorInFunction, fatalExit, repository::lookupObject(), repository::name(), pFlow::pointStructureFile__, pStruct, objectFile::READ_IF_PRESENT, readFromTimeFolder::repository_, and objectFile::WRITE_ALWAYS.
readPointField_D()
uniquePtr<pointField_D<T> > readPointField_D (word const & name) inline
Definition at line 195 of file readFromTimeFolder.hpp.
References readFromTimeFolder::checkForPointStructure(), pFlow::endl(), fatalErrorInFunction, fatalExit, repository::lookupObject(), repository::name(), pFlow::pointStructureFile__, pStruct, objectFile::READ_IF_PRESENT, readFromTimeFolder::repository_, and objectFile::WRITE_ALWAYS.
Member Data Documentation
repository_
repository& repository_ protected
Definition at line 35 of file readFromTimeFolder.hpp.
Referenced by readFromTimeFolder::checkForPointStructure(), readFromTimeFolder::createUniformPointField_H(), readFromTimeFolder::db(), readFromTimeFolder::path(), readFromTimeFolder::readPointField_D(), and readFromTimeFolder::readPointField_H().
The documentation for this class was generated from the following files:
utilities/Utilities/readFromTimeFolder.hpp
utilities/Utilities/readFromTimeFolder.cpp