PhasicFlow: line Class Reference
line Class Reference
Public Member Functions
TypeInfoNV ("line")
FUNCTION_HD line ()
FUNCTION_HD line (const realx3 &lp1, const realx3 &lp2)
FUNCTION_H line (const dictionary &dict)
FUNCTION_HD line (const line &src)=default
FUNCTION_HD line (line &&src)=default
FUNCTION_HD line & operator= (const line &)=default
FUNCTION_HD line & operator= (line &&)=default
INLINE_FUNCTION_HD void set (const realx3 &lp1, const realx3 &lp2)
INLINE_FUNCTION_HD realx3 point1 () const
INLINE_FUNCTION_HD realx3 point2 () const
INLINE_FUNCTION_HD realx3 point (real t) const
INLINE_FUNCTION_HD real length () const
INLINE_FUNCTION_HD realx3 unitVector () const
INLINE_FUNCTION_HD realx3 projectPoint (const realx3 &p) const
INLINE_FUNCTION_HD real projectNormalizedLength (realx3 p) const
FUNCTION_H bool read (const dictionary &dict)
FUNCTION_H bool write (dictionary &ditc) const
FUNCTION_H bool read (iIstream &is)
FUNCTION_H bool write (iOstream &os) const
Protected Attributes
realx3 p1_
realx3 v21_
Detailed Description
Definition at line 36 of file line.hpp.
Constructor & Destructor Documentation
line() [1/5]
FUNCTION_HD line () inline
Definition at line 52 of file line.hpp.
line() [2/5]
FUNCTION_HD line (const realx3 & lp1, const realx3 & lp2)
Definition at line 28 of file line.cpp.
line() [3/5]
FUNCTION_H line (const dictionary & dict)
Definition at line 38 of file line.cpp.
References fatalExit.
line() [4/5]
FUNCTION_HD line (const line & src) default
line() [5/5]
FUNCTION_HD line (line && src) default
Member Function Documentation
TypeInfoNV()
TypeInfoNV ("line")
operator=() [1/2]
FUNCTION_HD line& operator= (const line &) default
operator=() [2/2]
FUNCTION_HD line& operator= (line &&) default
set()
INLINE_FUNCTION_HD void set (const realx3 & lp1, const realx3 & lp2) inline
Definition at line 78 of file line.hpp.
References line::p1_, and line::v21_.
Referenced by multiRotatingAxis::move().
point1()
INLINE_FUNCTION_HD realx3 point1 () const inline
Definition at line 86 of file line.hpp.
References line::p1_.
Referenced by multiRotatingAxis::move(), and line::write().
point2()
INLINE_FUNCTION_HD realx3 point2 () const inline
Definition at line 90 of file line.hpp.
References line::point().
Referenced by multiRotatingAxis::move(), and line::write().
point()
INLINE_FUNCTION_HD realx3 point (real t) const inline
Definition at line 94 of file line.hpp.
References line::p1_, and line::v21_.
Referenced by planeWall::addPlaneWall(), line::point2(), line::projectPoint(), and cylinderWall::readCylinderWall().
length()
INLINE_FUNCTION_HD real length () const inline
Definition at line 98 of file line.hpp.
References length(), and line::v21_.
unitVector()
INLINE_FUNCTION_HD realx3 unitVector () const inline
Definition at line 102 of file line.hpp.
References normalize(), and line::v21_.
Referenced by rotatingAxis::linTangentialVelocityPoint().
projectPoint()
INLINE_FUNCTION_HD realx3 projectPoint (const realx3 & p) const inline
Definition at line 106 of file line.hpp.
References line::point(), and line::projectNormalizedLength().
Referenced by rotatingAxis::linTangentialVelocityPoint().
projectNormalizedLength()
INLINE_FUNCTION_HD real projectNormalizedLength (realx3 p) const inline
Definition at line 113 of file line.hpp.
References dot(), line::p1_, and line::v21_.
Referenced by line::projectPoint().
read() [1/2]
FUNCTION_H bool read (const dictionary & dict)
Definition at line 50 of file line.cpp.
References dictionary::getVal().
Referenced by rotatingAxis::read().
write() [1/2]
FUNCTION_H bool write (dictionary & ditc) const
Definition at line 61 of file line.cpp.
References dictionary::add(), pFlow::endl(), fatalErrorInFunction, dictionary::globalName(), line::point1(), and line::point2().
Referenced by rotatingAxis::write().
read() [2/2]
FUNCTION_H bool read (iIstream & is)
Definition at line 82 of file line.cpp.
References IOstream::check(), pFlow::endl(), FUNCTION_NAME, ioErrorInFile, IOstream::lineNumber(), IOstream::name(), and iIstream::readEndStatement().
write() [2/2]
FUNCTION_H bool write (iOstream & os) const
Definition at line 124 of file line.cpp.
References IOstream::check(), FUNCTION_NAME, and iOstream::writeWordEntry().
Member Data Documentation
p1_
realx3 p1_ protected
Definition at line 41 of file line.hpp.
Referenced by line::point(), line::point1(), line::projectNormalizedLength(), and line::set().
v21_
realx3 v21_ protected
Definition at line 44 of file line.hpp.
Referenced by line::length(), line::point(), line::projectNormalizedLength(), line::set(), and line::unitVector().
The documentation for this class was generated from the following files:
src/phasicFlow/structuredData/line/line.hpp
src/phasicFlow/structuredData/line/line.cpp