PhasicFlow: localProcessors Class Reference
localProcessors Class Reference
Public Member Functions
localProcessors (const word &name)
Construct a local processor communication similar to global with specified name.
localProcessors (const word &name, const std::vector< int > &ranks)
Construct a local processor communication from global communicator using a name and ranks.
const auto & name () const
return name of the local communicator
auto localRank () const
auto localSize () const
bool localMaster () const
int localMasterNo () const
bool localParallel () const
const char * localRunTypeName ()
bool isThisActive () const
Public Member Functions inherited from processors
processors ()
Constructor.
~processors ()
Destructor.
Static Public Member Functions
static bool builtForMPI ()
Static Public Member Functions inherited from processors
static void initProcessors (int argc, char *argv[])
Initialize MPI processors.
static void finalizeProcessors ()
Finalize MPI processors.
static int globalMasterNo ()
Master processors number (globaly in MPI).
static bool globalParallel ()
Is this a parallel MPI run.
static const char * globalRunTypeName ()
static bool isInitialized ()
Is MPI initialized?
static bool isFinalized ()
Is MPI finalized?
static bool globalMaster ()
Is this processor the master processor?
static int globalSize ()
Global size of processors.
static int globalRank ()
Rank of the processor in the global MPI.
static int argc ()
static char ** argv ()
static void abort (int error)
Abort MPI run or regular run.
Private Attributes
int localSize_ = 1
int localRank_ = 0
bool isPartOfLocal_ = true
word name_
Detailed Description
Definition at line 35 of file localProcessors.hpp.
Constructor & Destructor Documentation
localProcessors() [1/2]
localProcessors (const word & name)
Construct a local processor communication similar to global with specified name.
Parameters
name a given name to the local communicator
Definition at line 22 of file localProcessors.cpp.
localProcessors() [2/2]
localProcessors (const word & name, const std::vector< int > & ranks)
Construct a local processor communication from global communicator using a name and ranks.
Parameters
name a given name to the local communicator
ranks ranks to be included in the new communicator
Definition at line 37 of file localProcessors.cpp.
References CheckMPI, pFlow::endl(), fatalErrorInFunction, fatalExit, processors::globalRank(), and processors::globalSize().
Member Function Documentation
name()
const auto& name () const inline
return name of the local communicator
Definition at line 82 of file localProcessors.hpp.
References localProcessors::name_.
localRank()
auto localRank () const inline
Definition at line 88 of file localProcessors.hpp.
References localProcessors::localRank_.
Referenced by boundaryBase::thisProcessorNo().
localSize()
auto localSize () const inline
Definition at line 94 of file localProcessors.hpp.
References localProcessors::localSize_.
localMaster()
bool localMaster () const inline
Definition at line 102 of file localProcessors.hpp.
References localProcessors::localMasterNo(), and localProcessors::localRank_.
localMasterNo()
int localMasterNo () const inline
Definition at line 108 of file localProcessors.hpp.
Referenced by localProcessors::localMaster().
localParallel()
bool localParallel () const inline
Definition at line 114 of file localProcessors.hpp.
References localProcessors::localSize_.
Referenced by localProcessors::localRunTypeName().
localRunTypeName()
const char* localRunTypeName () inline
Definition at line 120 of file localProcessors.hpp.
References localProcessors::localParallel().
isThisActive()
bool isThisActive () const inline
Definition at line 129 of file localProcessors.hpp.
References localProcessors::isPartOfLocal_.
builtForMPI()
static bool builtForMPI () inline static
Definition at line 149 of file localProcessors.hpp.
Referenced by main().
Member Data Documentation
localSize_
int localSize_ = 1 private
Definition at line 47 of file localProcessors.hpp.
Referenced by localProcessors::localParallel(), and localProcessors::localSize().
localRank_
int localRank_ = 0 private
Definition at line 49 of file localProcessors.hpp.
Referenced by localProcessors::localMaster(), and localProcessors::localRank().
isPartOfLocal_
bool isPartOfLocal_ = true private
Definition at line 51 of file localProcessors.hpp.
Referenced by localProcessors::isThisActive().
name_
word name_ private
Definition at line 53 of file localProcessors.hpp.
Referenced by localProcessors::name().
The documentation for this class was generated from the following files:
src/phasicFlow/processors/localProcessors.hpp
src/phasicFlow/processors/localProcessors.cpp