PhasicFlow: domain Class Reference
domain Class Reference
Public Member Functions
TypeInfoNV ("domain")
INLINE_FUNCTION_HD domain ()=default
FUNCTION_H domain (const box &db)
INLINE_FUNCTION_HD domain (const domain &)=default
INLINE_FUNCTION_HD domain (domain &&)=default
INLINE_FUNCTION_HD domain & operator= (const domain &)=default
INLINE_FUNCTION_HD domain & operator= (domain &&)=default
INLINE_FUNCTION_HD ~domain ()=default
const INLINE_FUNCTION_HD auto & domainBox () const
const INLINE_FUNCTION_HD auto & left () const
const INLINE_FUNCTION_HD auto & right () const
const INLINE_FUNCTION_HD auto & bottom () const
const INLINE_FUNCTION_HD auto & top () const
const INLINE_FUNCTION_HD auto & rear () const
const INLINE_FUNCTION_HD auto & front () const
const INLINE_FUNCTION_H auto & boundaryPlane (uint32 i) const
const INLINE_FUNCTION_HD auto & minPoint () const
const INLINE_FUNCTION_HD auto & maxPoint () const
Private Attributes
box domainBox_
plane left_
-x
plane right_
+x
plane bottom_
-y
plane top_
+y
plane rear_
-z
plane front_
+z
Detailed Description
Definition at line 31 of file domain.hpp.
Constructor & Destructor Documentation
domain() [1/4]
INLINE_FUNCTION_HD domain () default
domain() [2/4]
FUNCTION_H domain (const box & db) explicit
Definition at line 24 of file domain.cpp.
domain() [3/4]
INLINE_FUNCTION_HD domain (const domain &) default
domain() [4/4]
INLINE_FUNCTION_HD domain (domain &&) default
~domain()
INLINE_FUNCTION_HD ~domain () default
Member Function Documentation
TypeInfoNV()
TypeInfoNV ("domain")
operator=() [1/2]
INLINE_FUNCTION_HD domain& operator= (const domain &) default
operator=() [2/2]
INLINE_FUNCTION_HD domain& operator= (domain &&) default
domainBox()
const INLINE_FUNCTION_HD auto& domainBox () const inline
Definition at line 86 of file domain.hpp.
References domain::domainBox_.
Referenced by pFlow::equal(), boundaryList::extendedDomainBox(), pointFlag< DefaultHostExecutionSpace >::markPointRegions(), and pFlow::operator<<().
left()
const INLINE_FUNCTION_HD auto& left () const inline
Definition at line 92 of file domain.hpp.
References domain::left_.
right()
const INLINE_FUNCTION_HD auto& right () const inline
Definition at line 98 of file domain.hpp.
References domain::right_.
Referenced by pointFlag< DefaultHostExecutionSpace >::markPointRegions().
bottom()
const INLINE_FUNCTION_HD auto& bottom () const inline
Definition at line 104 of file domain.hpp.
References domain::bottom_.
Referenced by pointFlag< DefaultHostExecutionSpace >::markPointRegions().
top()
const INLINE_FUNCTION_HD auto& top () const inline
Definition at line 110 of file domain.hpp.
References domain::top_.
Referenced by pointFlag< DefaultHostExecutionSpace >::markPointRegions().
rear()
const INLINE_FUNCTION_HD auto& rear () const inline
Definition at line 116 of file domain.hpp.
References domain::rear_.
Referenced by pointFlag< DefaultHostExecutionSpace >::markPointRegions().
front()
const INLINE_FUNCTION_HD auto& front () const inline
Definition at line 122 of file domain.hpp.
References domain::front_.
Referenced by pointFlag< DefaultHostExecutionSpace >::markPointRegions().
boundaryPlane()
const INLINE_FUNCTION_H auto& boundaryPlane (uint32 i) const inline
Definition at line 128 of file domain.hpp.
References domain::bottom_, fatalErrorInFunction, domain::front_, domain::left_, domain::rear_, domain::right_, and domain::top_.
minPoint()
const INLINE_FUNCTION_HD auto& minPoint () const inline
Definition at line 151 of file domain.hpp.
References domain::domainBox_, and box::minPoint().
maxPoint()
const INLINE_FUNCTION_HD auto& maxPoint () const inline
Definition at line 157 of file domain.hpp.
References domain::domainBox_, and box::maxPoint().
Member Data Documentation
domainBox_
box domainBox_ private
Definition at line 35 of file domain.hpp.
Referenced by domain::domainBox(), domain::maxPoint(), and domain::minPoint().
left_
plane left_ private
-x
Definition at line 38 of file domain.hpp.
Referenced by domain::boundaryPlane(), and domain::left().
right_
plane right_ private
+x
Definition at line 41 of file domain.hpp.
Referenced by domain::boundaryPlane(), and domain::right().
bottom_
plane bottom_ private
-y
Definition at line 44 of file domain.hpp.
Referenced by domain::bottom(), and domain::boundaryPlane().
top_
plane top_ private
+y
Definition at line 47 of file domain.hpp.
Referenced by domain::boundaryPlane(), and domain::top().
rear_
plane rear_ private
-z
Definition at line 50 of file domain.hpp.
Referenced by domain::boundaryPlane(), and domain::rear().
front_
plane front_ private
+z
Definition at line 53 of file domain.hpp.
Referenced by domain::boundaryPlane(), and domain::front().
The documentation for this class was generated from the following files:
src/phasicFlow/structuredData/domain/domain.hpp
src/phasicFlow/structuredData/domain/domain.cpp