PhasicFlow: dictionary Class Reference
dictionary Class Reference
Dictionary holds a set of data entries or sub-dictionaries that are enclosed in a curely braces or are in a file.
Public Member Functions
TypeInfo ("dictionary")
dictionary (const word &keyword, bool global)
construct an empty dictionary with keyword and make it global/fileDictionary (if true)
dictionary (const word &keyword, const fileSystem &file)
construct a dictionary with name and read it from file
dictionary ()
cunstructs a null dictionary
dictionary (const word &keyword)
construct an empty dictionary with keyword
dictionary (const word &keyword, const dictionary &parDict)
cunstruct an empty dictionary with keyword and parDict
dictionary (const word &keyword, const dictionary &parDict, iIstream &is)
cunstruct a dictionary with keyword and parDict and from stream
dictionary (const word &keyword, const dictionary &parDict, const dictionary &dict)
copy construct with keyword and new parrent dict discard the keyword and parDict of dict
dictionary (const dictionary &)
copy construct as default behavior entries_ are copied smoothly.
dictionary (const dictionary &src, bool global)
dictionary & operator= (const dictionary &rhs)
assignment preserve name of this dictionary only entries are transfered with ownership
virtual dictionary * dictPtr ()
pointer to this dictionary
virtual const dictionary * dictPtr () const
pointer to this dictionary
virtual bool isDictionary () const
if this is a dictionary
virtual word globalName () const
global name of entry, separated with dots
virtual const dictionary & parrentDict () const
const ref to parrent dictionary
virtual dictionary & dict ()
ref to this dictionary, if it is a dictionary
virtual const dictionary & dict () const
const ref to this dictionary, if it is a dictionary
virtual bool isFileDict () const
if dictionary is file dictionary, return false
bool addPtr (const word &keyword, uniquePtr< iEntry > &etry, bool warning=true)
add a pointer entry (dictionary/dataEntry) replaces this entry with existing one and issue a warning
bool add (const word &keyword, const float &v)
add a float dataEntry
bool add (const word &keyword, const double &v)
add a double dataEntry
bool add (const word &keyword, const word &v)
add a word dataEntry
bool add (const word &keyword, const int64 &v)
add a int64 dataEntry
bool add (const word &keyword, const int32 &v)
add a int32 dataEntry
bool add (const word &keyword, const int8 &v)
add a int8 dataEntry
bool add (const word &keyword, const uint64 &v)
add a uint64 dataEntry
bool add (const word &keyword, const uint32 &v)
add a uint32 dataEntry
bool add (const word &keyword, const uint8 &v)
add a uint8 dataEntry
bool addDict (const word &keyword, const dictionary &dict)
add a dictionary with the specifiedd keyword, if it exists, replace it.
template<typename T >
bool add (const word &keyword, const T &v)
add a dataEntry of type T
template<typename T >
bool addOrKeep (const word &keyword, const T &v)
template<typename T >
bool addOrReplace (const word &keyword, const T &v)
void clear ()
dictionary * subDictPtr (const word &keyword)
pointer to a subdictionary fatalExit if not found
dictionary & subDict (const word &keyword)
ref to a subdictioanry fatalExit if not found
const dictionary & subDict (const word &keyword) const
const ref to a subdictioanry fatalExit if not found
dataEntry * dataEntryPtr (const word &keyword)
pointer to a dataEntry fatalExit if not found/not a dataEntry
dataEntry & dataEntryRef (const word &keyword)
ref to a subdictioanry fatalExit if not found/not a dataEntry
const dataEntry & dataEntryRef (const word &keyword) const
const ref to a subdictioanry fatalExit if not found/not a dataEntry
dictionary & subDictOrCreate (const word &keyword)
search for a sub-dict with keyword create a new sub-dict if not found and return a ref to it fatalExit if fails
template<typename T >
T getVal (const word &keyword) const
get the value of data entry
template<typename T >
T getValMax (const word &keyword, const T &maxVal) const
get the value of data entry and return max(value, maxVal)
template<typename T >
T getValMin (const word &keyword, const T &minVal) const
get the value of data entry and return min(value, minVal)
template<typename T >
T getValOrSet (const word &keyword, const T &setVal) const
get the value of data entry or if not found, set the value to setVal
template<typename T >
T getValOrSetMax (const word &keyword, const T &setMaxVal) const
get the value of data entry anf return max(setMaxVal, value) if not found, set the value to setMaxVal
template<typename T >
T getValOrSetMin (const word &keyword, const T &setMinVal) const
get the value of data entry anf return max(setMinVal, value) if not found, set the value to setMinVal
size_t numEntries () const
return number of entris in this dictionary
size_t numDataEntries () const
return number of non-nullptr dataEntries
size_t numDictionaries () const
return number of non-nullptr dictionaries
wordList allKeywords () const
return all keywords (non-nullptr) in this dictionary
wordList dataEntryKeywords () const
return a list of all dataEntries (non-nullptr) keywords
wordList dictionaryKeywords () const
return a list of all dictionary (non-null) keywords
bool containsDictionay (const word &name) const
check if a sub-dictionary exists
bool containsDataEntry (const word &name) const
check if a data entry exist
virtual uniquePtr< iEntry > clone () const
clone polymorphic object (here dictionary)
virtual iEntry * clonePtr () const
clone the object
virtual uniquePtr< iEntry > clone (const dictionary &parDict) const
clone the polymorhpic object with parDict as the new parrent dictionary
virtual iEntry * clonePtr (const dictionary &parDict) const
clone the object and change its ownership to parDict
bool read (iIstream &is) override
read from stream
bool write (iOstream &os) const override
write to stream
Public Member Functions inherited from iEntry
TypeInfo ("iEntry")
Type info.
iEntry ()
empty constructor
iEntry (const word &key)
construct with a keyword
virtual ~iEntry ()
destructor
virtual const word & keyword () const
return keyword
virtual word & keyword ()
return keyword
virtual word name () const
name/keyword of entry
Static Public Attributes
static dictionary nullDict
Protected Member Functions
iEntry * findEntry (const word &keyword)
find an entry based on keyword return nullptr if not found
iEntry * findEntry (const word &keyword) const
find and entry based on keyword return nullptr if not found
template<typename T >
bool readDataEntry (const word &keyword, T &val) const
reads a dataEntry with keyword from dictionary
bool readDictionary (iIstream &is)
read dictionary from stream - without keyword
bool writeDictionary (iOstream &os, bool withBlock=true) const
write dictionary to stream - with keyword
Protected Member Functions inherited from iEntry
bool writeKeyword (iOstream &os) const
Protected Attributes
word name_
global name of dictionary, separated with dots
wordOrderedMapPtr< iEntry > entries_
all the entries (data and dictionary) of the current dictionary
List< iEntry * > orderedEntries_
entries in order of insertion
const dictionary & parDict_
ref to parrent dictionary
bool isGlobal_ = false
Protected Attributes inherited from iEntry
word keyword_
Additional Inherited Members
Static Public Member Functions inherited from iEntry
static bool readKeyword (iIstream &is, word &keyword, token &tok)
read a keyword from stream
static bool createEntry (dictionary &parDict, iIstream &is, bool hasBlockToken=false)
create an entry (dataEntry or dictionary) from stream
Detailed Description
Dictionary holds a set of data entries or sub-dictionaries that are enclosed in a curely braces or are in a file.
data entry format is:
entryName  value;
and a dictionary in a file can be:
entryName2  value2;
entryName3  value3;
subDict1
{
   entryName4 value4;
   ....
}
subDict2
{
   ...
}
Definition at line 67 of file dictionary.hpp.
Constructor & Destructor Documentation
dictionary() [1/9]
dictionary (const word & keyword, bool global)
construct an empty dictionary with keyword and make it global/fileDictionary (if true)
Constructors
Definition at line 160 of file dictionary.cpp.
dictionary() [2/9]
dictionary (const word & keyword, const fileSystem & file)
construct a dictionary with name and read it from file
Definition at line 175 of file dictionary.cpp.
References pFlow::endl(), fatalExit, ioErrorInFile, IOstream::lineNumber(), and Istream::name().
dictionary() [3/9]
dictionary ()
cunstructs a null dictionary
Definition at line 135 of file dictionary.cpp.
dictionary() [4/9]
dictionary (const word & keyword)
construct an empty dictionary with keyword
Definition at line 146 of file dictionary.cpp.
dictionary() [5/9]
dictionary (const word & keyword, const dictionary & parDict)
cunstruct an empty dictionary with keyword and parDict
Definition at line 199 of file dictionary.cpp.
dictionary() [6/9]
dictionary (const word & keyword, const dictionary & parDict, iIstream & is)
cunstruct a dictionary with keyword and parDict and from stream
Definition at line 215 of file dictionary.cpp.
References pFlow::endl(), fatalExit, ioErrorInFile, IOstream::lineNumber(), and IOstream::name().
dictionary() [7/9]
dictionary (const word & keyword, const dictionary & parDict, const dictionary & dict)
copy construct with keyword and new parrent dict discard the keyword and parDict of dict
Definition at line 238 of file dictionary.cpp.
References iEntry::clone(), pFlow::endl(), fatalErrorInFunction, fatalExit, and dictionary::orderedEntries_.
dictionary() [8/9]
dictionary (const dictionary & src)
copy construct as default behavior entries_ are copied smoothly.
set parrent dict to nullDict
Definition at line 271 of file dictionary.cpp.
References iEntry::clone(), pFlow::endl(), fatalErrorInFunction, fatalExit, and dictionary::orderedEntries_.
dictionary() [9/9]
dictionary (const dictionary & src, bool global)
Definition at line 302 of file dictionary.cpp.
References dictionary::isGlobal_.
Member Function Documentation
findEntry() [1/2]
pFlow::iEntry * findEntry (const word & keyword) protected
find an entry based on keyword return nullptr if not found
Definition at line 106 of file dictionary.cpp.
findEntry() [2/2]
pFlow::iEntry * findEntry (const word & keyword) const protected
find and entry based on keyword return nullptr if not found
Definition at line 121 of file dictionary.cpp.
readDataEntry()
bool readDataEntry (const word & keyword, T & val) const protected
reads a dataEntry with keyword from dictionary
Definition at line 357 of file dictionary.hpp.
References dataEntry::stream().
readDictionary()
bool readDictionary (iIstream & is) protected
read dictionary from stream - without keyword
Definition at line 37 of file dictionary.cpp.
References IOstream::eof(), IOstream::good(), ioErrorInFile, IOstream::lineNumber(), IOstream::name(), and iIstream::putBack().
writeDictionary()
bool writeDictionary (iOstream & os, bool withBlock = true) const protected
write dictionary to stream - with keyword
Definition at line 87 of file dictionary.cpp.
References iOstream::beginBlock(), iOstream::endBlock(), and iOstream::write().
TypeInfo()
TypeInfo ("dictionary")
operator=()
pFlow::dictionary & operator= (const dictionary & rhs)
assignment preserve name of this dictionary only entries are transfered with ownership
Definition at line 310 of file dictionary.cpp.
References pFlow::endl(), fatalErrorInFunction, and fatalExit.
dictPtr() [1/2]
const pFlow::dictionary * dictPtr () virtual
pointer to this dictionary
Reimplemented from iEntry.
Definition at line 339 of file dictionary.cpp.
dictPtr() [2/2]
virtual const dictionary* dictPtr () const virtual
pointer to this dictionary
Reimplemented from iEntry.
isDictionary()
bool isDictionary () const virtual
if this is a dictionary
Reimplemented from iEntry.
Definition at line 351 of file dictionary.cpp.
globalName()
pFlow::word globalName () const virtual
global name of entry, separated with dots
Implements iEntry.
Definition at line 356 of file dictionary.cpp.
Referenced by baseTimeControl::baseTimeControl(), conveyorBelt::conveyorBelt(), regularSimulationDomain::createBoundaryDicts(), iEntry< Key, T * >::createEntry(), cylinder::cylinder(), shape::findPropertyIds(), processField::getFieldType(), main(), multiRotatingAxis::multiRotatingAxis(), simulationDomain::prepareBoundaryDicts(), shapeMixture::read(), property::readDictionary(), sphereShape::readFromDictionary3(), grainShape::readFromDictionary3(), planeWall::readPlaneWall(), rotatingAxis::rotatingAxis(), shapeMixture::shapeMixture(), vibrating::vibrating(), sphereRegion::write(), conveyorBelt::write(), timeInterval::write(), stationaryWall::write(), conveyorBeltMotion::write(), rotatingAxisMotion::write(), vibratingMotion::write(), iBox< intType >::write(), shapeMixture::write(), sphere::write(), box::write(), insertion::write(), line::write(), vibrating::write(), rotatingAxis::write(), cylinder::write(), insertion::writeInsertionDict(), sphereShape::writeToDict(), shape::writeToDict(), and baseShapeNames::writeToDict().
parrentDict()
const pFlow::dictionary & parrentDict () const virtual
const ref to parrent dictionary
Implements iEntry.
Definition at line 362 of file dictionary.cpp.
dict() [1/2]
const pFlow::dictionary & dict () virtual
ref to this dictionary, if it is a dictionary
Implements iEntry.
Definition at line 369 of file dictionary.cpp.
dict() [2/2]
virtual const dictionary& dict () const virtual
const ref to this dictionary, if it is a dictionary
Implements iEntry.
isFileDict()
bool isFileDict () const virtual
if dictionary is file dictionary, return false
Definition at line 380 of file dictionary.cpp.
addPtr()
bool addPtr (const word & keyword, uniquePtr< iEntry > & etry, bool warning = true)
add a pointer entry (dictionary/dataEntry) replaces this entry with existing one and issue a warning
Definition at line 386 of file dictionary.cpp.
References warningInFunction.
Referenced by dictionary::add(), dictionary::addOrKeep(), and iEntry< Key, T * >::createEntry().
add() [1/10]
bool add (const word & keyword, const float & v)
add a float dataEntry
Definition at line 435 of file dictionary.cpp.
Referenced by regularSimulationDomain::createBoundaryDicts(), MotionModel< rotatingAxisMotion, rotatingAxis >::impl_writeDictionary(), baseTimeControl::write(), conveyorBelt::write(), timeInterval::write(), iBox< intType >::write(), shapeMixture::write(), sphere::write(), box::write(), line::write(), vibrating::write(), rotatingAxis::write(), cylinder::write(), multiRotatingAxis::write(), multiRotatingAxisMotion::writeDictionary(), insertion::writeInsertionDict(), insertionRegion::writeInsertionRegion(), sphereShape::writeToDict(), shape::writeToDict(), and baseShapeNames::writeToDict().
add() [2/10]
bool add (const word & keyword, const double & v)
add a double dataEntry
Definition at line 445 of file dictionary.cpp.
add() [3/10]
bool add (const word & keyword, const word & v)
add a word dataEntry
Definition at line 455 of file dictionary.cpp.
add() [4/10]
bool add (const word & keyword, const int64 & v)
add a int64 dataEntry
Definition at line 465 of file dictionary.cpp.
add() [5/10]
bool add (const word & keyword, const int32 & v)
add a int32 dataEntry
Definition at line 475 of file dictionary.cpp.
add() [6/10]
bool add (const word & keyword, const int8 & v)
add a int8 dataEntry
Definition at line 486 of file dictionary.cpp.
add() [7/10]
bool add (const word & keyword, const uint64 & v)
add a uint64 dataEntry
Definition at line 496 of file dictionary.cpp.
add() [8/10]
bool add (const word & keyword, const uint32 & v)
add a uint32 dataEntry
Definition at line 506 of file dictionary.cpp.
add() [9/10]
bool add (const word & keyword, const uint8 & v)
add a uint8 dataEntry
Definition at line 516 of file dictionary.cpp.
addDict()
bool addDict (const word & keyword, const dictionary & dict)
add a dictionary with the specifiedd keyword, if it exists, replace it.
Definition at line 526 of file dictionary.cpp.
Referenced by simulationDomain::prepareBoundaryDicts(), and insertionRegion::writeInsertionRegion().
add() [10/10]
bool add (const word & keyword, const T & v)
add a dataEntry of type T
Definition at line 333 of file dictionary.hpp.
References dictionary::addPtr(), and iEntry::keyword().
addOrKeep()
bool addOrKeep (const word & keyword, const T & v)
Definition at line 343 of file dictionary.hpp.
References dictionary::addPtr(), dictionary::containsDataEntry(), and iEntry::keyword().
addOrReplace()
bool addOrReplace (const word & keyword, const T & v) inline
Definition at line 445 of file dictionary.hpp.
Referenced by regularSimulationDomain::createBoundaryDicts(), and simulationDomain::prepareBoundaryDicts().
clear()
void clear ()
Definition at line 535 of file dictionary.cpp.
subDictPtr()
pFlow::dictionary * subDictPtr (const word & keyword)
pointer to a subdictionary fatalExit if not found
Definition at line 542 of file dictionary.cpp.
References pFlow::endl(), fatalErrorInFunction, and fatalExit.
subDict() [1/2]
pFlow::dictionary & subDict (const word & keyword)
ref to a subdictioanry fatalExit if not found
Definition at line 560 of file dictionary.cpp.
References pFlow::endl(), fatalErrorInFunction, and fatalExit.
Referenced by pFlow::applySelector(), subDomain::bottomDict(), simulationDomain::boundaryDict(), interaction::create(), regularSimulationDomain::createBoundaryDicts(), subDomain::frontDict(), MotionModel< rotatingAxisMotion, rotatingAxis >::impl_readDictionary(), subDomain::leftDict(), main(), positionParticles::positionParticles(), simulationDomain::prepareBoundaryDicts(), countFields::process(), postprocess::processTimeFolder(), multiRotatingAxisMotion::readDictionary(), subDomain::rearDict(), subDomain::rightDict(), simulationDomain::thisBoundariesDict(), and subDomain::topDict().
subDict() [2/2]
const pFlow::dictionary & subDict (const word & keyword) const
const ref to a subdictioanry fatalExit if not found
Definition at line 580 of file dictionary.cpp.
References pFlow::endl(), fatalErrorInFunction, and fatalExit.
dataEntryPtr()
pFlow::dataEntry * dataEntryPtr (const word & keyword)
pointer to a dataEntry fatalExit if not found/not a dataEntry
Definition at line 598 of file dictionary.cpp.
References pFlow::endl(), fatalErrorInFunction, and fatalExit.
dataEntryRef() [1/2]
pFlow::dataEntry & dataEntryRef (const word & keyword)
ref to a subdictioanry fatalExit if not found/not a dataEntry
Definition at line 613 of file dictionary.cpp.
References pFlow::endl(), fatalErrorInFunction, fatalExit, and dataEntry::nullDataEntry.
Referenced by processField::getFieldType(), and setFieldList::readSetFieldList().
dataEntryRef() [2/2]
const pFlow::dataEntry & dataEntryRef (const word & keyword) const
const ref to a subdictioanry fatalExit if not found/not a dataEntry
Definition at line 629 of file dictionary.cpp.
References pFlow::endl(), fatalErrorInFunction, fatalExit, and dataEntry::nullDataEntry.
subDictOrCreate()
pFlow::dictionary & subDictOrCreate (const word & keyword)
search for a sub-dict with keyword create a new sub-dict if not found and return a ref to it fatalExit if fails
Definition at line 647 of file dictionary.cpp.
References pFlow::endl(), fatalErrorInFunction, and fatalExit.
Referenced by countField::countField(), MotionModel< rotatingAxisMotion, rotatingAxis >::impl_writeDictionary(), postprocess::postprocess(), processField::processField(), multiRotatingAxisMotion::writeDictionary(), Insertion< ShapeType >::writeInsertionDict(), and insertionRegion::writeInsertionRegion().
getVal()
T getVal (const word & keyword) const
get the value of data entry
Definition at line 379 of file dictionary.hpp.
References pFlow::endl(), fatalErrorInFunction, and fatalExit.
Referenced by baseTimeControl::baseTimeControl(), boundaryList::boundaryList(), countField::countField(), pStructSelector::create(), interaction::create(), Wall::create(), positionParticles::create(), contactSearch::create(), geometry::create(), boundaryBase::create(), regularSimulationDomain::createBoundaryDicts(), cylinder::cylinder(), dynamicLinkLibs::dynamicLinkLibs(), processField::getFieldType(), MotionModel< rotatingAxisMotion, rotatingAxis >::impl_readDictionary(), simulationDomain::prepareBoundaryDicts(), conveyorBelt::read(), iBox< intType >::read(), shapeMixture::read(), sphere::read(), box::read(), line::read(), vibrating::read(), cylinder::read(), Wall::readCommon(), cuboidWall::readcuboidWall(), cylinderWall::readCylinderWall(), multiRotatingAxisMotion::readDictionary(), grainRolling< contactForceModel >::readGrainDict(), systemControl::readIncludeExclue(), linear< limited >::readLinearDictionary(), cGAbsoluteLinear< limited >::readLinearDictionary(), cGRelativeLinear< limited >::readLinearDictionary(), nonLinearMod< limited >::readNonLinearDictionary(), nonLinear< limited >::readNonLinearDictionary(), normalRolling< contactForceModel >::readNormalDict(), planeWall::readPlaneWall(), stlWall::readSTLWall(), and sphere::sphere().
getValMax()
T getValMax (const word & keyword, const T & maxVal) const
get the value of data entry and return max(value, maxVal)
Definition at line 395 of file dictionary.hpp.
References pFlow::max().
Referenced by boundaryList::boundaryList(), and simulationDomain::prepareBoundaryDicts().
getValMin()
T getValMin (const word & keyword, const T & minVal) const
get the value of data entry and return min(value, minVal)
Definition at line 405 of file dictionary.hpp.
References pFlow::min().
getValOrSet()
T getValOrSet (const word & keyword, const T & setVal) const
get the value of data entry or if not found, set the value to setVal
Definition at line 415 of file dictionary.hpp.
Referenced by baseTimeControl::baseTimeControl(), boundaryExit::boundaryExit(), boundaryReflective::boundaryReflective(), includeMask::getFieldType(), dictionary::getValOrSetMax(), dictionary::getValOrSetMin(), timeInterval::read(), vibrating::read(), rotatingAxis::read(), multiRotatingAxis::read(), Wall::readCommon(), cuboidWall::readcuboidWall(), cylinderWall::readCylinderWall(), Time::readDictionary(), and planeWall::readPlaneWall().
getValOrSetMax()
T getValOrSetMax (const word & keyword, const T & setMaxVal) const
get the value of data entry anf return max(setMaxVal, value) if not found, set the value to setMaxVal
Definition at line 432 of file dictionary.hpp.
References dictionary::getValOrSet(), iEntry::keyword(), and pFlow::max().
Referenced by simulationDomain::prepareBoundaryDicts().
getValOrSetMin()
T getValOrSetMin (const word & keyword, const T & setMinVal) const
get the value of data entry anf return max(setMinVal, value) if not found, set the value to setMinVal
Definition at line 438 of file dictionary.hpp.
References dictionary::getValOrSet(), iEntry::keyword(), and pFlow::min().
numEntries()
size_t numEntries () const
return number of entris in this dictionary
Definition at line 677 of file dictionary.cpp.
numDataEntries()
size_t numDataEntries () const
return number of non-nullptr dataEntries
Definition at line 682 of file dictionary.cpp.
numDictionaries()
size_t numDictionaries () const
return number of non-nullptr dictionaries
Definition at line 695 of file dictionary.cpp.
allKeywords()
pFlow::wordList allKeywords () const
return all keywords (non-nullptr) in this dictionary
Definition at line 708 of file dictionary.cpp.
dataEntryKeywords()
pFlow::wordList dataEntryKeywords () const
return a list of all dataEntries (non-nullptr) keywords
Definition at line 719 of file dictionary.cpp.
Referenced by shapeMixture::read(), and setFieldList::readSetFieldList().
dictionaryKeywords()
pFlow::wordList dictionaryKeywords () const
return a list of all dictionary (non-null) keywords
Definition at line 734 of file dictionary.cpp.
Referenced by MotionModel< rotatingAxisMotion, rotatingAxis >::impl_readDictionary(), postprocess::postprocess(), and multiRotatingAxisMotion::readDictionary().
containsDictionay()
bool containsDictionay (const word & name) const
check if a sub-dictionary exists
Definition at line 749 of file dictionary.cpp.
Referenced by simulationDomain::prepareBoundaryDicts().
containsDataEntry()
bool containsDataEntry (const word & name) const
check if a data entry exist
Definition at line 761 of file dictionary.cpp.
Referenced by dictionary::addOrKeep(), dynamicLinkLibs::dynamicLinkLibs(), processField::getFieldType(), and systemControl::readIncludeExclue().
clone() [1/2]
pFlow::uniquePtr< pFlow::iEntry > clone () const virtual
clone polymorphic object (here dictionary)
Implements iEntry.
Definition at line 804 of file dictionary.cpp.
clonePtr() [1/2]
pFlow::iEntry * clonePtr () const virtual
clone the object
Implements iEntry.
Definition at line 810 of file dictionary.cpp.
clone() [2/2]
pFlow::uniquePtr< pFlow::iEntry > clone (const dictionary & parDict) const virtual
clone the polymorhpic object with parDict as the new parrent dictionary
Implements iEntry.
Definition at line 818 of file dictionary.cpp.
clonePtr() [2/2]
pFlow::iEntry * clonePtr (const dictionary & parDict) const virtual
clone the object and change its ownership to parDict
Implements iEntry.
Definition at line 826 of file dictionary.cpp.
read()
bool read (iIstream & is) override virtual
read from stream
Implements iEntry.
Definition at line 772 of file dictionary.cpp.
References pFlow::endl(), fatalExit, ioErrorInFile, IOstream::lineNumber(), and IOstream::name().
Referenced by fileDictionary::read(), and multiRotatingAxisMotion::read().
write()
bool write (iOstream & os) const override virtual
write to stream
Implements iEntry.
Definition at line 793 of file dictionary.cpp.
References fatalExit, ioErrorInFile, IOstream::lineNumber(), and IOstream::name().
Referenced by fileDictionary::write(), stationaryWall::write(), conveyorBeltMotion::write(), rotatingAxisMotion::write(), vibratingMotion::write(), insertion::write(), baseShapeNames::write(), and multiRotatingAxisMotion::write().
Member Data Documentation
name_
word name_ protected
global name of dictionary, separated with dots
Definition at line 76 of file dictionary.hpp.
Referenced by fileDictionary::fileDictionary().
entries_
wordOrderedMapPtr<iEntry> entries_ protected
all the entries (data and dictionary) of the current dictionary
Definition at line 79 of file dictionary.hpp.
orderedEntries_
List<iEntry*> orderedEntries_ protected
entries in order of insertion
Definition at line 82 of file dictionary.hpp.
Referenced by dictionary::dictionary().
parDict_
const dictionary& parDict_ protected
ref to parrent dictionary
Definition at line 85 of file dictionary.hpp.
isGlobal_
bool isGlobal_ = false protected
Definition at line 87 of file dictionary.hpp.
Referenced by dictionary::dictionary().
nullDict
pFlow::dictionary nullDict static
Definition at line 116 of file dictionary.hpp.
The documentation for this class was generated from the following files:
src/phasicFlow/dictionary/dictionary.hpp
src/phasicFlow/dictionary/dictionary.cpp