PhasicFlow: postprocess Class Reference
postprocess Class Reference
Public Member Functions
postprocess (systemControl &control)
bool processTimeFolder (real time, const word &tName, const fileSystem &localFolder)
bool processTimeFolder (const timeFolder &tFolder)
bool writeToVTK (fileSystem path, word bName) const
Protected Member Functions
auto & timeFolderReposiory ()
Protected Attributes
systemControl & control_
dictionary dict_
wordList numberBasedDictNames_
wordList weightBasedDictNames_
wordList countDictNames_
List< wordList > countedVariableNamesList_
List< uint32List > countedVairablesLists_
uniquePtr< repository > timeFolderReposiory_ {nullptr}
uniquePtr< pointRectCell > pointToCell_ {nullptr}
ListPtr< processField > processedFields_
real time_ =0.0
Logical saveTimes {"No"}
Logical saveTimeFolders {"No"}
Detailed Description
Definition at line 37 of file postprocess.hpp.
Constructor & Destructor Documentation
postprocess()
postprocess (systemControl & control)
Definition at line 28 of file postprocess.cpp.
References postprocess::countDictNames_, postprocess::dict_, dictionary::dictionaryKeywords(), END_REPORT, pFlow::endl(), postprocess::numberBasedDictNames_, REPORT, dictionary::subDictOrCreate(), postprocess::weightBasedDictNames_, and Yellow_Text.
Member Function Documentation
timeFolderReposiory()
auto& timeFolderReposiory () inline protected
Definition at line 73 of file postprocess.hpp.
References postprocess::timeFolderReposiory_.
processTimeFolder() [1/2]
bool processTimeFolder (real time, const word & tName, const fileSystem & localFolder)
Definition at line 58 of file postprocess.cpp.
References countFields::countedValues(), processField::create(), Cyan_Text, END_REPORT, pFlow::endl(), fatalExit, pFlow::output, countFields::process(), pStruct, REPORT, dictionary::subDict(), countFields::variableNames(), and Yellow_Text.
Referenced by main().
processTimeFolder() [2/2]
bool processTimeFolder (const timeFolder & tFolder)
Definition at line 124 of file postprocess.cpp.
References timeFolder::localFolder(), timeFolder::time(), and timeFolder::timeName().
writeToVTK()
bool writeToVTK (fileSystem path, word bName) const
Definition at line 133 of file postprocess.cpp.
References END_REPORT, fatalErrorInFunction, ForAll, and REPORT.
Referenced by main().
Member Data Documentation
control_
systemControl& control_ protected
Definition at line 41 of file postprocess.hpp.
dict_
dictionary dict_ protected
Definition at line 43 of file postprocess.hpp.
Referenced by postprocess::postprocess().
numberBasedDictNames_
wordList numberBasedDictNames_ protected
Definition at line 45 of file postprocess.hpp.
Referenced by postprocess::postprocess().
weightBasedDictNames_
wordList weightBasedDictNames_ protected
Definition at line 47 of file postprocess.hpp.
Referenced by postprocess::postprocess().
countDictNames_
wordList countDictNames_ protected
Definition at line 49 of file postprocess.hpp.
Referenced by postprocess::postprocess().
countedVariableNamesList_
List<wordList> countedVariableNamesList_ protected
Definition at line 51 of file postprocess.hpp.
countedVairablesLists_
List<uint32List> countedVairablesLists_ protected
Definition at line 53 of file postprocess.hpp.
timeFolderReposiory_
uniquePtr<repository> timeFolderReposiory_ {nullptr} protected
Definition at line 55 of file postprocess.hpp.
Referenced by postprocess::timeFolderReposiory().
pointToCell_
uniquePtr<pointRectCell> pointToCell_ {nullptr} protected
Definition at line 57 of file postprocess.hpp.
processedFields_
ListPtr<processField> processedFields_ protected
Definition at line 61 of file postprocess.hpp.
time_
real time_ =0.0 protected
Definition at line 63 of file postprocess.hpp.
saveTimes
Logical saveTimes {"No"} protected
Definition at line 68 of file postprocess.hpp.
saveTimeFolders
Logical saveTimeFolders {"No"} protected
Definition at line 70 of file postprocess.hpp.
The documentation for this class was generated from the following files:
utilities/postprocessPhasicFlow/postprocess.hpp
utilities/postprocessPhasicFlow/postprocess.cpp