PhasicFlow: dynamicPointStructure Class Reference
dynamicPointStructure Class Reference
Public Member Functions
TypeInfo ("dynamicPointStructure")
dynamicPointStructure (systemControl &control)
dynamicPointStructure (const dynamicPointStructure &ps)=delete
dynamicPointStructure (dynamicPointStructure &&)=delete
dynamicPointStructure & operator= (const dynamicPointStructure &)=delete
dynamicPointStructure & operator= (dynamicPointStructure &&)=delete
~dynamicPointStructure () override=default
const realx3PointField_D & velocity () const
realx3PointField_D & velocity ()
bool beforeIteration () override
In the time loop before iterate.
bool iterate () override
This is called in time loop.
bool predict (real dt, realx3PointField_D &acceleration)
prediction step (if any), is called in beforeIteration
bool correct (real dt, realx3PointField_D &acceleration)
correction step, is called in iterate
Public Member Functions inherited from pointStructure
TypeInfo ("pointStructure")
pointStructure (systemControl &control)
an empty pointStructure, good for reading from file
pointStructure (systemControl &control, const realx3Vector &posVec)
construct from point positions, assume all points are active
pointStructure (const pointStructure &)=delete
pointStructure (pointStructure &&)=delete
pointStructure & operator= (const pointStructure &)=delete
pointStructure & operator= (pointStructure &&)=delete
~pointStructure () override=default
bool beforeIteration () override
In the time loop before iterate.
bool iterate () override
This is called in time loop.
bool afterIteration () override
This is called in time loop, after iterate.
auto & boundaries ()
const auto & boundaries () const
Time & time () override
const Time & time () const override
boundaryBase & boundary (size_t i) override
const boundaryBase & boundary (size_t i) const override
const auto & simDomain () const
const auto & thisDomain () const
const auto & extendedDomain () const
auto internalDomainBox () const
bool read (iIstream &is, const IOPattern &iop) override
read the point structure from the input stream.
bool write (iOstream &os, const IOPattern &iop) const override
Write.
Public Member Functions inherited from IOobject
virtual word typeName () const =0
IOobject (const objectFile &objf, const IOPattern &iop, repository *owner)
~IOobject () override
IOobject (const IOobject &src)=delete
IOobject (IOobject &&src)=delete
const IOPattern & ioPattern () const
const repository * owner () const override
repository * owner ()
repository * releaseOwner (bool fromOwner=false)
bool isIncluded (const word &objName) const override
bool isExcluded (const word &objName) const override
bool readObject (bool rdHdr=true)
bool writeObject () const
bool readObject (iIstream &is, bool rdHdr=true)
bool writeObject (iOstream &os) const
Public Member Functions inherited from IOfileHeader
IOfileHeader (const objectFile &objf)
const word & objectName () const
const word & objectType () const
fileSystem path () const
bool outFileBinary () const
bool inFileBinary () const
bool headerOk (bool silent=false)
bool implyRead () const
Imply read.
bool implyWrite () const
Imply write.
bool fileExist () const
Check if file exists.
bool readIfPresent () const
Check read if present.
bool writeHeader () const
Check if the header should be written to file True: on master + implyWrite + readWriteHeader = true False: otherwise.
bool writeHeader (iOstream &os, const word &typeName, bool forceWrite=false) const
Write the header to the file , typeName comes from caller.
bool writeHeader (iOstream &os, bool forceWrite=false) const
Write the header to the file, typeName comes from the one read from file.
bool readHeader () const
Check if header should be read from file.
bool readHeader (iIstream &is, bool silent=false)
Read the header in the file.
bool writeBanner (iOstream &os) const
write the banner
bool writeSeparator (iOstream &os) const
wirte a separator line
Public Member Functions inherited from objectFile
objectFile (const word &name)
objectFile (const word &name, const fileSystem &localPath, const readFlag &rf=readFlag::READ_NEVER, const writeFlag &wf=writeFlag::WRITE_NEVER, bool rwHeader=true)
objectFile (const objectFile &src)=default
objectFile (objectFile &&src)=default
objectFile & operator= (const objectFile &rhs)=default
objectFile & operator= (objectFile &&rhs)=default
virtual ~objectFile ()=default
virtual const word & name () const
virtual const fileSystem & localPath () const
readFlag rFlag () const
writeFlag wFlag () const
bool isReadAlways () const
bool isReadNever () const
bool isReadIfPresent () const
bool isWriteAlways () const
bool isWriteNever () const
bool readWriteHeader () const
Public Member Functions inherited from demComponent
TypeInfo ("demComponent")
Type info.
demComponent (const word &name, systemControl &control)
construct from components
demComponent (const demComponent &)=delete
No copy constructor.
demComponent (demComponent &&)=delete
No move constructor.
demComponent & operator= (const demComponent &)=delete
No copy assignment.
demComponent & operator= (demComponent &&)=delete
No move assignment.
virtual ~demComponent ()=default
destructor
const auto & control () const
Const ref to systemControl.
auto & control ()
Ref to systemControl.
real dt () const
Time step of integration.
real currentTime () const
Current simulation time.
uint32 currentIter () const
return current iteration number
timeInfo TimeInfo () const
return time info of the simulaiton
const auto & time () const
auto & time ()
const auto & timers () const
Const ref to timers.
auto & timers ()
Ref to timers.
virtual bool beforeTimeLoop ()
This is called before the start of time loop.
virtual bool afterTimeLoop ()
This is called after the time loop.
Public Member Functions inherited from internalPoints
TypeInfo ("internalPoints")
internalPoints ()
internalPoints (const realx3Vector &posVec)
Construct from point positions, assume all points are active.
internalPoints (const internalPoints &)=delete
No Copy construct.
internalPoints (internalPoints &&)=default
Move construct.
internalPoints & operator= (const internalPoints &)=delete
No Copy assignment.
internalPoints & operator= (internalPoints &&)=default
Move assignment.
~internalPoints () override=default
Destructor.
const pFlagTypeDevice & activePointsMaskDevice () const
const pFlagTypeHost & activePointsMaskHost () const
const PointsType & pointPosition () const
PointsType & pointPosition ()
auto pointPositionHost () const
auto pointPositionDevice () const
PointsTypeHost activePointsHost () const
uint32 size () const
uint32 capacity () const
bool empty () const
uint32 numActive () const
bool isAllActive () const
auto activeRange () const
bool deletePoints (scatteredFieldAccess< uint32, memory_space > delPoints)
delete points at indices given in delPoints.
uint32 updateFlag (const domain &dm, const std::array< real, 6 > &dist)
void fillNeighborsLists (ViewType1D< uint32, memory_space > leftList, ViewType1D< uint32, memory_space > rightList, ViewType1D< uint32, memory_space > bottomList, ViewType1D< uint32, memory_space > topList, ViewType1D< uint32, memory_space > rearList, ViewType1D< uint32, memory_space > frontList)
bool insertPoints (const realx3Vector &points, anyList &varList)
bool insertPointsOnly (const realx3Vector_D &points, message &msg, anyList &varList)
bool read (iIstream &is)
Read.
bool write (iOstream &os) const
Write.
bool read (iIstream &is, const IOPattern &iop)
Read.
bool write (iOstream &os, const IOPattern &iop) const
Write.
Public Member Functions inherited from subscriber
subscriber (const word &name)
subscriber (const subscriber &)
Copy constructor, only copies the name, not the list.
subscriber (subscriber &&)
Move constructor, moves the name and the list, also change the subriber of the object in the list
subscriber & operator= (const subscriber &)
Copy assignemnt, only assign the name, do not assign the list.
subscriber & operator= (subscriber &&)
Move assignment, move assign name and list, also change the subcriber of the object in the list
virtual ~subscriber ()
virtual bool subscribe (message msg, observer *obsevr) const
virtual bool unsubscribe (observer *obsevr) const
bool notify (uint32 iter, real t, real dt, const message msg, const anyList &varList)
bool notify (const timeInfo &ti, const message msg, const anyList &varList)
const word & subscriberName () const
Private Attributes
realx3PointField_D velocity_
uniquePtr< integration > integrationPos_ = nullptr
uniquePtr< integration > integrationVel_ = nullptr
Timer velocityUpdateTimer_
word integrationMethod_
integration method for velocity and position
Additional Inherited Members
Public Types inherited from pointStructure
using PointsType = typename internalPoints::PointsType
using PointsTypeHost = typename PointsType::FieldTypeHost
using device_type = typename PointsType::device_type
using memory_space = typename PointsType::memory_space
using execution_space = typename PointsType::execution_space
Public Types inherited from objectFile
enum readFlag { READ_ALWAYS, READ_NEVER, READ_IF_PRESENT }
enum writeFlag { WRITE_ALWAYS, WRITE_NEVER }
Public Types inherited from internalPoints
using PointsType = realx3Field_D
using PointsTypeHost = typename PointsType::FieldTypeHost
using device_type = typename PointsType::device_type
using memory_space = typename PointsType::memory_space
using execution_space = typename PointsType::execution_space
Static Public Attributes inherited from internalPoints
static const uint32 initialCapacity_ = 10000
Protected Member Functions inherited from IOfileHeader
uniquePtr< iFstream > inStream () const
uniquePtr< oFstream > outStream () const
uniquePtr< oFstream > dummyOutStream () const
Protected Member Functions inherited from internalPoints
void syncPFlag () const
void unSyncFlag ()
void createDeviceFlag (uint32 cap, uint32 start, uint32 end)
bool sortPoints (const uint32IndexContainer &sortedIndices)
Protected Attributes inherited from IOfileHeader
word objectName_
word objectType_
word fileFormat_ = "ASCII"
file format read from file
Detailed Description
Definition at line 35 of file dynamicPointStructure.hpp.
Constructor & Destructor Documentation
dynamicPointStructure() [1/3]
dynamicPointStructure (systemControl & control) explicit
Definition at line 25 of file dynamicPointStructure.cpp.
References END_REPORT, fatalErrorInFunction, fatalExit, Green_Text, and REPORT.
dynamicPointStructure() [2/3]
dynamicPointStructure (const dynamicPointStructure & ps) delete
dynamicPointStructure() [3/3]
dynamicPointStructure (dynamicPointStructure &&) delete
~dynamicPointStructure()
~dynamicPointStructure () override default
Member Function Documentation
TypeInfo()
TypeInfo ("dynamicPointStructure")
operator=() [1/2]
dynamicPointStructure& operator= (const dynamicPointStructure &) delete
operator=() [2/2]
dynamicPointStructure& operator= (dynamicPointStructure &&) delete
velocity() [1/2]
const realx3PointField_D& velocity () const inline
Definition at line 74 of file dynamicPointStructure.hpp.
References dynamicPointStructure::velocity_.
Referenced by particles::velocity().
velocity() [2/2]
realx3PointField_D& velocity () inline
Definition at line 80 of file dynamicPointStructure.hpp.
References dynamicPointStructure::velocity_.
beforeIteration()
bool beforeIteration () override virtual
In the time loop before iterate.
Implements demComponent.
Definition at line 83 of file dynamicPointStructure.cpp.
References pointStructure::beforeIteration(), Timer::end(), dynamicPointStructure::integrationPos_, dynamicPointStructure::integrationVel_, Timer::start(), pointField< T, MemorySpace >::updateBoundariesSlaveToMasterIfRequested(), dynamicPointStructure::velocity_, and dynamicPointStructure::velocityUpdateTimer_.
iterate()
bool iterate () override virtual
This is called in time loop.
Perform the main calculations when the component should evolve along time.
Implements demComponent.
Definition at line 94 of file dynamicPointStructure.cpp.
References pointStructure::iterate().
predict()
bool predict (real dt, realx3PointField_D & acceleration)
prediction step (if any), is called in beforeIteration
Definition at line 104 of file dynamicPointStructure.cpp.
References pFlow::grainParticlesKernels::acceleration().
correct()
bool correct (real dt, realx3PointField_D & acceleration)
correction step, is called in iterate
Definition at line 116 of file dynamicPointStructure.cpp.
References pFlow::grainParticlesKernels::acceleration().
Member Data Documentation
velocity_
realx3PointField_D velocity_ private
Definition at line 41 of file dynamicPointStructure.hpp.
Referenced by dynamicPointStructure::beforeIteration(), and dynamicPointStructure::velocity().
integrationPos_
uniquePtr<integration> integrationPos_ = nullptr private
Definition at line 43 of file dynamicPointStructure.hpp.
Referenced by dynamicPointStructure::beforeIteration().
integrationVel_
uniquePtr<integration> integrationVel_ = nullptr private
Definition at line 45 of file dynamicPointStructure.hpp.
Referenced by dynamicPointStructure::beforeIteration().
velocityUpdateTimer_
Timer velocityUpdateTimer_ private
Definition at line 47 of file dynamicPointStructure.hpp.
Referenced by dynamicPointStructure::beforeIteration().
integrationMethod_
word integrationMethod_ private
integration method for velocity and position
Definition at line 50 of file dynamicPointStructure.hpp.
The documentation for this class was generated from the following files:
src/Particles/dynamicPointStructure/dynamicPointStructure.hpp
src/Particles/dynamicPointStructure/dynamicPointStructure.cpp