PhasicFlow: nonLinear< limited > Class Template Reference
nonLinear< limited > Class Template Reference
Classes
struct contactForceStorage
struct nonLinearProperties
Public Member Functions
TypeInfoNV (modelName())
INLINE_FUNCTION_HD nonLinear ()
nonLinear (int32 nMaterial, const ViewType1D< real > &rho, const dictionary &dict)
INLINE_FUNCTION_HD nonLinear (const nonLinear &)=default
INLINE_FUNCTION_HD nonLinear (nonLinear &&)=default
INLINE_FUNCTION_HD nonLinear & operator= (const nonLinear &)=default
INLINE_FUNCTION_HD nonLinear & operator= (nonLinear &&)=default
INLINE_FUNCTION_HD ~nonLinear ()=default
INLINE_FUNCTION_HD int32 numMaterial () const
INLINE_FUNCTION_HD void contactForce (const real dt, const int32 i, const int32 j, const int32 propId_i, const int32 propId_j, const real Ri, const real Rj, const real ovrlp_n, const realx3 &Vr, const realx3 &Nij, contactForceStorage &history, realx3 &FCn, realx3 &FCt) const
Protected Types
using NonLinearArrayType = symArray< nonLinearProperties >
Protected Member Functions
bool readNonLinearDictionary (const dictionary &dict)
Static Protected Member Functions
static const char * modelName ()
Protected Attributes
int32 numMaterial_ = 0
ViewType1D< real > rho_
NonLinearArrayType nonlinearProperties_
Detailed Description
template<bool limited = true>
class pFlow::cfModels::nonLinear< limited >
Definition at line 30 of file nonLinearCF.hpp.
Member Typedef Documentation
NonLinearArrayType
using NonLinearArrayType = symArray<nonLinearProperties> protected
Definition at line 66 of file nonLinearCF.hpp.
Constructor & Destructor Documentation
nonLinear() [1/4]
INLINE_FUNCTION_HD nonLinear () inline
Definition at line 170 of file nonLinearCF.hpp.
nonLinear() [2/4]
nonLinear (int32 nMaterial, const ViewType1D< real > & rho, const dictionary & dict) inline
Definition at line 172 of file nonLinearCF.hpp.
References fatalExit, nonLinear< limited >::readNonLinearDictionary(), and nonLinear< limited >::rho_.
nonLinear() [3/4]
INLINE_FUNCTION_HD nonLinear (const nonLinear< limited > &) default
nonLinear() [4/4]
INLINE_FUNCTION_HD nonLinear (nonLinear< limited > &&) default
~nonLinear()
INLINE_FUNCTION_HD ~nonLinear () default
Member Function Documentation
readNonLinearDictionary()
bool readNonLinearDictionary (const dictionary & dict) inline protected
Definition at line 74 of file nonLinearCF.hpp.
References symArray< T, MemorySpace >::assign(), fatalErrorInFunction, ForAll, symArray< nonLinearProperties >::getN(), dictionary::getVal(), pFlow::log(), nonLinear< limited >::nonlinearProperties_, nonLinear< limited >::numMaterial_, pFlow::Pi, pFlow::pow(), Vector< T, Allocator >::size(), and pFlow::sqrt().
Referenced by nonLinear< limited >::nonLinear().
modelName()
static const char* modelName () inline static protected
Definition at line 152 of file nonLinearCF.hpp.
TypeInfoNV()
TypeInfoNV (modelName())
operator=() [1/2]
INLINE_FUNCTION_HD nonLinear& operator= (const nonLinear< limited > &) default
operator=() [2/2]
INLINE_FUNCTION_HD nonLinear& operator= (nonLinear< limited > &&) default
numMaterial()
INLINE_FUNCTION_HD int32 numMaterial () const inline
Definition at line 206 of file nonLinearCF.hpp.
References nonLinear< limited >::numMaterial_.
contactForce()
INLINE_FUNCTION_HD void contactForce (const real dt, const int32 i, const int32 j, const int32 propId_i, const int32 propId_j, const real Ri, const real Rj, const real ovrlp_n, const realx3 & Vr, const realx3 & Nij, contactForceStorage & history, realx3 & FCn, realx3 & FCt) const inline
Definition at line 215 of file nonLinearCF.hpp.
References dot(), length(), nonLinear< limited >::nonlinearProperties_, nonLinear< limited >::contactForceStorage::overlap_t_, pFlow::Pi, pFlow::pow(), nonLinear< limited >::rho_, and pFlow::sqrt().
Member Data Documentation
numMaterial_
int32 numMaterial_ = 0 protected
Definition at line 68 of file nonLinearCF.hpp.
Referenced by nonLinear< limited >::numMaterial(), and nonLinear< limited >::readNonLinearDictionary().
rho_
ViewType1D<real> rho_ protected
Definition at line 70 of file nonLinearCF.hpp.
Referenced by nonLinear< limited >::contactForce(), and nonLinear< limited >::nonLinear().
nonlinearProperties_
NonLinearArrayType nonlinearProperties_ protected
Definition at line 72 of file nonLinearCF.hpp.
Referenced by nonLinear< limited >::contactForce(), and nonLinear< limited >::readNonLinearDictionary().
The documentation for this class was generated from the following file:
src/Interaction/Models/contactForce/nonLinearCF.hpp