PhasicFlow: processorOstream Class Reference
processorOstream Class Reference
Output stream for MPI parallel run, when we need to know which the processor number in the output line.
Public Member Functions
processorOstream (std::ostream &os, const word &streamName)
From components.
processorOstream (const processorOstream &)=delete
No copy construct.
void operator= (const processorOstream &)=delete
No copy assignment.
word setPrefixNum (int procNum)
Set processor number to be used in the prefix.
void activatePrefix ()
Activate prefix for this stream.
bool write (const token &tok)
Write token to stream or otherwise handle it.
iOstream & write (const char c) override
Write character.
iOstream & write (const char *str) override
Write character string.
iOstream & write (const word &str) override
Write word.
iOstream & writeQuoted (const word &str, const bool quoted=true) override
Write std::string surrounded by quotes.
iOstream & write (const int64 val) override
Write int64.
iOstream & write (const int32 val) override
Write int32.
iOstream & write (const int8 val) override
Write int32.
iOstream & write (const uint64 val) override
Write uint64.
iOstream & write (const uint32 val) override
Write uint32.
iOstream & write (const uint8 val) override
Write uint8.
iOstream & write (const float val) override
Write float.
iOstream & write (const double val) override
Write double.
iOstream & write (const size_t val) override
Write double.
iOstream & write (const char *binaryData, std::streamsize count) override
Write a block of binray data.
void indent () override
Add indentation characters.
processorOstream & setColor (const char *colorCode)
Public Member Functions inherited from Ostream
Ostream (std::ostream &os, const word &streamName, writeFormat wf=ASCII)
Construct from components.
Ostream (const Ostream &)=delete
No copy construct.
void operator= (const Ostream &)=delete
No copy assignment.
virtual const word & name () const
Return the name of the stream.
virtual word & name ()
Return non-const access to the name of the stream.
virtual ios_base::fmtflags flags () const
Return flags of output stream.
bool write (const token &tok) override
Write token to stream or otherwise handle it.
iOstream & write (const char c) override
Write character.
iOstream & write (const char *str) override
Write character string.
iOstream & write (const word &str) override
Write word.
iOstream & writeQuoted (const word &str, const bool quoted=true) override
Write std::string surrounded by quotes.
iOstream & write (const int64 val) override
Write int64.
iOstream & write (const int32 val) override
Write int32.
iOstream & write (const int8 val) override
Write int32.
iOstream & write (const uint64 val) override
Write uint64.
iOstream & write (const uint32 val) override
Write uint32.
iOstream & write (const uint8 val) override
Write uint8.
iOstream & write (const float val) override
Write float.
iOstream & write (const double val) override
Write double.
iOstream & write (const size_t val) override
Write size_t.
iOstream & write (const char *binaryData, std::streamsize count) override
Write a block of binray data.
iOstream & writeBinaryBlockFlag () override
Write the flag to indicate the start of a binary block.
void seek (size_t pos) override
void indent () override
Add indentation characters.
ios_base::fmtflags flags (const ios_base::fmtflags f) override
Set stream flags.
void startOfBinaryStreaming () override
Add a new line and flush stream.
void endOfBinaryStreaming () override
Reach end of file add a new line and flush stream.
void flush () override
Flush stream.
void endl () override
Add newline and flush stream.
char fill () const override
Get the current padding character.
char fill (const char fillch) override
Set padding character for formatted field up to field width.
int width () const override
Get width of output field.
int width (const int w) override
Set width of output field.
int precision () const override
Get precision of output field.
int precision (const int p) override
Set precision of output field return old precision.
virtual std::ostream & stdStream ()
Access to underlying std::ostream.
virtual const std::ostream & stdStream () const
Const access to underlying std::ostream.
Public Member Functions inherited from iOstream
iOstream ()
Default.
iOstream (writeFormat wF)
Construct from writeFormat.
iOstream (const iOstream &)=default
Copy construct.
virtual ~iOstream ()=default
Destructor.
unsigned short indentSize () const
Return indent level.
unsigned short & indentSize ()
Access to indent size.
unsigned short indentLevel () const
Return indent level.
unsigned short & indentLevel ()
Access to indent level.
void incrIndent ()
Increment the indent level.
void decrIndent ()
Decrement the indent level.
virtual iOstream & beginBlock (const word &kw)
Write begin block group with a name Increments indentation, adds newline.
virtual iOstream & beginBlock ()
Write begin block group without a name Increments indentation, adds newline.
virtual iOstream & endBlock ()
Write end block group Decrements indentation, adds newline.
virtual iOstream & beginList ()
Write begin list "(".
virtual iOstream & beginList (const word &kw)
Write begin list with keyword "kw (".
virtual iOstream & endList ()
Write end list ")".
virtual iOstream & beginSquare ()
Write begin list "[".
virtual iOstream & beginSquare (const word &kw)
Write begin list with keyword "kw [".
virtual iOstream & endSquare ()
Write end list "]".
virtual iOstream & endEntry ()
Write end entry (';') followed by newline.
virtual iOstream & newLine ()
Write a newLine to stream.
virtual iOstream & space (int32 n=1)
Write space to stream.
virtual iOstream & writeWordKeyword (const word &kw)
Write the keyword followed by an appropriate indentation.
template<class T >
iOstream & writeWordEntry (const word &key, const T &value)
Write a keyword/value entry.
iOstream & operator() () const
Return a non-const reference to const iOstream Needed for write functions where the stream argument is temporary: e.g.
Public Member Functions inherited from IOstream
IOstream ()
Default.
IOstream (writeFormat wF)
Construct and set write format.
IOstream (const IOstream &)=default
Copy.
virtual ~IOstream ()=default
Destructor.
virtual bool check (const char *operation) const
Check IOstream status for given operation.
bool fatalCheck (const char *operation) const
Check IOstream status for given operation.
bool opened () const
Return true if stream has been opened.
bool closed () const
Return true if stream is closed.
bool isBinary () const
Return true if stream format is binray.
bool good () const
Return true if next operation might succeed.
bool eof () const
Return true if end of input seen.
bool fail () const
Return true if next operation will fail.
bool bad () const
Return true if stream is corrupted.
operator bool () const
Return true if the stream has not failed.
bool operator! () const
Return true if the stream has failed.
int32 lineNumber () const
Const access to the current stream line number.
int32 & lineNumber ()
Non-const access to the current stream line number.
int32 lineNumber (const int32 num)
Set the stream line number return the previous value.
void setEof ()
Set stream to have reached eof.
void setFail ()
Set stream to have failed.
void setBad ()
Set stream to be bad.
ios_base::fmtflags setf (const ios_base::fmtflags f)
Set flags of stream.
ios_base::fmtflags setf (const ios_base::fmtflags f, const ios_base::fmtflags mask)
Set flags of given field of stream.
void unsetf (const ios_base::fmtflags f)
Unset flags of stream.
Protected Member Functions
void checkForPrefix ()
Output the prefix if required.
Protected Member Functions inherited from IOstream
void setOpened ()
Set stream opened.
void setClosed ()
Set stream closed.
void setState (ios_base::iostate state)
Set stream state.
void setWriteFormat (writeFormat wF)
void setGood ()
Set stream to be good.
Protected Attributes
bool printPrefix_ = false
Print prefix?
word prefix_ = ""
Prefix word
Protected Attributes inherited from iOstream
unsigned short indentSize_ = 4
Number of spaces per indent level.
unsigned short indentLevel_ = 0
Current indent level.
Protected Attributes inherited from IOstream
streamAccess openClosed_
Is stream open or closed.
writeFormat writeFormat_ = ASCII
write format
ios_base::iostate ioState_
state
int32 lineNumber_
The file line.
Additional Inherited Members
Public Types inherited from IOstream
enum streamAccess : char { CLOSED = 0, OPENED }
enum writeFormat : char { ASCII = 0, BINARY }
Static Public Member Functions inherited from IOstream
static unsigned int defaultPrecision ()
Return the default precision.
static unsigned int defaultPrecision (unsigned int prec)
Reset the default precision return the previous value.
Static Public Attributes inherited from IOstream
static unsigned int precision_ = 6
Default precision, only works for ASCII.
Static Protected Attributes inherited from iOstream
static constexpr const unsigned short entryIndentation_ = 16
Indentation of the entry from the start of the keyword.
Static Protected Attributes inherited from IOstream
static word staticName_
Name for any generic stream - normally treat as readonly.
Detailed Description
Output stream for MPI parallel run, when we need to know which the processor number in the output line.
The processor number is shown as a prefix for the output line.
It is based on OpenFOAM stream, with some modifications/simplifications to be tailored to our needs.
Definition at line 36 of file processorOstream.hpp.
Constructor & Destructor Documentation
processorOstream() [1/2]
processorOstream (std::ostream & os, const word & streamName)
From components.
Definition at line 28 of file processorOstream.cpp.
processorOstream() [2/2]
processorOstream (const processorOstream &) delete
No copy construct.
Member Function Documentation
checkForPrefix()
void checkForPrefix () inline protected
Output the prefix if required.
Definition at line 50 of file processorOstream.hpp.
References processorOstream::prefix_, processorOstream::printPrefix_, and Ostream::write().
Referenced by processorOstream::write().
operator=()
void operator= (const processorOstream &) delete
No copy assignment.
setPrefixNum()
word setPrefixNum (int procNum) inline
Set processor number to be used in the prefix.
Definition at line 76 of file processorOstream.hpp.
References pFlow::int322Word(), and processorOstream::prefix_.
Referenced by processors::initProcessors().
activatePrefix()
void activatePrefix () inline
Activate prefix for this stream.
Definition at line 83 of file processorOstream.hpp.
References processorOstream::printPrefix_.
Referenced by processors::initProcessors().
write() [1/14]
bool write (const token & tok) inline virtual
Write token to stream or otherwise handle it.
return false if the token type was not handled by this method
Implements iOstream.
Definition at line 90 of file processorOstream.hpp.
References Ostream::write().
write() [2/14]
pFlow::iOstream & write (const char c) override virtual
Write character.
Implements iOstream.
Definition at line 37 of file processorOstream.cpp.
References processorOstream::checkForPrefix(), token::NL, processorOstream::printPrefix_, and Ostream::write().
write() [3/14]
pFlow::iOstream & write (const char * str) override virtual
Write character string.
Implements iOstream.
Definition at line 52 of file processorOstream.cpp.
References token::NL, and Ostream::write().
write() [4/14]
pFlow::iOstream & write (const word & str) override virtual
Write word.
Implements iOstream.
Definition at line 67 of file processorOstream.cpp.
References Ostream::write().
writeQuoted()
pFlow::iOstream & writeQuoted (const word & str, const bool quoted = true) override virtual
Write std::string surrounded by quotes.
Implements iOstream.
Definition at line 75 of file processorOstream.cpp.
References Ostream::writeQuoted().
write() [5/14]
pFlow::iOstream & write (const int64 val) override virtual
Write int64.
Implements iOstream.
Definition at line 86 of file processorOstream.cpp.
References Ostream::write().
write() [6/14]
pFlow::iOstream & write (const int32 val) override virtual
Write int32.
Implements iOstream.
Definition at line 93 of file processorOstream.cpp.
References Ostream::write().
write() [7/14]
pFlow::iOstream & write (const int8 val) override virtual
Write int32.
Implements iOstream.
Definition at line 100 of file processorOstream.cpp.
References Ostream::write().
write() [8/14]
pFlow::iOstream & write (const uint64 val) override virtual
Write uint64.
Implements iOstream.
Definition at line 106 of file processorOstream.cpp.
References Ostream::write().
write() [9/14]
pFlow::iOstream & write (const uint32 val) override virtual
Write uint32.
Implements iOstream.
Definition at line 112 of file processorOstream.cpp.
References Ostream::write().
write() [10/14]
pFlow::iOstream & write (const uint8 val) override virtual
Write uint8.
Implements iOstream.
Definition at line 118 of file processorOstream.cpp.
References Ostream::write().
write() [11/14]
pFlow::iOstream & write (const float val) override virtual
Write float.
Implements iOstream.
Definition at line 124 of file processorOstream.cpp.
References Ostream::write().
write() [12/14]
pFlow::iOstream & write (const double val) override virtual
Write double.
Implements iOstream.
Definition at line 131 of file processorOstream.cpp.
References Ostream::write().
write() [13/14]
pFlow::iOstream & write (const size_t val) override virtual
Write double.
Implements iOstream.
Definition at line 137 of file processorOstream.cpp.
References Ostream::write().
write() [14/14]
pFlow::iOstream & write (const char * binaryData, std::streamsize count) override virtual
Write a block of binray data.
Implements iOstream.
Definition at line 144 of file processorOstream.cpp.
References pFlow::count(), and Ostream::write().
indent()
void indent () override virtual
Add indentation characters.
Implements iOstream.
Definition at line 154 of file processorOstream.cpp.
References Ostream::indent().
setColor()
pFlow::processorOstream & setColor (const char * colorCode)
Definition at line 160 of file processorOstream.cpp.
References Ostream::write().
Member Data Documentation
printPrefix_
bool printPrefix_ = false protected
Print prefix?
Definition at line 43 of file processorOstream.hpp.
Referenced by processorOstream::activatePrefix(), processorOstream::checkForPrefix(), and processorOstream::write().
prefix_
word prefix_ = "" protected
Prefix word
Definition at line 46 of file processorOstream.hpp.
Referenced by processorOstream::checkForPrefix(), and processorOstream::setPrefixNum().
The documentation for this class was generated from the following files:
src/phasicFlow/streams/processorOstream/processorOstream.hpp
src/phasicFlow/streams/processorOstream/processorOstream.cpp