PhasicFlow: processors Class Reference
processors Class Reference
This class holds the information about the global execution world and number of processors in communication.
Public Member Functions
processors ()
Constructor.
~processors ()
Destructor.
Static Public Member Functions
static void initProcessors (int argc, char *argv[])
Initialize MPI processors.
static void finalizeProcessors ()
Finalize MPI processors.
static int globalMasterNo ()
Master processors number (globaly in MPI).
static bool globalParallel ()
Is this a parallel MPI run.
static const char * globalRunTypeName ()
static bool isInitialized ()
Is MPI initialized?
static bool isFinalized ()
Is MPI finalized?
static bool globalMaster ()
Is this processor the master processor?
static int globalSize ()
Global size of processors.
static int globalRank ()
Rank of the processor in the global MPI.
static int argc ()
static char ** argv ()
static void abort (int error)
Abort MPI run or regular run.
Static Private Attributes
static bool initProcessorsCelled_ = false
Is the static member initProcessors is called.
static int globalRank_ = 0
Global rank of the current processor.
static int globalSize_ = 1
The global size of all processors.
static int argc_ = 0
static char ** argv_ = nullptr
Detailed Description
This class holds the information about the global execution world and number of processors in communication.
Definition at line 51 of file processors.hpp.
Constructor & Destructor Documentation
processors()
processors ()
Constructor.
Definition at line 105 of file processors.cpp.
References processors::abort(), pFlow::endl(), and fatalErrorInFunction.
~processors()
~processors ()
Destructor.
Definition at line 119 of file processors.cpp.
Member Function Documentation
initProcessors()
void initProcessors (int argc, char * argv[]) static
Initialize MPI processors.
Definition at line 42 of file processors.cpp.
References processorOstream::activatePrefix(), processors::argc(), processors::argc_, processors::argv(), processors::argv_, CheckMPI, pFlow::errReport, processors::globalMaster(), processors::globalParallel(), processors::globalRank_, processors::globalSize_, processors::initProcessorsCelled_, processors::isInitialized(), pFlow::mOutput, pFlow::pOutput, masterOstream::setMasterSlave(), and processorOstream::setPrefixNum().
Referenced by main().
finalizeProcessors()
void finalizeProcessors () static
Finalize MPI processors.
Definition at line 88 of file processors.cpp.
References CheckMPI.
Referenced by main().
globalMasterNo()
static int globalMasterNo () inline static
Master processors number (globaly in MPI).
Definition at line 91 of file processors.hpp.
Referenced by processors::globalMaster().
globalParallel()
static bool globalParallel () inline static
Is this a parallel MPI run.
Definition at line 98 of file processors.hpp.
References processors::globalSize().
Referenced by processors::globalRunTypeName(), and processors::initProcessors().
globalRunTypeName()
static const char* globalRunTypeName () inline static
Definition at line 104 of file processors.hpp.
References processors::globalParallel().
Referenced by IOPattern::exeMode().
isInitialized()
bool isInitialized () static
Is MPI initialized?
Definition at line 123 of file processors.cpp.
Referenced by processors::initProcessors().
isFinalized()
bool isFinalized () static
Is MPI finalized?
Definition at line 135 of file processors.cpp.
globalMaster()
static bool globalMaster () inline static
Is this processor the master processor?
Definition at line 125 of file processors.hpp.
References processors::globalMasterNo(), and processors::globalRank().
Referenced by processors::initProcessors().
globalSize()
static int globalSize () inline static
Global size of processors.
Definition at line 132 of file processors.hpp.
References processors::globalSize_.
Referenced by processors::globalParallel(), and localProcessors::localProcessors().
globalRank()
static int globalRank () inline static
Rank of the processor in the global MPI.
Definition at line 139 of file processors.hpp.
References processors::globalRank_.
Referenced by regularSimulationDomain::createBoundaryDicts(), processors::globalMaster(), and localProcessors::localProcessors().
argc()
static int argc () inline static
Definition at line 145 of file processors.hpp.
References processors::argc_.
Referenced by processors::initProcessors().
argv()
static char** argv () inline static
Definition at line 151 of file processors.hpp.
References processors::argv_.
Referenced by processors::initProcessors().
abort()
void abort (int error) static
Abort MPI run or regular run.
Definition at line 147 of file processors.cpp.
Referenced by fatalExitPhasicFlow(), and processors::processors().
Member Data Documentation
initProcessorsCelled_
bool initProcessorsCelled_ = false inline static private
Is the static member initProcessors is called.
Definition at line 57 of file processors.hpp.
Referenced by processors::initProcessors().
globalRank_
int globalRank_ = 0 inline static private
Global rank of the current processor.
Definition at line 61 of file processors.hpp.
Referenced by processors::globalRank(), and processors::initProcessors().
globalSize_
int globalSize_ = 1 inline static private
The global size of all processors.
Definition at line 65 of file processors.hpp.
Referenced by processors::globalSize(), and processors::initProcessors().
argc_
int argc_ = 0 inline static private
Definition at line 68 of file processors.hpp.
Referenced by processors::argc(), and processors::initProcessors().
argv_
char** argv_ = nullptr inline static private
Definition at line 71 of file processors.hpp.
Referenced by processors::argv(), and processors::initProcessors().
The documentation for this class was generated from the following files:
src/phasicFlow/processors/processors.hpp
src/phasicFlow/processors/processors.cpp