PhasicFlow: AdamsBashforth5 Class Reference
AdamsBashforth5 Class Reference
Fifth order Adams-Bashforth integration method for solving ODE.
Public Member Functions
TypeInfo ("AdamsBashforth5")
Type info.
AdamsBashforth5 (const word &baseName, repository &owner, const pointStructure &pStruct, const word &method)
uniquePtr< integration > clone () const override
virtual ~AdamsBashforth5 ()=default
add_vCtor (integration, AdamsBashforth5, word)
Add this to the virtual constructor table.
bool predict (real UNUSED(dt), realx3Vector_D &UNUSED(y), realx3Vector_D &UNUSED(dy)) override
bool correct (real dt, realx3Vector_D &y, realx3Vector_D &dy) override
bool setInitialVals (const int32IndexContainer &newIndices, const realx3Vector &y) override
Set the initial values for new indices.
bool needSetInitialVals () const override
Check if the method requires any set initial vals.
bool intAll (real dt, realx3Vector_D &y, realx3Vector_D &dy, range activeRng)
Integrate on all points in the active range.
template<typename activeFunctor >
bool intRange (real dt, realx3Vector_D &y, realx3Vector_D &dy, activeFunctor activeP)
Integrate on active points in the active range.
Public Member Functions inherited from integration
TypeInfo ("integration")
Type info.
integration (const word &baseName, pointStructure &pStruct, const word &method, const realx3Field_D &initialValField)
Construct from components.
integration (const integration &)=default
Copy constructor.
integration (integration &&)=default
Move constructor.
integration & operator= (const integration &)=default
Copy assignment.
integration & operator= (integration &&)=default
Move assignment.
virtual ~integration ()=default
Destructor.
create_vCtor (integration, word,(const word &baseName, pointStructure &pStruct, const word &method, const realx3Field_D &initialValField),(baseName, pStruct, method, initialValField))
Add a virtual constructor.
const auto & pStruct () const
Const ref to pointStructure.
const word & baseName () const
Base name.
repository & owner ()
Ref to the owner repository.
virtual void updateBoundariesSlaveToMasterIfRequested ()=0
virtual word method () const =0
return integration method
virtual bool predict (real dt, realx3PointField_D &y, realx3PointField_D &dy)=0
Prediction step in integration.
virtual bool predict (real dt, realx3Field_D &y, realx3PointField_D &dy)=0
virtual bool correct (real dt, realx3PointField_D &y, realx3PointField_D &dy)=0
Correction/main integration step.
virtual bool correctPStruct (real dt, pointStructure &pStruct, realx3PointField_D &vel)=0
Protected Types
using rpIntegration = Kokkos::RangePolicy< DefaultExecutionSpace, Kokkos::Schedule< Kokkos::Static >, Kokkos::IndexType< int32 > >
Range policy for integration kernel.
Protected Attributes
pointField< VectorSingle, AB5History > & history_
Integration history.
Additional Inherited Members
Static Public Member Functions inherited from integration
static uniquePtr< integration > create (const word &baseName, pointStructure &pStruct, const word &method, const realx3Field_D &initialValField)
Create the polymorphic object based on inputs.
Detailed Description
Fifth order Adams-Bashforth integration method for solving ODE.
This is a one-step integration method and does not have prediction step.
Definition at line 79 of file AdamsBashforth5.hpp.
Member Typedef Documentation
rpIntegration
using rpIntegration = Kokkos::RangePolicy< DefaultExecutionSpace, Kokkos::Schedule<Kokkos::Static>, Kokkos::IndexType<int32> > protected
Range policy for integration kernel.
Definition at line 93 of file AdamsBashforth5.hpp.
Constructor & Destructor Documentation
AdamsBashforth5()
AdamsBashforth5 (const word & baseName, repository & owner, const pointStructure & pStruct, const word & method)
Definition at line 26 of file AdamsBashforth5.cpp.
References pFlow::zero3.
~AdamsBashforth5()
virtual ~AdamsBashforth5 () virtual default
Member Function Documentation
TypeInfo()
TypeInfo ("AdamsBashforth5")
Type info.
clone()
uniquePtr<integration> clone () const inline override
Definition at line 108 of file AdamsBashforth5.hpp.
add_vCtor()
add_vCtor (integration , AdamsBashforth5 , word)
Add this to the virtual constructor table.
predict()
bool predict (real UNUSEDdt, realx3Vector_D & UNUSEDy, realx3Vector_D & UNUSEDdy) override
Definition at line 49 of file AdamsBashforth5.cpp.
correct()
bool correct (real dt, realx3Vector_D & y, realx3Vector_D & dy) override
Definition at line 60 of file AdamsBashforth5.cpp.
References pStruct.
setInitialVals()
bool setInitialVals (const int32IndexContainer & newIndices, const realx3Vector & y) override virtual
Set the initial values for new indices.
Implements integration.
Definition at line 79 of file AdamsBashforth5.cpp.
needSetInitialVals()
bool needSetInitialVals () const inline override virtual
Check if the method requires any set initial vals.
Implements integration.
Definition at line 138 of file AdamsBashforth5.hpp.
intAll()
bool intAll (real dt, realx3Vector_D & y, realx3Vector_D & dy, range activeRng)
Integrate on all points in the active range.
Definition at line 86 of file AdamsBashforth5.cpp.
References VectorSingle< T, MemorySpace >::deviceViewAll(), and LAMBDA_HD.
intRange()
bool intRange (real dt, realx3Vector_D & y, realx3Vector_D & dy, activeFunctor activeP)
Integrate on active points in the active range.
Definition at line 162 of file AdamsBashforth5.hpp.
References internalField< T, void >::deviceViewAll(), VectorSingle< T, MemorySpace >::deviceViewAll(), and LAMBDA_HD.
Member Data Documentation
history_
pointField<VectorSingle,AB5History>& history_ protected
Integration history.
Definition at line 86 of file AdamsBashforth5.hpp.
The documentation for this class was generated from the following files:
src/Integration/AdamsBashforth5/AdamsBashforth5.hpp
src/Integration/AdamsBashforth5/AdamsBashforth5.cpp