PhasicFlow: multiRotatingAxis Class Reference
multiRotatingAxis Class Reference
Public Member Functions
INLINE_FUNCTION_HD multiRotatingAxis ()
FUNCTION_H multiRotatingAxis (multiRotatingAxisMotion *axisMotion)
FUNCTION_H multiRotatingAxis (multiRotatingAxisMotion *axisMotion, const dictionary &dict)
FUNCTION_HD multiRotatingAxis (const multiRotatingAxis &)=default
FUNCTION_HD multiRotatingAxis & operator= (const multiRotatingAxis &)=default
INLINE_FUNCTION_HD realx3 pointTangentialVel (const realx3 &p) const
INLINE_FUNCTION_HD realx3 transferPoint (const realx3 &p, real dt) const
INLINE_FUNCTION_HD bool hasParrent () const
INLINE_FUNCTION_HD int32 parentAxisIndex () const
INLINE_FUNCTION_H void setAxisList (multiRotatingAxis *axisList)
void move (real dt)
FUNCTION_H bool read (multiRotatingAxisMotion *axisMotion, const dictionary &dict)
FUNCTION_H bool write (const multiRotatingAxisMotion *axisMotion, dictionary &dict) const
Public Member Functions inherited from rotatingAxis
FUNCTION_HD rotatingAxis ()
FUNCTION_H rotatingAxis (const dictionary &dict)
FUNCTION_HD rotatingAxis (const realx3 &p1, const realx3 &p2, real omega=0.0)
FUNCTION_HD rotatingAxis (const rotatingAxis &)=default
rotatingAxis & operator= (const rotatingAxis &)=default
FUNCTION_HD real setOmega (real omega)
INLINE_FUNCTION_HD real omega () const
INLINE_FUNCTION_HD bool isRotating () const
INLINE_FUNCTION_HD realx3 linTangentialVelocityPoint (const realx3 &p) const
FUNCTION_H bool read (const dictionary &dict)
FUNCTION_H bool write (dictionary &dict) const
FUNCTION_H bool read (iIstream &is)
FUNCTION_H bool write (iOstream &os) const
Public Member Functions inherited from timeInterval
INLINE_FUNCTION_HD timeInterval ()
INLINE_FUNCTION_HD timeInterval (const timeInterval &)=default
INLINE_FUNCTION_HD timeInterval & operator= (const timeInterval &)=default
FUNCTION_H timeInterval (const dictionary &dict)
INLINE_FUNCTION_HD ~timeInterval ()=default
INLINE_FUNCTION_HD auto startTime () const
INLINE_FUNCTION_HD auto endTime () const
INLINE_FUNCTION_HD auto time () const
INLINE_FUNCTION_HD void setTime (real t)
INLINE_FUNCTION_HD bool inTimeRange (real t) const
INLINE_FUNCTION_HD bool inTimeRange () const
FUNCTION_H bool read (const dictionary &dict)
FUNCTION_H bool write (dictionary &dict) const
FUNCTION_H bool read (iIstream &is)
FUNCTION_H bool write (iOstream &os) const
Public Member Functions inherited from line
TypeInfoNV ("line")
FUNCTION_HD line ()
FUNCTION_HD line (const realx3 &lp1, const realx3 &lp2)
FUNCTION_H line (const dictionary &dict)
FUNCTION_HD line (const line &src)=default
FUNCTION_HD line (line &&src)=default
FUNCTION_HD line & operator= (const line &)=default
FUNCTION_HD line & operator= (line &&)=default
INLINE_FUNCTION_HD void set (const realx3 &lp1, const realx3 &lp2)
INLINE_FUNCTION_HD realx3 point1 () const
INLINE_FUNCTION_HD realx3 point2 () const
INLINE_FUNCTION_HD realx3 point (real t) const
INLINE_FUNCTION_HD real length () const
INLINE_FUNCTION_HD realx3 unitVector () const
INLINE_FUNCTION_HD realx3 projectPoint (const realx3 &p) const
INLINE_FUNCTION_HD real projectNormalizedLength (realx3 p) const
FUNCTION_H bool read (const dictionary &dict)
FUNCTION_H bool write (dictionary &ditc) const
FUNCTION_H bool read (iIstream &is)
FUNCTION_H bool write (iOstream &os) const
Protected Attributes
multiRotatingAxis * axisList_
int32 parentAxisIndex_ = -1
Protected Attributes inherited from rotatingAxis
real omega_ = 0
bool rotating_ = false
Protected Attributes inherited from timeInterval
real startTime_ = 0
real endTime_ = largeValue
real time_ =0
bool isInInterval_ = true
Protected Attributes inherited from line
realx3 p1_
realx3 v21_
Detailed Description
Definition at line 36 of file multiRotatingAxis.hpp.
Constructor & Destructor Documentation
multiRotatingAxis() [1/4]
INLINE_FUNCTION_HD multiRotatingAxis () inline
Definition at line 50 of file multiRotatingAxis.hpp.
multiRotatingAxis() [2/4]
FUNCTION_H multiRotatingAxis (multiRotatingAxisMotion * axisMotion)
Definition at line 27 of file multiRotatingAxis.cpp.
multiRotatingAxis() [3/4]
FUNCTION_H multiRotatingAxis (multiRotatingAxisMotion * axisMotion, const dictionary & dict)
Definition at line 36 of file multiRotatingAxis.cpp.
References pFlow::endl(), fatalErrorInFunction, fatalExit, and dictionary::globalName().
multiRotatingAxis() [4/4]
FUNCTION_HD multiRotatingAxis (const multiRotatingAxis &) default
Member Function Documentation
operator=()
FUNCTION_HD multiRotatingAxis& operator= (const multiRotatingAxis &) default
pointTangentialVel()
INLINE_FUNCTION_HD realx3 pointTangentialVel (const realx3 & p) const inline
Definition at line 68 of file multiRotatingAxis.hpp.
References multiRotatingAxis::axisList_, rotatingAxis::linTangentialVelocityPoint(), and multiRotatingAxis::parentAxisIndex().
transferPoint()
INLINE_FUNCTION_HD realx3 transferPoint (const realx3 & p, real dt) const inline
Definition at line 86 of file multiRotatingAxis.hpp.
References multiRotatingAxis::axisList_, rotatingAxis::isRotating(), multiRotatingAxis::parentAxisIndex_, and rotate().
Referenced by multiRotatingAxis::move().
hasParrent()
INLINE_FUNCTION_HD bool hasParrent () const inline
Definition at line 108 of file multiRotatingAxis.hpp.
References multiRotatingAxis::parentAxisIndex_.
Referenced by multiRotatingAxis::move().
parentAxisIndex()
INLINE_FUNCTION_HD int32 parentAxisIndex () const inline
Definition at line 114 of file multiRotatingAxis.hpp.
References multiRotatingAxis::parentAxisIndex_.
Referenced by multiRotatingAxis::move(), and multiRotatingAxis::pointTangentialVel().
setAxisList()
INLINE_FUNCTION_H void setAxisList (multiRotatingAxis * axisList) inline
Definition at line 121 of file multiRotatingAxis.hpp.
References multiRotatingAxis::axisList_.
move()
void move (real dt) inline
Definition at line 128 of file multiRotatingAxis.hpp.
References multiRotatingAxis::axisList_, multiRotatingAxis::hasParrent(), multiRotatingAxis::parentAxisIndex(), line::point1(), line::point2(), line::set(), and multiRotatingAxis::transferPoint().
read()
FUNCTION_H bool read (multiRotatingAxisMotion * axisMotion, const dictionary & dict)
Definition at line 56 of file multiRotatingAxis.cpp.
References dictionary::getValOrSet().
write()
FUNCTION_H bool write (const multiRotatingAxisMotion * axisMotion, dictionary & dict) const
Definition at line 80 of file multiRotatingAxis.cpp.
References dictionary::add(), and multiRotatingAxisMotion::indexToName().
Member Data Documentation
axisList_
multiRotatingAxis* axisList_ protected
Definition at line 43 of file multiRotatingAxis.hpp.
Referenced by multiRotatingAxis::move(), multiRotatingAxis::pointTangentialVel(), multiRotatingAxis::setAxisList(), and multiRotatingAxis::transferPoint().
parentAxisIndex_
int32 parentAxisIndex_ = -1 protected
Definition at line 45 of file multiRotatingAxis.hpp.
Referenced by multiRotatingAxis::hasParrent(), multiRotatingAxis::parentAxisIndex(), and multiRotatingAxis::transferPoint().
The documentation for this class was generated from the following files:
src/MotionModel/entities/multiRotatingAxis/multiRotatingAxis.hpp
src/MotionModel/entities/multiRotatingAxis/multiRotatingAxis.cpp