PhasicFlow: token Class Reference
token Class Reference
Classes
union content
Public Types
enum tokenType {
UNDEFINED = 0, FLAG, PUNCTUATION, BOOL,
INT64, FLOAT, DOUBLE, WORD,
STRING, DIRECTIVE, VARIABLE, ERROR
}
enum flagType { NO_FLAG = 0, ASCII = 1, BINARY = 2 }
enum punctuationToken : char {
NULL_TOKEN = '\0', SPACE = ' ', TAB = '\t', NL = '\n',
END_STATEMENT = ';', BEGIN_LIST = '(', END_LIST = ')', BEGIN_SQR = '[',
END_SQR = ']', BEGIN_BLOCK = '{', END_BLOCK = '}', COLON = ':',
COMMA = ',', DOLLAR = '$', SQUOTE = '\'', DQUOTE = '"',
SUBTRACT = '-', DIVIDE = '/', BEGIN_STRING = DQUOTE, END_STRING = DQUOTE
}
Public Member Functions
constexpr token () noexcept
token (const token &t)
token (token &&t)
token (punctuationToken p, int32 lineNumber=0)
token (const label val, int32 lineNumber=0)
token (const uint32 val, int32 lineNumber=0)
token (const int64 val, int32 lineNumber=0)
token (const int32 val, int32 lineNumber=0)
token (const float val, int32 lineNumber=0)
token (const double val, int32 lineNumber=0)
token (const word &w, int32 lineNumber=0, bool isString=false)
token (word &&w, int32 lineNumber=0, bool isString=false)
token (iIstream &is)
~token ()
word name () const
tokenType type () const
bool setType (const tokenType tokType)
int32 lineNumber () const
int32 & lineNumber ()
bool good () const
bool undefined () const
bool error () const
bool isBool () const
bool isFlag () const
bool isPunctuation () const
bool isSeparator () const
bool isEndStatement () const
bool isEndBlock () const
bool isInt64 () const
bool isInt32 () const
bool isFloat () const
bool isDouble () const
bool isReal () const
bool isNumber () const
bool isWord () const
bool isDirective () const
bool isString () const
bool isVariable () const
bool isStringType () const
bool boolToken () const
int flagToken () const
punctuationToken pToken () const
int64 int64Token () const
int32 int32Token () const
float floatToken () const
double doubleToken () const
real realToken () const
real number () const
const word & wordToken () const
const word & stringToken () const
void reset ()
void setBad ()
void swap (token &tok)
void operator= (const token &tok)
void operator= (token &&tok)
void operator= (const punctuationToken p)
void operator= (const int64 val)
void operator= (const int32 val)
void operator= (const float val)
void operator= (const double val)
void operator= (const word &w)
void operator= (word &&w)
bool operator== (const token &tok) const
bool operator== (const punctuationToken p) const
bool operator== (const int64 val) const
bool operator== (const int32 val) const
bool operator== (const float val) const
bool operator== (const double val) const
bool operator== (const word &w) const
bool operator!= (const token &tok) const
bool operator!= (const punctuationToken p) const
bool operator!= (const int64 val) const
bool operator!= (const int32 val) const
bool operator!= (const float val) const
bool operator!= (const double val) const
bool operator!= (const word &w) const
iOstream & printInfo (iOstream &os) const
std::ostream & printInfo (std::ostream &os) const
void operator= (word *)=delete
Static Public Member Functions
static const token undefinedToken ()
static token endList ()
static token beginList ()
static token endStatement ()
static token beginBlock ()
static token endBlocK ()
static token beginSquare ()
static token endSquare ()
static token space ()
static token newLine ()
static token boolean (bool on)
static token flag (int bitmask)
static bool isseparator (int c)
Private Member Functions
void setUndefined ()
void parseError (const char *expected) const
Private Attributes
content data_
tokenType type_
int32 lineNumber_
Friends
iOstream & operator<< (iOstream &os, const token &tok)
iOstream & operator<< (iOstream &os, const punctuationToken &pt)
std::ostream & operator<< (std::ostream &os, const token &tok)
std::ostream & operator<< (std::ostream &os, const punctuationToken &pt)
Detailed Description
Definition at line 42 of file token.hpp.
Member Enumeration Documentation
tokenType
enum tokenType
Enumerator
UNDEFINED
An undefined token-type.
FLAG
stream flag (1-byte bitmask)
PUNCTUATION
single character punctuation
BOOL
boolean type
INT64
int64 (integer) type
FLOAT
float (single-precision) type
DOUBLE
double (double-precision) type
WORD
A pFlow::word.
STRING
A string whth double quuote.
DIRECTIVE
A dictionary #directive (word variant)
VARIABLE
A dictionary $variable (string variant)
ERROR
A token error encountered.
Definition at line 49 of file token.hpp.
flagType
enum flagType
Enumerator
NO_FLAG
No flags.
ASCII
ASCII-mode stream.
BINARY
BINARY-mode stream.
Definition at line 72 of file token.hpp.
punctuationToken
enum punctuationToken : char
Enumerator
NULL_TOKEN
Nul character.
SPACE
Space [isspace].
TAB
Tab [isspace].
NL
Newline [isspace].
END_STATEMENT
End entry [isseparator].
BEGIN_LIST
Begin list [isseparator].
END_LIST
End list [isseparator].
BEGIN_SQR
Begin dimensions [isseparator].
END_SQR
End dimensions [isseparator].
BEGIN_BLOCK
Begin block [isseparator].
END_BLOCK
End block [isseparator].
COLON
Colon [isseparator].
COMMA
Comma [isseparator].
DOLLAR
Dollar - start variable.
SQUOTE
Single quote.
DQUOTE
Double quote.
SUBTRACT
Subtract or start of negative number.
DIVIDE
Divide [isseparator].
BEGIN_STRING
Begin string with double quote.
END_STRING
End string with double quote.
Definition at line 81 of file token.hpp.
Constructor & Destructor Documentation
token() [1/13]
constexpr token () inline constexpr noexcept
Definition at line 89 of file tokenI.hpp.
Referenced by token::beginBlock(), token::beginList(), token::beginSquare(), token::endBlocK(), token::endList(), token::endSquare(), token::endStatement(), token::newLine(), and token::space().
token() [2/13]
token (const token & t) inline
Definition at line 97 of file tokenI.hpp.
References token::data_, token::content::stringPtr, token::type_, and token::content::wordPtr.
token() [3/13]
token (token && t) inline
Definition at line 127 of file tokenI.hpp.
token() [4/13]
token (punctuationToken p, int32 lineNumber = 0) inline explicit
Definition at line 138 of file tokenI.hpp.
References token::data_, and token::content::punctuationVal.
token() [5/13]
token (const label val, int32 lineNumber = 0) inline explicit
Definition at line 147 of file tokenI.hpp.
References token::data_, and token::content::int64Val.
token() [6/13]
token (const uint32 val, int32 lineNumber = 0) inline explicit
Definition at line 156 of file tokenI.hpp.
References token::data_, and token::content::int64Val.
token() [7/13]
token (const int64 val, int32 lineNumber = 0) inline explicit
Definition at line 165 of file tokenI.hpp.
References token::data_, and token::content::int64Val.
token() [8/13]
token (const int32 val, int32 lineNumber = 0) inline explicit
Definition at line 174 of file tokenI.hpp.
References token::data_, and token::content::int64Val.
token() [9/13]
token (const float val, int32 lineNumber = 0) inline explicit
Definition at line 183 of file tokenI.hpp.
References token::data_, and token::content::floatVal.
token() [10/13]
token (const double val, int32 lineNumber = 0) inline explicit
Definition at line 193 of file tokenI.hpp.
References token::data_, and token::content::doubleVal.
token() [11/13]
token (const word & w, int32 lineNumber = 0, bool isString = false) inline explicit
Definition at line 203 of file tokenI.hpp.
References token::data_, token::isString(), token::content::stringPtr, token::type_, and token::content::wordPtr.
token() [12/13]
token (word && w, int32 lineNumber = 0, bool isString = false) inline explicit
Definition at line 220 of file tokenI.hpp.
References token::data_, token::isString(), token::content::stringPtr, token::type_, and token::content::wordPtr.
token() [13/13]
token (iIstream & is) explicit
Definition at line 100 of file tokenIO.cpp.
References iIstream::read().
~token()
~token () inline
Definition at line 237 of file tokenI.hpp.
Member Function Documentation
undefinedToken()
static const token undefinedToken () inline static
endList()
static token endList () inline static
Definition at line 111 of file token.hpp.
References token::token().
Referenced by pFlow::endListToken().
beginList()
static token beginList () inline static
Definition at line 116 of file token.hpp.
References token::token().
Referenced by pFlow::beginListToken().
endStatement()
static token endStatement () inline static
Definition at line 121 of file token.hpp.
References token::token().
Referenced by pFlow::endStatementToken().
beginBlock()
static token beginBlock () inline static
Definition at line 126 of file token.hpp.
References token::token().
Referenced by pFlow::beginBlockToken().
endBlocK()
static token endBlocK () inline static
Definition at line 131 of file token.hpp.
References token::token().
Referenced by pFlow::endBlocKToken().
beginSquare()
static token beginSquare () inline static
Definition at line 136 of file token.hpp.
References token::token().
endSquare()
static token endSquare () inline static
Definition at line 141 of file token.hpp.
References token::token().
space()
static token space () inline static
Definition at line 146 of file token.hpp.
References token::token().
Referenced by pFlow::spaceToken().
newLine()
static token newLine () inline static
Definition at line 151 of file token.hpp.
References token::token().
Referenced by pFlow::newLineToken().
setUndefined()
void setUndefined () inline private
Definition at line 79 of file tokenI.hpp.
parseError()
void parseError (const char * expected) const private
Definition at line 30 of file token.cpp.
References pFlow::endl(), and fatalError.
boolean()
pFlow::token boolean (bool on) inline static
Definition at line 28 of file tokenI.hpp.
References token::data_, token::content::int64Val, and token::type_.
flag()
pFlow::token flag (int bitmask) inline static
Definition at line 38 of file tokenI.hpp.
References token::data_, token::content::flagVal, and token::type_.
isseparator()
bool isseparator (int c) inline static
Definition at line 48 of file tokenI.hpp.
References token::BEGIN_BLOCK, token::BEGIN_LIST, token::BEGIN_SQR, token::COLON, token::COMMA, token::DIVIDE, token::END_BLOCK, token::END_LIST, token::END_SQR, and token::END_STATEMENT.
name()
pFlow::word name () const
Definition at line 110 of file tokenIO.cpp.
type()
pFlow::token::tokenType type () const inline
Definition at line 284 of file tokenI.hpp.
Referenced by pFlow::printTokenInfo(), and Ostream::write().
setType()
bool setType (const tokenType tokType) inline
Definition at line 290 of file tokenI.hpp.
Referenced by Istream::read().
lineNumber() [1/2]
pFlow::int32 & lineNumber () const inline
Definition at line 360 of file tokenI.hpp.
Referenced by pFlow::printTokenInfo(), iTstream::read(), and Istream::read().
lineNumber() [2/2]
int32& lineNumber () inline
good()
bool good () const inline
Definition at line 372 of file tokenI.hpp.
Referenced by pFlow::badInput(), iEntry< Key, T * >::createEntry(), iIstream::findKeywordAndVal(), iIstream::nextData(), pFlow::operator>>(), Logical::read(), dataEntry::readDataEntry(), iEntry< Key, T * >::readKeyword(), and oTstream::write().
undefined()
bool undefined () const inline
Definition at line 378 of file tokenI.hpp.
error()
bool error () const inline
Definition at line 384 of file tokenI.hpp.
Referenced by iIstream::findTokenAndNext(), iIstream::findTokenAndNextSilent(), iIstream::findTokenResume(), iIstream::findTokenResumeSilent(), and iIstream::nextData().
isBool()
bool isBool () const inline
Definition at line 390 of file tokenI.hpp.
isFlag()
bool isFlag () const inline
Definition at line 408 of file tokenI.hpp.
isPunctuation()
bool isPunctuation () const inline
Definition at line 426 of file tokenI.hpp.
Referenced by dataEntry::readDataEntry(), List< word >::readList(), and Vector< word, vecAllocator< word > >::readVector().
isSeparator()
bool isSeparator () const inline
Definition at line 464 of file tokenI.hpp.
isEndStatement()
bool isEndStatement () const inline
Definition at line 431 of file tokenI.hpp.
Referenced by iIstream::findKeywordAndVal(), iIstream::findTokenAndNext(), iIstream::findTokenAndNextSilent(), iIstream::findTokenResume(), iIstream::findTokenResumeSilent(), iIstream::nextData(), and iIstream::readEndStatement().
isEndBlock()
bool isEndBlock () const inline
Definition at line 442 of file tokenI.hpp.
Referenced by iIstream::findTokenResume(), and iIstream::findTokenResumeSilent().
isInt64()
bool isInt64 () const inline
Definition at line 474 of file tokenI.hpp.
isInt32()
bool isInt32 () const inline
Definition at line 479 of file tokenI.hpp.
isFloat()
bool isFloat () const inline
Definition at line 500 of file tokenI.hpp.
isDouble()
bool isDouble () const inline
Definition at line 518 of file tokenI.hpp.
isReal()
bool isReal () const inline
Definition at line 536 of file tokenI.hpp.
isNumber()
bool isNumber () const inline
Definition at line 562 of file tokenI.hpp.
Referenced by pFlow::checkNumberToken(), and pFlow::operator>>().
isWord()
bool isWord () const inline
Definition at line 584 of file tokenI.hpp.
Referenced by pFlow::checkWordToken(), iIstream::findTokenAndNext(), iIstream::findTokenAndNextSilent(), iIstream::findTokenResume(), iIstream::findTokenResumeSilent(), iIstream::nextData(), pFlow::operator>>(), Logical::read(), and iEntry< Key, T * >::readKeyword().
isDirective()
bool isDirective () const inline
Definition at line 594 of file tokenI.hpp.
isString()
bool isString () const inline
Definition at line 615 of file tokenI.hpp.
Referenced by pFlow::operator>>(), Logical::read(), and token::token().
isVariable()
bool isVariable () const inline
Definition at line 648 of file tokenI.hpp.
isStringType()
bool isStringType () const inline
Definition at line 653 of file tokenI.hpp.
boolToken()
bool boolToken () const inline
Definition at line 396 of file tokenI.hpp.
flagToken()
int flagToken () const inline
Definition at line 414 of file tokenI.hpp.
pToken()
pFlow::token::punctuationToken pToken () const inline
Definition at line 452 of file tokenI.hpp.
Referenced by pFlow::operator<<(), pFlow::printTokenInfo(), iIstream::readBeginList(), dataEntry::readDataEntry(), iIstream::readEndList(), and iIstream::readEndStatement().
int64Token()
pFlow::int64 int64Token () const inline
Definition at line 484 of file tokenI.hpp.
Referenced by pFlow::operator<<(), and pFlow::printTokenInfo().
int32Token()
pFlow::int32 int32Token () const inline
Definition at line 495 of file tokenI.hpp.
floatToken()
float floatToken () const inline
Definition at line 506 of file tokenI.hpp.
Referenced by pFlow::operator<<(), and pFlow::printTokenInfo().
doubleToken()
double doubleToken () const inline
Definition at line 524 of file tokenI.hpp.
Referenced by pFlow::operator<<(), and pFlow::printTokenInfo().
realToken()
pFlow::real realToken () const inline
Definition at line 546 of file tokenI.hpp.
number()
pFlow::real number () const inline
Definition at line 568 of file tokenI.hpp.
Referenced by pFlow::checkNumberToken(), and pFlow::operator>>().
wordToken()
const pFlow::word & wordToken () const inline
Definition at line 600 of file tokenI.hpp.
References pFlow::nullWord.
Referenced by pFlow::checkWordToken(), iIstream::findTokenAndNext(), iIstream::findTokenAndNextSilent(), iIstream::findTokenResume(), iIstream::findTokenResumeSilent(), iIstream::nextData(), pFlow::operator<<(), pFlow::operator>>(), pFlow::printTokenInfo(), Logical::read(), iEntry< Key, T * >::readKeyword(), and Ostream::write().
stringToken()
const pFlow::word & stringToken () const inline
Definition at line 624 of file tokenI.hpp.
References pFlow::nullWord.
Referenced by pFlow::operator<<(), pFlow::operator>>(), pFlow::printTokenInfo(), and Logical::read().
reset()
void reset () inline
Definition at line 245 of file tokenI.hpp.
Referenced by pFlow::operator>>(), iIstream::peekBack(), iTstream::read(), and iIstream::resetPutBack().
setBad()
void setBad () inline
Definition at line 658 of file tokenI.hpp.
Referenced by Istream::read(), and Istream::readWordToken().
swap()
void swap (token & tok) inline
Definition at line 271 of file tokenI.hpp.
References token::data_, token::lineNumber_, and token::type_.
operator=() [1/10]
void operator= (const token & tok) inline
Definition at line 667 of file tokenI.hpp.
References token::data_, token::lineNumber_, token::content::stringPtr, token::type_, and token::content::wordPtr.
operator=() [2/10]
void operator= (token && tok) inline
Definition at line 705 of file tokenI.hpp.
operator=() [3/10]
void operator= (const punctuationToken p) inline
Definition at line 718 of file tokenI.hpp.
operator=() [4/10]
void operator= (const int64 val) inline
Definition at line 726 of file tokenI.hpp.
operator=() [5/10]
void operator= (const int32 val) inline
Definition at line 733 of file tokenI.hpp.
operator=() [6/10]
void operator= (const float val) inline
Definition at line 741 of file tokenI.hpp.
operator=() [7/10]
void operator= (const double val) inline
Definition at line 749 of file tokenI.hpp.
operator=() [8/10]
void operator= (const word & w) inline
Definition at line 757 of file tokenI.hpp.
operator=() [9/10]
void operator= (word && w) inline
Definition at line 765 of file tokenI.hpp.
operator==() [1/7]
bool operator== (const token & tok) const inline
Definition at line 773 of file tokenI.hpp.
References token::data_, token::content::doubleVal, pFlow::equal(), token::content::flagVal, token::content::floatVal, token::content::int64Val, token::content::punctuationVal, token::content::stringPtr, token::type_, and token::content::wordPtr.
operator==() [2/7]
bool operator== (const punctuationToken p) const inline
Definition at line 819 of file tokenI.hpp.
operator==() [3/7]
bool operator== (const int64 val) const inline
Definition at line 825 of file tokenI.hpp.
operator==() [4/7]
bool operator== (const int32 val) const inline
Definition at line 834 of file tokenI.hpp.
operator==() [5/7]
bool operator== (const float val) const inline
Definition at line 844 of file tokenI.hpp.
References pFlow::equal().
operator==() [6/7]
bool operator== (const double val) const inline
Definition at line 854 of file tokenI.hpp.
References pFlow::equal().
operator==() [7/7]
bool operator== (const word & w) const inline
Definition at line 863 of file tokenI.hpp.
operator!=() [1/7]
bool operator!= (const token & tok) const inline
Definition at line 872 of file tokenI.hpp.
References operator==().
operator!=() [2/7]
bool operator!= (const punctuationToken p) const inline
Definition at line 878 of file tokenI.hpp.
References operator==().
operator!=() [3/7]
bool operator!= (const int64 val) const inline
Definition at line 884 of file tokenI.hpp.
References operator==().
operator!=() [4/7]
bool operator!= (const int32 val) const inline
Definition at line 889 of file tokenI.hpp.
References operator==().
operator!=() [5/7]
bool operator!= (const float val) const inline
Definition at line 895 of file tokenI.hpp.
References operator==().
operator!=() [6/7]
bool operator!= (const double val) const inline
Definition at line 901 of file tokenI.hpp.
References operator==().
operator!=() [7/7]
bool operator!= (const word & w) const inline
Definition at line 907 of file tokenI.hpp.
References operator==().
printInfo() [1/2]
pFlow::iOstream & printInfo (iOstream & os) const
Definition at line 224 of file tokenIO.cpp.
References pFlow::printTokenInfo().
printInfo() [2/2]
std::ostream & printInfo (std::ostream & os) const
Definition at line 229 of file tokenIO.cpp.
References pFlow::printTokenInfo().
operator=() [10/10]
void operator= (word *) delete
Friends And Related Function Documentation
operator<< [1/4]
iOstream& operator<< (iOstream & os, const token & tok) friend
operator<< [2/4]
iOstream& operator<< (iOstream & os, const punctuationToken & pt) friend
operator<< [3/4]
std::ostream& operator<< (std::ostream & os, const token & tok) friend
operator<< [4/4]
std::ostream& operator<< (std::ostream & os, const punctuationToken & pt) friend
Member Data Documentation
data_
content data_ private
Definition at line 179 of file token.hpp.
Referenced by token::boolean(), token::flag(), token::operator=(), token::operator==(), token::swap(), and token::token().
type_
tokenType type_ private
Definition at line 182 of file token.hpp.
Referenced by token::boolean(), token::flag(), pFlow::operator<<(), token::operator=(), token::operator==(), token::swap(), and token::token().
lineNumber_
int32 lineNumber_ private
Definition at line 185 of file token.hpp.
Referenced by token::operator=(), and token::swap().
The documentation for this class was generated from the following files:
src/phasicFlow/streams/token/token.hpp
src/phasicFlow/streams/token/token.cpp
src/phasicFlow/streams/token/tokenI.hpp
src/phasicFlow/streams/token/tokenIO.cpp