PhasicFlow: MPITimer Class Reference
MPITimer Class Reference
Public Member Functions
TypeInfo ("MPITimer")
MPITimer (const word &name)
real totalTimeMax () const
std::vector< real > totalTimeAllToAll () const
std::vector< real > totalTimeAllToMaster () const
real averageTimeMax () const
std::vector< real > averageTimeAllToAll () const
std::vector< real > averageTimeAllAtoMaster () const
bool write (iOstream &os) const
Public Member Functions inherited from Timer
TypeInfo ("Timer")
Timer ()=default
Timer (const word &name)
Timer (const word &name, Timers *parrent)
const word & name () const
virtual ~Timer ()
virtual void removeParrent ()
virtual int32 level () const
virtual bool master () const
Timers * parrent () const
void start ()
void pause ()
void resume ()
void end ()
bool timerActive () const
real lastTime () const
real totalTime () const
real averageTime () const
virtual real accTimersTotal () const
virtual bool write (iOstream &os, bool subTree) const
virtual bool read (iIstream &is)
Private Member Functions
virtual real accTimersTotal () const
real averageTime () const
Additional Inherited Members
Protected Member Functions inherited from Timer
real averageTimeMax () const
real accTimersTotalMax () const
Detailed Description
Definition at line 12 of file MPITimer.hpp.
Constructor & Destructor Documentation
MPITimer()
MPITimer (const word & name) inline explicit
Definition at line 26 of file MPITimer.hpp.
Member Function Documentation
TypeInfo()
TypeInfo ("MPITimer")
totalTimeMax()
pFlow::real totalTimeMax () const
Definition at line 8 of file MPITimer.cpp.
References Timer::accTimersTotalMax().
totalTimeAllToAll()
std::vector< pFlow::real > totalTimeAllToAll () const
Definition at line 13 of file MPITimer.cpp.
References pFlow::pFlowProcessors().
totalTimeAllToMaster()
std::vector< pFlow::real > totalTimeAllToMaster () const
Definition at line 24 of file MPITimer.cpp.
References pFlow::pFlowProcessors().
averageTimeMax()
pFlow::real averageTimeMax () const
Definition at line 35 of file MPITimer.cpp.
References Timer::averageTimeMax().
averageTimeAllToAll()
std::vector< pFlow::real > averageTimeAllToAll () const
Definition at line 40 of file MPITimer.cpp.
References pFlow::pFlowProcessors().
averageTimeAllAtoMaster()
std::vector< pFlow::real > averageTimeAllAtoMaster () const
Definition at line 51 of file MPITimer.cpp.
References pFlow::pFlowProcessors().
write()
bool write (iOstream & os) const
Definition at line 62 of file MPITimer.cpp.
References pFlow::endl(), and Red_Text.
accTimersTotal()
virtual real accTimersTotal inline private
Definition at line 163 of file Timer.hpp.
averageTime()
real averageTime inline private
Definition at line 157 of file Timer.hpp.
The documentation for this class was generated from the following files:
src/phasicFlow/processors/MPITimer.hpp
src/phasicFlow/processors/MPITimer.cpp