PhasicFlow: triSurface Class Reference
triSurface Class Reference
Public Member Functions
TypeInfo ("triSurface")
triSurface (const objectFile &objf, repository *owner, const triSurface &surf)
triSurface (const realx3x3Field_H &triangles, repository *owner=nullptr)
~triSurface () override=default
uint32 numPoints () const
uint32 size () const
uint32 capacity () const
const realx3Field_D & points () const
realx3Field_D & points ()
const auto & area () const
auto & area ()
const uint32x3Field_D & vertices () const
uint32x3Field_D & vertices ()
auto & normals ()
const auto & normals () const
void clear ()
auto getTriangleAccessor () const
Obtain an object for accessing triangles.
bool read (iIstream &is, const IOPattern &iop) override
bool write (iOstream &os, const IOPattern &iop) const override
Public Member Functions inherited from IOobject
virtual word typeName () const =0
IOobject (const objectFile &objf, const IOPattern &iop, repository *owner)
~IOobject () override
IOobject (const IOobject &src)=delete
IOobject (IOobject &&src)=delete
const IOPattern & ioPattern () const
const repository * owner () const override
repository * owner ()
repository * releaseOwner (bool fromOwner=false)
bool isIncluded (const word &objName) const override
bool isExcluded (const word &objName) const override
bool readObject (bool rdHdr=true)
bool writeObject () const
bool readObject (iIstream &is, bool rdHdr=true)
bool writeObject (iOstream &os) const
Public Member Functions inherited from IOfileHeader
IOfileHeader (const objectFile &objf)
const word & objectName () const
const word & objectType () const
fileSystem path () const
bool outFileBinary () const
bool inFileBinary () const
bool headerOk (bool silent=false)
bool implyRead () const
Imply read.
bool implyWrite () const
Imply write.
bool fileExist () const
Check if file exists.
bool readIfPresent () const
Check read if present.
bool writeHeader () const
Check if the header should be written to file True: on master + implyWrite + readWriteHeader = true False: otherwise.
bool writeHeader (iOstream &os, const word &typeName, bool forceWrite=false) const
Write the header to the file , typeName comes from caller.
bool writeHeader (iOstream &os, bool forceWrite=false) const
Write the header to the file, typeName comes from the one read from file.
bool readHeader () const
Check if header should be read from file.
bool readHeader (iIstream &is, bool silent=false)
Read the header in the file.
bool writeBanner (iOstream &os) const
write the banner
bool writeSeparator (iOstream &os) const
wirte a separator line
Public Member Functions inherited from objectFile
objectFile (const word &name)
objectFile (const word &name, const fileSystem &localPath, const readFlag &rf=readFlag::READ_NEVER, const writeFlag &wf=writeFlag::WRITE_NEVER, bool rwHeader=true)
objectFile (const objectFile &src)=default
objectFile (objectFile &&src)=default
objectFile & operator= (const objectFile &rhs)=default
objectFile & operator= (objectFile &&rhs)=default
virtual ~objectFile ()=default
virtual const word & name () const
virtual const fileSystem & localPath () const
readFlag rFlag () const
writeFlag wFlag () const
bool isReadAlways () const
bool isReadNever () const
bool isReadIfPresent () const
bool isWriteAlways () const
bool isWriteNever () const
bool readWriteHeader () const
Protected Member Functions
bool calculateNormals ()
bool calculateArea ()
bool append (const realx3x3Field_H &triangles)
bool append (const realx3x3Vector &triangles)
triSurface (const objectFile &obj, repository *owner)
Protected Member Functions inherited from IOfileHeader
uniquePtr< iFstream > inStream () const
uniquePtr< oFstream > outStream () const
uniquePtr< oFstream > dummyOutStream () const
Private Attributes
realx3Field_D points_ {"points", "points"}
points of triangles
uint32x3Field_D vertices_ {"vertices", "vertices"}
vectices indices of triangles
realField_D area_ {"area", "area"}
area of each triangle
realx3Field_D normals_ {"normals", "normals"}
normal vector of triangles
Additional Inherited Members
Public Types inherited from objectFile
enum readFlag { READ_ALWAYS, READ_NEVER, READ_IF_PRESENT }
enum writeFlag { WRITE_ALWAYS, WRITE_NEVER }
Protected Attributes inherited from IOfileHeader
word objectName_
word objectType_
word fileFormat_ = "ASCII"
file format read from file
Detailed Description
Definition at line 103 of file triSurface.hpp.
Constructor & Destructor Documentation
triSurface() [1/3]
triSurface (const objectFile & obj, repository * owner) protected
Definition at line 191 of file triSurface.cpp.
triSurface() [2/3]
triSurface (const objectFile & objf, repository * owner, const triSurface & surf)
Definition at line 208 of file triSurface.cpp.
triSurface() [3/3]
triSurface (const realx3x3Field_H & triangles, repository * owner = nullptr) explicit
Definition at line 233 of file triSurface.cpp.
References fatalExit.
~triSurface()
~triSurface () override default
Member Function Documentation
calculateNormals()
bool calculateNormals () protected
Definition at line 107 of file triSurface.cpp.
References pFlow::triSurfaceKernels::calculateNormals(), triSurface::normals_, triSurface::points_, and triSurface::vertices_.
calculateArea()
bool calculateArea () protected
Definition at line 115 of file triSurface.cpp.
References pFlow::triSurfaceKernels::calculateArea().
append() [1/2]
bool append (const realx3x3Field_H & triangles) protected
Definition at line 124 of file triSurface.cpp.
References pFlow::convertToTriSurfaceComponents(), pFlow::endl(), fatalErrorInFunction, VectorSingle< T, MemorySpace >::getSpan(), Field< T, MemorySpace >::name(), and pFlow::triangle::normal().
append() [2/2]
bool append (const realx3x3Vector & triangles) protected
Definition at line 158 of file triSurface.cpp.
References pFlow::convertToTriSurfaceComponents(), pFlow::endl(), fatalErrorInFunction, Vector< T, Allocator >::getSpan(), Vector< T, Allocator >::name(), and pFlow::triangle::normal().
TypeInfo()
TypeInfo ("triSurface")
numPoints()
uint32 numPoints () const inline
Definition at line 157 of file triSurface.hpp.
References triSurface::points_, and VectorSingle< T, MemorySpace >::size().
Referenced by ContactSearch< searchMethod >::ContactSearch().
size()
uint32 size () const inline
Definition at line 162 of file triSurface.hpp.
References VectorSingle< T, MemorySpace >::size(), and triSurface::vertices_.
Referenced by triSurfaceField< uint32 >::assign(), ContactSearch< searchMethod >::ContactSearch(), and geometry::createPropertyId().
capacity()
uint32 capacity () const inline
Definition at line 167 of file triSurface.hpp.
References VectorSingle< T, MemorySpace >::capacity(), and triSurface::vertices_.
Referenced by triSurfaceField< uint32 >::assign(), and geometry::createPropertyId().
points() [1/2]
const realx3Field_D& points () const inline
Definition at line 172 of file triSurface.hpp.
References triSurface::points_.
Referenced by ContactSearch< searchMethod >::ContactSearch().
points() [2/2]
realx3Field_D& points () inline
Definition at line 177 of file triSurface.hpp.
References triSurface::points_.
area() [1/2]
const auto& area () const inline
Definition at line 182 of file triSurface.hpp.
References triSurface::area_.
area() [2/2]
auto& area () inline
Definition at line 187 of file triSurface.hpp.
References triSurface::area_.
vertices() [1/2]
const uint32x3Field_D& vertices () const inline
Definition at line 192 of file triSurface.hpp.
References triSurface::vertices_.
Referenced by ContactSearch< searchMethod >::ContactSearch().
vertices() [2/2]
uint32x3Field_D& vertices () inline
Definition at line 197 of file triSurface.hpp.
References triSurface::vertices_.
normals() [1/2]
auto& normals () inline
Definition at line 202 of file triSurface.hpp.
References triSurface::normals_.
Referenced by ContactSearch< searchMethod >::ContactSearch().
normals() [2/2]
const auto& normals () const inline
Definition at line 207 of file triSurface.hpp.
References triSurface::normals_.
clear()
void clear () inline
Definition at line 212 of file triSurface.hpp.
References triSurface::area_, VectorSingle< T, MemorySpace >::clear(), triSurface::normals_, triSurface::points_, and triSurface::vertices_.
Referenced by multiTriSurface::clear().
getTriangleAccessor()
auto getTriangleAccessor () const inline
Obtain an object for accessing triangles.
Definition at line 221 of file triSurface.hpp.
References VectorSingle< T, MemorySpace >::deviceViewAll(), triSurface::points_, VectorSingle< T, MemorySpace >::size(), and triSurface::vertices_.
read()
bool read (iIstream & is, const IOPattern & iop) override virtual
Implements IOobject.
Definition at line 257 of file triSurface.cpp.
References pFlow::triSurfaceKernels::calculateArea(), pFlow::triSurfaceKernels::calculateNormals(), pFlow::endl(), ioErrorInFile, IOstream::lineNumber(), and IOstream::name().
Referenced by pFlow::operator>>(), and multiTriSurface::read().
write()
bool write (iOstream & os, const IOPattern & iop) const override virtual
Implements IOobject.
Definition at line 282 of file triSurface.cpp.
References pFlow::endl(), ioErrorInFile, IOstream::lineNumber(), and IOstream::name().
Referenced by pFlow::operator<<(), and multiTriSurface::write().
Member Data Documentation
points_
realx3Field_D points_ {"points", "points"} private
points of triangles
Definition at line 110 of file triSurface.hpp.
Referenced by triSurface::calculateNormals(), triSurface::clear(), triSurface::getTriangleAccessor(), triSurface::numPoints(), and triSurface::points().
vertices_
uint32x3Field_D vertices_ {"vertices", "vertices"} private
vectices indices of triangles
Definition at line 113 of file triSurface.hpp.
Referenced by triSurface::calculateNormals(), triSurface::capacity(), triSurface::clear(), triSurface::getTriangleAccessor(), triSurface::size(), and triSurface::vertices().
area_
realField_D area_ {"area", "area"} private
area of each triangle
Definition at line 116 of file triSurface.hpp.
Referenced by triSurface::area(), and triSurface::clear().
normals_
realx3Field_D normals_ {"normals", "normals"} private
normal vector of triangles
Definition at line 119 of file triSurface.hpp.
Referenced by triSurface::calculateNormals(), triSurface::clear(), and triSurface::normals().
The documentation for this class was generated from the following files:
src/phasicFlow/triSurface/triSurface.hpp
src/phasicFlow/triSurface/triSurface.cpp