PhasicFlow: rectMeshField< T > Class Template Reference
rectMeshField< T > Class Template Reference
Public Types
using viewType = ViewType3D< T, HostSpace >
using memory_space = typename viewType::memory_space
Public Types inherited from objectFile
enum readFlag { READ_ALWAYS, READ_NEVER, READ_IF_PRESENT }
enum writeFlag { WRITE_ALWAYS, WRITE_NEVER }
Public Member Functions
TypeInfoTemplateNV111 ("rectMeshField", T, memoerySpaceName())
rectMeshField (rectangleMesh &mesh, const word &name, const T &defVal)
rectMeshField (rectangleMesh &mesh, const T &defVal)
rectMeshField (const rectMeshField &)=default
rectMeshField & operator= (const rectMeshField &)=default
rectMeshField (rectMeshField &&)=default
rectMeshField & operator= (rectMeshField &&)=default
uniquePtr< rectMeshField > clone () const
rectMeshField * clonePtr () const
const INLINE_FUNCTION_H word & name () const
INLINE_FUNCTION_HD int64 size () const
auto nx () const
auto ny () const
auto nz () const
const auto & mesh ()
INLINE_FUNCTION_HD real cellVol () const
INLINE_FUNCTION_HD T & operator() (int32 i, int32 j, int32 k)
const INLINE_FUNCTION_HD T & operator() (int32 i, int32 j, int32 k) const
void fill (T val)
bool write (iOstream &is, const IOPattern &iop) const override
bool read (iIstream &is, const IOPattern &iop) override
bool read (iIstream &is)
bool write (iOstream &os) const
Public Member Functions inherited from IOobject
virtual word typeName () const =0
IOobject (const objectFile &objf, const IOPattern &iop, repository *owner)
~IOobject () override
IOobject (const IOobject &src)=delete
IOobject (IOobject &&src)=delete
const IOPattern & ioPattern () const
const repository * owner () const override
repository * owner ()
repository * releaseOwner (bool fromOwner=false)
bool isIncluded (const word &objName) const override
bool isExcluded (const word &objName) const override
bool readObject (bool rdHdr=true)
bool writeObject () const
bool readObject (iIstream &is, bool rdHdr=true)
bool writeObject (iOstream &os) const
Public Member Functions inherited from IOfileHeader
IOfileHeader (const objectFile &objf)
const word & objectName () const
const word & objectType () const
fileSystem path () const
bool outFileBinary () const
bool inFileBinary () const
bool headerOk (bool silent=false)
bool implyRead () const
Imply read.
bool implyWrite () const
Imply write.
bool fileExist () const
Check if file exists.
bool readIfPresent () const
Check read if present.
bool writeHeader () const
Check if the header should be written to file True: on master + implyWrite + readWriteHeader = true False: otherwise.
bool writeHeader (iOstream &os, const word &typeName, bool forceWrite=false) const
Write the header to the file , typeName comes from caller.
bool writeHeader (iOstream &os, bool forceWrite=false) const
Write the header to the file, typeName comes from the one read from file.
bool readHeader () const
Check if header should be read from file.
bool readHeader (iIstream &is, bool silent=false)
Read the header in the file.
bool writeBanner (iOstream &os) const
write the banner
bool writeSeparator (iOstream &os) const
wirte a separator line
Public Member Functions inherited from objectFile
objectFile (const word &name)
objectFile (const word &name, const fileSystem &localPath, const readFlag &rf=readFlag::READ_NEVER, const writeFlag &wf=writeFlag::WRITE_NEVER, bool rwHeader=true)
objectFile (const objectFile &src)=default
objectFile (objectFile &&src)=default
objectFile & operator= (const objectFile &rhs)=default
objectFile & operator= (objectFile &&rhs)=default
virtual ~objectFile ()=default
virtual const fileSystem & localPath () const
readFlag rFlag () const
writeFlag wFlag () const
bool isReadAlways () const
bool isReadNever () const
bool isReadIfPresent () const
bool isWriteAlways () const
bool isWriteNever () const
bool readWriteHeader () const
Static Protected Member Functions
constexpr static const char * memoerySpaceName ()
Protected Attributes
const rectangleMesh * mesh_
word name_ ="noName"
viewType field_
T defaultValue_ {}
Protected Attributes inherited from IOfileHeader
word objectName_
word objectType_
word fileFormat_ = "ASCII"
file format read from file
Additional Inherited Members
Protected Member Functions inherited from IOfileHeader
uniquePtr< iFstream > inStream () const
uniquePtr< oFstream > outStream () const
uniquePtr< oFstream > dummyOutStream () const
Detailed Description
template<typename T>
class pFlow::rectMeshField< T >
Definition at line 31 of file rectMeshField.hpp.
Member Typedef Documentation
viewType
using viewType = ViewType3D<T,HostSpace>
Definition at line 37 of file rectMeshField.hpp.
memory_space
using memory_space = typename viewType::memory_space
Definition at line 39 of file rectMeshField.hpp.
Constructor & Destructor Documentation
rectMeshField() [1/4]
rectMeshField (rectangleMesh & mesh, const word & name, const T & defVal) inline
Definition at line 61 of file rectMeshField.hpp.
Referenced by rectMeshField< int32 >::clonePtr().
rectMeshField() [2/4]
rectMeshField (rectangleMesh & mesh, const T & defVal) inline
Definition at line 82 of file rectMeshField.hpp.
rectMeshField() [3/4]
rectMeshField (const rectMeshField< T > &) default
rectMeshField() [4/4]
rectMeshField (rectMeshField< T > &&) default
Member Function Documentation
memoerySpaceName()
constexpr static const char* memoerySpaceName () inline static constexpr protected
Definition at line 51 of file rectMeshField.hpp.
TypeInfoTemplateNV111()
TypeInfoTemplateNV111 ("rectMeshField< T >" , T , memoerySpaceName())
operator=() [1/2]
rectMeshField& operator= (const rectMeshField< T > &) default
operator=() [2/2]
rectMeshField& operator= (rectMeshField< T > &&) default
clone()
uniquePtr<rectMeshField> clone () const inline
Definition at line 112 of file rectMeshField.hpp.
clonePtr()
rectMeshField* clonePtr () const inline
Definition at line 117 of file rectMeshField.hpp.
name()
const INLINE_FUNCTION_H word& name () const inline virtual
Reimplemented from objectFile.
Definition at line 123 of file rectMeshField.hpp.
Referenced by pFlow::convertRectMeshField().
size()
INLINE_FUNCTION_HD int64 size () const inline
Definition at line 129 of file rectMeshField.hpp.
Referenced by pFlow::convertRectMeshField().
nx()
auto nx () const inline
Definition at line 134 of file rectMeshField.hpp.
Referenced by pFlow::convertRectMeshField().
ny()
auto ny () const inline
Definition at line 139 of file rectMeshField.hpp.
Referenced by pFlow::convertRectMeshField().
nz()
auto nz () const inline
Definition at line 144 of file rectMeshField.hpp.
Referenced by pFlow::convertRectMeshField().
mesh()
const auto& mesh () inline
Definition at line 149 of file rectMeshField.hpp.
cellVol()
INLINE_FUNCTION_HD real cellVol () const inline
Definition at line 155 of file rectMeshField.hpp.
operator()() [1/2]
INLINE_FUNCTION_HD T& operator() (int32 i, int32 j, int32 k) inline
Definition at line 161 of file rectMeshField.hpp.
operator()() [2/2]
const INLINE_FUNCTION_HD T& operator() (int32 i, int32 j, int32 k) const inline
Definition at line 167 of file rectMeshField.hpp.
fill()
void fill (T val) inline
Definition at line 172 of file rectMeshField.hpp.
Referenced by rectMeshField< int32 >::rectMeshField().
write() [1/2]
bool write (iOstream & is, const IOPattern & iop) const inline override virtual
Implements IOobject.
Definition at line 181 of file rectMeshField.hpp.
read() [1/2]
bool read (iIstream & is, const IOPattern & iop) inline override virtual
Implements IOobject.
Definition at line 187 of file rectMeshField.hpp.
read() [2/2]
bool read (iIstream & is) inline
Definition at line 193 of file rectMeshField.hpp.
write() [2/2]
bool write (iOstream & os) const inline
Definition at line 199 of file rectMeshField.hpp.
Member Data Documentation
mesh_
const rectangleMesh* mesh_ protected
Definition at line 43 of file rectMeshField.hpp.
Referenced by rectMeshField< int32 >::cellVol(), rectMeshField< int32 >::mesh(), rectMeshField< int32 >::nx(), rectMeshField< int32 >::ny(), rectMeshField< int32 >::nz(), and rectMeshField< int32 >::size().
name_
word name_ ="noName" protected
Definition at line 45 of file rectMeshField.hpp.
Referenced by rectMeshField< int32 >::name().
field_
viewType field_ protected
Definition at line 47 of file rectMeshField.hpp.
Referenced by rectMeshField< int32 >::fill(), and rectMeshField< int32 >::operator()().
defaultValue_
T defaultValue_ {} protected
Definition at line 49 of file rectMeshField.hpp.
Referenced by rectMeshField< int32 >::rectMeshField().
The documentation for this class was generated from the following file:
utilities/postprocessPhasicFlow/rectMeshField.hpp