PhasicFlow: timeControl Class Reference
timeControl Class Reference
Public Member Functions
timeControl (const dictionary &dict)
timeControl (dictionary &dict, real startTime, real endTime, real saveInterval, word startTimeName)
virtual ~timeControl ()
real dt () const
real setTime (real t)
void setStopAt (real sT)
real startTime () const
word timeName () const
real currentTime () const
word currentTimeWord (bool forSave=true) const
int32 currentIter () const
bool finalTime () const
bool reachedStopAt () const
bool outputToFile () const
bool timersReportTime () const
bool sortTime () const
bool setOutputToFile (real writeTime, const word &timeName)
bool operator++ (int)
void setSaveTimeFolder (bool saveToFile, const word &timeName="wrongTimeFolder")
int32 timePrecision () const
Protected Member Functions
void checkForOutputToFile ()
bool screenReport () const
Protected Attributes
real dt_
real startTime_
real endTime_
real stopAt_
real currentTime_
real saveInterval_
real lastSaved_
int32 currentIter_
int32 timePrecision_
bool managedExternaly_ = false
word timeName_ = "wrongSettings"
real writeTime_ = 0
realStridedRange timersReportInterval_
Logical performSorting_
realStridedRange sortingInterval_
int32StridedRagne screenReportInterval_ ={0,100}
bool outputToFile_ = false
Detailed Description
Definition at line 37 of file timeControl.hpp.
Constructor & Destructor Documentation
timeControl() [1/2]
timeControl (const dictionary & dict)
Definition at line 32 of file timeControl.cpp.
timeControl() [2/2]
timeControl (dictionary & dict, real startTime, real endTime, real saveInterval, word startTimeName)
Definition at line 78 of file timeControl.cpp.
References timeControl::checkForOutputToFile().
~timeControl()
virtual ~timeControl () inline virtual
Definition at line 102 of file timeControl.hpp.
Member Function Documentation
checkForOutputToFile()
void checkForOutputToFile () protected
Definition at line 142 of file timeControl.cpp.
References pFlow::abs(), pFlow::min(), and pFlow::pow().
Referenced by timeControl::setTime(), and timeControl::timeControl().
screenReport()
bool screenReport () const protected
Definition at line 26 of file timeControl.cpp.
References timeControl::currentIter_, stridedRange< T >::isMember(), and timeControl::screenReportInterval_.
dt()
real dt () const inline
Definition at line 106 of file timeControl.hpp.
References timeControl::dt_.
Referenced by demComponent::dt().
setTime()
real setTime (real t) inline
Definition at line 111 of file timeControl.hpp.
References timeControl::checkForOutputToFile(), timeControl::currentTime_, and timeControl::lastSaved_.
setStopAt()
void setStopAt (real sT) inline
Definition at line 120 of file timeControl.hpp.
References timeControl::managedExternaly_, and timeControl::stopAt_.
startTime()
real startTime () const inline
Definition at line 128 of file timeControl.hpp.
References timeControl::startTime_.
timeName()
pFlow::word timeName () const
Definition at line 120 of file timeControl.cpp.
Referenced by Time::localPath(), and timeControl::setOutputToFile().
currentTime()
real currentTime () const inline
Definition at line 135 of file timeControl.hpp.
References timeControl::currentTime_.
Referenced by demComponent::currentTime(), and timeControl::currentTimeWord().
currentTimeWord()
word currentTimeWord (bool forSave = true) const inline
Definition at line 140 of file timeControl.hpp.
References timeControl::currentTime(), pFlow::real2FixedStripZeros(), and timeControl::timePrecision().
currentIter()
int32 currentIter () const inline
Definition at line 156 of file timeControl.hpp.
References timeControl::currentIter_.
finalTime()
bool finalTime () const
Definition at line 128 of file timeControl.cpp.
References pFlow::abs().
reachedStopAt()
bool reachedStopAt () const
Definition at line 135 of file timeControl.cpp.
References pFlow::abs().
outputToFile()
bool outputToFile () const inline
Definition at line 165 of file timeControl.hpp.
References timeControl::outputToFile_.
timersReportTime()
bool timersReportTime () const
Definition at line 174 of file timeControl.cpp.
sortTime()
bool sortTime () const
Definition at line 180 of file timeControl.cpp.
Referenced by particles::beforeIteration().
setOutputToFile()
bool setOutputToFile (real writeTime, const word & timeName) inline
Definition at line 174 of file timeControl.hpp.
References timeControl::managedExternaly_, timeControl::timeName(), timeControl::timeName_, and timeControl::writeTime_.
operator++()
bool operator++ (int)
Definition at line 196 of file timeControl.cpp.
References cyanText, endREPORT, and REPORT.
setSaveTimeFolder()
void setSaveTimeFolder (bool saveToFile, const word & timeName = "wrongTimeFolder")
Definition at line 185 of file timeControl.cpp.
Referenced by systemControl::setSaveTimeFolder().
timePrecision()
int32 timePrecision () const inline
Definition at line 190 of file timeControl.hpp.
References timeControl::timePrecision_.
Referenced by timeControl::currentTimeWord().
Member Data Documentation
dt_
real dt_ protected
Definition at line 45 of file timeControl.hpp.
Referenced by timeControl::dt().
startTime_
real startTime_ protected
Definition at line 48 of file timeControl.hpp.
Referenced by timeControl::startTime().
endTime_
real endTime_ protected
Definition at line 51 of file timeControl.hpp.
stopAt_
real stopAt_ protected
Definition at line 54 of file timeControl.hpp.
Referenced by timeControl::setStopAt().
currentTime_
real currentTime_ protected
Definition at line 57 of file timeControl.hpp.
Referenced by timeControl::currentTime(), and timeControl::setTime().
saveInterval_
real saveInterval_ protected
Definition at line 60 of file timeControl.hpp.
lastSaved_
real lastSaved_ protected
Definition at line 63 of file timeControl.hpp.
Referenced by timeControl::setTime().
currentIter_
int32 currentIter_ protected
Definition at line 66 of file timeControl.hpp.
Referenced by timeControl::currentIter(), and timeControl::screenReport().
timePrecision_
int32 timePrecision_ protected
Definition at line 69 of file timeControl.hpp.
Referenced by timeControl::timePrecision().
managedExternaly_
bool managedExternaly_ = false protected
Definition at line 71 of file timeControl.hpp.
Referenced by timeControl::setOutputToFile(), and timeControl::setStopAt().
timeName_
word timeName_ = "wrongSettings" protected
Definition at line 73 of file timeControl.hpp.
Referenced by timeControl::setOutputToFile().
writeTime_
real writeTime_ = 0 protected
Definition at line 75 of file timeControl.hpp.
Referenced by timeControl::setOutputToFile().
timersReportInterval_
realStridedRange timersReportInterval_ protected
Definition at line 77 of file timeControl.hpp.
performSorting_
Logical performSorting_ protected
Definition at line 79 of file timeControl.hpp.
sortingInterval_
realStridedRange sortingInterval_ protected
Definition at line 81 of file timeControl.hpp.
screenReportInterval_
int32StridedRagne screenReportInterval_ ={0,100} protected
Definition at line 83 of file timeControl.hpp.
Referenced by timeControl::screenReport().
outputToFile_
bool outputToFile_ = false protected
Definition at line 85 of file timeControl.hpp.
Referenced by timeControl::outputToFile().
The documentation for this class was generated from the following files:
src/phasicFlow/repository/Time/timeControl.hpp
src/phasicFlow/repository/Time/timeControl.cpp