PhasicFlow: fileSeries Class Reference
fileSeries Class Reference
Public Member Functions
fileSeries (const fileSystem dest)
~fileSeries ()
bool addTimeFile (const word &baseName, real time, const word &fileName)
bool addTimeFile (const wordList &baseNames, real time, const wordList &fileNames)
Private Types
using TimeFileType = Map< real, word >
Private Member Functions
void writeOneBaseName (const word &baseName)
Private Attributes
Map< word, TimeFileType > timeFiles_
fileSystem destDir_
Detailed Description
Definition at line 14 of file fileSeries.hpp.
Member Typedef Documentation
TimeFileType
using TimeFileType = Map<real, word> private
Definition at line 18 of file fileSeries.hpp.
Constructor & Destructor Documentation
fileSeries()
fileSeries (const fileSystem dest)
Definition at line 33 of file fileSeries.cpp.
~fileSeries()
~fileSeries ()
Definition at line 40 of file fileSeries.cpp.
References END_REPORT, and REPORT.
Member Function Documentation
writeOneBaseName()
void writeOneBaseName (const word & baseName) private
Definition at line 5 of file fileSeries.cpp.
References pFlow::baseName(), fileSeries::destDir_, END_REPORT, Ostream::name(), REPORT, and fileSeries::timeFiles_.
addTimeFile() [1/2]
bool addTimeFile (const word & baseName, real time, const word & fileName)
Definition at line 49 of file fileSeries.cpp.
References pFlow::baseName(), Map< Key, T, Compare >::insertIf(), fileSystem::relative(), and fileSystem::wordPath().
addTimeFile() [2/2]
bool addTimeFile (const wordList & baseNames, real time, const wordList & fileNames)
Definition at line 67 of file fileSeries.cpp.
References fatalErrorInFunction, and List< T >::size().
Member Data Documentation
timeFiles_
Map<word, TimeFileType> timeFiles_ private
Definition at line 20 of file fileSeries.hpp.
Referenced by fileSeries::writeOneBaseName().
destDir_
fileSystem destDir_ private
Definition at line 22 of file fileSeries.hpp.
Referenced by fileSeries::writeOneBaseName().
The documentation for this class was generated from the following files:
utilities/pFlowToVTK/fileSeries.hpp
utilities/pFlowToVTK/fileSeries.cpp