PhasicFlow: cells< indexType > Class Template Reference
cells< indexType > Class Template Reference
Public Types
using CellType = triple< indexType >
using CellType = triple< indexType >
Public Member Functions
INLINE_FUNCTION_HD cells ()
INLINE_FUNCTION_H cells (const box &domain, real cellSize)
INLINE_FUNCTION_H cells (const box &domain, int32 nx, int32 ny, int32 nz)
INLINE_FUNCTION_HD cells (const cells &)=default
INLINE_FUNCTION_HD cells & operator= (const cells &)=default
INLINE_FUNCTION_HD cells (cells &&)=default
INLINE_FUNCTION_HD cells & operator= (cells &&)=default
cells getCells () const
INLINE_FUNCTION_H void setCellSize (real cellSize)
INLINE_FUNCTION_H void setCellSize (realx3 cellSize)
INLINE_FUNCTION_HD realx3 cellSize () const
const INLINE_FUNCTION_HD CellType & numCells () const
INLINE_FUNCTION_HD indexType nx () const
INLINE_FUNCTION_HD indexType ny () const
INLINE_FUNCTION_HD indexType nz () const
INLINE_FUNCTION_HD int64 totalCells () const
const auto & domain () const
INLINE_FUNCTION_HD CellType pointIndex (const realx3 &p) const
INLINE_FUNCTION_HD bool pointIndexInDomain (const realx3 p, CellType &index) const
INLINE_FUNCTION_HD bool inDomain (const realx3 &p) const
INLINE_FUNCTION_HD bool isInRange (const CellType &cell) const
INLINE_FUNCTION_HD bool isInRange (indexType i, indexType j, indexType k) const
INLINE_FUNCTION_HD void extendBox (const CellType &p1, const CellType &p2, const CellType &p3, indexType extent, CellType &minP, CellType &maxP) const
INLINE_FUNCTION_HD void extendBox (const realx3 &p1, const realx3 &p2, const realx3 &p3, real extent, realx3 &minP, realx3 &maxP) const
INLINE_FUNCTION_HD CellType bound (CellType p) const
INLINE_FUNCTION_HD realx3 bound (realx3 p) const
INLINE_FUNCTION_HD cells ()
INLINE_FUNCTION_H cells (const box &domain, real cellSize)
INLINE_FUNCTION_H cells (const box &domain, int32 nx, int32 ny, int32 nz)
INLINE_FUNCTION_HD cells (const cells &)=default
INLINE_FUNCTION_HD cells & operator= (const cells &)=default
INLINE_FUNCTION_HD cells (cells &&)=default
INLINE_FUNCTION_HD cells & operator= (cells &&)=default
cells getCells () const
INLINE_FUNCTION_H void setCellSize (real cellSize)
INLINE_FUNCTION_H void setCellSize (realx3 cellSize)
INLINE_FUNCTION_HD realx3 cellSize () const
const INLINE_FUNCTION_HD CellType & numCells () const
INLINE_FUNCTION_HD indexType nx () const
INLINE_FUNCTION_HD indexType ny () const
INLINE_FUNCTION_HD indexType nz () const
INLINE_FUNCTION_HD int64 totalCells () const
const auto & domain () const
INLINE_FUNCTION_HD CellType pointIndex (const realx3 &p) const
INLINE_FUNCTION_HD bool pointIndexInDomain (const realx3 p, CellType &index) const
INLINE_FUNCTION_HD bool inDomain (const realx3 &p) const
INLINE_FUNCTION_HD bool isInRange (const CellType &cell) const
INLINE_FUNCTION_HD bool isInRange (indexType i, indexType j, indexType k) const
INLINE_FUNCTION_HD void extendBox (const CellType &p1, const CellType &p2, const CellType &p3, indexType extent, CellType &minP, CellType &maxP) const
INLINE_FUNCTION_HD void extendBox (const realx3 &p1, const realx3 &p2, const realx3 &p3, real extent, realx3 &minP, realx3 &maxP) const
INLINE_FUNCTION_HD CellType bound (CellType p) const
INLINE_FUNCTION_HD realx3 bound (realx3 p) const
Protected Member Functions
INLINE_FUNCTION_H void calculate ()
INLINE_FUNCTION_H void calculate ()
Protected Attributes
box domain_ {realx3(0.0), realx3(1.0)}
realx3 cellSize_ {1,1,1}
CellType numCells_ {1,1,1}
Detailed Description
template<typename indexType>
class pFlow::cells< indexType >
Definition at line 32 of file cells.hpp.
Member Typedef Documentation
CellType [1/2]
using CellType = triple<indexType>
Definition at line 36 of file cells.hpp.
CellType [2/2]
using CellType = triple<indexType>
Definition at line 36 of file cells.hpp.
Constructor & Destructor Documentation
cells() [1/10]
INLINE_FUNCTION_HD cells () inline
Definition at line 60 of file cells.hpp.
cells() [2/10]
INLINE_FUNCTION_H cells (const box & domain, real cellSize) inline
Definition at line 64 of file cells.hpp.
cells() [3/10]
INLINE_FUNCTION_H cells (const box & domain, int32 nx, int32 ny, int32 nz) inline
Definition at line 74 of file cells.hpp.
cells() [4/10]
INLINE_FUNCTION_HD cells (const cells< indexType > &) default
cells() [5/10]
INLINE_FUNCTION_HD cells (cells< indexType > &&) default
cells() [6/10]
INLINE_FUNCTION_HD cells () inline
Definition at line 60 of file cells.hpp.
cells() [7/10]
INLINE_FUNCTION_H cells (const box & domain, real cellSize) inline
Definition at line 64 of file cells.hpp.
cells() [8/10]
INLINE_FUNCTION_H cells (const box & domain, int32 nx, int32 ny, int32 nz) inline
Definition at line 74 of file cells.hpp.
cells() [9/10]
INLINE_FUNCTION_HD cells (const cells< indexType > &) default
cells() [10/10]
INLINE_FUNCTION_HD cells (cells< indexType > &&) default
Member Function Documentation
calculate() [1/2]
INLINE_FUNCTION_H void calculate () inline protected
Definition at line 51 of file cells.hpp.
Referenced by cells< int32 >::cells(), and cells< int32 >::setCellSize().
operator=() [1/4]
INLINE_FUNCTION_HD cells& operator= (const cells< indexType > &) default
operator=() [2/4]
INLINE_FUNCTION_HD cells& operator= (cells< indexType > &&) default
getCells() [1/2]
cells getCells () const inline
Definition at line 95 of file cells.hpp.
Referenced by NBS< executionSpace >::getCells(), and NBS< executionSpace >::getCellsLevels().
setCellSize() [1/4]
INLINE_FUNCTION_H void setCellSize (real cellSize) inline
Definition at line 101 of file cells.hpp.
setCellSize() [2/4]
INLINE_FUNCTION_H void setCellSize (realx3 cellSize) inline
Definition at line 108 of file cells.hpp.
cellSize() [1/2]
INLINE_FUNCTION_HD realx3 cellSize () const inline
Definition at line 115 of file cells.hpp.
Referenced by cells< int32 >::setCellSize().
numCells() [1/2]
const INLINE_FUNCTION_HD CellType& numCells () const inline
Definition at line 121 of file cells.hpp.
nx() [1/2]
INLINE_FUNCTION_HD indexType nx () const inline
Definition at line 127 of file cells.hpp.
Referenced by rectMeshField< int32, HostSpace >::fill(), pointRectCell::mapPOints(), and rectMeshField< int32, HostSpace >::nx().
ny() [1/2]
INLINE_FUNCTION_HD indexType ny () const inline
Definition at line 133 of file cells.hpp.
Referenced by rectMeshField< int32, HostSpace >::fill(), pointRectCell::mapPOints(), and rectMeshField< int32, HostSpace >::ny().
nz() [1/2]
INLINE_FUNCTION_HD indexType nz () const inline
Definition at line 139 of file cells.hpp.
Referenced by rectMeshField< int32, HostSpace >::fill(), pointRectCell::mapPOints(), and rectMeshField< int32, HostSpace >::nz().
totalCells() [1/2]
INLINE_FUNCTION_HD int64 totalCells () const inline
Definition at line 145 of file cells.hpp.
domain() [1/2]
const auto& domain () const inline
Definition at line 152 of file cells.hpp.
pointIndex() [1/2]
INLINE_FUNCTION_HD CellType pointIndex (const realx3 & p) const inline
Definition at line 158 of file cells.hpp.
Referenced by mapperNBS< DefaultHostExecutionSpace >::build(), pFlow::getSortedIndex(), cells< int32 >::pointIndexInDomain(), and positionParticles::sortByMortonCode().
pointIndexInDomain() [1/2]
INLINE_FUNCTION_HD bool pointIndexInDomain (const realx3 p, CellType & index) const inline
Definition at line 164 of file cells.hpp.
Referenced by mapperNBS< DefaultHostExecutionSpace >::buildCheckInDomain().
inDomain() [1/2]
INLINE_FUNCTION_HD bool inDomain (const realx3 & p) const inline
Definition at line 173 of file cells.hpp.
isInRange() [1/4]
INLINE_FUNCTION_HD bool isInRange (const CellType & cell) const inline
Definition at line 179 of file cells.hpp.
isInRange() [2/4]
INLINE_FUNCTION_HD bool isInRange (indexType i, indexType j, indexType k) const inline
Definition at line 191 of file cells.hpp.
extendBox() [1/4]
INLINE_FUNCTION_HD void extendBox (const CellType & p1, const CellType & p2, const CellType & p3, indexType extent, CellType & minP, CellType & maxP) const inline
Definition at line 203 of file cells.hpp.
extendBox() [2/4]
INLINE_FUNCTION_HD void extendBox (const realx3 & p1, const realx3 & p2, const realx3 & p3, real extent, realx3 & minP, realx3 & maxP) const inline
Definition at line 219 of file cells.hpp.
bound() [1/4]
INLINE_FUNCTION_HD CellType bound (CellType p) const inline
Definition at line 235 of file cells.hpp.
Referenced by cells< int32 >::extendBox().
bound() [2/4]
INLINE_FUNCTION_HD realx3 bound (realx3 p) const inline
Definition at line 245 of file cells.hpp.
calculate() [2/2]
INLINE_FUNCTION_H void calculate () inline protected
Definition at line 51 of file cells.hpp.
operator=() [3/4]
INLINE_FUNCTION_HD cells& operator= (const cells< indexType > &) default
operator=() [4/4]
INLINE_FUNCTION_HD cells& operator= (cells< indexType > &&) default
getCells() [2/2]
cells getCells () const inline
Definition at line 95 of file cells.hpp.
setCellSize() [3/4]
INLINE_FUNCTION_H void setCellSize (real cellSize) inline
Definition at line 101 of file cells.hpp.
setCellSize() [4/4]
INLINE_FUNCTION_H void setCellSize (realx3 cellSize) inline
Definition at line 108 of file cells.hpp.
cellSize() [2/2]
INLINE_FUNCTION_HD realx3 cellSize () const inline
Definition at line 115 of file cells.hpp.
numCells() [2/2]
const INLINE_FUNCTION_HD CellType& numCells () const inline
Definition at line 121 of file cells.hpp.
nx() [2/2]
INLINE_FUNCTION_HD indexType nx () const inline
Definition at line 127 of file cells.hpp.
ny() [2/2]
INLINE_FUNCTION_HD indexType ny () const inline
Definition at line 133 of file cells.hpp.
nz() [2/2]
INLINE_FUNCTION_HD indexType nz () const inline
Definition at line 139 of file cells.hpp.
totalCells() [2/2]
INLINE_FUNCTION_HD int64 totalCells () const inline
Definition at line 145 of file cells.hpp.
domain() [2/2]
const auto& domain () const inline
Definition at line 152 of file cells.hpp.
pointIndex() [2/2]
INLINE_FUNCTION_HD CellType pointIndex (const realx3 & p) const inline
Definition at line 158 of file cells.hpp.
pointIndexInDomain() [2/2]
INLINE_FUNCTION_HD bool pointIndexInDomain (const realx3 p, CellType & index) const inline
Definition at line 164 of file cells.hpp.
inDomain() [2/2]
INLINE_FUNCTION_HD bool inDomain (const realx3 & p) const inline
Definition at line 173 of file cells.hpp.
isInRange() [3/4]
INLINE_FUNCTION_HD bool isInRange (const CellType & cell) const inline
Definition at line 179 of file cells.hpp.
isInRange() [4/4]
INLINE_FUNCTION_HD bool isInRange (indexType i, indexType j, indexType k) const inline
Definition at line 191 of file cells.hpp.
extendBox() [3/4]
INLINE_FUNCTION_HD void extendBox (const CellType & p1, const CellType & p2, const CellType & p3, indexType extent, CellType & minP, CellType & maxP) const inline
Definition at line 203 of file cells.hpp.
extendBox() [4/4]
INLINE_FUNCTION_HD void extendBox (const realx3 & p1, const realx3 & p2, const realx3 & p3, real extent, realx3 & minP, realx3 & maxP) const inline
Definition at line 219 of file cells.hpp.
bound() [3/4]
INLINE_FUNCTION_HD CellType bound (CellType p) const inline
Definition at line 235 of file cells.hpp.
bound() [4/4]
INLINE_FUNCTION_HD realx3 bound (realx3 p) const inline
Definition at line 245 of file cells.hpp.
Member Data Documentation
domain_
box domain_ {realx3(0.0), realx3(1.0)} protected
Definition at line 41 of file cells.hpp.
Referenced by cells< int32 >::bound(), cells< int32 >::calculate(), cells< int32 >::domain(), cells< int32 >::inDomain(), cells< int32 >::pointIndex(), and cells< int32 >::pointIndexInDomain().
cellSize_
realx3 cellSize_ {1,1,1} protected
Definition at line 44 of file cells.hpp.
Referenced by cells< int32 >::calculate(), cells< int32 >::cellSize(), cells< int32 >::extendBox(), cells< int32 >::pointIndex(), and cells< int32 >::setCellSize().
numCells_
CellType numCells_ {1,1,1} protected
Definition at line 46 of file cells.hpp.
Referenced by cells< int32 >::bound(), cells< int32 >::calculate(), cells< int32 >::isInRange(), cells< int32 >::numCells(), cells< int32 >::nx(), cells< int32 >::ny(), cells< int32 >::nz(), and cells< int32 >::totalCells().
The documentation for this class was generated from the following file:
src/Interaction/contactSearch/cells.hpp