PhasicFlow: triSurfaceField< VectorField, T, MemorySpace > Class Template Reference
triSurfaceField< VectorField, T, MemorySpace > Class Template Reference
Public Types
using triSurfaceFieldType = triSurfaceField< VectorField, T, MemorySpace >
using FieldType = Field< VectorField, T, MemorySpace >
using VectorType = typename FieldType::VectorType
using iterator = typename FieldType::iterator
using constIterator = typename FieldType::constIterator
using reference = typename FieldType::reference
using constReference = typename FieldType::constReference
using valueType = typename FieldType::valueType
using pointer = typename FieldType::pointer
using constPointer = typename FieldType::constPointer
Public Types inherited from Field< VectorField, T, void >
using VectorType = VectorField< T, void >
using FieldType = Field< VectorField, T, void >
using iterator = typename VectorType::iterator
using constIterator = typename VectorType::constIterator
using reference = typename VectorType::reference
using constReference = typename VectorType::constReference
using valueType = typename VectorType::valueType
using pointer = typename VectorType::pointer
using constPointer = typename VectorType::constPointer
Public Member Functions
TypeInfoTemplateNV2 ("triSurfaceField", T, VectorType::memoerySpaceName())
triSurfaceField (const triSurface &surface, const T &defVal, bool subscribe=true)
triSurfaceField (const triSurface &surface, const T &val, const T &defVal, bool subscribe=true)
triSurfaceField (const triSurfaceField &src, bool subscribe)
triSurfaceField (const triSurfaceField &src)
triSurfaceField (triSurfaceField &&src)=delete
triSurfaceField & operator= (const triSurfaceField &rhs)
triSurfaceField & operator= (triSurfaceField &&)=delete
uniquePtr< triSurfaceFieldType > clone () const
triSurfaceFieldType * clonePtr () const
const triSurface & surface () const
auto getTriangleAccessor () const
bool update (const eventMessage &msg)
bool readTriSurfacceField (iIstream &is)
bool writeTriSurfaceField (iOstream &os) const
bool read (iIstream &is)
bool write (iOstream &os) const
Public Member Functions inherited from eventObserver
eventObserver ()
eventObserver (const eventSubscriber &subscriber, bool subscribe=true)
virtual ~eventObserver ()
bool subscribed () const
bool subscribe (const eventSubscriber &subscriber)
void invalidateSubscriber ()
Public Member Functions inherited from Field< VectorField, T, void >
TypeInfoTemplateNV2 ("Field", T, VectorType::memoerySpaceName())
Field ()
Field (const word &fieldKey)
Field (const word &name, const word &fieldKey)
Field (size_t len)
Field (const word &fieldKey, size_t len)
Field (const word &name, const word &fieldKey, size_t len)
Field (size_t len, const T &val)
Field (const word &fieldKey, size_t len, const T &val)
Field (const word &name, const word &fieldKey, size_t len, const T &val)
Field (size_t capacity, size_t len, RESERVE)
Field (const word &fieldKey, size_t capacity, size_t len, RESERVE)
Field (const word &name, const word &fieldKey, size_t capacity, size_t len, RESERVE)
Field (const Vector< T > &vec)
Field (const word &fieldKey, const Vector< T > &vec)
Field (const word &name, const word &fieldKey, const Vector< T > &vec)
Field (const word &name, const word &fieldKey, const FieldType &src)
Field (const FieldType &)=default
Field (FieldType &&)=delete
FieldType & operator= (const FieldType &)=default
FieldType & operator= (FieldType &&)=delete
INLINE_FUNCTION_H uniquePtr< FieldType > clone () const
INLINE_FUNCTION_H FieldType * clonePtr () const
const word & fieldKey () const
bool readField (iIstream &is, const size_t len, bool resume, bool readLength=true)
bool readField (iIstream &is, bool resume)
bool writeField (iOstream &os) const
bool read (iIstream &is, bool resume=false)
bool write (iOstream &os) const
Protected Attributes
const triSurface & surface_
T defaultValue_
Protected Attributes inherited from eventObserver
const eventSubscriber * subscriber_ = nullptr
bool subscribed_ = false
Protected Attributes inherited from Field< VectorField, T, void >
const word fieldKey_
Additional Inherited Members
Protected Member Functions inherited from Field< VectorField, T, void >
bool readUniform (iIstream &is, size_t len, bool readLength=true)
bool readNonUniform (iIstream &is, size_t len)
Static Protected Attributes inherited from Field< VectorField, T, void >
static const word FKey
Detailed Description
template<template< class, class > class VectorField, class T, class MemorySpace = void>
class pFlow::triSurfaceField< VectorField, T, MemorySpace >
Definition at line 34 of file triSurfaceField.hpp.
Member Typedef Documentation
triSurfaceFieldType
using triSurfaceFieldType = triSurfaceField<VectorField, T, MemorySpace>
Definition at line 41 of file triSurfaceField.hpp.
FieldType
using FieldType = Field<VectorField, T, MemorySpace>
Definition at line 43 of file triSurfaceField.hpp.
VectorType
using VectorType = typename FieldType::VectorType
Definition at line 45 of file triSurfaceField.hpp.
iterator
using iterator = typename FieldType::iterator
Definition at line 47 of file triSurfaceField.hpp.
constIterator
using constIterator = typename FieldType::constIterator
Definition at line 49 of file triSurfaceField.hpp.
reference
using reference = typename FieldType::reference
Definition at line 51 of file triSurfaceField.hpp.
constReference
using constReference = typename FieldType::constReference
Definition at line 53 of file triSurfaceField.hpp.
valueType
using valueType = typename FieldType::valueType
Definition at line 55 of file triSurfaceField.hpp.
pointer
using pointer = typename FieldType::pointer
Definition at line 57 of file triSurfaceField.hpp.
constPointer
using constPointer = typename FieldType::constPointer
Definition at line 59 of file triSurfaceField.hpp.
Constructor & Destructor Documentation
triSurfaceField() [1/5]
triSurfaceField (const triSurface & surface, const T & defVal, bool subscribe = true)
Definition at line 23 of file triSurfaceField.cpp.
References fill().
triSurfaceField() [2/5]
triSurfaceField (const triSurface & surface, const T & val, const T & defVal, bool subscribe = true)
Definition at line 39 of file triSurfaceField.cpp.
References fill().
triSurfaceField() [3/5]
triSurfaceField (const triSurfaceField< VectorField, T, MemorySpace > & src, bool subscribe)
Definition at line 57 of file triSurfaceField.cpp.
triSurfaceField() [4/5]
triSurfaceField (const triSurfaceField< VectorField, T, MemorySpace > & src)
Definition at line 72 of file triSurfaceField.cpp.
triSurfaceField() [5/5]
triSurfaceField (triSurfaceField< VectorField, T, MemorySpace > && src) delete
Member Function Documentation
TypeInfoTemplateNV2()
TypeInfoTemplateNV2 ("triSurfaceField< VectorField, T, MemorySpace >" , T , VectorType::memoerySpaceName())
operator=() [1/2]
pFlow::triSurfaceField< VectorField, T, MemorySpace > & operator= (const triSurfaceField< VectorField, T, MemorySpace > & rhs)
Definition at line 82 of file triSurfaceField.cpp.
operator=() [2/2]
triSurfaceField& operator= (triSurfaceField< VectorField, T, MemorySpace > &&) delete
clone()
uniquePtr<triSurfaceFieldType> clone () const inline
Definition at line 103 of file triSurfaceField.hpp.
clonePtr()
triSurfaceFieldType* clonePtr () const inline
Definition at line 108 of file triSurfaceField.hpp.
surface()
const triSurface& surface () const inline
Definition at line 115 of file triSurfaceField.hpp.
References triSurfaceField< VectorField, T, MemorySpace >::surface_.
getTriangleAccessor()
auto getTriangleAccessor () const inline
Definition at line 119 of file triSurfaceField.hpp.
References triSurface::getTriangleAccessor(), and triSurfaceField< VectorField, T, MemorySpace >::surface_.
update()
bool update (const eventMessage & msg) virtual
Implements eventObserver.
Definition at line 94 of file triSurfaceField.cpp.
References notImplementedFunction.
readTriSurfacceField()
bool readTriSurfacceField (iIstream & is)
Definition at line 105 of file triSurfaceField.cpp.
Referenced by triSurfaceField< VectorField, T, MemorySpace >::read().
writeTriSurfaceField()
bool writeTriSurfaceField (iOstream & os) const
Definition at line 114 of file triSurfaceField.cpp.
Referenced by triSurfaceField< VectorField, T, MemorySpace >::write().
read()
bool read (iIstream & is) inline
Definition at line 133 of file triSurfaceField.hpp.
References triSurfaceField< VectorField, T, MemorySpace >::readTriSurfacceField().
Referenced by pFlow::operator>>().
write()
bool write (iOstream & os) const inline
Definition at line 138 of file triSurfaceField.hpp.
References triSurfaceField< VectorField, T, MemorySpace >::writeTriSurfaceField().
Referenced by pFlow::operator<<().
Member Data Documentation
surface_
const triSurface& surface_ protected
Definition at line 64 of file triSurfaceField.hpp.
Referenced by triSurfaceField< VectorField, T, MemorySpace >::getTriangleAccessor(), and triSurfaceField< VectorField, T, MemorySpace >::surface().
defaultValue_
T defaultValue_ protected
Definition at line 67 of file triSurfaceField.hpp.
The documentation for this class was generated from the following files:
src/phasicFlow/containers/triSurfaceField/triSurfaceField.hpp
src/phasicFlow/containers/triSurfaceField/triSurfaceField.cpp