PhasicFlow: oTstream Class Reference
oTstream Class Reference
Public Member Functions
oTstream (const word &nm)
oTstream (const oTstream &src)
oTstream (oTstream &&)=default
virtual ~oTstream ()=default
const tokenList & tokens () const
tokenList & tokens ()
virtual bool write (const token &tok)
Write Functions.
virtual iOstream & write (const char c)
Write character.
virtual iOstream & write (const char *str)
Write character string.
virtual iOstream & write (const word &str)
Write word.
virtual iOstream & writeQuoted (const std::string &str, const bool quoted=true)
Write std::string surrounded by quotes.
virtual iOstream & write (const int64 val) override
Write int64.
virtual iOstream & write (const int32 val) override
Write int32.
virtual iOstream & write (const label val) override
Write label.
virtual iOstream & write (const uint32 val) override
Write uint32.
virtual iOstream & write (const uint16 val) override
Write uint16.
virtual iOstream & write (const float val) override
Write float.
virtual iOstream & write (const double val) override
Write double.
iOstream & write (const char *binaryData, std::streamsize count) override
Write a block of binray data.
virtual void append (const token &tok)
virtual void append (const tokenList &tLisk)
void reset ()
virtual void rewind ()
virtual void indent ()
Add indentation characters.
virtual void flush ()
Flush stream.
virtual void endl ()
Add newline and flush stream.
virtual char fill () const
Get padding character.
virtual char fill (const char)
Set padding character for formatted field up to field width.
virtual int width () const
Get width of output field.
virtual int width (const int)
Set width of output field (and return old width)
virtual int precision () const
Get precision of output field.
virtual int precision (const int)
Set precision of output field (and return old precision)
virtual ios_base::fmtflags flags () const
Return flags of stream.
ios_base::fmtflags flags (const ios_base::fmtflags)
Set flags of stream.
Public Member Functions inherited from iOstream
iOstream ()
Default.
iOstream (writeFormat wF)
Construct from writeFormat.
iOstream (const iOstream &)=default
Copy construct.
virtual ~iOstream ()=default
Destructor.
unsigned short indentSize () const
Return indent level.
unsigned short & indentSize ()
Access to indent size.
unsigned short indentLevel () const
Return indent level.
unsigned short & indentLevel ()
Access to indent level.
void incrIndent ()
Increment the indent level.
void decrIndent ()
Decrement the indent level.
virtual iOstream & beginBlock (const word &kw)
Write begin block group with a name Increments indentation, adds newline.
virtual iOstream & beginBlock ()
Write begin block group without a name Increments indentation, adds newline.
virtual iOstream & endBlock ()
Write end block group Decrements indentation, adds newline.
virtual iOstream & beginList ()
Write begin list "(".
virtual iOstream & beginList (const word &kw)
Write begin list with keyword "kw (".
virtual iOstream & endList ()
Write end list ")".
virtual iOstream & beginSquare ()
Write begin list "[".
virtual iOstream & beginSquare (const word &kw)
Write begin list with keyword "kw [".
virtual iOstream & endSquare ()
Write end list "]".
virtual iOstream & endEntry ()
Write end entry (';') followed by newline.
virtual iOstream & newLine ()
Write a newLine to stream.
virtual iOstream & space (int32 n=1)
Write space to stream.
virtual iOstream & writeWordKeyword (const word &kw)
Write the keyword followed by an appropriate indentation.
template<class T >
iOstream & writeWordEntry (const word &key, const T &value)
Write a keyword/value entry.
iOstream & operator() () const
Return a non-const reference to const iOstream Needed for write functions where the stream argument is temporary: e.g.
Public Member Functions inherited from IOstream
IOstream ()
Default.
IOstream (writeFormat wF)
Construct and set write format.
IOstream (const IOstream &)=default
Copy.
virtual ~IOstream ()=default
Destructor.
virtual const word & name () const
Return the name of the stream.
virtual word & name ()
Return non-const access to the name of the stream.
virtual bool check (const char *operation) const
Check IOstream status for given operation.
bool fatalCheck (const char *operation) const
Check IOstream status for given operation.
bool opened () const
Return true if stream has been opened.
bool closed () const
Return true if stream is closed.
bool isBinary () const
Return true if stream format is binray.
bool good () const
Return true if next operation might succeed.
bool eof () const
Return true if end of input seen.
bool fail () const
Return true if next operation will fail.
bool bad () const
Return true if stream is corrupted.
operator bool () const
Return true if the stream has not failed.
bool operator! () const
Return true if the stream has failed.
int32 lineNumber () const
Const access to the current stream line number.
int32 & lineNumber ()
Non-const access to the current stream line number.
int32 lineNumber (const int32 num)
Set the stream line number return the previous value.
void setEof ()
Set stream to have reached eof.
void setFail ()
Set stream to have failed.
void setBad ()
Set stream to be bad.
ios_base::fmtflags setf (const ios_base::fmtflags f)
Set flags of stream.
ios_base::fmtflags setf (const ios_base::fmtflags f, const ios_base::fmtflags mask)
Set flags of given field of stream.
void unsetf (const ios_base::fmtflags f)
Unset flags of stream.
Protected Attributes
word name_
tokenList tokenList_
Protected Attributes inherited from iOstream
unsigned short indentSize_ = 4
Number of spaces per indent level.
unsigned short indentLevel_ = 0
Current indent level.
Protected Attributes inherited from IOstream
streamAccess openClosed_
Is stream open or closed.
writeFormat writeFormat_ = ASCII
write format
ios_base::iostate ioState_
state
int32 lineNumber_
The file line.
Additional Inherited Members
Public Types inherited from IOstream
enum streamAccess : char { CLOSED = 0, OPENED }
enum writeFormat : char { ASCII = 0, BINARY }
Static Public Member Functions inherited from IOstream
static unsigned int defaultPrecision ()
Return the default precision.
static unsigned int defaultPrecision (unsigned int prec)
Reset the default precision return the previous value.
Static Public Attributes inherited from IOstream
static unsigned int precision_ = 6
Default precision, only works for ASCII.
Protected Member Functions inherited from IOstream
void setOpened ()
Set stream opened.
void setClosed ()
Set stream closed.
void setState (ios_base::iostate state)
Set stream state.
void setWriteFormat (writeFormat wF)
void setGood ()
Set stream to be good.
Static Protected Attributes inherited from iOstream
static constexpr const unsigned short entryIndentation_ = 16
Indentation of the entry from the start of the keyword.
Static Protected Attributes inherited from IOstream
static word staticName_
Name for any generic stream - normally treat as readonly.
Detailed Description
Definition at line 23 of file oTstream.hpp.
Constructor & Destructor Documentation
oTstream() [1/3]
oTstream (const word & nm)
Definition at line 6 of file oTstream.cpp.
oTstream() [2/3]
oTstream (const oTstream & src)
Definition at line 19 of file oTstream.cpp.
oTstream() [3/3]
oTstream (oTstream &&) default
~oTstream()
virtual ~oTstream () virtual default
Member Function Documentation
tokens() [1/2]
pFlow::tokenList & tokens () const
Definition at line 32 of file oTstream.cpp.
References oTstream::tokenList_.
Referenced by dataEntry::dataEntry().
tokens() [2/2]
tokenList& tokens ()
write() [1/12]
bool write (const token & tok) virtual
Write Functions.
Write token to stream or otherwise handle it. return false if the token type was not handled by this method
Implements iOstream.
Definition at line 44 of file oTstream.cpp.
References token::good().
write() [2/12]
pFlow::iOstream & write (const char c) virtual
Write character.
Implements iOstream.
Definition at line 56 of file oTstream.cpp.
write() [3/12]
pFlow::iOstream & write (const char * str) virtual
Write character string.
Implements iOstream.
Definition at line 68 of file oTstream.cpp.
write() [4/12]
pFlow::iOstream & write (const word & str) virtual
Write word.
Implements iOstream.
Definition at line 77 of file oTstream.cpp.
writeQuoted()
pFlow::iOstream & writeQuoted (const std::string & str, const bool quoted = true) virtual
Write std::string surrounded by quotes.
Optional write without quotes.
Implements iOstream.
Definition at line 86 of file oTstream.cpp.
write() [5/12]
pFlow::iOstream & write (const int64 val) override virtual
Write int64.
Implements iOstream.
Definition at line 97 of file oTstream.cpp.
write() [6/12]
pFlow::iOstream & write (const int32 val) override virtual
Write int32.
Implements iOstream.
Definition at line 104 of file oTstream.cpp.
write() [7/12]
pFlow::iOstream & write (const label val) override virtual
Write label.
Implements iOstream.
Definition at line 114 of file oTstream.cpp.
write() [8/12]
pFlow::iOstream & write (const uint32 val) override virtual
Write uint32.
Implements iOstream.
Definition at line 121 of file oTstream.cpp.
write() [9/12]
pFlow::iOstream & write (const uint16 val) override virtual
Write uint16.
Implements iOstream.
Definition at line 128 of file oTstream.cpp.
write() [10/12]
pFlow::iOstream & write (const float val) override virtual
Write float.
Implements iOstream.
Definition at line 136 of file oTstream.cpp.
write() [11/12]
pFlow::iOstream & write (const double val) override virtual
Write double.
Implements iOstream.
Definition at line 144 of file oTstream.cpp.
write() [12/12]
pFlow::iOstream & write (const char * binaryData, std::streamsize count) override virtual
Write a block of binray data.
Implements iOstream.
Definition at line 152 of file oTstream.cpp.
References notImplementedFunction.
append() [1/2]
void append (const token & tok) virtual
Definition at line 162 of file oTstream.cpp.
References pFlow::validTokenForStream().
append() [2/2]
void append (const tokenList & tLisk) virtual
Definition at line 169 of file oTstream.cpp.
reset()
void reset ()
Definition at line 177 of file oTstream.cpp.
rewind()
void rewind () virtual
Definition at line 183 of file oTstream.cpp.
indent()
virtual void indent () inline virtual
Add indentation characters.
Implements iOstream.
Definition at line 127 of file oTstream.hpp.
flush()
virtual void flush () inline virtual
Flush stream.
Implements iOstream.
Definition at line 131 of file oTstream.hpp.
endl()
virtual void endl () inline virtual
Add newline and flush stream.
Implements iOstream.
Definition at line 135 of file oTstream.hpp.
fill() [1/2]
virtual char fill () const inline virtual
Get padding character.
Implements iOstream.
Definition at line 140 of file oTstream.hpp.
fill() [2/2]
virtual char fill (const char fillch) inline virtual
Set padding character for formatted field up to field width.
Implements iOstream.
Definition at line 146 of file oTstream.hpp.
width() [1/2]
virtual int width () const inline virtual
Get width of output field.
Implements iOstream.
Definition at line 152 of file oTstream.hpp.
width() [2/2]
virtual int width (const int w) inline virtual
Set width of output field (and return old width)
Implements iOstream.
Definition at line 159 of file oTstream.hpp.
precision() [1/2]
virtual int precision () const inline virtual
Get precision of output field.
Implements iOstream.
Definition at line 165 of file oTstream.hpp.
precision() [2/2]
virtual int precision (const int p) inline virtual
Set precision of output field (and return old precision)
Implements iOstream.
Definition at line 172 of file oTstream.hpp.
flags() [1/2]
virtual ios_base::fmtflags flags () const inline virtual
Return flags of stream.
Implements IOstream.
Definition at line 178 of file oTstream.hpp.
flags() [2/2]
ios_base::fmtflags flags (const ios_base::fmtflags f) inline virtual
Set flags of stream.
Implements IOstream.
Definition at line 184 of file oTstream.hpp.
Member Data Documentation
name_
word name_ protected
Definition at line 31 of file oTstream.hpp.
tokenList_
tokenList tokenList_ protected
Definition at line 34 of file oTstream.hpp.
Referenced by oTstream::tokens().
The documentation for this class was generated from the following files:
src/phasicFlow/streams/TStream/oTstream.hpp
src/phasicFlow/streams/TStream/oTstream.cpp