PhasicFlow: shapeMixture Class Reference
shapeMixture Class Reference
Defines a mixture of particles for particle insertion.
Public Member Functions
TypeInfoNV ("shapeMixture")
Type info.
shapeMixture (const dictionary &dict, const wordList &validNames)
Construct from dictionary.
shapeMixture (const shapeMixture &)=default
Copy.
shapeMixture (shapeMixture &&)=default
Move.
shapeMixture & operator= (const shapeMixture &)=default
Copy assignment.
shapeMixture & operator= (shapeMixture &&)=default
Move assignment.
uniquePtr< shapeMixture > clone () const
Polymorphic copy.
~shapeMixture ()=default
Destructor.
word getNextShapeName ()
The name of the next shape that should be inserted.
void getNextShapeNameN (size_t n, wordVector &names)
The name of the n next shapes that should be inserted.
auto size () const
Size of mixture (names)
auto totalInserted () const
Total number inserted particles.
bool read (const dictionary &dict)
bool write (dictionary &dict) const
Private Attributes
wordVector names_ {"shapeNames"}
List of shape names.
uint32Vector number_ {"number"}
Number composition.
uint32Vector numberInserted_ {"numberInserted"}
Number of inserted particles of each shape.
uint32Vector current_ {"currentInserted"}
Current number of inserted.
uint32 lastPeaked_ = 0
Detailed Description
Defines a mixture of particles for particle insertion.
The mixture composition is defined based on the integer numbers. For example, if there are 3 shape names in the simulaiotn (shape1, shape2, and shape3), the mixture composition can be defined as:
{
   shape1 4;
   shape2 2;
   shape3 6;
}
Definition at line 47 of file shapeMixture.hpp.
Constructor & Destructor Documentation
shapeMixture() [1/3]
shapeMixture (const dictionary & dict, const wordList & validNames)
Construct from dictionary.
Definition at line 24 of file shapeMixture.cpp.
References pFlow::endl(), fatalErrorInFunction, fatalExit, dictionary::globalName(), shapeMixture::names_, and shapeMixture::read().
shapeMixture() [2/3]
shapeMixture (const shapeMixture &) default
Copy.
shapeMixture() [3/3]
shapeMixture (shapeMixture &&) default
Move.
~shapeMixture()
~shapeMixture () default
Destructor.
Member Function Documentation
TypeInfoNV()
TypeInfoNV ("shapeMixture")
Type info.
operator=() [1/2]
shapeMixture& operator= (const shapeMixture &) default
Copy assignment.
operator=() [2/2]
shapeMixture& operator= (shapeMixture &&) default
Move assignment.
clone()
uniquePtr<shapeMixture> clone () const inline
Polymorphic copy.
Definition at line 88 of file shapeMixture.hpp.
getNextShapeName()
pFlow::word getNextShapeName ()
The name of the next shape that should be inserted.
Definition at line 57 of file shapeMixture.cpp.
References pFlow::fill(), and ForAll.
getNextShapeNameN()
void getNextShapeNameN (size_t n, wordVector & names)
The name of the n next shapes that should be inserted.
Definition at line 74 of file shapeMixture.cpp.
References n.
size()
auto size () const inline
Size of mixture (names)
Definition at line 105 of file shapeMixture.hpp.
References shapeMixture::names_, and Vector< T, Allocator >::size().
totalInserted()
auto totalInserted () const inline
Total number inserted particles.
Definition at line 110 of file shapeMixture.hpp.
References shapeMixture::numberInserted_, and pFlow::sum().
read()
bool read (const dictionary & dict)
Definition at line 85 of file shapeMixture.cpp.
References dictionary::dataEntryKeywords(), pFlow::endl(), fatalErrorInFunction, ForAll, dictionary::getVal(), and dictionary::globalName().
Referenced by shapeMixture::shapeMixture().
write()
bool write (dictionary & dict) const
Definition at line 146 of file shapeMixture.cpp.
References dictionary::add(), pFlow::endl(), fatalErrorInFunction, ForAll, and dictionary::globalName().
Member Data Documentation
names_
wordVector names_ {"shapeNames"} private
List of shape names.
Definition at line 52 of file shapeMixture.hpp.
Referenced by shapeMixture::shapeMixture(), and shapeMixture::size().
number_
uint32Vector number_ {"number"} private
Number composition.
Definition at line 55 of file shapeMixture.hpp.
numberInserted_
uint32Vector numberInserted_ {"numberInserted"} private
Number of inserted particles of each shape.
Definition at line 58 of file shapeMixture.hpp.
Referenced by shapeMixture::totalInserted().
current_
uint32Vector current_ {"currentInserted"} private
Current number of inserted.
Definition at line 61 of file shapeMixture.hpp.
lastPeaked_
uint32 lastPeaked_ = 0 private
Definition at line 63 of file shapeMixture.hpp.
The documentation for this class was generated from the following files:
src/Particles/Insertion/shapeMixture/shapeMixture.hpp
src/Particles/Insertion/shapeMixture/shapeMixture.cpp