PhasicFlow: VectorDual< T, MemorySpace > Class Template Reference
VectorDual< T, MemorySpace > Class Template Reference
Public Types
using iterator = T *
using constIterator = const T *
using reference = T &
using constReference = const T &
using valueType = T
using pointer = T *
using constPointer = const T *
using VectorType = VectorDual< T, MemorySpace >
using dualViewType = Kokkos::DualView< T *, MemorySpace >
using hostMirrorSpace = typename dualViewType::host_mirror_space
using deviceViewType = typename dualViewType::t_dev
using hostViewType = typename dualViewType::t_host
using deviceType = typename deviceViewType::device_type
using hostType = typename hostViewType::device_type
using viewType = dualViewType
using memory_space = typename viewType::memory_space
using execution_space = typename deviceType::execution_space
Public Member Functions
TypeInfoTemplateNV2 ("VectorDual", T, memoerySpaceName())
VectorDual ()
VectorDual (const word &name)
VectorDual (size_t n)
VectorDual (const word &name, size_t n)
VectorDual (size_t n, const T &val)
VectorDual (const word &name, size_t n, const T &val)
VectorDual (size_t cap, size_t n, RESERVE)
VectorDual (const word &name, size_t cap, size_t n, RESERVE)
VectorDual (const Vector< T > &src)
VectorDual (const word &name, const Vector< T > &src)
VectorDual (const VectorDual &src)
VectorDual (const word &name, const VectorDual &src)
VectorDual & operator= (const VectorDual &rhs)
VectorDual (VectorDual &&)=delete
VectorDual & operator= (VectorDual &&)=delete
INLINE_FUNCTION_H uniquePtr< VectorDual > clone () const
INLINE_FUNCTION_H VectorDual * clonePtr () const
INLINE_FUNCTION_H VectorType & VectorField ()
const INLINE_FUNCTION_H VectorType & VectorField () const
INLINE_FUNCTION_H deviceViewType & deviceViewAll ()
const INLINE_FUNCTION_H deviceViewType & deviceViewAll () const
INLINE_FUNCTION_H hostViewType & hostViewAll ()
const INLINE_FUNCTION_H hostViewType & hostViewAll () const
INLINE_FUNCTION_H deviceViewType & deviceView ()
const INLINE_FUNCTION_H deviceViewType & deviceView () const
INLINE_FUNCTION_H hostViewType & hostView ()
const INLINE_FUNCTION_H hostViewType & hostView () const
INLINE_FUNCTION_H hostViewType hostView (int32 start, int32 end) const
INLINE_FUNCTION_H deviceViewType deviceView (int32 start, int32 end) const
const INLINE_FUNCTION_H word name () const
INLINE_FUNCTION_H size_t size () const
INLINE_FUNCTION_H size_t capacity () const
INLINE_FUNCTION_H bool empty () const
INLINE_FUNCTION_H void reserve (size_t cap)
INLINE_FUNCTION_H void resize (size_t n)
INLINE_FUNCTION_H void reallocate (size_t cap)
INLINE_FUNCTION_H void resizeSync (size_t n)
INLINE_FUNCTION_H void resize (size_t n, const T &val)
INLINE_FUNCTION_H void resizeSync (size_t n, const T &val)
INLINE_FUNCTION_H void clear ()
INLINE_FUNCTION_H void fill (const T &val)
INLINE_FUNCTION_H void fillHost (const T &val)
INLINE_FUNCTION_H void fillDevice (const T &val)
FUNCTION_H void assign (size_t n, const T &val)
FUNCTION_H void assign (const Vector< T > &src)
bool deleteElement (const Vector< label > &indices)
INLINE_FUNCTION_H void sortItems (const int32IndexContainer &indices)
INLINE_FUNCTION_H bool insertSetElement (const int32IndexContainer &indices, const T &val)
template<typename side = HostSide>
INLINE_FUNCTION_H bool insertSetElement (const int32IndexContainer &indices, const Vector< T > &vals)
template<typename side = HostSide>
INLINE_FUNCTION_H bool insertSetElement (const Vector< int32 > &indices, const T &val)
template<typename side = HostSide>
INLINE_FUNCTION_H bool insertSetElement (const Vector< int32 > &indices, const Vector< T > &vals)
void push_back (const T &val)
INLINE_FUNCTION_H pointer data ()
INLINE_FUNCTION_H constPointer data () const
INLINE_FUNCTION_H iterator begin ()
INLINE_FUNCTION_H constIterator begin () const
INLINE_FUNCTION_H iterator end ()
INLINE_FUNCTION_H constIterator end () const
INLINE_FUNCTION_H reference operator[] (label i)
INLINE_FUNCTION_H constReference operator[] (label i) const
INLINE_FUNCTION_H void modifyOnHost ()
INLINE_FUNCTION_H void modifyOnDevice ()
INLINE_FUNCTION_H bool hostRequiresSync () const
INLINE_FUNCTION_H bool deviceRequiresSync () const
INLINE_FUNCTION_H bool areViewsSimilar () const
INLINE_FUNCTION_H void copyHostToDevice ()
INLINE_FUNCTION_H void copyHostToDevice (int32 start, int32 end, bool setUpdated=true)
INLINE_FUNCTION_H void copyDeviceToHost ()
INLINE_FUNCTION_H void copyDeviceToHost (int32 start, int32 end, bool setUpdated=true)
INLINE_FUNCTION_H void syncToHost ()
INLINE_FUNCTION_H void syncToDevice ()
INLINE_FUNCTION_H void syncViews ()
INLINE_FUNCTION_H void syncViews (int32 start, int32 end)
FUNCTION_H bool readVector (iIstream &is, size_t len=0)
FUNCTION_H bool read (iIstream &is)
FUNCTION_H bool write (iOstream &os) const
Protected Member Functions
INLINE_FUNCTION_H void changeSize (size_t n, bool actualCap=false)
INLINE_FUNCTION_H void setSize (size_t n)
INLINE_FUNCTION_H void updateSubViews () const
Static Protected Member Functions
constexpr static const char * memoerySpaceName ()
static INLINE_FUNCTION_H size_t evalCapacity (size_t n)
Protected Attributes
size_t size_ = 0
size_t capacity_ = 0
dualViewType dualView_
deviceViewType deviceSubView_
hostViewType hostSubView_
bool subViewsUpdated_ = false
Static Protected Attributes
static const real growthFactor_ = vectorGrowthFactor__
static constexpr bool isHostAccessible_
static const word hdName__
Detailed Description
template<typename T, typename MemorySpace = void>
class pFlow::VectorDual< T, MemorySpace >
Definition at line 43 of file VectorDual.hpp.
Member Typedef Documentation
iterator
using iterator = T*
Definition at line 51 of file VectorDual.hpp.
constIterator
using constIterator = const T*
Definition at line 53 of file VectorDual.hpp.
reference
using reference = T&
Definition at line 55 of file VectorDual.hpp.
constReference
using constReference = const T&
Definition at line 57 of file VectorDual.hpp.
valueType
using valueType = T
Definition at line 59 of file VectorDual.hpp.
pointer
using pointer = T*
Definition at line 61 of file VectorDual.hpp.
constPointer
using constPointer = const T*
Definition at line 63 of file VectorDual.hpp.
VectorType
using VectorType = VectorDual<T, MemorySpace>
Definition at line 65 of file VectorDual.hpp.
dualViewType
using dualViewType = Kokkos::DualView<T*, MemorySpace>
Definition at line 68 of file VectorDual.hpp.
hostMirrorSpace
using hostMirrorSpace = typename dualViewType::host_mirror_space
Definition at line 71 of file VectorDual.hpp.
deviceViewType
using deviceViewType = typename dualViewType::t_dev
Definition at line 74 of file VectorDual.hpp.
hostViewType
using hostViewType = typename dualViewType::t_host
Definition at line 77 of file VectorDual.hpp.
deviceType
using deviceType = typename deviceViewType::device_type
Definition at line 79 of file VectorDual.hpp.
hostType
using hostType = typename hostViewType::device_type
Definition at line 81 of file VectorDual.hpp.
viewType
using viewType = dualViewType
Definition at line 84 of file VectorDual.hpp.
memory_space
using memory_space = typename viewType::memory_space
Definition at line 87 of file VectorDual.hpp.
execution_space
using execution_space = typename deviceType::execution_space
Definition at line 90 of file VectorDual.hpp.
Constructor & Destructor Documentation
VectorDual() [1/13]
VectorDual () inline
Definition at line 173 of file VectorDual.hpp.
Referenced by VectorDual< multiRotatingAxis >::clonePtr().
VectorDual() [2/13]
VectorDual (const word & name) inline
Definition at line 179 of file VectorDual.hpp.
VectorDual() [3/13]
VectorDual (size_t n) inline
Definition at line 189 of file VectorDual.hpp.
VectorDual() [4/13]
VectorDual (const word & name, size_t n) inline
Definition at line 195 of file VectorDual.hpp.
VectorDual() [5/13]
VectorDual (size_t n, const T & val) inline
Definition at line 205 of file VectorDual.hpp.
VectorDual() [6/13]
VectorDual (const word & name, size_t n, const T & val) inline
Definition at line 211 of file VectorDual.hpp.
VectorDual() [7/13]
VectorDual (size_t cap, size_t n, RESERVE) inline
Definition at line 218 of file VectorDual.hpp.
VectorDual() [8/13]
VectorDual (const word & name, size_t cap, size_t n, RESERVE) inline
Definition at line 223 of file VectorDual.hpp.
VectorDual() [9/13]
VectorDual (const Vector< T > & src) inline
Definition at line 232 of file VectorDual.hpp.
VectorDual() [10/13]
VectorDual (const word & name, const Vector< T > & src) inline
Definition at line 237 of file VectorDual.hpp.
VectorDual() [11/13]
VectorDual (const VectorDual< T, MemorySpace > & src) inline
Definition at line 246 of file VectorDual.hpp.
VectorDual() [12/13]
VectorDual (const word & name, const VectorDual< T, MemorySpace > & src) inline
Definition at line 267 of file VectorDual.hpp.
VectorDual() [13/13]
VectorDual (VectorDual< T, MemorySpace > &&) delete
Member Function Documentation
memoerySpaceName()
constexpr static const char* memoerySpaceName () inline static constexpr protected
Definition at line 118 of file VectorDual.hpp.
evalCapacity()
static INLINE_FUNCTION_H size_t evalCapacity (size_t n) inline static protected
Definition at line 123 of file VectorDual.hpp.
Referenced by VectorDual< multiRotatingAxis >::assign(), VectorDual< multiRotatingAxis >::changeSize(), and VectorDual< multiRotatingAxis >::push_back().
changeSize()
INLINE_FUNCTION_H void changeSize (size_t n, bool actualCap = false) inline protected
Definition at line 129 of file VectorDual.hpp.
Referenced by VectorDual< multiRotatingAxis >::push_back(), VectorDual< multiRotatingAxis >::reserve(), VectorDual< multiRotatingAxis >::resize(), VectorDual< multiRotatingAxis >::resizeSync(), and VectorDual< multiRotatingAxis >::VectorDual().
setSize()
INLINE_FUNCTION_H void setSize (size_t n) inline protected
Definition at line 149 of file VectorDual.hpp.
Referenced by VectorDual< multiRotatingAxis >::assign(), VectorDual< multiRotatingAxis >::changeSize(), VectorDual< multiRotatingAxis >::clear(), VectorDual< multiRotatingAxis >::deleteElement(), VectorDual< multiRotatingAxis >::operator=(), VectorDual< multiRotatingAxis >::reallocate(), VectorDual< multiRotatingAxis >::sortItems(), and VectorDual< multiRotatingAxis >::VectorDual().
updateSubViews()
INLINE_FUNCTION_H void updateSubViews () const inline protected
Definition at line 156 of file VectorDual.hpp.
Referenced by VectorDual< multiRotatingAxis >::deviceView(), and VectorDual< multiRotatingAxis >::hostView().
TypeInfoTemplateNV2()
TypeInfoTemplateNV2 ("VectorDual< T, MemorySpace >" , T , memoerySpaceName())
operator=() [1/2]
VectorDual& operator= (const VectorDual< T, MemorySpace > & rhs) inline
Definition at line 288 of file VectorDual.hpp.
operator=() [2/2]
VectorDual& operator= (VectorDual< T, MemorySpace > &&) delete
clone()
INLINE_FUNCTION_H uniquePtr<VectorDual> clone () const inline
Definition at line 307 of file VectorDual.hpp.
clonePtr()
INLINE_FUNCTION_H VectorDual* clonePtr () const inline
Definition at line 313 of file VectorDual.hpp.
VectorField() [1/2]
INLINE_FUNCTION_H VectorType& VectorField () inline
Definition at line 322 of file VectorDual.hpp.
VectorField() [2/2]
const INLINE_FUNCTION_H VectorType& VectorField () const inline
Definition at line 329 of file VectorDual.hpp.
deviceViewAll() [1/2]
INLINE_FUNCTION_H deviceViewType& deviceViewAll () inline
Definition at line 335 of file VectorDual.hpp.
Referenced by pFlow::count(), VectorDual< multiRotatingAxis >::insertSetElement(), pFlow::max(), pFlow::min(), and VectorDual< multiRotatingAxis >::sortItems().
deviceViewAll() [2/2]
const INLINE_FUNCTION_H deviceViewType& deviceViewAll () const inline
Definition at line 340 of file VectorDual.hpp.
hostViewAll() [1/2]
INLINE_FUNCTION_H hostViewType& hostViewAll () inline
Definition at line 345 of file VectorDual.hpp.
Referenced by pFlow::count(), VectorDual< multiRotatingAxis >::insertSetElement(), pFlow::max(), and pFlow::min().
hostViewAll() [2/2]
const INLINE_FUNCTION_H hostViewType& hostViewAll () const inline
Definition at line 350 of file VectorDual.hpp.
deviceView() [1/3]
INLINE_FUNCTION_H deviceViewType& deviceView () inline
Definition at line 354 of file VectorDual.hpp.
Referenced by VectorDual< multiRotatingAxis >::copyDeviceToHost(), VectorDual< multiRotatingAxis >::copyHostToDevice(), VectorDual< multiRotatingAxis >::fill(), VectorDual< multiRotatingAxis >::fillDevice(), VectorDual< multiRotatingAxis >::sortItems(), VectorDual< multiRotatingAxis >::VectorDual(), and VectorDual< multiRotatingAxis >::write().
deviceView() [2/3]
const INLINE_FUNCTION_H deviceViewType& deviceView () const inline
Definition at line 359 of file VectorDual.hpp.
hostView() [1/3]
INLINE_FUNCTION_H hostViewType& hostView () inline
Definition at line 364 of file VectorDual.hpp.
Referenced by VectorDual< multiRotatingAxis >::copyDeviceToHost(), VectorDual< multiRotatingAxis >::copyHostToDevice(), VectorDual< multiRotatingAxis >::fill(), VectorDual< multiRotatingAxis >::fillHost(), VectorDual< multiRotatingAxis >::VectorDual(), and VectorDual< multiRotatingAxis >::write().
hostView() [2/3]
const INLINE_FUNCTION_H hostViewType& hostView () const inline
Definition at line 369 of file VectorDual.hpp.
hostView() [3/3]
INLINE_FUNCTION_H hostViewType hostView (int32 start, int32 end) const inline
Definition at line 375 of file VectorDual.hpp.
deviceView() [3/3]
INLINE_FUNCTION_H deviceViewType deviceView (int32 start, int32 end) const inline
Definition at line 381 of file VectorDual.hpp.
name()
const INLINE_FUNCTION_H word name () const inline
Definition at line 386 of file VectorDual.hpp.
size()
INLINE_FUNCTION_H size_t size () const inline
Definition at line 391 of file VectorDual.hpp.
Referenced by pFlow::count(), VectorDual< multiRotatingAxis >::deleteElement(), VectorDual< multiRotatingAxis >::insertSetElement(), pFlow::max(), pFlow::min(), VectorDual< multiRotatingAxis >::operator=(), and VectorDual< multiRotatingAxis >::write().
capacity()
INLINE_FUNCTION_H size_t capacity () const inline
Definition at line 396 of file VectorDual.hpp.
Referenced by VectorDual< multiRotatingAxis >::assign(), and VectorDual< multiRotatingAxis >::operator=().
empty()
INLINE_FUNCTION_H bool empty () const inline
Definition at line 401 of file VectorDual.hpp.
Referenced by VectorDual< multiRotatingAxis >::copyDeviceToHost(), VectorDual< multiRotatingAxis >::copyHostToDevice(), VectorDual< multiRotatingAxis >::fill(), VectorDual< multiRotatingAxis >::fillDevice(), VectorDual< multiRotatingAxis >::fillHost(), and VectorDual< multiRotatingAxis >::insertSetElement().
reserve()
INLINE_FUNCTION_H void reserve (size_t cap) inline
Definition at line 408 of file VectorDual.hpp.
resize() [1/2]
INLINE_FUNCTION_H void resize (size_t n) inline
Definition at line 414 of file VectorDual.hpp.
Referenced by VectorDual< multiRotatingAxis >::insertSetElement().
reallocate()
INLINE_FUNCTION_H void reallocate (size_t cap) inline
Definition at line 419 of file VectorDual.hpp.
Referenced by VectorDual< multiRotatingAxis >::assign(), and VectorDual< multiRotatingAxis >::VectorDual().
resizeSync() [1/2]
INLINE_FUNCTION_H void resizeSync (size_t n) inline
Definition at line 429 of file VectorDual.hpp.
resize() [2/2]
INLINE_FUNCTION_H void resize (size_t n, const T & val) inline
Definition at line 437 of file VectorDual.hpp.
resizeSync() [2/2]
INLINE_FUNCTION_H void resizeSync (size_t n, const T & val) inline
Definition at line 443 of file VectorDual.hpp.
clear()
INLINE_FUNCTION_H void clear () inline
Definition at line 448 of file VectorDual.hpp.
fill()
INLINE_FUNCTION_H void fill (const T & val) inline
Definition at line 455 of file VectorDual.hpp.
Referenced by VectorDual< multiRotatingAxis >::assign().
fillHost()
INLINE_FUNCTION_H void fillHost (const T & val) inline
Definition at line 463 of file VectorDual.hpp.
fillDevice()
INLINE_FUNCTION_H void fillDevice (const T & val) inline
Definition at line 470 of file VectorDual.hpp.
assign() [1/2]
FUNCTION_H void assign (size_t n, const T & val) inline
Definition at line 481 of file VectorDual.hpp.
Referenced by VectorDual< multiRotatingAxis >::readVector(), VectorDual< multiRotatingAxis >::resize(), VectorDual< multiRotatingAxis >::resizeSync(), and VectorDual< multiRotatingAxis >::VectorDual().
assign() [2/2]
FUNCTION_H void assign (const Vector< T > & src) inline
Definition at line 496 of file VectorDual.hpp.
deleteElement()
bool deleteElement (const Vector< label > & indices) inline
Definition at line 515 of file VectorDual.hpp.
sortItems()
INLINE_FUNCTION_H void sortItems (const int32IndexContainer & indices) inline
Definition at line 549 of file VectorDual.hpp.
insertSetElement() [1/4]
INLINE_FUNCTION_H bool insertSetElement (const int32IndexContainer & indices, const T & val) inline
Definition at line 579 of file VectorDual.hpp.
insertSetElement() [2/4]
INLINE_FUNCTION_H bool insertSetElement (const int32IndexContainer & indices, const Vector< T > & vals) inline
Definition at line 610 of file VectorDual.hpp.
insertSetElement() [3/4]
INLINE_FUNCTION_H bool insertSetElement (const Vector< int32 > & indices, const T & val) inline
Definition at line 671 of file VectorDual.hpp.
insertSetElement() [4/4]
INLINE_FUNCTION_H bool insertSetElement (const Vector< int32 > & indices, const Vector< T > & vals) inline
Definition at line 716 of file VectorDual.hpp.
push_back()
void push_back (const T & val) inline
Definition at line 771 of file VectorDual.hpp.
Referenced by VectorDual< multiRotatingAxis >::assign().
data() [1/2]
INLINE_FUNCTION_H pointer data () inline
Definition at line 787 of file VectorDual.hpp.
Referenced by VectorDual< multiRotatingAxis >::begin(), VectorDual< multiRotatingAxis >::end(), multiRotatingAxisMotion::getAxisListPtrDevice(), multiRotatingAxisMotion::getAxisListPtrHost(), VectorDual< multiRotatingAxis >::insertSetElement(), and VectorDual< multiRotatingAxis >::push_back().
data() [2/2]
INLINE_FUNCTION_H constPointer data () const inline
Definition at line 791 of file VectorDual.hpp.
begin() [1/2]
INLINE_FUNCTION_H iterator begin () inline
Definition at line 797 of file VectorDual.hpp.
begin() [2/2]
INLINE_FUNCTION_H constIterator begin () const inline
Definition at line 803 of file VectorDual.hpp.
end() [1/2]
INLINE_FUNCTION_H iterator end () inline
Definition at line 809 of file VectorDual.hpp.
Referenced by VectorDual< multiRotatingAxis >::copyDeviceToHost(), VectorDual< multiRotatingAxis >::copyHostToDevice(), VectorDual< multiRotatingAxis >::deviceView(), VectorDual< multiRotatingAxis >::hostView(), and VectorDual< multiRotatingAxis >::syncViews().
end() [2/2]
INLINE_FUNCTION_H constIterator end () const inline
Definition at line 815 of file VectorDual.hpp.
operator[]() [1/2]
INLINE_FUNCTION_H reference operator[] (label i) inline
Definition at line 819 of file VectorDual.hpp.
operator[]() [2/2]
INLINE_FUNCTION_H constReference operator[] (label i) const inline
Definition at line 823 of file VectorDual.hpp.
modifyOnHost()
INLINE_FUNCTION_H void modifyOnHost () inline
Definition at line 830 of file VectorDual.hpp.
Referenced by VectorDual< multiRotatingAxis >::deleteElement(), VectorDual< multiRotatingAxis >::fillHost(), multiRotatingAxisMotion::getModel(), VectorDual< multiRotatingAxis >::insertSetElement(), VectorDual< multiRotatingAxis >::push_back(), and VectorDual< multiRotatingAxis >::VectorDual().
modifyOnDevice()
INLINE_FUNCTION_H void modifyOnDevice () inline
Definition at line 835 of file VectorDual.hpp.
Referenced by VectorDual< multiRotatingAxis >::fillDevice(), VectorDual< multiRotatingAxis >::insertSetElement(), VectorDual< multiRotatingAxis >::sortItems(), and VectorDual< multiRotatingAxis >::VectorDual().
hostRequiresSync()
INLINE_FUNCTION_H bool hostRequiresSync () const inline
Definition at line 840 of file VectorDual.hpp.
Referenced by VectorDual< multiRotatingAxis >::syncToHost(), VectorDual< multiRotatingAxis >::syncViews(), VectorDual< multiRotatingAxis >::VectorDual(), and VectorDual< multiRotatingAxis >::write().
deviceRequiresSync()
INLINE_FUNCTION_H bool deviceRequiresSync () const inline
Definition at line 845 of file VectorDual.hpp.
Referenced by VectorDual< multiRotatingAxis >::syncToDevice(), VectorDual< multiRotatingAxis >::syncViews(), and VectorDual< multiRotatingAxis >::VectorDual().
areViewsSimilar()
INLINE_FUNCTION_H bool areViewsSimilar () const inline
Definition at line 850 of file VectorDual.hpp.
copyHostToDevice() [1/2]
INLINE_FUNCTION_H void copyHostToDevice () inline
Definition at line 857 of file VectorDual.hpp.
Referenced by VectorDual< multiRotatingAxis >::syncToDevice(), and VectorDual< multiRotatingAxis >::syncViews().
copyHostToDevice() [2/2]
INLINE_FUNCTION_H void copyHostToDevice (int32 start, int32 end, bool setUpdated = true) inline
Definition at line 866 of file VectorDual.hpp.
copyDeviceToHost() [1/2]
INLINE_FUNCTION_H void copyDeviceToHost () inline
Definition at line 876 of file VectorDual.hpp.
Referenced by VectorDual< multiRotatingAxis >::syncToHost(), and VectorDual< multiRotatingAxis >::syncViews().
copyDeviceToHost() [2/2]
INLINE_FUNCTION_H void copyDeviceToHost (int32 start, int32 end, bool setUpdated = true) inline
Definition at line 884 of file VectorDual.hpp.
syncToHost()
INLINE_FUNCTION_H void syncToHost () inline
Definition at line 892 of file VectorDual.hpp.
Referenced by VectorDual< multiRotatingAxis >::push_back().
syncToDevice()
INLINE_FUNCTION_H void syncToDevice () inline
Definition at line 900 of file VectorDual.hpp.
syncViews() [1/2]
INLINE_FUNCTION_H void syncViews () inline
Definition at line 909 of file VectorDual.hpp.
Referenced by VectorDual< multiRotatingAxis >::assign(), VectorDual< multiRotatingAxis >::changeSize(), VectorDual< multiRotatingAxis >::deleteElement(), multiRotatingAxisMotion::getModel(), VectorDual< multiRotatingAxis >::insertSetElement(), VectorDual< multiRotatingAxis >::resizeSync(), and VectorDual< multiRotatingAxis >::sortItems().
syncViews() [2/2]
INLINE_FUNCTION_H void syncViews (int32 start, int32 end) inline
Definition at line 921 of file VectorDual.hpp.
readVector()
FUNCTION_H bool readVector (iIstream & is, size_t len = 0) inline
Definition at line 935 of file VectorDual.hpp.
Referenced by VectorDual< multiRotatingAxis >::read().
read()
FUNCTION_H bool read (iIstream & is) inline
Definition at line 948 of file VectorDual.hpp.
Referenced by pFlow::operator>>().
write()
FUNCTION_H bool write (iOstream & os) const inline
Definition at line 954 of file VectorDual.hpp.
Referenced by pFlow::operator<<().
Member Data Documentation
size_
size_t size_ = 0 protected
Definition at line 94 of file VectorDual.hpp.
Referenced by VectorDual< multiRotatingAxis >::empty(), VectorDual< multiRotatingAxis >::end(), VectorDual< multiRotatingAxis >::push_back(), VectorDual< multiRotatingAxis >::setSize(), VectorDual< multiRotatingAxis >::size(), VectorDual< multiRotatingAxis >::updateSubViews(), and VectorDual< multiRotatingAxis >::VectorDual().
capacity_
size_t capacity_ = 0 protected
Definition at line 96 of file VectorDual.hpp.
Referenced by VectorDual< multiRotatingAxis >::assign(), VectorDual< multiRotatingAxis >::capacity(), VectorDual< multiRotatingAxis >::changeSize(), VectorDual< multiRotatingAxis >::operator=(), VectorDual< multiRotatingAxis >::push_back(), and VectorDual< multiRotatingAxis >::reallocate().
dualView_
dualViewType dualView_ protected
Definition at line 98 of file VectorDual.hpp.
Referenced by VectorDual< multiRotatingAxis >::assign(), VectorDual< multiRotatingAxis >::changeSize(), VectorDual< multiRotatingAxis >::clear(), VectorDual< multiRotatingAxis >::copyDeviceToHost(), VectorDual< multiRotatingAxis >::copyHostToDevice(), VectorDual< multiRotatingAxis >::data(), VectorDual< multiRotatingAxis >::deleteElement(), VectorDual< multiRotatingAxis >::deviceRequiresSync(), VectorDual< multiRotatingAxis >::deviceView(), VectorDual< multiRotatingAxis >::deviceViewAll(), VectorDual< multiRotatingAxis >::fill(), VectorDual< multiRotatingAxis >::hostRequiresSync(), VectorDual< multiRotatingAxis >::hostView(), VectorDual< multiRotatingAxis >::hostViewAll(), VectorDual< multiRotatingAxis >::modifyOnDevice(), VectorDual< multiRotatingAxis >::modifyOnHost(), VectorDual< multiRotatingAxis >::name(), VectorDual< multiRotatingAxis >::operator=(), VectorDual< multiRotatingAxis >::operator[](), VectorDual< multiRotatingAxis >::reallocate(), VectorDual< multiRotatingAxis >::updateSubViews(), and VectorDual< multiRotatingAxis >::VectorDual().
deviceSubView_
deviceViewType deviceSubView_ mutable protected
Definition at line 100 of file VectorDual.hpp.
Referenced by VectorDual< multiRotatingAxis >::deviceView(), and VectorDual< multiRotatingAxis >::updateSubViews().
hostSubView_
hostViewType hostSubView_ mutable protected
Definition at line 102 of file VectorDual.hpp.
Referenced by VectorDual< multiRotatingAxis >::hostView(), and VectorDual< multiRotatingAxis >::updateSubViews().
subViewsUpdated_
bool subViewsUpdated_ = false mutable protected
Definition at line 104 of file VectorDual.hpp.
Referenced by VectorDual< multiRotatingAxis >::changeSize(), VectorDual< multiRotatingAxis >::push_back(), VectorDual< multiRotatingAxis >::setSize(), and VectorDual< multiRotatingAxis >::updateSubViews().
growthFactor_
const real growthFactor_ = vectorGrowthFactor__ inline static protected
Definition at line 106 of file VectorDual.hpp.
Referenced by VectorDual< multiRotatingAxis >::evalCapacity().
isHostAccessible_
constexpr bool isHostAccessible_ static constexpr protected
Initial value:
=
    Kokkos::SpaceAccessibility<execution_space,Kokkos::HostSpace>::accessible
Definition at line 109 of file VectorDual.hpp.
hdName__
const word hdName__ inline static protected
Initial value:
=
        word(hostType::memory_space::name())+
        word(deviceType::memory_space::name())
Definition at line 113 of file VectorDual.hpp.
Referenced by VectorDual< multiRotatingAxis >::memoerySpaceName().
The documentation for this class was generated from the following file:
src/phasicFlow/containers/VectorHD/VectorDual.hpp