PhasicFlow: boundaryList Class Reference
boundaryList Class Reference
Public Member Functions
TypeInfo ("boundaryList")
type info
boundaryList (pointStructure &pStruct)
virtual ~boundaryList ()=default
bool updateNeighborLists (uint32 iter, bool force=false)
update neighbor list of boundaries based on the time intervals
bool createBoundaries ()
const pointStructure & pStruct () const
auto & boundary (size_t i)
const auto & boundary (size_t i) const
bool boundariesUpdated () const
const auto & extendedDomain () const
const auto & extendedDomainBox () const
box internalDomainBox () const
bool beforeIteration (const timeInfo &tf, bool force=false)
bool iterate (const timeInfo &tf, bool force=false)
bool afterIteration (const timeInfo &tf, bool force=false)
Public Member Functions inherited from ListPtr< boundaryBase >
TypeInfoTemplateNV11 ("ListPtr", boundaryBase)
ListPtr ()
ListPtr (size_t len)
ListPtr (const ListPtrType &src)
ListPtr (ListPtrType &&src)
ListPtrType & operator= (const ListPtrType &rhs)
ListPtrType & operator= (ListPtrType &&rhs)
ListPtrType * clonePtr () const
uniquePtr< ListPtrType > clone () const
~ListPtr ()
uniquePtr< boundaryBase > set (size_t i, boundaryBase *ptr)
uniquePtr< boundaryBase > set (size_t i, uniquePtr< boundaryBase > &&ptr)
uniquePtr< boundaryBase > setSafe (size_t i, Args &&... args)
pFlow::uniquePtr< boundaryBase > setSafe (size_t i, Args &&... args)
void push_back (boundaryBase *ptr)
void push_back (uniquePtr< boundaryBase > &&ptr)
void push_backSafe (Args &&... args)
boundaryBase & operator[] (size_t i)
const boundaryBase & operator[] (size_t i) const
size_t size () const
auto empty () const
uniquePtr< boundaryBase > release (size_t i)
void clear ()
void clear (size_t i)
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
Private Member Functions
void setExtendedDomain ()
bool resetLists ()
bool updateNeighborLists ()
update neighbor list of boundaries regardless of the time intervals
Private Attributes
pointStructure & pStruct_
uint32 neighborListUpdateInterval_
uint32 updateInterval_
uint32 lastNeighborUpdated_ = 0
bool neighborListUpdate_
bool boundaryUpdate_
bool iterBeforeBoundaryUpdate_
domain extendedDomain_
box internalDomainBox_
bool listSet_ = false
Additional Inherited Members
Public Types inherited from ListPtr< boundaryBase >
using ListPtrType = ListPtr< boundaryBase >
using listType = std::list< boundaryBase * >
using iterator = typename listType::iterator
using const_iterator = typename listType::const_iterator
Static Public Member Functions inherited from ListPtr< boundaryBase >
static uniquePtr< boundaryBase > makeSafe (Args &&... args)
Protected Member Functions inherited from ListPtr< boundaryBase >
bool copy (const ListPtrType &src)
boundaryBase * ptr (size_t i)
const boundaryBase * ptr (size_t i) const
auto pos (size_t i)
auto pos (size_t i) const
Protected Attributes inherited from ListPtr< boundaryBase >
std::list< boundaryBase * > list_
Detailed Description
Definition at line 35 of file boundaryList.hpp.
Constructor & Destructor Documentation
boundaryList()
boundaryList (pointStructure & pStruct) explicit
Definition at line 91 of file boundaryList.cpp.
References dictionary::getVal(), dictionary::getValMax(), boundaryList::neighborListUpdateInterval_, boundaryList::pStruct_, pointStructure::simDomain(), and boundaryList::updateInterval_.
~boundaryList()
virtual ~boundaryList () virtual default
Member Function Documentation
setExtendedDomain()
void setExtendedDomain () private
Definition at line 25 of file boundaryList.cpp.
References boundaryList::boundary(), pFlow::endl(), boundaryList::extendedDomain_, fatalErrorInFunction, fatalExit, boundaryList::listSet_, boundaryList::pStruct_, and pointStructure::simDomain().
resetLists()
bool resetLists () private
Definition at line 46 of file boundaryList.cpp.
updateNeighborLists() [1/2]
bool updateNeighborLists () private
update neighbor list of boundaries regardless of the time intervals
Definition at line 54 of file boundaryList.cpp.
TypeInfo()
TypeInfo ("boundaryList")
type info
updateNeighborLists() [2/2]
bool updateNeighborLists (uint32 iter, bool force = false)
update neighbor list of boundaries based on the time intervals
Definition at line 106 of file boundaryList.cpp.
References pFlow::endl(), and fatalErrorInFunction.
createBoundaries()
bool createBoundaries ()
Definition at line 141 of file boundaryList.cpp.
References boundaryBase::create().
pStruct()
const pointStructure& pStruct () const inline
Definition at line 89 of file boundaryList.hpp.
References boundaryList::pStruct_.
Referenced by boundaryFieldList< VectorField, realx3, void >::boundaryFieldList().
boundary() [1/2]
auto& boundary (size_t i) inline
Definition at line 95 of file boundaryList.hpp.
References ListPtr< T >::operator[]().
Referenced by boundaryList::setExtendedDomain().
boundary() [2/2]
const auto& boundary (size_t i) const inline
Definition at line 101 of file boundaryList.hpp.
References ListPtr< T >::operator[]().
boundariesUpdated()
bool boundariesUpdated () const inline
Definition at line 107 of file boundaryList.hpp.
References boundaryList::boundaryUpdate_.
extendedDomain()
const auto& extendedDomain () const inline
Definition at line 113 of file boundaryList.hpp.
References boundaryList::extendedDomain_.
Referenced by pointStructure::extendedDomain().
extendedDomainBox()
const auto& extendedDomainBox () const inline
Definition at line 119 of file boundaryList.hpp.
References domain::domainBox(), and boundaryList::extendedDomain_.
internalDomainBox()
pFlow::box internalDomainBox () const
Definition at line 165 of file boundaryList.cpp.
Referenced by pointStructure::internalDomainBox().
beforeIteration()
bool beforeIteration (const timeInfo & tf, bool force = false)
Definition at line 186 of file boundaryList.cpp.
References pFlow::endl(), fatalErrorInFunction, and timeInfo::iter().
iterate()
bool iterate (const timeInfo & tf, bool force = false)
Definition at line 237 of file boundaryList.cpp.
References pFlow::endl(), and fatalErrorInFunction.
afterIteration()
bool afterIteration (const timeInfo & tf, bool force = false)
Definition at line 252 of file boundaryList.cpp.
References pFlow::endl(), fatalErrorInFunction, and timeInfo::iter().
Member Data Documentation
pStruct_
pointStructure& pStruct_ private
Definition at line 42 of file boundaryList.hpp.
Referenced by boundaryList::boundaryList(), boundaryList::pStruct(), and boundaryList::setExtendedDomain().
neighborListUpdateInterval_
uint32 neighborListUpdateInterval_ private
Definition at line 44 of file boundaryList.hpp.
Referenced by boundaryList::boundaryList().
updateInterval_
uint32 updateInterval_ private
Definition at line 46 of file boundaryList.hpp.
Referenced by boundaryList::boundaryList().
lastNeighborUpdated_
uint32 lastNeighborUpdated_ = 0 private
Definition at line 48 of file boundaryList.hpp.
neighborListUpdate_
bool neighborListUpdate_ private
Definition at line 50 of file boundaryList.hpp.
boundaryUpdate_
bool boundaryUpdate_ private
Definition at line 52 of file boundaryList.hpp.
Referenced by boundaryList::boundariesUpdated().
iterBeforeBoundaryUpdate_
bool iterBeforeBoundaryUpdate_ private
Definition at line 54 of file boundaryList.hpp.
extendedDomain_
domain extendedDomain_ private
Definition at line 56 of file boundaryList.hpp.
Referenced by boundaryList::extendedDomain(), boundaryList::extendedDomainBox(), and boundaryList::setExtendedDomain().
internalDomainBox_
box internalDomainBox_ private
Definition at line 58 of file boundaryList.hpp.
listSet_
bool listSet_ = false private
Definition at line 60 of file boundaryList.hpp.
Referenced by boundaryList::setExtendedDomain().
The documentation for this class was generated from the following files:
src/phasicFlow/structuredData/boundaries/boundaryList.hpp
src/phasicFlow/structuredData/boundaries/boundaryList.cpp