PhasicFlow: selectBox Class Reference
selectBox Class Reference
Public Member Functions
TypeInfo ("selectBox")
selectBox (const pointStructure &pStruct, const dictionary &dict)
add_vCtor (pStructSelector, selectBox, dictionary)
virtual ~selectBox ()=default
const uint32Vector & selectedPoints () const override
uint32Vector & selectedPoints () override
Public Member Functions inherited from pStructSelector
TypeInfo ("pStructSelector")
pStructSelector (const pointStructure &pStruct, const dictionary &UNUSED(dict))
the dictionary contains the selector keyword and another dictionary which is used for creating selector
pStructSelector (const word &type, const pointStructure &pStruct, const dictionary &UNUSED(dict))
construct using selector type and a dictionary that contains info of selector
create_vCtor (pStructSelector, dictionary,(const pointStructure &pStruct, const dictionary &dict),(pStruct, dict))
create_vCtor (pStructSelector, word,(const word &type, const pointStructure &pStruct, const dictionary &dict),(type, pStruct, dict))
virtual ~pStructSelector ()=default
const pointStructure & pStruct () const
realx3Vector selectedPointPositions () const
Protected Member Functions
void selectAllPointsInBox ()
Protected Attributes
uint32Vector selectedPoints_
box box_
Protected Attributes inherited from pStructSelector
const pointStructure & pStruct_
Additional Inherited Members
Static Public Member Functions inherited from pStructSelector
static uniquePtr< pStructSelector > create (const pointStructure &pStruct, const dictionary &dict)
static uniquePtr< pStructSelector > create (const word &type, const pointStructure &pStruct, const dictionary &dict)
Detailed Description
Definition at line 35 of file selectBox.hpp.
Constructor & Destructor Documentation
selectBox()
selectBox (const pointStructure & pStruct, const dictionary & dict)
Definition at line 43 of file selectBox.cpp.
~selectBox()
virtual ~selectBox () virtual default
Member Function Documentation
selectAllPointsInBox()
void selectAllPointsInBox () protected
Definition at line 25 of file selectBox.cpp.
References selectBox::box_, ForAll, VectorSingle< T, MemorySpace >::hostView(), box::isInside(), internalPoints::pointPosition(), pStructSelector::pStruct(), Vector< T, Allocator >::reserve(), and selectBox::selectedPoints_.
TypeInfo()
TypeInfo ("selectBox")
add_vCtor()
add_vCtor (pStructSelector , selectBox , dictionary)
selectedPoints() [1/2]
const uint32Vector& selectedPoints () const inline override virtual
Implements pStructSelector.
Definition at line 66 of file selectBox.hpp.
References selectBox::selectedPoints_.
selectedPoints() [2/2]
uint32Vector& selectedPoints () inline override virtual
Implements pStructSelector.
Definition at line 71 of file selectBox.hpp.
References selectBox::selectedPoints_.
Member Data Documentation
selectedPoints_
uint32Vector selectedPoints_ protected
Definition at line 41 of file selectBox.hpp.
Referenced by selectBox::selectAllPointsInBox(), and selectBox::selectedPoints().
box_
box box_ protected
Definition at line 43 of file selectBox.hpp.
Referenced by selectBox::selectAllPointsInBox().
The documentation for this class was generated from the following files:
src/phasicFlow/structuredData/pointStructure/selectors/selectBox/selectBox.hpp
src/phasicFlow/structuredData/pointStructure/selectors/selectBox/selectBox.cpp