PhasicFlow: utilities/geometryPhasicFlow/geometryPhasicFlow.cpp File Reference
geometryPhasicFlow.cpp File Reference
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 29 of file geometryPhasicFlow.cpp.
References Control, Wall::create(), geometry::create(), Cyan_Text, END_REPORT, Green_Text, commandLine::parse(), proprties, objectFile::READ_ALWAYS, objectFile::READ_NEVER, REPORT, pFlow::triangle::surface(), pFlow::triSurfaceFile__, objectFile::WRITE_ALWAYS, and objectFile::WRITE_NEVER.