PhasicFlow: solvers/grainGranFlow/createDEMComponents.hpp File Reference
createDEMComponents.hpp File Reference
Functions
REPORT (0)<<"\nReading sphere particles . . ."<< END_REPORT
Variables
pFlow::grainParticles grnParticles (Control, proprties)
auto grnInsertion
auto interactionPtr
auto & grnInteraction = interactionPtr()
Function Documentation
REPORT()
REPORT (0)
Variable Documentation
grnParticles
pFlow::grainParticles grnParticles(Control, proprties)
Referenced by periodicBoundaryGrainInteraction< contactForceModel, geometryMotionModel >::grainGrainInteraction(), and main().
grnInsertion
auto grnInsertion
Initial value:
=  pFlow::grainInsertion(
    grnParticles,
    grnParticles.grains())
Definition at line 39 of file createDEMComponents.hpp.
Referenced by main().
interactionPtr
auto interactionPtr
Initial value:
= pFlow::interaction::create(
    Control,
    grnParticles,
    surfGeometry
    )
Definition at line 44 of file createDEMComponents.hpp.
grnInteraction
auto& grnInteraction = interactionPtr()
Definition at line 50 of file createDEMComponents.hpp.
Referenced by main().