PhasicFlow: src/setHelpers/initialize_Control.hpp File Reference
initialize_Control.hpp File Reference
Functions
REPORT (0)<<"\nCreating Control repository . . ."<< endREPORT
if (isCoupling)
Variables
pFlow::uniquePtr< pFlow::systemControl > ControlPtr = nullptr
else
auto & Control = ControlPtr()
Function Documentation
REPORT()
REPORT (0)
if()
if (isCoupling)
Definition at line 30 of file initialize_Control.hpp.
References ControlPtr, readControlDict::endTime(), readControlDict::saveInterval(), readControlDict::startTime(), and readControlDict::startTimeName().
Variable Documentation
ControlPtr
pFlow::uniquePtr<pFlow::systemControl> ControlPtr = nullptr
Definition at line 28 of file initialize_Control.hpp.
Referenced by if().
else
else
Initial value:
{
    ControlPtr = pFlow::makeUnique<pFlow::systemControl>()
Definition at line 43 of file initialize_Control.hpp.
Referenced by Timer::write().
Control
auto& Control = ControlPtr()
Definition at line 47 of file initialize_Control.hpp.
Referenced by main().