PhasicFlow: pFlow::TSFtoVTK Namespace Reference
pFlow::TSFtoVTK Namespace Reference
Functions
bool convertTimeFolderTriSurfaceFields (systemControl &control, const fileSystem &destPath, const word &bName, bool separate, wordList &surfNames, wordList &fileNames)
bool triSurfaceToVTK (Ostream &os, const realx3 *points, const uint32x3 *vertices, const subSurface &subSurf)
bool triSurfaceToVTK (Ostream &os, const realx3 *points, const uint32x3 *vertices, uint32 numPoints, uint32 numTris)
bool convertTimeFolderTriSurfaceFieldsSingle (multiTriSurface &surface, const fileSystem &destPath, real time, const word &bName, wordList &surfNames, wordList &fileNames)
bool convertTimeFolderTriSurfaceFieldsSeparate (multiTriSurface &surface, const fileSystem &destPath, real time, const word &bName, wordList &surfNames, wordList &fileNames)
bool regexCheck (const word &TYPENAME, const word &fieldType)
template<typename Type >
bool checkTriFieldType (word objectType)
bool convertRealx3TypetriSurfaceField (Ostream &os, const IOfileHeader &header, multiTriSurface &tSurface)
bool convertRealx3TypetriSurfaceFieldSeparate (const fileSystem &destPath, const IOfileHeader &header, multiTriSurface &tSurface, const word &bName, real time)
Function Documentation
convertTimeFolderTriSurfaceFields()
bool convertTimeFolderTriSurfaceFields (systemControl & control, const fileSystem & destPath, const word & bName, bool separate, wordList & surfNames, wordList & fileNames)
Definition at line 5 of file triSurfaceFieldToVTK.cpp.
References convertTimeFolderTriSurfaceFieldsSeparate(), convertTimeFolderTriSurfaceFieldsSingle(), timeControl::currentTime(), END_WARNING, systemControl::geometry(), IOfileHeader::headerOk(), repository::path(), systemControl::time(), pFlow::triSurfaceFile__, and WARNING.
Referenced by main().
triSurfaceToVTK() [1/2]
bool triSurfaceToVTK (Ostream & os, const realx3 * points, const uint32x3 * vertices, const subSurface & subSurf)
Definition at line 64 of file triSurfaceFieldToVTK.cpp.
References subSurface::end(), pFlow::endl(), subSurface::numPoints(), subSurface::pointEnd(), subSurface::pointStart(), subSurface::size(), subSurface::start(), triple< T >::x(), triple< T >::y(), and triple< T >::z().
Referenced by convertTimeFolderTriSurfaceFieldsSeparate(), and convertTimeFolderTriSurfaceFieldsSingle().
triSurfaceToVTK() [2/2]
bool triSurfaceToVTK (Ostream & os, const realx3 * points, const uint32x3 * vertices, uint32 numPoints, uint32 numTris)
Definition at line 108 of file triSurfaceFieldToVTK.cpp.
References pFlow::endl(), triple< T >::x(), triple< T >::y(), and triple< T >::z().
convertTimeFolderTriSurfaceFieldsSingle()
bool convertTimeFolderTriSurfaceFieldsSingle (multiTriSurface & surface, const fileSystem & destPath, real time, const word & bName, wordList & surfNames, wordList & fileNames)
Definition at line 151 of file triSurfaceFieldToVTK.cpp.
References pFlow::containingFiles(), convertRealx3TypetriSurfaceField(), END_REPORT, pFlow::endl(), fatalErrorInFunction, vtkFile::fileName(), Green_Text, IOfileHeader::headerOk(), pFlow::output, REPORT, pFlow::triangle::surface(), triSurfaceToVTK(), and fileSystem::wordPath().
Referenced by convertTimeFolderTriSurfaceFields().
convertTimeFolderTriSurfaceFieldsSeparate()
bool convertTimeFolderTriSurfaceFieldsSeparate (multiTriSurface & surface, const fileSystem & destPath, real time, const word & bName, wordList & surfNames, wordList & fileNames)
Definition at line 211 of file triSurfaceFieldToVTK.cpp.
References pFlow::containingFiles(), convertRealx3TypetriSurfaceFieldSeparate(), END_REPORT, pFlow::endl(), fatalErrorInFunction, vtkFile::fileName(), Green_Text, pFlow::groupNames(), IOfileHeader::headerOk(), pFlow::output, REPORT, pFlow::triangle::surface(), triSurfaceToVTK(), and fileSystem::wordPath().
Referenced by convertTimeFolderTriSurfaceFields().
regexCheck()
bool pFlow::TSFtoVTK::regexCheck (const word & TYPENAME, const word & fieldType) inline
Definition at line 73 of file triSurfaceFieldToVTK.hpp.
Referenced by pFlow::PFtoVTK::checkFieldType(), and checkTriFieldType().
checkTriFieldType()
bool pFlow::TSFtoVTK::checkTriFieldType (word objectType) inline
Definition at line 87 of file triSurfaceFieldToVTK.hpp.
References regexCheck().
convertRealx3TypetriSurfaceField()
bool convertRealx3TypetriSurfaceField (Ostream & os, const IOfileHeader & header, multiTriSurface & tSurface)
Definition at line 289 of file triSurfaceFieldToVTK.cpp.
References pFlow::PFtoVTK::addRealx3PointField(), defaultColor, END_REPORT, greenColor, IOfileHeader::objectName(), IOfileHeader::objectType(), and REPORT.
Referenced by convertTimeFolderTriSurfaceFieldsSingle().
convertRealx3TypetriSurfaceFieldSeparate()
bool convertRealx3TypetriSurfaceFieldSeparate (const fileSystem & destPath, const IOfileHeader & header, multiTriSurface & tSurface, const word & bName, real time)
Definition at line 321 of file triSurfaceFieldToVTK.cpp.
References pFlow::PFtoVTK::addRealx3PointField(), END_REPORT, vtkFile::fileName(), Green_Text, pFlow::groupNames(), multiTriSurface::numSurfaces(), IOfileHeader::objectName(), IOfileHeader::objectType(), REPORT, and multiTriSurface::subSurfaces().
Referenced by convertTimeFolderTriSurfaceFieldsSeparate().