PhasicFlow: pFlow::NBSLevel0Kernels Namespace Reference
pFlow::NBSLevel0Kernels Namespace Reference
Typedefs
using mdrPolicyFindPairs = Kokkos::MDRangePolicy< Kokkos::IndexType< uint32 >, Kokkos::Rank< 3 >, Kokkos::Schedule< Kokkos::Dynamic >, DefaultExecutionSpace >
Functions
template<typename T >
INLINE_FUNCTION_HD void Swap (T &x, T &y)
INLINE_FUNCTION_HD bool sphereSphereCheck (const realx3 &p1, const realx3 p2, real d1, real d2)
uint32 findPairsCount (csPairContainerType &pairs, real sizeRatio, const deviceViewType1D< realx3 > &pointPos, const pFlagTypeDevice &flags, const deviceViewType1D< real > &diameter, mapperNBS::CellIterator cellIter)
Typedef Documentation
mdrPolicyFindPairs
using mdrPolicyFindPairs = Kokkos::MDRangePolicy< Kokkos::IndexType<uint32>, Kokkos::Rank<3>, Kokkos::Schedule<Kokkos::Dynamic>, DefaultExecutionSpace>
Definition at line 34 of file NBSLevel0Kernels.hpp.
Function Documentation
Swap()
INLINE_FUNCTION_HD void pFlow::NBSLevel0Kernels::Swap (T & x, T & y)
Definition at line 38 of file NBSLevel0Kernels.hpp.
Referenced by pFlow::byteSwaper(), and while().
sphereSphereCheck()
INLINE_FUNCTION_HD bool pFlow::NBSLevel0Kernels::sphereSphereCheck (const realx3 & p1, const realx3 p2, real d1, real d2)
Definition at line 46 of file NBSLevel0Kernels.hpp.
References length().
Referenced by while().
findPairsCount()
uint32 pFlow::NBSLevel0Kernels::findPairsCount (csPairContainerType & pairs, real sizeRatio, const deviceViewType1D< realx3 > & pointPos, const pFlagTypeDevice & flags, const deviceViewType1D< real > & diameter, mapperNBS::CellIterator cellIter) inline
Definition at line 53 of file NBSLevel0Kernels.hpp.
References LAMBDA_HD, and mapperNBS::CellIterator::numCells().
Referenced by NBSLevel0::findPairs().