PhasicFlow: pFlow::algorithms::STD Namespace Reference
pFlow::algorithms::STD Namespace Reference
Functions
template<typename Type , bool useParallel = useStdParallel__>
INLINE_FUNCTION_H int32 count (const Type *first, int32 numElems, const Type &val)
template<typename Type , bool useParallel = useStdParallel__>
INLINE_FUNCTION_H void fill (Type *first, int32 numElems, const Type &val)
template<typename Type , typename indexType , bool useParallel = useStdParallel__>
INLINE_FUNCTION_H void fillSelected (Type *first, const indexType *indices, const int32 numElems, const Type val)
template<typename Type , typename indexType , bool useParallel = useStdParallel__>
INLINE_FUNCTION_H void fillSelected (Type *first, const indexType *indices, const Type *vals, const int32 numElems)
template<typename Type , bool useParallel = useStdParallel__>
INLINE_FUNCTION_H void fillSequence (Type *first, int32 numElems, const Type &firstVal)
template<typename Type , bool useParallel = useStdParallel__>
INLINE_FUNCTION_H Type max (const Type *first, int32 numElems)
template<typename Type , bool useParallel = useStdParallel__>
INLINE_FUNCTION_H Type min (const Type *first, int32 numElems)
template<typename Type , bool useParallel = useStdParallel__>
INLINE_FUNCTION_H void sort (Type *first, int32 numElems)
template<typename Type , typename CompareFunc , bool useParallel = useStdParallel__>
INLINE_FUNCTION_H void sort (Type *first, int32 numElems, CompareFunc compare)
template<typename Type , typename PermuteType , bool useParallel = useStdParallel__>
INLINE_FUNCTION_H void permuteSort (const Type *first, PermuteType *pFirst, int32 numElems)
template<typename Type , typename DestType , bool useParallel = useStdParallel__>
void exclusiveScan (Type *first, DestType *dFirst, int32 numElems)
template<typename Type , typename DestType , bool useParallel = useStdParallel__>
void inclusiveScan (Type *first, DestType *dFirst, int32 numElems)
Function Documentation
count()
INLINE_FUNCTION_H int32 pFlow::algorithms::STD::count (const Type * first, int32 numElems, const Type & val)
Definition at line 36 of file stdAlgorithms.hpp.
References count_if(), and pFlow::equal().
fill()
INLINE_FUNCTION_H void pFlow::algorithms::STD::fill (Type * first, int32 numElems, const Type & val)
Definition at line 53 of file stdAlgorithms.hpp.
References fill().
fillSelected() [1/2]
INLINE_FUNCTION_H void pFlow::algorithms::STD::fillSelected (Type * first, const indexType * indices, const int32 numElems, const Type val)
Definition at line 63 of file stdAlgorithms.hpp.
fillSelected() [2/2]
INLINE_FUNCTION_H void pFlow::algorithms::STD::fillSelected (Type * first, const indexType * indices, const Type * vals, const int32 numElems)
Definition at line 88 of file stdAlgorithms.hpp.
fillSequence()
INLINE_FUNCTION_H void pFlow::algorithms::STD::fillSequence (Type * first, int32 numElems, const Type & firstVal)
Definition at line 98 of file stdAlgorithms.hpp.
max()
INLINE_FUNCTION_H Type pFlow::algorithms::STD::max (const Type * first, int32 numElems)
Definition at line 112 of file stdAlgorithms.hpp.
min()
INLINE_FUNCTION_H Type pFlow::algorithms::STD::min (const Type * first, int32 numElems)
Definition at line 129 of file stdAlgorithms.hpp.
sort() [1/2]
INLINE_FUNCTION_H void pFlow::algorithms::STD::sort (Type * first, int32 numElems)
Definition at line 146 of file stdAlgorithms.hpp.
References sort().
sort() [2/2]
INLINE_FUNCTION_H void pFlow::algorithms::STD::sort (Type * first, int32 numElems, CompareFunc compare)
Definition at line 167 of file stdAlgorithms.hpp.
References sort().
permuteSort()
INLINE_FUNCTION_H void pFlow::algorithms::STD::permuteSort (const Type * first, PermuteType * pFirst, int32 numElems)
Definition at line 188 of file stdAlgorithms.hpp.
Referenced by pFlow::getSortedIndex().
exclusiveScan()
void pFlow::algorithms::STD::exclusiveScan (Type * first, DestType * dFirst, int32 numElems)
Definition at line 204 of file stdAlgorithms.hpp.
inclusiveScan()
void pFlow::algorithms::STD::inclusiveScan (Type * first, DestType * dFirst, int32 numElems)
Definition at line 223 of file stdAlgorithms.hpp.