PhasicFlow: pFlow::PFtoVTK Namespace Reference
pFlow::PFtoVTK Namespace Reference
Classes
class fileSeries
Functions
bool convertTimeFolderPointFields (systemControl &control, const fileSystem &destPath, const word &bName, word &filename)
bool convertTimeFolderPointFieldsSelected (systemControl &control, const fileSystem &destPath, const word &bName, const wordVector &fieldsName, bool mustExist, word &filename)
bool addUndstrcuturedGridField (Ostream &os, realx3 *position, uint32 numPoints)
bool convertRealTypePointField (Ostream &os, const IOfileHeader &header, pointStructure &pStruct)
bool convertRealx3TypePointField (Ostream &os, const IOfileHeader &header, pointStructure &pStruct)
template<typename IntType >
bool addIntPointField (Ostream &os, const word &fieldName, IntType *field, uint32 numData)
bool addRealPointField (Ostream &os, const word &fieldName, const real *field, uint32 numData)
bool addRealx3PointField (Ostream &os, const word &fieldName, const realx3 *field, uint32 numData)
template<typename Type >
bool checkFieldType (word objectType)
bool regexCheck (const word &TYPENAME, const word &fieldType)
template<typename IntType >
bool convertIntPointField (Ostream &os, const IOfileHeader &header, pointStructure &pStruct)
Function Documentation
convertTimeFolderPointFields()
bool convertTimeFolderPointFields (systemControl & control, const fileSystem & destPath, const word & bName, word & filename)
Definition at line 8 of file pointFieldToVTK.cpp.
References addUndstrcuturedGridField(), bindaryOutput__, pFlow::containingFiles(), convertRealTypePointField(), convertRealx3TypePointField(), timeControl::currentTime(), defaultColor, END_REPORT, END_WARNING, pFlow::endl(), vtkFile::fileName(), IOfileHeader::headerOk(), pFlow::nl, IOfileHeader::objectName(), IOfileHeader::objectType(), pFlow::output, repository::path(), pFlow::pointStructureFile__, pStruct, REPORT, systemControl::time(), WARNING, fileSystem::wordPath(), Yellow_Text, and yellowColor.
Referenced by main().
convertTimeFolderPointFieldsSelected()
bool convertTimeFolderPointFieldsSelected (systemControl & control, const fileSystem & destPath, const word & bName, const wordVector & fieldsName, bool mustExist, word & filename)
Definition at line 95 of file pointFieldToVTK.cpp.
References addUndstrcuturedGridField(), bindaryOutput__, pFlow::containingFiles(), convertRealTypePointField(), convertRealx3TypePointField(), timeControl::currentTime(), defaultColor, END_REPORT, END_WARNING, pFlow::endl(), fatalErrorInFunction, vtkFile::fileName(), IOfileHeader::headerOk(), pFlow::nl, IOfileHeader::objectName(), IOfileHeader::objectType(), pFlow::output, repository::path(), pFlow::pointStructureFile__, pStruct, REPORT, systemControl::time(), WARNING, fileSystem::wordPath(), Yellow_Text, and yellowColor.
Referenced by main().
addUndstrcuturedGridField()
bool addUndstrcuturedGridField (Ostream & os, realx3 * position, uint32 numPoints)
Definition at line 200 of file pointFieldToVTK.cpp.
References bindaryOutput__, pFlow::byteSwaper(), pFlow::endl(), Ostream::stdStream(), triple< T >::x(), triple< T >::y(), and triple< T >::z().
Referenced by convertTimeFolderPointFields(), and convertTimeFolderPointFieldsSelected().
convertRealTypePointField()
bool convertRealTypePointField (Ostream & os, const IOfileHeader & header, pointStructure & pStruct)
Definition at line 270 of file pointFieldToVTK.cpp.
References addRealPointField(), END_REPORT, Green_Text, IOfileHeader::objectName(), IOfileHeader::objectType(), pStruct, and REPORT.
Referenced by convertTimeFolderPointFields(), and convertTimeFolderPointFieldsSelected().
convertRealx3TypePointField()
bool convertRealx3TypePointField (Ostream & os, const IOfileHeader & header, pointStructure & pStruct)
Definition at line 298 of file pointFieldToVTK.cpp.
References addRealx3PointField(), END_REPORT, Green_Text, IOfileHeader::objectName(), IOfileHeader::objectType(), pStruct, and REPORT.
Referenced by convertTimeFolderPointFields(), and convertTimeFolderPointFieldsSelected().
addIntPointField()
bool addIntPointField (Ostream & os, const word & fieldName, IntType * field, uint32 numData) inline
Definition at line 127 of file pointFieldToVTK.hpp.
References bindaryOutput__, pFlow::byteSwaper(), END_WARNING, Ostream::stdStream(), and WARNING.
Referenced by convertIntPointField().
addRealPointField()
bool addRealPointField (Ostream & os, const word & fieldName, const real * field, uint32 numData)
Definition at line 326 of file pointFieldToVTK.cpp.
References bindaryOutput__, pFlow::byteSwaper(), and Ostream::stdStream().
Referenced by convertRealTypePointField().
addRealx3PointField()
bool addRealx3PointField (Ostream & os, const word & fieldName, const realx3 * field, uint32 numData)
Definition at line 357 of file pointFieldToVTK.cpp.
References bindaryOutput__, pFlow::byteSwaper(), Ostream::stdStream(), triple< T >::x(), triple< T >::y(), and triple< T >::z().
Referenced by convertRealx3TypePointField(), pFlow::TSFtoVTK::convertRealx3TypetriSurfaceField(), and pFlow::TSFtoVTK::convertRealx3TypetriSurfaceFieldSeparate().
checkFieldType()
bool checkFieldType (word objectType) inline
Definition at line 88 of file pointFieldToVTK.hpp.
References regexCheck().
regexCheck()
bool regexCheck (const word & TYPENAME, const word & fieldType) inline
Definition at line 396 of file pointFieldToVTK.cpp.
Referenced by checkFieldType(), and pFlow::TSFtoVTK::checkTriFieldType().
convertIntPointField()
bool pFlow::PFtoVTK::convertIntPointField (Ostream & os, const IOfileHeader & header, pointStructure & pStruct) inline
Definition at line 94 of file pointFieldToVTK.hpp.
References addIntPointField(), Green_Text, IOfileHeader::objectName(), IOfileHeader::objectType(), pStruct, and REPORT.