PhasicFlow: pFlow Namespace Reference
pFlow Namespace Reference
Namespaces
AB2Kernels
algorithms
boundaryBaseKernels
cfModels
GMotion
grainInteractionKernels
grainParticlesKernels
grnTriInteraction
gSettings
internalPointsKernels
mapperNBSKernels
NBSLevel0Kernels
periodicBoundarySIKernels
PFtoVTK
pointStructureKernels
pweBndryContactSearchKernels
sphereInteractionKernels
sphereParticlesKernels
sphTriInteraction
triangle
triSurfaceKernels
TSFtoVTK
utilities
Classes
struct AB3History
struct AB4History
struct AB5History
class AdamsBashforth2
Second order Adams-Bashforth integration method for solving ODE.
class AdamsBashforth3
Third order Adams-Bashforth integration method for solving ODE.
class AdamsBashforth4
Fourth order Adams-Bashforth integration method for solving ODE.
class AdamsBashforth5
Fifth order Adams-Bashforth integration method for solving ODE.
class AdamsMoulton3
Third order Adams-Moulton integration method for solving ODE.
class AdamsMoulton4
Fourth order Adams-Moulton integration method for solving ODE.
class AdamsMoulton5
Fifth order Adams-Moulton integration method for solving ODE.
struct allOp
class anyList
struct array2D
class baseShapeNames
class baseTimeControl
struct betweenEqOp
struct betweenOp
class bitsetHD
class boundariesMask
class boundaryBase
class boundaryContactSearch
class boundaryContactSearchList
class boundaryExit
class boundaryField
class boundaryFieldList
class boundaryGrainInteraction
class boundaryGrainInteractionList
class boundaryGrainParticles
class boundaryGrainParticlesList
class boundaryIntegration
class boundaryIntegrationList
class boundaryList
class boundaryNone
class boundaryPeriodic
class boundaryReflective
class boundarySphereInteraction
class boundarySphereInteractionList
class boundarySphereParticles
class boundarySphereParticlesList
class box
class boxRegion
class cellMapper
class cells
class cellsWallLevel0
struct checkStatic
class collisionCheck
class combinedRange
class commandLine
class compareOne
class compareTwo
class compareZero
class ContactSearch
class contactSearch
class conveyorBelt
conveyor belt model for a wall
class conveyorBeltMotion
conveyor belt model for walls
class countField
class countFields
class cuboidWall
class cylinder
class cylinderRegion
class cylinderWall
class dataEntry
Data entry to be used in dictionries.
class dataIO
class dataIORegular
class demComponent
A base class for every main component of DEM system.
class demGeometry
base for geometry that manages control
class dictionary
Dictionary holds a set of data entries or sub-dictionaries that are enclosed in a curely braces or are in a file.
class domain
class dynamicLinkLibs
class dynamicPointStructure
class empty
struct equalOp
class exitBoundaryField
class Field
class fileDictionary
class fileStream
Creates and manages an input/output file stream with specified format.
class fileSystem
Manages file pathes, manupulate and combines them.
class generalBoundary
class geometricRegion
class geometry
Base class for geometry for managing tri-surfaces, geometry motion, and surface physical properties.
class geometryMotion
class grainInteraction
class grainParticles
class grainShape
struct greaterThanEqOp
struct greaterThanOp
class hashMap
class iBox
class iEntry
Interface calss for data entry and dictionary
class iFstream
Input file stream for reading binary or ascii data from a file.
class iIstream
Interface class for any input stream
class includeMask
class IncludeMask
class IncludeMask< T, allOp< T > >
class indexContainer
It holds two vectors of indecis on Host and Device.
struct indexMorton
class infinitePlane
class insertion
Base class for particle insertion.
class Insertion
This class manages all the insertion regions for particles insertion in the simulation.
class insertionRegion
This class defines all the necessary enteties for defining an insertion region.
class InsertionRegion
This manages insertion of particles from a region based on the ShapeType.
class integration
Base class for integrating the first order ODE (IVP)
class interaction
class internalField
class internalPoints
class intervalRange
class IOfileHeader
class IOobject
class IOPattern
class iOstream
Interface class for any output stream.
class IOstream
A base calss for input/output streams.
class Istream
Standard input stream for binary and ascii data.
class iTstream
Input token stream.
struct lessThanEqOp
struct lessThanOp
class line
class List
class ListPtr
class localProcessors
class Logical
Holds a bool value and converts strings to bool.
class Map
class mapperNBS
class MapPtr
class masterOstream
Output stream for MPI parallel run, when we need to know which the processor number in the output line.
class message
class MotionModel
Motion model abstract class (CRTP) for all the motion models.
class MPITimer
class multiRotatingAxis
Defines an axis of rotation that rotates around itself and rotates around another axis.
class multiRotatingAxisMotion
Rotating axis motion model for walls.
class multiTriSurface
class NBS
class NBSLevel0
class noConstructAllocator
class objectFile
class observer
class oFstream
Output file stream to send binary or ascii data to a file.
class Ostream
Standard output stream for BINARY and ASCII formats.
class oTstream
Output token stream.
class particleIdHandler
class particles
class particleWallContactSearchs
class PeakableRegion
class peakableRegion
class periodicBoundaryContactSearch
class periodicBoundaryField
class periodicBoundaryGrainInteraction
class periodicBoundarySphereInteraction
class plane
class planeWall
class pointField
class pointFlag
class pointRectCell
class pointSorting
class pointStructure
class positionOrdered
class positionParticles
class positionRandom
class postprocess
class ppwBndryContactSearch
class processField
class ProcessField
class processorOstream
Output stream for MPI parallel run, when we need to know which the processor number in the output line.
class processors
This class holds the information about the global execution world and number of processors in communication.
class property
property holds the pure properties of materials.
class pStructSelector
struct quadruple
class RandomReal
class randomReal
struct Range
Range for elements in an vector [start,end)
class readControlDict
class readFromTimeFolder
class rectangleMesh
class rectMeshField
class reflectiveBoundaryField
class regularParticleIdHandler
class regularSimulationDomain
class repository
class rotatingAxis
An axis which rotates around itself at specified speed.
class rotatingAxisMotion
Rotating axis motion model for walls.
class scatteredFieldAccess
class selectBox
class selectorGeometric
class selectorRandomPoints
class selectorStridedRange
class setFieldEntry
class setFieldList
class shape
class shapeMixture
Defines a mixture of particles for particle insertion.
class simulationDomain
class sortedContactList
class sortedPairs
class span
class sphere
class sphereInteraction
class sphereParticles
Class for managing spherical particles.
class sphereRegion
class sphereShape
class stationary
stationary model for a wall
class stationaryWall
stationary model for walls
class stlFile
class stlWall
class stridedRange
class subDomain
class subscriber
class subSurface
class symArray
class systemControl
class Time
class timeControl
class timeFolder
class timeInfo
class timeInterval
class Timer
class Timers
class token
Token class based on OpenFOAM stream, with some modifications/simplifications to be tailored to our needs.
class triangleAccessor
struct triple
A set of 3 variables that can be used for vector variables.
class triSurface
class triSurfaceField
class twoPartEntry
class uniformRandomReal
class uniformRandomUint32
class uniquePtr
class unsortedContactList
class unsortedPairs
class Vector
class VectorDual
class VectorSingle
class VectorSingle< word, HostSpace >
class vibrating
Vibrating model for a wall.
class vibratingMotion
Vibrating motion model for walls.
struct vtkByteSwapper
struct vtkByteSwapper< 1 >
with char, no re-ordering is required
struct vtkByteSwapper< 2 >
re-order 2-byte data
struct vtkByteSwapper< 4 >
re-order 4-byte data
struct vtkByteSwapper< 8 >
re-order of 8-byte data
class vtkFile
class Wall
class wallBoundaryContactSearch
class zAxis
Typedefs
using vibratingMotionGeometry = geometryMotion< vibratingMotion >
using rotationAxisMotionGeometry = geometryMotion< rotatingAxisMotion >
using stationaryGeometry = geometryMotion< stationaryWall >
using conveyorBeltMotionGeometry = geometryMotion< conveyorBeltMotion >
using rpIntegration = Kokkos::RangePolicy< DefaultExecutionSpace, Kokkos::Schedule< Kokkos::Static >, Kokkos::IndexType< uint32 > >
Range policy for integration kernel (alias)
using csExecutionSpace = DefaultExecutionSpace
using csIdType = uint32
using csPairContainerType = unsortedPairs< DefaultExecutionSpace, uint32 >
using sphereInsertion = Insertion< sphereShape >
using grainInsertion = Insertion< grainShape >
using bitset32_D = bitsetHD< unsigned >
using bitset32_H = bitsetHD< unsigned, HostSpace >
using bitset64_D = bitsetHD< unsigned long >
using bitset64_H = bitsetHD< unsigned long, HostSpace >
using int8Field_D = Field< int8 >
using int8Field_H = Field< int8, HostSpace >
using int32Field_D = Field< int32 >
using int32Field_H = Field< int32, HostSpace >
using int64Field_D = Field< int64 >
using int64Field_H = Field< int64, HostSpace >
using uint8Field_D = Field< uint8 >
using uint8Field_H = Field< uint8, HostSpace >
using uint32Field_D = Field< uint32 >
using uint32Field_H = Field< uint32, HostSpace >
using uint64Field_D = Field< uint64 >
using uint64Field_H = Field< uint64, HostSpace >
using uint32x3Field_D = Field< uint32x3 >
using uint32x3Field_H = Field< uint32x3, HostSpace >
using realField_D = Field< real >
using realField_H = Field< real, HostSpace >
using realx3Field_D = Field< realx3 >
using realx3Field_H = Field< realx3, HostSpace >
using realx3x3Field_D = Field< realx3x3 >
using realx3x3Field_H = Field< realx3x3, HostSpace >
using wordField_H = Field< word, HostSpace >
using int32IndexContainer = indexContainer< int32 >
using int64IndexContainer = indexContainer< int64 >
using uint32IndexContainer = indexContainer< uint32 >
using uint64IndexContainer = indexContainer< uint64 >
using int64List = List< int64 >
using int32List = List< int32 >
using int8List = List< int8 >
using uint64List = List< uint64 >
using uint32List = List< uint32 >
using realList = List< real >
using realx3List = List< realx3 >
using realx3x3List = List< realx3x3 >
using boolList = List< bool >
using wordList = List< word >
template<typename T >
using wordHashMap = hashMap< word, T >
template<typename T >
using uint64HashMap = hashMap< uint64, T >
template<typename T >
using uint32HashMap = hashMap< uint32, T >
template<typename T >
using int64HashMap = hashMap< int64, T >
template<typename T >
using int32HashMap = hashMap< int32, T >
template<typename T >
using wordMap = Map< word, T >
template<typename T >
using uint64Map = Map< uint64, T >
template<typename T >
using uint32Map = Map< uint32, T >
template<typename T >
using int32Map = Map< int32, T >
template<typename T >
using int64Map = Map< int64, T >
template<typename key , typename T >
using orderedMapPtr = MapPtr< std::map, key, T >
template<typename key , typename T >
using hashMapPtr = MapPtr< std::unordered_map, key, T >
template<typename T >
using wordOrderedMapPtr = orderedMapPtr< word, T >
template<typename T >
using wordHashMapPtr = hashMapPtr< word, T >
template<typename T >
using pointField_H = pointField< T, HostSpace >
template<typename T >
using pointField_D = pointField< T >
using uint8PointField_D = pointField_D< uint8 >
using uint8PointField_H = pointField_H< uint8 >
using uint32PointField_D = pointField_D< uint32 >
using uint32PointField_H = pointField_H< uint32 >
using uint64PointField_D = pointField_D< uint64 >
using uint64PointField_H = pointField_H< uint64 >
using realPointField_D = pointField_D< real >
using realPointField_H = pointField_H< real >
using realx3PointField_D = pointField_D< realx3 >
using realx3PointField_H = pointField_H< realx3 >
using realx4PointField_D = pointField_D< realx4 >
using realx4PointField_H = pointField_H< realx4 >
using wordPointField_H = pointField_H< word >
template<typename Key >
using Set = std::set< Key, std::less< Key >, std::allocator< Key > >
using wordSet = Set< word >
using realSymArray_D = symArray< real >
using realSymArray_H = symArray< real, HostSpace >
using realx3SymArray_D = symArray< realx3 >
using realx3SymArray_H = symArray< realx3, HostSpace >
using uint32TriSurfaceField_D = triSurfaceField< uint32 >
using uint32TriSurfaceField_H = triSurfaceField< uint32, HostSpace >
using realTriSurfaceField_D = triSurfaceField< real >
using realTriSurfaceField_H = triSurfaceField< real, HostSpace >
using realx3TriSurfaceField_D = triSurfaceField< realx3 >
using realx3TriSurfaceField_H = triSurfaceField< realx3, HostSpace >
template<typename T >
using vecAllocator = std::allocator< T >
using int8Vector = Vector< int8 >
using int32Vector = Vector< int32 >
using int64Vector = Vector< int64 >
using uint8Vector = Vector< uint8 >
using uint32Vector = Vector< uint32 >
using uint64Vector = Vector< uint64 >
using uint32x3Vector = Vector< uint32x3 >
using realVector = Vector< real >
using realx3Vector = Vector< realx3 >
using realx3x3Vector = Vector< realx3x3 >
using wordVector = Vector< word >
using int8Vector_HD = VectorDual< int8 >
using int16Vector_HD = VectorDual< int16 >
using int32Vector_HD = VectorDual< int32 >
using int64Vector_HD = VectorDual< int64 >
using uint32Vector_HD = VectorDual< uint32 >
using labelVector_HD = VectorDual< label >
using realVector_HD = VectorDual< real >
using realx3Vector_HD = VectorDual< realx3 >
using realx3x3Vector_HD = VectorDual< realx3x3 >
typedef VectorSingle< int8 > int8Vector_D
typedef VectorSingle< int8, HostSpace > int8Vector_H
typedef VectorSingle< int32 > int32Vector_D
typedef VectorSingle< int32, HostSpace > int32Vector_H
typedef VectorSingle< int64 > int64Vector_D
typedef VectorSingle< int64, HostSpace > int64Vector_H
typedef VectorSingle< uint8 > uint8Vector_D
typedef VectorSingle< uint8, HostSpace > uint8Vector_H
typedef VectorSingle< uint32 > uint32Vector_D
typedef VectorSingle< uint32, HostSpace > uint32Vector_H
typedef VectorSingle< uint64 > uint64Vector_D
typedef VectorSingle< uint64, HostSpace > uint64Vector_H
typedef VectorSingle< real > realVector_D
typedef VectorSingle< real, HostSpace > realVector_H
typedef VectorSingle< realx3 > realx3Vector_D
typedef VectorSingle< realx3, HostSpace > realx3Vector_H
typedef VectorSingle< int32x3 > int32x3Vector_D
typedef VectorSingle< int32x3, HostSpace > int32x3Vector_H
typedef VectorSingle< int64x3 > int64x3Vector_D
typedef VectorSingle< int64x3, HostSpace > int64x3Vector_H
typedef VectorSingle< uint32x3 > uint32x3Vector_D
typedef VectorSingle< uint32x3, HostSpace > uint32x3Vector_H
typedef VectorSingle< realx3x3 > realx3x3Vector_D
typedef VectorSingle< realx3x3, HostSpace > realx3x3Vector_H
typedef VectorSingle< word, HostSpace > wordVector_H
using fileSystemList = List< fileSystem >
using HostSpace = Kokkos::HostSpace
Host memory space.
using Serial = Kokkos::Serial
Serial execution space.
using DefaultHostExecutionSpace = Kokkos::DefaultHostExecutionSpace
Default Host execution space, on top of all host execution spaces.
using DefaultExecutionSpace = Kokkos::DefaultExecutionSpace
Default execution space, it can be device exe.
using deviceRPolicyStatic = Kokkos::RangePolicy< Kokkos::DefaultExecutionSpace, Kokkos::Schedule< Kokkos::Static >, Kokkos::IndexType< pFlow::uint32 > >
using hostRPolicyStatic = Kokkos::RangePolicy< Kokkos::DefaultExecutionSpace, Kokkos::Schedule< Kokkos::Static >, Kokkos::IndexType< pFlow::uint32 > >
using deviceRPolicyDynamic = Kokkos::RangePolicy< Kokkos::DefaultExecutionSpace, Kokkos::Schedule< Kokkos::Dynamic >, Kokkos::IndexType< pFlow::uint32 > >
using hostRPolicyDynamic = Kokkos::RangePolicy< Kokkos::DefaultExecutionSpace, Kokkos::Schedule< Kokkos::Dynamic >, Kokkos::IndexType< pFlow::uint32 > >
template<typename T1 , typename T2 >
using Pair = Kokkos::pair< T1, T2 >
Pair of two variables.
template<typename T , typename... properties>
using ViewTypeScalar = Kokkos::View< T, properties... >
View for a scalar.
template<typename T , typename... properties>
using ViewType1D = Kokkos::View< T *, properties... >
1D veiw as a vector
template<typename T , typename... properties>
using ViewType2D = Kokkos::View< T **, properties... >
2D view as an array
template<typename T , typename... properties>
using ViewType3D = Kokkos::View< T ***, properties... >
3D view as an array
template<typename T , typename... properties>
using DualViewType1D = Kokkos::DualView< T *, properties... >
1D dual view as a vector
template<typename Key , typename Value , typename... properties>
using unorderedMap = Kokkos::UnorderedMap< Key, Value, properties... >
unordered map
template<typename Key , typename... properties>
using unorderedSet = Kokkos::UnorderedMap< Key, void, properties... >
unordered set
template<typename T >
using deviceViewTypeScalar = Kokkos::View< T >
Scalar on device.
template<typename T >
using deviceViewType1D = Kokkos::View< T * >
1D array (vector) with default device (memory space and execution space)
template<typename T , typename Layout = void>
using deviceViewType2D = Kokkos::View< T **, Layout, void >
2D view on device as an array on device
template<typename T , typename Layout = void>
using deviceViewType3D = Kokkos::View< T ***, Layout, void >
3D view on device as an array on device
template<typename T >
using hostViewTypeScalar = Kokkos::View< T, Kokkos::HostSpace >
template<typename T >
using hostViewType1D = Kokkos::View< T *, Kokkos::HostSpace >
1D array (vector with host memeory space)
template<typename T , typename Layout = void>
using hostViewType2D = Kokkos::View< T **, Layout, Kokkos::HostSpace >
2D array on host
template<typename T , typename Layout = void>
using hostViewType3D = Kokkos::View< T ***, Layout, Kokkos::HostSpace >
3D array on host
template<typename T >
using deviceAtomicViewType1D = Kokkos::View< T *, Kokkos::MemoryTraits< std::is_same_v< DefaultExecutionSpace, Serial > ? 0 :Kokkos::Atomic > >
1D vector on device with atomic capabilities
template<typename T >
using deviceAtomicViewType3D = Kokkos::View< T ***, Kokkos::MemoryTraits< std::is_same_v< DefaultExecutionSpace, Serial > ? 0 :Kokkos::Atomic > >
3D array on device with atomic capabilities
using range32 = Range< int32 >
using range64 = Range< int64 >
using rangeU32 = Range< uint32 >
using rangeU64 = Range< uint64 >
typedef RandomReal< uniformRandomReal > uniformRandomRealDistribution
using int32StridedRagne = stridedRange< int32 >
using int64StridedRange = stridedRange< int64 >
using realStridedRange = stridedRange< real >
using int32IntervalRange = intervalRange< int32 >
using int64IntervalRange = intervalRange< int64 >
using realIntervalRange = intervalRange< real >
using int32CombinedRange = combinedRange< int32 >
using int64CombinedRange = combinedRange< int64 >
using realCombinedRange = combinedRange< real >
typedef iIstream &(* iIstreamManip) (iIstream &)
typedef iOstream &(* iOstreamManip) (iOstream &)
An iOstream manipulator.
typedef IOstream &(* IOstreamManip) (IOstream &)
An IOstream manipulator.
using tokenList = List< token >
using tokenTypeList = List< token::tokenType >
template<typename T >
using deviceScatteredFieldAccess = scatteredFieldAccess< T, typename DefaultExecutionSpace::memory_space >
template<typename T >
using hostScatteredFieldAccess = scatteredFieldAccess< T, HostSpace >
using boxRegion = geometricRegion< box >
using sphereRegion = geometricRegion< sphere >
using cylinderRegion = geometricRegion< cylinder >
using pFlagTypeDevice = pointFlag< DefaultExecutionSpace >
using pFlagTypeHost = pointFlag< DefaultHostExecutionSpace >
using subSurfaceList = List< subSurface >
using real = float
using int8 = signed char
using int32 = int
using int64 = long long int
using uint8 = unsigned char
using uint32 = unsigned int
using uint64 = unsigned long long int
using id_t = uint32
using size_t = std::size_t
using word = std::string
using int8x3 = triple< int8 >
using int32x3 = triple< int32 >
using int64x3 = triple< int64 >
using uint8x3 = triple< uint8 >
using uint32x3 = triple< uint32 >
using uint64x3 = triple< uint64 >
using realx3 = triple< real >
using int32x3x3 = triple< int32x3 >
using uint32x3x3 = triple< uint32x3 >
using realx3x3 = triple< realx3 >
using realx4 = quadruple< real >
using realx4x3 = quadruple< realx3 >
template<typename T >
using rectMeshField_H = rectMeshField< T >
using int8RectMeshField_H = rectMeshField< int8 >
using int32RectMeshField_H = rectMeshField< int32 >
using int64RectMeshField_H = rectMeshField< int64 >
using realRectMeshField_H = rectMeshField< real >
using realx3RectMeshField_H = rectMeshField< realx3 >
Enumerations
enum DataDirection { MasterToSlave, SlaveToMaster, TwoWay }
Functions
bool intAllActive (real dt, realx3Field_D &y, realx3PointField_D &dy, realx3PointField_D &dy1)
bool intScattered (real dt, realx3Field_D &y, realx3PointField_D &dy, realx3PointField_D &dy1)
INLINE_FUNCTION iIstream & operator>> (iIstream &str, AB3History &ab3)
INLINE_FUNCTION iOstream & operator<< (iOstream &str, const AB3History &ab3)
INLINE_FUNCTION iIstream & operator>> (iIstream &str, AB4History &ab4)
INLINE_FUNCTION iOstream & operator<< (iOstream &str, const AB4History &ab4)
INLINE_FUNCTION iIstream & operator>> (iIstream &str, AB5History &ab5)
INLINE_FUNCTION iOstream & operator<< (iOstream &str, const AB5History &ab5)
INLINE_FUNCTION_HD uint64_t splitBy3 (const uint64_t val)
INLINE_FUNCTION_HD uint64_t xyzToMortonCode64 (uint64_t x, uint64_t y, uint64_t z)
INLINE_FUNCTION_HD uint64_t getThirdBits (uint64_t x)
INLINE_FUNCTION_HD void mortonCode64Toxyz (uint64_t morton, uint64_t &x, uint64_t &y, uint64_t &z)
template<typename indexType , typename cellIndexType >
INLINE_FUNCTION_HD void indexToCell (const indexType idx, const triple< cellIndexType > &extent, triple< cellIndexType > &cell)
template<typename cellIndexType >
INLINE_FUNCTION_HD triple< cellIndexType > boxExtent (const iBox< cellIndexType > &box)
template<typename indexType , typename cellIndexType >
INLINE_FUNCTION_HD void indexToCell (const indexType idx, const iBox< cellIndexType > &box, triple< cellIndexType > &cell)
iOstream & operator<< (iOstream &os, const conveyorBelt &obj)
iIstream & operator>> (iIstream &is, conveyorBelt &obj)
iOstream & operator<< (iOstream &os, const rotatingAxis &ax)
iIstream & operator>> (iIstream &is, rotatingAxis &ax)
INLINE_FUNCTION_HD realx3 rotate (const realx3 &p, const line &ln, real theta)
INLINE_FUNCTION_HD realx3 rotate (const realx3 &p, const rotatingAxis &ax, real dt)
INLINE_FUNCTION_HD void rotate (realx3 *p, uint32 n, const line &ln, real theta)
INLINE_FUNCTION_HD void rotate (realx3 *p, uint32 n, const rotatingAxis &ax, real dt)
iOstream & operator<< (iOstream &os, const stationary &obj)
iIstream & operator>> (iIstream &is, stationary &obj)
iOstream & operator<< (iOstream &os, const timeInterval &obj)
iIstream & operator>> (iIstream &is, timeInterval &obj)
iOstream & operator<< (iOstream &os, const vibrating &obj)
iIstream & operator>> (iIstream &is, vibrating &obj)
template<typename T >
bool setOneEntry (const twoPartEntry &tpEntry, anyList &varList)
bool readOneEtrty (const dataEntry &entry, anyList &varList)
template<class T , class MemorySpace >
iIstream & operator>> (iIstream &is, Field< T, MemorySpace > &ifld)
template<typename T , typename MemorySpace >
iOstream & operator<< (iOstream &os, const Field< T, MemorySpace > &ofld)
template<typename T >
iOstream & operator<< (iOstream &os, const List< T > &lst)
template<typename T >
iIstream & operator>> (iIstream &is, List< T > &lst)
template<typename T >
iOstream & printKeys (iOstream &os, const wordHashMap< T > &m)
template<typename T >
iOstream & printKeys (iOstream &os, const uint64HashMap< T > &m)
template<typename T >
iOstream & printKeys (iOstream &os, const uint32HashMap< T > &m)
template<typename T >
iOstream & printKeys (iOstream &os, const int64HashMap< T > &m)
template<typename T >
iOstream & printKeys (iOstream &os, const int32HashMap< T > &m)
template<typename T >
iOstream & printKeys (iOstream &os, const wordMap< T > &m)
template<typename T >
iOstream & printKeys (iOstream &os, const uint64Map< T > &m)
template<typename T >
iOstream & printKeys (iOstream &os, const uint32Map< T > &m)
template<typename T >
iOstream & printKeys (iOstream &os, const int32Map< T > &m)
template<typename T >
iOstream & printKeys (iOstream &os, const int64Map< T > &m)
template<typename T >
iOstream & printKeys (iOstream &os, const wordHashMapPtr< T > &m)
template<class T , class MemorySpace >
iOstream & operator<< (iOstream &os, const internalField< T, MemorySpace > &ifeild)
template<class T , class MemorySpace >
T min (const internalField< T, MemorySpace > &iField)
template<class T , class MemorySpace >
T max (const internalField< T, MemorySpace > &iField)
template<class T , class MemorySpace >
Pair< T, T > minMax (const internalField< T, MemorySpace > &iField)
template<class T , class MemorySpace >
void fillSequence (internalField< T, MemorySpace > &iField, const T &startVal)
template<class T , class MemorySpace >
iOstream & operator<< (iOstream &os, const pointField< T, MemorySpace > &pF)
template<template< class, class > class VectorField, class T , class MemorySpace >
iIstream & operator>> (iIstream &is, pointField< VectorField, T, MemorySpace > &pF)
template<template< class, class > class VectorField, class T , class MemorySpace >
iOstream & operator<< (iOstream &os, const pointField< VectorField, T, MemorySpace > &pF)
template<class T , typename... properties>
T maxActive_serial (const Kokkos::View< T *, properties... > &view, const Kokkos::View< int8 *, Kokkos::LayoutLeft, Kokkos::HostSpace > &flag, size_t start, size_t end)
template<typename T , typename... properties>
INLINE_FUNCTION_H T maxActiveH (const Kokkos::View< T *, properties... > &view, const Kokkos::View< int8 *, Kokkos::LayoutLeft, Kokkos::HostSpace > &flag, size_t start, size_t end)
template<typename T , typename... properties>
INLINE_FUNCTION_H T maxActiveD (const Kokkos::View< T *, properties... > &view, const Kokkos::View< int8 *, Kokkos::LayoutLeft > &flag, size_t start, size_t end)
template<class T , class MemorySpace >
T maxActive (const pointField< VectorSingle, T, MemorySpace > &pField)
template<class side , class T , class MemorySpace = void>
T maxActive (const pointField< VectorDual, T, MemorySpace > &pField)
template<typename T >
span< char > charSpan (span< T > s)
template<typename T >
span< const char > charSpan (span< const T > s)
template<typename Type >
INLINE_FUNCTION_HD void SWAP (Type &x, Type &y)
template<typename T , typename MemorySpace >
iIstream & operator>> (iIstream &is, symArray< T, MemorySpace > &iArr)
template<typename T , typename MemorySpace >
iOstream & operator<< (iOstream &os, const symArray< T, MemorySpace > &oArr)
template<typename T >
span< T > makeSpan (std::vector< T > &container)
template<typename T >
span< T > makeSpan (const std::vector< T > &container)
template<typename T >
bool writeSpan (iOstream &os, span< T > sp)
template<typename T >
bool writeSpan (iOstream &os, span< T > sp, const IOPattern &iop)
template<typename T , typename Allocator >
bool writeStdVector (iOstream &os, const std::vector< T, Allocator > &vec)
template<typename T , typename Allocator >
bool writeStdVector (iOstream &os, const std::vector< T, Allocator > &vec, const IOPattern &iop)
template<typename T , typename Allocator >
bool readStdVector (iIstream &is, std::vector< T, Allocator > &vec)
template<typename T , typename Allocator >
bool readStdVector (iIstream &is, std::vector< T, Allocator > &vec, const IOPattern &iop)
template<typename T , typename Allocator >
iOstream & operator<< (iOstream &os, const std::vector< T, Allocator > &vec)
template<typename T , typename Allocator >
iIstream & operator>> (iIstream &is, std::vector< T, Allocator > &vec)
Always assume ASCII is in the input stream.
template<typename T , typename Allocator >
iIstream & operator>> (iIstream &is, Vector< T, Allocator > &ivec)
template<typename T , typename Allocator >
iOstream & operator<< (iOstream &os, const Vector< T, Allocator > &ovec)
template<typename T , typename Allocator >
auto count (const Vector< T, Allocator > &vec, const T &val)
template<typename T , typename Allocator , typename UnaryPredicate >
auto count_if (const Vector< T, Allocator > &vec, UnaryPredicate p)
template<typename T , typename Allocator >
void fill_n (Vector< T, Allocator > &vec, size_t n, const T &val)
template<typename T , typename Allocator >
void fill (Vector< T, Allocator > &vec, const T &val)
template<typename T , typename Allocator >
void fillSequence (Vector< T, Allocator > &vec, int32 start, int32 end, const T &startVal)
template<typename T , typename Allocator >
void fillSequence (Vector< T, Allocator > &vec, const T &startVal)
template<typename T , typename Allocator >
void sort (Vector< T, Allocator > &vec)
template<typename T , typename Allocator >
int64 find (Vector< T, Allocator > &vec, const T &val)
template<typename T , typename Allocator >
Vector< T, Allocator > abs (const Vector< T, Allocator > &v)
template<typename T , typename Allocator , typename indexFunc >
Vector< T, Allocator > abs (const Vector< T, Allocator > &v, indexFunc iFn)
template<typename T , typename Allocator >
Vector< T, Allocator > mod (const Vector< T, Allocator > &v1, const Vector< T, Allocator > &v2)
template<typename T , typename Allocator , typename indexFunc >
Vector< T, Allocator > mod (const Vector< T, Allocator > &v1, const Vector< T, Allocator > &v2, indexFunc iFn)
template<typename T , typename Allocator >
Vector< T, Allocator > exp (const Vector< T, Allocator > &v)
template<typename T , typename Allocator , typename indexFunc >
Vector< T, Allocator > exp (const Vector< T, Allocator > &v, indexFunc iFn)
template<typename T , typename Allocator >
Vector< T, Allocator > log (const Vector< T, Allocator > &v)
template<typename T , typename Allocator , typename indexFunc >
Vector< T, Allocator > log (const Vector< T, Allocator > &v, indexFunc iFn)
template<typename T , typename Allocator >
Vector< T, Allocator > log10 (const Vector< T, Allocator > &v)
template<typename T , typename Allocator , typename indexFunc >
Vector< T, Allocator > log10 (const Vector< T, Allocator > &v, indexFunc iFn)
template<typename T , typename Allocator >
Vector< T, Allocator > pow (const Vector< T, Allocator > &v1, const Vector< T, Allocator > &v2)
template<typename T , typename Allocator , typename indexFunc >
Vector< T, Allocator > pow (const Vector< T, Allocator > &v1, const Vector< T, Allocator > &v2, indexFunc iFn)
template<typename T , typename Allocator >
Vector< T, Allocator > sqrt (const Vector< T, Allocator > &v)
template<typename T , typename Allocator , typename indexFunc >
Vector< T, Allocator > sqrt (const Vector< T, Allocator > &v, indexFunc iFn)
template<typename T , typename Allocator >
Vector< T, Allocator > cbrt (const Vector< T, Allocator > &v)
template<typename T , typename Allocator , typename indexFunc >
Vector< T, Allocator > cbrt (const Vector< T, Allocator > &v, indexFunc iFn)
template<typename T , typename Allocator >
Vector< T, Allocator > sin (const Vector< T, Allocator > &v)
template<typename T , typename Allocator , typename indexFunc >
Vector< T, Allocator > sin (const Vector< T, Allocator > &v, indexFunc iFn)
template<typename T , typename Allocator >
Vector< T, Allocator > cos (const Vector< T, Allocator > &v)
template<typename T , typename Allocator , typename indexFunc >
Vector< T, Allocator > cos (const Vector< T, Allocator > &v, indexFunc iFn)
template<typename T , typename Allocator >
Vector< T, Allocator > tan (const Vector< T, Allocator > &v)
template<typename T , typename Allocator , typename indexFunc >
Vector< T, Allocator > tan (const Vector< T, Allocator > &v, indexFunc iFn)
template<typename T , typename Allocator >
Vector< T, Allocator > asin (const Vector< T, Allocator > &v)
template<typename T , typename Allocator , typename indexFunc >
Vector< T, Allocator > asin (const Vector< T, Allocator > &v, indexFunc iFn)
template<typename T , typename Allocator >
Vector< T, Allocator > acos (const Vector< T, Allocator > &v)
template<typename T , typename Allocator , typename indexFunc >
Vector< T, Allocator > acos (const Vector< T, Allocator > &v, indexFunc iFn)
template<typename T , typename Allocator >
Vector< T, Allocator > atan (const Vector< T, Allocator > &v)
template<typename T , typename Allocator , typename indexFunc >
Vector< T, Allocator > atan (const Vector< T, Allocator > &v, indexFunc iFn)
template<typename T , typename Allocator >
Vector< T, Allocator > atan2 (const Vector< T, Allocator > &v1, const Vector< T, Allocator > &v2)
template<typename T , typename Allocator , typename indexFunc >
Vector< T, Allocator > atan2 (const Vector< T, Allocator > &v1, const Vector< T, Allocator > &v2, indexFunc iFn)
template<typename T , typename Allocator >
Vector< T, Allocator > sinh (const Vector< T, Allocator > &v)
template<typename T , typename Allocator , typename indexFunc >
Vector< T, Allocator > sinh (const Vector< T, Allocator > &v, indexFunc iFn)
template<typename T , typename Allocator >
Vector< T, Allocator > cosh (const Vector< T, Allocator > &v)
template<typename T , typename Allocator , typename indexFunc >
Vector< T, Allocator > cosh (const Vector< T, Allocator > &v, indexFunc iFn)
template<typename T , typename Allocator >
Vector< T, Allocator > tanh (const Vector< T, Allocator > &v)
template<typename T , typename Allocator , typename indexFunc >
Vector< T, Allocator > tanh (const Vector< T, Allocator > &v, indexFunc iFn)
template<typename T , typename Allocator >
Vector< T, Allocator > asinh (const Vector< T, Allocator > &v)
template<typename T , typename Allocator , typename indexFunc >
Vector< T, Allocator > asinh (const Vector< T, Allocator > &v, indexFunc iFn)
template<typename T , typename Allocator >
Vector< T, Allocator > acosh (const Vector< T, Allocator > &v)
template<typename T , typename Allocator , typename indexFunc >
Vector< T, Allocator > acosh (const Vector< T, Allocator > &v, indexFunc iFn)
template<typename T , typename Allocator >
Vector< T, Allocator > atanh (const Vector< T, Allocator > &v)
template<typename T , typename Allocator , typename indexFunc >
Vector< T, Allocator > atanh (const Vector< T, Allocator > &v, indexFunc iFn)
template<typename T , typename Allocator >
Vector< T, Allocator > pow (const Vector< T, Allocator > &v, T e)
template<typename T , typename Allocator , typename indexFunc >
Vector< T, Allocator > pow (const Vector< T, Allocator > &v, T e, indexFunc iFn)
template<typename T , typename Allocator >
T min (const Vector< T, Allocator > &v)
template<typename T , typename Allocator , typename indexFunc >
T min (const Vector< T, Allocator > &v, indexFunc iFn)
template<typename T , typename Allocator >
T max (const Vector< T, Allocator > &v)
template<typename T , typename Allocator , typename indexFunc >
T max (const Vector< T, Allocator > &v, indexFunc iFn)
template<typename T , typename Allocator >
T sum (const Vector< T, Allocator > &v)
template<typename T , typename Allocator , typename indexFunc >
T sum (const Vector< T, Allocator > &v, indexFunc iFn)
template<typename T , typename memory_space >
iIstream & operator>> (iIstream &is, VectorDual< T, memory_space > &ivec)
template<typename T , typename memory_space >
iOstream & operator<< (iOstream &os, const VectorDual< T, memory_space > &ovec)
template<typename side , typename T , typename MemorySpace >
INLINE_FUNCTION_H int64 count (const VectorDual< T, MemorySpace > &vec, const T &val)
template<typename T , typename MemorySpace >
INLINE_FUNCTION_H int64 count (const VectorDual< T, MemorySpace > &vec, const T &val)
template<typename side , typename T , typename MemorySpace >
INLINE_FUNCTION_H int64 min (const VectorDual< T, MemorySpace > &vec)
template<typename T , typename MemorySpace >
INLINE_FUNCTION_H int64 min (const VectorDual< T, MemorySpace > &vec)
template<typename side , typename T , typename MemorySpace >
INLINE_FUNCTION_H int64 max (const VectorDual< T, MemorySpace > &vec)
template<typename T , typename MemorySpace >
INLINE_FUNCTION_H int64 max (const VectorDual< T, MemorySpace > &vec)
template<typename T , typename MemorySpace >
iIstream & operator>> (iIstream &is, VectorSingle< T, MemorySpace > &ivec)
template<typename T , typename MemorySpace >
iOstream & operator<< (iOstream &os, const VectorSingle< T, MemorySpace > &ovec)
template<typename T , typename MemorySpace >
INLINE_FUNCTION_H size_t count (const VectorSingle< T, MemorySpace > &vec, const T &val)
template<class T , class MemorySpace >
INLINE_FUNCTION_H T min (const VectorSingle< T, MemorySpace > &vec)
template<class T , class MemorySpace >
INLINE_FUNCTION_H T max (const VectorSingle< T, MemorySpace > &vec)
iIstream & operator>> (iIstream &is, VectorSingle< word, HostSpace > &ivec)
iOstream & operator<< (iOstream &os, const VectorSingle< word, HostSpace > &ovec)
iOstream & operator<< (iOstream &os, const iEntry &e)
iIstream & operator>> (iIstream &is, iEntry &e)
bool isTwoPartEntry (dataEntry entry)
iOstream & operator<< (iOstream &os, const message &msg)
message operator+ (message::EVENT evnt1, message::EVENT evnt2)
iOstream & operator<< (iOstream &os, const fileSystem &fs)
std::ostream & operator<< (std::ostream &os, const fileSystem &fs)
fileSystem operator/ (const fileSystem &fs1, const fileSystem &fs2)
fileSystem operator/ (const fileSystem &fs1, const word &dir2)
fileSystem operator+ (const fileSystem &fs1, const word fName)
fileSystem CWD ()
Free function to reture current working directory.
bool isDirectory (const fileSystem &path)
Free function to check if the path is dir path.
bool isRegularFile (const fileSystem &path)
free function to check if the path is regular file
fileSystemList subDirectories (const fileSystem &path)
A list of sub-directories that exist in path.
fileSystemList containingFiles (const fileSystem &path)
A list of file paths that exist in the path.
template<typename T , typename... properties>
INLINE_FUNCTION_H T min (const ViewType1D< T, properties... > &view, size_t start, size_t end)
template<typename T , typename... properties>
INLINE_FUNCTION_H T max (const ViewType1D< T, properties... > &view, size_t start, size_t end)
template<typename T , typename... properties>
INLINE_FUNCTION_H T min_serial (const ViewType1D< T, properties... > &view, size_t start, size_t end)
template<typename T , typename... properties>
INLINE_FUNCTION_H T max_serial (const ViewType1D< T, properties... > &view, size_t start, size_t end)
template<typename UnaryFunction , typename T , typename... properties>
void apply_to_each (const ViewType1D< T, properties... > &view, size_t start, size_t end, UnaryFunction func)
template<typename T , typename... properties>
void insertSetElementH (ViewType1D< T, properties... > &view, hostViewType1D< label > &selected, T val)
template<typename T , typename... properties>
void insertSetElementH (ViewType1D< T, properties... > &view, hostViewType1D< label > &selected, hostViewType1D< T > &vals)
template<typename T , typename... properties>
void insertSetElementD (ViewType1D< T, properties... > &view, deviceViewType1D< label > &selected, T val)
template<typename T , typename... properties>
void insertSetElementD (ViewType1D< T, properties... > &view, deviceViewType1D< label > &selected, deviceViewType1D< T > &vals)
template<typename T , typename... properties>
void fill (ViewType3D< T, properties... > &view, range range1, range range2, range range3, T val)
template<typename ExecutionSpace >
INLINE_FUNCTION_H constexpr bool isHostAccessible ()
template<typename ExecutionSpace >
INLINE_FUNCTION_H constexpr bool isDeviceAccessible ()
template<typename ExecutionSpace , typename MemoerySpace >
INLINE_FUNCTION_H constexpr bool areAccessible ()
Is MemoerySpace accessible from ExecutionSpace.
template<typename Type , typename... Properties>
INLINE_FUNCTION_H void reallocInit (ViewType1D< Type, Properties... > &view, uint32 len)
template<typename Type , typename... Properties>
INLINE_FUNCTION_H void reallocNoInit (ViewType1D< Type, Properties... > &view, uint32 len)
template<typename Type , typename... Properties>
INLINE_FUNCTION_H void reallocFill (ViewType1D< Type, Properties... > &view, uint32 len, Type val)
template<typename Type , typename... Properties>
INLINE_FUNCTION_H void reallocInit (ViewType2D< Type, Properties... > &view, uint32 len1, uint32 len2)
template<typename Type , typename... Properties>
INLINE_FUNCTION_H void reallocNoInit (ViewType2D< Type, Properties... > &view, uint32 len1, uint32 len2)
template<typename Type , typename... Properties>
INLINE_FUNCTION_H void reallocFill (ViewType2D< Type, Properties... > &view, uint32 len1, uint32 len2, Type val)
template<typename Type , typename... Properties>
INLINE_FUNCTION_H void reallocInit (ViewType3D< Type, Properties... > &view, uint32 len1, uint32 len2, uint32 len3)
template<typename Type , typename... Properties>
INLINE_FUNCTION_H void reallocNoInit (ViewType3D< Type, Properties... > &view, uint32 len1, uint32 len2, uint32 len3)
template<typename Type , typename... Properties>
INLINE_FUNCTION_H void reallocFill (ViewType3D< Type, Properties... > &view, uint32 len1, uint32 len2, uint32 len3, Type val)
template<typename Type , typename... Properties>
INLINE_FUNCTION_H void resizeInit (ViewType1D< Type, Properties... > &view, uint32 newLen)
template<typename Type , typename... Properties>
INLINE_FUNCTION_H void resizeNoInit (ViewType1D< Type, Properties... > &view, uint32 newLen)
template<typename ViewType >
INLINE_FUNCTION_H void swapViews (ViewType &v1, ViewType &v2)
template<typename T1 , typename T2 >
INLINE_FUNCTION_H iOstream & operator<< (iOstream &os, const Pair< T1, T2 > &p)
template<typename T , typename... properties>
INLINE_FUNCTION_H span< T > makeSpan (ViewType1D< T, properties... > &v)
template<typename T , typename... properties>
INLINE_FUNCTION_H span< T > makeSpan (ViewType1D< T, properties... > &v, uint32 size)
template<typename T , typename... properties>
INLINE_FUNCTION_H span< T > makeSpan (const ViewType1D< T, properties... > &v)
template<typename T , typename... properties>
INLINE_FUNCTION_H span< T > makeSpan (const ViewType1D< T, properties... > &v, uint32 size)
template<typename T , typename... properties>
INLINE_FUNCTION_H iOstream & operator<< (iOstream &os, const ViewType1D< T, properties... > &v)
template<typename T >
INLINE_FUNCTION_H iOstream & operator<< (iOstream &os, const Range< T > &rng)
template<typename T , typename... properties>
INLINE_FUNCTION_H uint32 count (const ViewType1D< T, properties... > &view, uint32 start, uint32 end, const T &val)
template<typename T , typename... properties>
INLINE_FUNCTION_H void fill (ViewType1D< T, properties... > &view, rangeU32 span, T val)
template<typename T , typename... properties>
void fill (ViewType1D< T, properties... > &view, uint32 start, uint32 end, T val)
template<typename T , typename... properties>
void fill (ViewType3D< T, properties... > &view, rangeU32 range1, rangeU32 range2, rangeU32 range3, const T &val)
template<typename T , typename... properties>
void fill (ViewType3D< T, properties... > &view, const T &val)
template<typename Type , typename... properties>
void fillSequence (ViewType1D< Type, properties... > &view, uint32 start, uint32 end, const Type startVal)
template<typename Type , typename... properties, typename indexType , typename... indexProperties>
bool fillSelected (ViewType1D< Type, properties... > view, ViewType1D< indexType, indexProperties... > indices, uint32 numElems, Type val)
template<typename Type , typename... properties, typename indexType , typename... indexProperties>
bool fillSelected (ViewType1D< Type, properties... > view, const ViewType1D< indexType, indexProperties... > indices, const ViewType1D< Type, properties... > vals, const uint32 numElems)
template<typename T , typename... properties>
INLINE_FUNCTION_H T min (const ViewType1D< T, properties... > &view, uint32 start, uint32 end)
template<typename T , typename... properties>
INLINE_FUNCTION_H T max (const ViewType1D< T, properties... > &view, uint32 start, uint32 end)
template<typename dType , typename... dProperties, typename sType , typename... sProperties>
INLINE_FUNCTION_H void copy (const ViewType1D< dType, dProperties... > &dst, const ViewType1D< sType, sProperties... > &src)
template<typename dType , typename... dProperties, typename sType , typename... sProperties>
INLINE_FUNCTION_H void copy (const ViewType1D< dType, dProperties... > &dst, uint32 dStart, const ViewType1D< sType, sProperties... > &src, uint32 sStart, uint32 sEnd)
template<typename Type , typename... sProperties>
INLINE_FUNCTION_H void getNth (Type &dst, const ViewType1D< Type, sProperties... > &src, const uint32 n)
template<typename T , typename... properties>
INLINE_FUNCTION_H void sort (ViewType1D< T, properties... > &view, uint32 start, uint32 end)
template<typename T , typename... properties, typename CompareFunc >
INLINE_FUNCTION_H void sort (ViewType1D< T, properties... > &view, uint32 start, uint32 end, CompareFunc compare)
template<typename Type , typename... properties, typename permType , typename... permProperties>
void permuteSort (const ViewType1D< Type, properties... > &view, uint32 start, uint32 end, ViewType1D< permType, permProperties... > &permuteView, uint32 permStart)
template<typename T >
INLINE_FUNCTION_HD int32 binarySearch_ (const T *array, int32 length, const T &val)
template<typename Type , typename... properties>
INLINE_FUNCTION_HD uint32 binarySearch (const ViewType1D< Type, properties... > &view, uint32 start, uint32 end, const Type &val)
On DEVICE and HOST calls.
template<typename Type , typename... properties, typename... dProperties>
void exclusiveScan (const ViewType1D< Type, properties... > &view, uint32 start, uint32 end, ViewType1D< Type, dProperties... > &dView, uint32 dStart)
template<typename Type , typename... properties, typename... dProperties>
void inclusiveScan (const ViewType1D< Type, properties... > &view, uint32 start, uint32 end, ViewType1D< Type, dProperties... > &dView, uint32 dStart)
MPITimer & ComputationTimer ()
localProcessors & pFlowProcessors ()
void initialize_pFlowProcessors ()
void initialize_pFlowProcessors (const std::vector< int > &ranks)
bool checkMPI (const char *funcName, int error, bool forceAbort, const char *fileName, int lineNumebr)
Map< real, fileSystem > getTimeFolders (const fileSystem &path)
template<class T , class... Args>
uniquePtr< T > makeUnique (Args &&... args)
template<typename T >
uniquePtr< dataIO< T > > createDataIO (const word &runType, const IOPattern &iop)
template<typename T >
bool writeDataAsciiBinary (iOstream &os, span< T > data)
template<typename T >
bool writeDataASCII (iOstream &os, span< T > data)
template<typename T >
bool readDataAscii (iIstream &is, std::vector< T > &vec)
template<typename T >
bool readDataAsciiBinary (iIstream &is, std::vector< T > &data)
template<typename T >
iOstream & operator<< (iOstream &os, const span< T > &s)
iIstream & operator>> (iIstream &is, iIstreamManip f)
operator>> handling for manipulators without arguments
iIstream & operator>> (iIstream &is, IOstreamManip f)
operator>> handling for manipulators without arguments
iIstream & operator>> (iIstream &is, word &w)
iIstream & operator>> (iIstream &is, int64 &val)
iIstream & operator>> (iIstream &is, int32 &val)
iIstream & operator>> (iIstream &is, int8 &val)
iIstream & operator>> (iIstream &is, uint64 &val)
iIstream & operator>> (iIstream &is, uint32 &val)
iIstream & operator>> (iIstream &is, uint8 &val)
iIstream & operator>> (iIstream &is, float &val)
iIstream & operator>> (iIstream &is, double &val)
iIstream & operator>> (iIstream &is, size_t &val)
iOstream & operator<< (iOstream &os, iOstreamManip f)
operator<< handling for manipulators without arguments
iOstream & operator<< (iOstream &os, IOstreamManip f)
operator<< handling for manipulators without arguments
iOstream & indent (iOstream &os)
Indent stream.
iOstream & incrIndent (iOstream &os)
Increment the indent level.
iOstream & decrIndent (iOstream &os)
Decrement the indent level.
iOstream & flush (iOstream &os)
Flush stream.
iOstream & endl (iOstream &os)
Add newline and flush stream.
iOstream & beginBlock (iOstream &os)
Write begin block group without a name.
iOstream & endBlock (iOstream &os)
Write end block group.
iOstream & endEntry (iOstream &os)
Write end entry (';') followed by newline.
iOstream & operator<< (iOstream &os, const char c)
iOstream & operator<< (iOstream &os, const char *buf)
iOstream & operator<< (iOstream &os, const word &w)
iOstream & operator<< (iOstream &os, const int64 &val)
iOstream & operator<< (iOstream &os, const int32 &val)
iOstream & operator<< (iOstream &os, const int8 &val)
iOstream & operator<< (iOstream &os, const uint64 &val)
iOstream & operator<< (iOstream &os, const uint32 &val)
iOstream & operator<< (iOstream &os, const uint8 &val)
iOstream & operator<< (iOstream &os, const float &val)
iOstream & operator<< (iOstream &os, const double &val)
iOstream & operator<< (iOstream &os, const size_t &val)
IOstream & dec (IOstream &io)
IOstream & hex (IOstream &io)
IOstream & oct (IOstream &io)
IOstream & fixed (IOstream &io)
IOstream & scientific (IOstream &io)
iOstream & operator<< (iOstream &os, const token &tok)
iIstream & operator>> (iIstream &is, token &tok)
iOstream & operator<< (iOstream &os, const token::punctuationToken &pt)
std::ostream & operator<< (std::ostream &os, const token::punctuationToken &pt)
std::ostream & operator<< (std::ostream &os, const token &tok)
token endListToken ()
token beginListToken ()
token endStatementToken ()
token beginBlockToken ()
token endBlocKToken ()
token spaceToken ()
token newLineToken ()
template<class OS >
static OS & printTokenInfo (OS &os, const token &tok)
bool validTokenForStream (const token tok)
Is tok a valid token for this stream?
bool isBeginToken (const token &tok)
Is tok a begin token?
bool isEndToken (const token &tok)
Is tok an end token?
FUNCTION_H iIstream & operator>> (iIstream &is, box &b)
FUNCTION_H iOstream & operator<< (iOstream &os, const box &b)
INLINE_FUNCTION_HD bool equal (const box &b1, const box &b2, real tol=smallValue)
INLINE_FUNCTION_HD bool operator== (const box &b1, const box &b2)
INLINE_FUNCTION_HD box extendBox (const box &b, const realx3 &dl)
FUNCTION_H iIstream & operator>> (iIstream &is, cylinder &b)
FUNCTION_H iOstream & operator<< (iOstream &os, const cylinder &b)
INLINE_FUNCTION_HD bool equal (const domain &d1, const domain &d2, real tol=smallValue)
INLINE_FUNCTION_HD bool operator== (const domain &d1, const domain &d2)
FUNCTION_H iIstream & operator>> (iIstream &is, domain &d)
FUNCTION_H iOstream & operator<< (iOstream &os, const domain &d)
template<typename intType >
FUNCTION_H iIstream & operator>> (iIstream &is, iBox< intType > &b)
template<typename intType >
FUNCTION_H iOstream & operator<< (iOstream &os, const iBox< intType > &b)
iOstream & operator<< (iOstream &os, const internalPoints &ip)
uint32IndexContainer getSortedIndices (box boundingBox, real dx, const ViewType1D< realx3 > &pos, const pFlagTypeDevice &flag)
template<typename T >
Vector< T > selectedFieldVals (const pStructSelector &selector, const word &name)
FUNCTION_H iIstream & operator>> (iIstream &is, sphere &b)
FUNCTION_H iOstream & operator<< (iOstream &os, const sphere &b)
template<typename T , size_t nRow, size_t nCol>
array2D< T, nRow, nCol > operator+ (const array2D< T, nRow, nCol > &arr1, const array2D< T, nRow, nCol > &arr2)
template<typename T , size_t nRow, size_t nCol>
array2D< T, nRow, nCol > operator- (const array2D< T, nRow, nCol > &arr1, const array2D< T, nRow, nCol > &arr2)
template<typename T , size_t nRow, size_t nCol>
array2D< T, nRow, nCol > operator* (const array2D< T, nRow, nCol > &arr1, const array2D< T, nRow, nCol > &arr2)
template<typename T , size_t nRow, size_t nCol>
array2D< T, nRow, nCol > operator* (const T &s, const array2D< T, nRow, nCol > &arr2)
template<typename T , size_t nRow, size_t nCol>
array2D< T, nRow, nCol > operator/ (const array2D< T, nRow, nCol > &arr1, const array2D< T, nRow, nCol > &arr2)
template<typename T , size_t nRow, size_t nCol>
array2D< T, nRow, nCol > operator/ (const T &val, const array2D< T, nRow, nCol > &arr2)
template<typename T , size_t nRow, size_t nInner, size_t nCol>
array2D< T, nRow, nCol > MatMul (const array2D< T, nRow, nInner > &A, const array2D< T, nInner, nCol > &B)
template<typename T , size_t nRow, size_t nCol>
array2D< T, nCol, nRow > transpose (const array2D< T, nRow, nCol > &arr)
template<typename T , size_t nRow, size_t nCol>
iOstream & operator<< (iOstream &os, const array2D< T, nRow, nCol > &arr)
iOstream & operator<< (iOstream &os, const Timer &t)
iIstream & operator>> (iIstream &is, Timer &t)
iOstream & operator<< (iOstream &os, const Timers &t)
iIstream & operator>> (iIstream &is, Timers &t)
iOstream & operator<< (iOstream &os, const multiTriSurface &tri)
iOstream & operator<< (iOstream &str, const subSurface &sub)
iIstream & operator>> (iIstream &str, subSurface &sub)
bool convertToTriSurfaceComponents (uint32 basePointIndex, span< realx3x3 > tris, realx3Vector &points, uint32x3Vector &vertices, realVector &area, realx3Vector &normal)
iIstream & operator>> (iIstream &is, triSurface &tri)
iOstream & operator<< (iOstream &os, const triSurface &tri)
const word whiteSpace (" \t\n\v\f\r")
white space
int32 countChar (const word &s, const char c)
Count numer of chars c in a word.
int32 countChar (const char *s, const char c)
Count numer of chars c in a char string.
word toUpper (const word &inStr)
convert a word to all caps
word firstCapital (const word &inStr)
bool isYes (const word &str)
Check if str equals "Yes", "Y", "True", "Ok", "ON", or "T".
bool isNo (const word &str)
Check if str equals "No", "N", "False", or "Off".
word real2Fixed (const real &v, int32 numPrecision=6)
Convert floating point variable to string with fixed number of precisions.
word real2Word (const real &v, int32 numPrecision=6)
Convert floating point variable to string with general format.
word int322Word (const int32 &v)
Convert int32 to word.
word removeDecimalZeros (const word &str)
Remove zeros from decimal part of a string number.
word real2FixedStripZeros (const real &v, int32 numPrecision=6)
Convert to fixed point variable and remove zeros.
word angleBracketsNames (const word &w1, const word &w2)
Output <w1,w2>
word angleBracketsNames2 (const word &base, const word &w1, const word &w2)
Output base<w1,w2>
word angleBracketsNames3 (const word &base, const word &w1, const word &w2, const word &w3)
Output base<w1,sw2,w3>
word groupNames (const word &bw, const word &tw, char sep='.')
Group words and output bw.tw.
word baseName (const word &w, char sep='.')
Find the base in a group separated by "." and return it.
word tailName (const word &w, char sep='.')
Find tail name in a group separated by "." and return it.
bool validWord (char c)
Is the character valid for a word name?
bool validWordWithQuote (char c)
Is c a valid character including quote?
bool validWord (const word &w)
Is a valid word?
bool validWordWithQuote (const word &c)
Is a valid word with qoute?
bool readUint32 (const word &w, uint32 &val)
Convert word to uint32.
bool readUint32 (const char *buf, uint32 &val)
Convert char string to uint32.
bool readInt64 (const word &w, int64 &val)
Convert word to int64.
bool readInt64 (const char *buf, int64 &val)
Convert char string to int64.
bool readInt32 (const word &w, int32 &val)
Convert word to int32.
bool readInt32 (const char *buf, int32 &val)
Convert char string to int32.
bool readInt8 (const word &w, int8 &val)
Convert word to int8.
bool readInt8 (const char *buf, int8 &val)
Convert char string to int8.
bool readReal (const word &w, real &val)
Convert word to real.
bool readReal (const char *buf, real &val)
Convert char string to real.
bool readBoolian_Str (const word &w, bool &val)
Convert word to bool.
bool readBoolian_Str (const char *buf, bool &val)
Convert char string to bool.
bool readValue (const word &w, real &val)
bool readValue (const word &w, uint32 &val)
bool readValue (const word &w, int64 &val)
bool readValue (const word &w, int32 &val)
bool readValue (const word &w, int8 &val)
bool readValue (const word &w, bool &val)
INLINE_FUNCTION_HD bool equal (const real &s1, const real &s2, real tol=smallValue)
INLINE_FUNCTION_HD bool equal (const int64 &s1, const int64 &s2)
INLINE_FUNCTION_HD bool equal (const int32 &s1, const int32 &s2)
INLINE_FUNCTION_HD bool equal (const int8 &s1, const int8 &s2)
INLINE_FUNCTION_HD bool equal (const uint32 &s1, const uint32 &s2)
INLINE_FUNCTION bool equal (const word &s1, const word &s2)
Are two words equal (host only)?
INLINE_FUNCTION_HD real degree2Radian (const real &theta)
Convert degree to radians.
INLINE_FUNCTION_HD real radian2Degree (const real &phi)
Convert radians to degree.
word floatingPointDescription ()
iIstream & operator>> (iIstream &is, Logical &L)
iOstream & operator<< (iOstream &os, const Logical &L)
INLINE_FUNCTION_HD real abs (real x)
INLINE_FUNCTION_HD int64 abs (int64 x)
INLINE_FUNCTION_HD int32 abs (int32 x)
INLINE_FUNCTION_HD real mod (real x, real y)
INLINE_FUNCTION_HD int64 mod (int64 x, int64 y)
INLINE_FUNCTION_HD int32 mod (int32 x, int32 y)
INLINE_FUNCTION_HD int64 mod (uint64 x, uint64 y)
INLINE_FUNCTION_HD auto mod (uint32 x, uint32 y)
INLINE_FUNCTION_HD real remainder (real x, real y)
INLINE_FUNCTION_HD real exp (real x)
INLINE_FUNCTION_HD real log (real x)
INLINE_FUNCTION_HD real log10 (real x)
INLINE_FUNCTION_HD real pow (real x, real y)
INLINE_FUNCTION_HD real sqrt (real x)
INLINE_FUNCTION_HD real cbrt (real x)
INLINE_FUNCTION_HD real sin (real x)
INLINE_FUNCTION_HD real cos (real x)
INLINE_FUNCTION_HD real tan (real x)
INLINE_FUNCTION_HD real asin (real x)
INLINE_FUNCTION_HD real acos (real x)
INLINE_FUNCTION_HD real atan (real x)
INLINE_FUNCTION_HD real atan2 (real y, real x)
INLINE_FUNCTION_HD real sinh (real x)
INLINE_FUNCTION_HD real cosh (real x)
INLINE_FUNCTION_HD real tanh (real x)
INLINE_FUNCTION_HD real asinh (real x)
INLINE_FUNCTION_HD real acosh (real x)
INLINE_FUNCTION_HD real atanh (real x)
INLINE_FUNCTION_HD real min (real x, real y)
INLINE_FUNCTION_HD int64 min (int32 x, int32 y)
INLINE_FUNCTION_HD int64 min (int64 x, int64 y)
INLINE_FUNCTION_HD uint64 min (uint64 x, uint64 y)
INLINE_FUNCTION_HD uint32 min (uint32 x, uint32 y)
INLINE_FUNCTION_HD real max (real x, real y)
INLINE_FUNCTION_HD int64 max (int64 x, int64 y)
INLINE_FUNCTION_HD int32 max (int32 x, int32 y)
INLINE_FUNCTION_HD uint64 max (uint64 x, uint64 y)
INLINE_FUNCTION_HD uint32 max (uint32 x, uint32 y)
template<typename T >
constexpr T largestNegative ()
template<typename T >
constexpr T epsilonValue ()
template<typename T >
constexpr T largestPositive ()
template<typename T >
bool INLINE_FUNCTION_HD equal (const triple< T > &opr1, const triple< T > &opr2)
bool INLINE_FUNCTION_HD equal (const triple< real > &opr1, const triple< real > &opr2, real tol)
template<typename T >
INLINE_FUNCTION_HD triple< T > abs (const triple< T > &v)
template<typename T >
INLINE_FUNCTION_HD triple< T > mod (const triple< T > &arg1, const triple< T > &arg2)
template<typename T >
INLINE_FUNCTION_HD triple< T > exp (const triple< T > &v)
template<typename T >
INLINE_FUNCTION_HD triple< T > log (const triple< T > &v)
template<typename T >
INLINE_FUNCTION_HD triple< T > log10 (const triple< T > &v)
template<typename T >
INLINE_FUNCTION_HD triple< T > pow (const triple< T > &arg1, const triple< T > &arg2)
template<typename T >
INLINE_FUNCTION_HD triple< T > sqrt (const triple< T > &v)
template<typename T >
INLINE_FUNCTION_HD triple< T > cbrt (const triple< T > &v)
template<typename T >
INLINE_FUNCTION_HD triple< T > sin (const triple< T > &v)
template<typename T >
INLINE_FUNCTION_HD triple< T > cos (const triple< T > &v)
template<typename T >
INLINE_FUNCTION_HD triple< T > tan (const triple< T > &v)
template<typename T >
INLINE_FUNCTION_HD triple< T > asin (const triple< T > &v)
template<typename T >
INLINE_FUNCTION_HD triple< T > acos (const triple< T > &v)
template<typename T >
INLINE_FUNCTION_HD triple< T > atan (const triple< T > &v)
template<typename T >
INLINE_FUNCTION_HD triple< T > atan2 (const triple< T > &arg1, const triple< T > &arg2)
template<typename T >
INLINE_FUNCTION_HD triple< T > sinh (const triple< T > &v)
template<typename T >
INLINE_FUNCTION_HD triple< T > cosh (const triple< T > &v)
template<typename T >
INLINE_FUNCTION_HD triple< T > tanh (const triple< T > &v)
template<typename T >
INLINE_FUNCTION_HD triple< T > asinh (const triple< T > &v)
template<typename T >
INLINE_FUNCTION_HD triple< T > acosh (const triple< T > &v)
template<typename T >
INLINE_FUNCTION_HD triple< T > atanh (const triple< T > &v)
template<typename T >
INLINE_FUNCTION_HD triple< T > min (const triple< T > &arg1, const triple< T > &arg2)
template<typename T >
INLINE_FUNCTION_HD triple< T > max (const triple< T > &arg1, const triple< T > &arg2)
template<typename T >
INLINE_FUNCTION_HD triple< T > pow (const triple< T > &t3, T e)
template<typename T >
INLINE_FUNCTION_HD T min (const triple< T > &t3)
template<typename T >
INLINE_FUNCTION_HD T max (const triple< T > &t3)
template<typename T >
word basicTypeName ()
template<>
word basicTypeName< word > ()
template<>
word basicTypeName< int64 > ()
template<>
word basicTypeName< int32 > ()
template<>
word basicTypeName< int8 > ()
template<>
word basicTypeName< uint64 > ()
template<>
word basicTypeName< uint32 > ()
template<>
word basicTypeName< uint8 > ()
template<>
word basicTypeName< real > ()
template<typename T >
word getTypeName ()
template<typename T >
word getTypeName (const T &)
template<typename Type1 , typename Type2 >
bool checkType (Type2 *object)
template<typename Type1 , typename Type2 >
bool checkType (Type2 &object)
bool applySelector (systemControl &control, const pointStructure &pStruct, const dictionary &selDict)
template<typename T >
uniquePtr< rectMeshField_H< T > > sumOp (pointField_H< T > &field, pointRectCell &pointToCell)
template<typename T , typename incMask >
uniquePtr< rectMeshField_H< T > > sumMaksOp (pointField_H< T > &field, pointRectCell &pointToCell, const incMask &mask)
template<typename T >
bool convertRectMeshField (iOstream &os, const rectMeshField_H< T > &field)
template<>
bool convertRectMeshField (iOstream &os, const rectMeshField_H< real > &field)
template<>
bool convertRectMeshField (iOstream &os, const rectMeshField_H< realx3 > &field)
template<>
bool convertRectMeshField (iOstream &os, const rectMeshField_H< int32 > &field)
bool badInput (iIstream &is, token &tok)
bool checkWordToken (iIstream &is, token &tok, const word &check)
bool checkNumberToken (iIstream &is, token &tok, real &val)
bool checkNormalVec (const realx3 &p1, const realx3 &p2, const realx3 &p3, realx3 &norm)
template<typename T >
T byteSwaper (const T &p)
Variables
const uint32 BASE_MIRROR_WALL_INDEX = 1000000
const auto ActivePoint = pointStructure::ACTIVE
const char *const settingsFolder__ = "settings"
const char *const settingsRepository__ = "settings"
const char *const caseSetupFolder__ = "caseSetup"
const char *const caseSetupRepository__ = "caseSetup"
const char *const geometryFolder__ = "geometry"
const char *const geometryRepository_ = "geometry"
const char *const integrationRepository__ = "integration"
const char *const integrationFolder__ = "integration"
const char *const settingsFile__ = "settingsDict"
const char *const domainFile__ = "domainDict"
const char *const insertionFile__ = "particleInsertion"
const char *const shapeFile__ = "shapes"
const char *const pointStructureFile__ = "pStructure"
const char *const triSurfaceFile__ = "triSurface"
const char *const createParticles__ = "createParticles"
const char *const motionModelFile__ = "motionModel"
const char *const contactSearchFile__ = "contactSearch"
const char *const propertyFile__ = "interaction"
const char *const interactionFile__ = "interaction"
const char *const postprocessFile__ = "postprocessDict"
const char *const uniform__ = "uniform"
const char *const nonUniform__ = "nonUniform"
constexpr char tab = '\t'
constexpr char nl = '\n'
Ostream output
masterOstream mOutput
processorOstream pOutput
Istream input
processorOstream errReport
const real zero = 0.0
Zero real variable.
const real one = 1.0
one real variable
const int32 zero32 = 0
zero int32 variable
const int32 one32 = 1
one int32 variable
const word nullWord
null/empty word
const char * floatingPointType__ = "float"
const bool usingDouble__ = false
const int numBytesForReal__ = sizeof(real)
const real Pi = real(3.1415926535897932384626433832)
const real smallValue = 1.0e-15
const real verySmallValue = 1.0e-30
const real largeValue = 1.0e15
const real veryLargeValue = 1.0e30
const int32 largestNegInt32 = largestNegative<int32>()
const int32 largestPosInt32 = largestPositive<int32>()
const int64 largestNegInt64 = largestNegative<int64>()
const int64 largestPosInt64 = largestPositive<int64>()
const real largestNegREAL = largestNegative<real>()
const real largestPosREAL = largestPositive<real>()
const real epsilonREAL = epsilonValue<real>()
const realx3 zero3 (0.0)
const realx3 one3 (1.0)
const realx3x3 zero33 (zero3)
const realx3x3 one33 (one3)
const realx4 zero4 (zero)
Typedef Documentation
vibratingMotionGeometry
using vibratingMotionGeometry = geometryMotion<vibratingMotion>
Definition at line 35 of file geometryMotions.hpp.
rotationAxisMotionGeometry
using rotationAxisMotionGeometry = geometryMotion<rotatingAxisMotion>
Definition at line 37 of file geometryMotions.hpp.
stationaryGeometry
using stationaryGeometry = geometryMotion<stationaryWall>
Definition at line 39 of file geometryMotions.hpp.
conveyorBeltMotionGeometry
using conveyorBeltMotionGeometry = geometryMotion<conveyorBeltMotion>
Definition at line 41 of file geometryMotions.hpp.
rpIntegration
using rpIntegration = Kokkos::RangePolicy< DefaultExecutionSpace, Kokkos::Schedule<Kokkos::Static>, Kokkos::IndexType<uint32> >
Range policy for integration kernel (alias)
Definition at line 34 of file AdamsBashforth2.cpp.
csExecutionSpace
using csExecutionSpace = DefaultExecutionSpace
Definition at line 30 of file contactSearchGlobals.hpp.
csIdType
using csIdType = uint32
Definition at line 32 of file contactSearchGlobals.hpp.
csPairContainerType
using csPairContainerType = unsortedPairs<DefaultExecutionSpace, uint32>
Definition at line 34 of file contactSearchGlobals.hpp.
sphereInsertion
using sphereInsertion = Insertion<sphereShape>
Definition at line 33 of file Insertions.hpp.
grainInsertion
using grainInsertion = Insertion<grainShape>
Definition at line 34 of file Insertions.hpp.
bitset32_D
using bitset32_D = bitsetHD<unsigned>
Definition at line 211 of file bitsetHD.hpp.
bitset32_H
using bitset32_H = bitsetHD<unsigned, HostSpace>
Definition at line 213 of file bitsetHD.hpp.
bitset64_D
using bitset64_D = bitsetHD<unsigned long>
Definition at line 215 of file bitsetHD.hpp.
bitset64_H
using bitset64_H = bitsetHD<unsigned long, HostSpace>
Definition at line 217 of file bitsetHD.hpp.
int8Field_D
using int8Field_D = Field<int8>
Definition at line 33 of file Fields.hpp.
int8Field_H
using int8Field_H = Field<int8, HostSpace>
Definition at line 35 of file Fields.hpp.
int32Field_D
using int32Field_D = Field<int32>
Definition at line 37 of file Fields.hpp.
int32Field_H
using int32Field_H = Field<int32, HostSpace>
Definition at line 39 of file Fields.hpp.
int64Field_D
using int64Field_D = Field<int64>
Definition at line 41 of file Fields.hpp.
int64Field_H
using int64Field_H = Field<int64, HostSpace>
Definition at line 43 of file Fields.hpp.
uint8Field_D
using uint8Field_D = Field<uint8>
Definition at line 45 of file Fields.hpp.
uint8Field_H
using uint8Field_H = Field<uint8, HostSpace>
Definition at line 47 of file Fields.hpp.
uint32Field_D
using uint32Field_D = Field<uint32>
Definition at line 49 of file Fields.hpp.
uint32Field_H
using uint32Field_H = Field<uint32, HostSpace>
Definition at line 51 of file Fields.hpp.
uint64Field_D
using uint64Field_D = Field<uint64>
Definition at line 53 of file Fields.hpp.
uint64Field_H
using uint64Field_H = Field<uint64, HostSpace>
Definition at line 55 of file Fields.hpp.
uint32x3Field_D
using uint32x3Field_D = Field<uint32x3>
Definition at line 57 of file Fields.hpp.
uint32x3Field_H
using uint32x3Field_H = Field<uint32x3, HostSpace>
Definition at line 59 of file Fields.hpp.
realField_D
using realField_D = Field<real>
Definition at line 61 of file Fields.hpp.
realField_H
using realField_H = Field<real, HostSpace>
Definition at line 63 of file Fields.hpp.
realx3Field_D
using realx3Field_D = Field<realx3>
Definition at line 65 of file Fields.hpp.
realx3Field_H
using realx3Field_H = Field<realx3, HostSpace>
Definition at line 67 of file Fields.hpp.
realx3x3Field_D
using realx3x3Field_D = Field<realx3x3>
Definition at line 69 of file Fields.hpp.
realx3x3Field_H
using realx3x3Field_H = Field<realx3x3, HostSpace>
Definition at line 71 of file Fields.hpp.
wordField_H
using wordField_H = Field<word, HostSpace>
Definition at line 74 of file Fields.hpp.
int32IndexContainer
using int32IndexContainer = indexContainer<int32>
Definition at line 283 of file indexContainer.hpp.
int64IndexContainer
using int64IndexContainer = indexContainer<int64>
Definition at line 284 of file indexContainer.hpp.
uint32IndexContainer
using uint32IndexContainer = indexContainer<uint32>
Definition at line 286 of file indexContainer.hpp.
uint64IndexContainer
using uint64IndexContainer = indexContainer<uint64>
Definition at line 287 of file indexContainer.hpp.
int64List
using int64List = List<int64>
Definition at line 218 of file List.hpp.
int32List
using int32List = List<int32>
Definition at line 219 of file List.hpp.
int8List
using int8List = List<int8>
Definition at line 220 of file List.hpp.
uint64List
using uint64List = List<uint64>
Definition at line 221 of file List.hpp.
uint32List
using uint32List = List<uint32>
Definition at line 222 of file List.hpp.
realList
using realList = List<real>
Definition at line 224 of file List.hpp.
realx3List
using realx3List = List<realx3>
Definition at line 225 of file List.hpp.
realx3x3List
using realx3x3List = List<realx3x3>
Definition at line 226 of file List.hpp.
boolList
using boolList = List<bool>
Definition at line 229 of file List.hpp.
wordList
using wordList = List<word>
Definition at line 230 of file List.hpp.
wordHashMap
using wordHashMap = hashMap<word,T>
Definition at line 120 of file hashMap.hpp.
uint64HashMap
using uint64HashMap = hashMap<uint64,T>
Definition at line 123 of file hashMap.hpp.
uint32HashMap
using uint32HashMap = hashMap<uint32,T>
Definition at line 126 of file hashMap.hpp.
int64HashMap
using int64HashMap = hashMap<int64,T>
Definition at line 129 of file hashMap.hpp.
int32HashMap
using int32HashMap = hashMap<int32,T>
Definition at line 132 of file hashMap.hpp.
wordMap
using wordMap = Map<word,T>
Definition at line 138 of file Map.hpp.
uint64Map
using uint64Map = Map<uint64,T>
Definition at line 141 of file Map.hpp.
uint32Map
using uint32Map = Map<uint32,T>
Definition at line 144 of file Map.hpp.
int32Map
using int32Map = Map<int32,T>
Definition at line 147 of file Map.hpp.
int64Map
using int64Map = Map<int64,T>
Definition at line 150 of file Map.hpp.
orderedMapPtr
using orderedMapPtr = MapPtr<std::map, key, T>
Definition at line 226 of file MapPtr.hpp.
hashMapPtr
using hashMapPtr = MapPtr<std::unordered_map , key, T>
Definition at line 230 of file MapPtr.hpp.
wordOrderedMapPtr
using wordOrderedMapPtr = orderedMapPtr<word,T>
Definition at line 233 of file MapPtr.hpp.
wordHashMapPtr
using wordHashMapPtr = hashMapPtr<word,T>
Definition at line 236 of file MapPtr.hpp.
pointField_H
using pointField_H = pointField<T, HostSpace>
Definition at line 33 of file pointFields.hpp.
pointField_D
using pointField_D = pointField<T>
Definition at line 36 of file pointFields.hpp.
uint8PointField_D
using uint8PointField_D = pointField_D<uint8>
Definition at line 40 of file pointFields.hpp.
uint8PointField_H
using uint8PointField_H = pointField_H<uint8>
Definition at line 41 of file pointFields.hpp.
uint32PointField_D
using uint32PointField_D = pointField_D<uint32>
Definition at line 43 of file pointFields.hpp.
uint32PointField_H
using uint32PointField_H = pointField_H<uint32>
Definition at line 44 of file pointFields.hpp.
uint64PointField_D
using uint64PointField_D = pointField_D<uint64>
Definition at line 46 of file pointFields.hpp.
uint64PointField_H
using uint64PointField_H = pointField_H<uint64>
Definition at line 47 of file pointFields.hpp.
realPointField_D
using realPointField_D = pointField_D<real>
Definition at line 49 of file pointFields.hpp.
realPointField_H
using realPointField_H = pointField_H<real>
Definition at line 50 of file pointFields.hpp.
realx3PointField_D
using realx3PointField_D = pointField_D<realx3>
Definition at line 52 of file pointFields.hpp.
realx3PointField_H
using realx3PointField_H = pointField_H<realx3>
Definition at line 53 of file pointFields.hpp.
realx4PointField_D
using realx4PointField_D = pointField_D<realx4>
Definition at line 55 of file pointFields.hpp.
realx4PointField_H
using realx4PointField_H = pointField_H<realx4>
Definition at line 56 of file pointFields.hpp.
wordPointField_H
using wordPointField_H = pointField_H<word>
Definition at line 58 of file pointFields.hpp.
Set
using Set = std::set<Key,std::less<Key>,std::allocator<Key> >
Definition at line 33 of file Set.hpp.
wordSet
using wordSet = Set<word>
Definition at line 35 of file Set.hpp.
realSymArray_D
using realSymArray_D = symArray<real>
Definition at line 27 of file symArrays.hpp.
realSymArray_H
using realSymArray_H = symArray<real, HostSpace>
Definition at line 29 of file symArrays.hpp.
realx3SymArray_D
using realx3SymArray_D = symArray<realx3>
Definition at line 31 of file symArrays.hpp.
realx3SymArray_H
using realx3SymArray_H = symArray<realx3, HostSpace>
Definition at line 33 of file symArrays.hpp.
uint32TriSurfaceField_D
using uint32TriSurfaceField_D = triSurfaceField<uint32>
Definition at line 32 of file triSurfaceFields.hpp.
uint32TriSurfaceField_H
using uint32TriSurfaceField_H = triSurfaceField<uint32, HostSpace>
Definition at line 34 of file triSurfaceFields.hpp.
realTriSurfaceField_D
using realTriSurfaceField_D = triSurfaceField<real>
Definition at line 36 of file triSurfaceFields.hpp.
realTriSurfaceField_H
using realTriSurfaceField_H = triSurfaceField<real, HostSpace>
Definition at line 38 of file triSurfaceFields.hpp.
realx3TriSurfaceField_D
using realx3TriSurfaceField_D = triSurfaceField<realx3>
Definition at line 40 of file triSurfaceFields.hpp.
realx3TriSurfaceField_H
using realx3TriSurfaceField_H = triSurfaceField<realx3, HostSpace>
Definition at line 42 of file triSurfaceFields.hpp.
vecAllocator
using vecAllocator = std::allocator<T>
Definition at line 49 of file stdVectorHelper.hpp.
int8Vector
using int8Vector = Vector<int8>
Definition at line 32 of file Vectors.hpp.
int32Vector
using int32Vector = Vector<int32>
Definition at line 34 of file Vectors.hpp.
int64Vector
using int64Vector = Vector<int64>
Definition at line 36 of file Vectors.hpp.
uint8Vector
using uint8Vector = Vector<uint8>
Definition at line 38 of file Vectors.hpp.
uint32Vector
using uint32Vector = Vector<uint32>
Definition at line 40 of file Vectors.hpp.
uint64Vector
using uint64Vector = Vector<uint64>
Definition at line 42 of file Vectors.hpp.
uint32x3Vector
using uint32x3Vector = Vector<uint32x3>
Definition at line 44 of file Vectors.hpp.
realVector
using realVector = Vector<real>
Definition at line 46 of file Vectors.hpp.
realx3Vector
using realx3Vector = Vector<realx3>
Definition at line 48 of file Vectors.hpp.
realx3x3Vector
using realx3x3Vector = Vector<realx3x3>
Definition at line 50 of file Vectors.hpp.
wordVector
using wordVector = Vector<word>
Definition at line 52 of file Vectors.hpp.
int8Vector_HD
using int8Vector_HD = VectorDual<int8>
Definition at line 31 of file VectorDuals.hpp.
int16Vector_HD
using int16Vector_HD = VectorDual<int16>
Definition at line 33 of file VectorDuals.hpp.
int32Vector_HD
using int32Vector_HD = VectorDual<int32>
Definition at line 35 of file VectorDuals.hpp.
int64Vector_HD
using int64Vector_HD = VectorDual<int64>
Definition at line 37 of file VectorDuals.hpp.
uint32Vector_HD
using uint32Vector_HD = VectorDual<uint32>
Definition at line 39 of file VectorDuals.hpp.
labelVector_HD
using labelVector_HD = VectorDual<label>
Definition at line 41 of file VectorDuals.hpp.
realVector_HD
using realVector_HD = VectorDual<real>
Definition at line 43 of file VectorDuals.hpp.
realx3Vector_HD
using realx3Vector_HD = VectorDual<realx3>
Definition at line 45 of file VectorDuals.hpp.
realx3x3Vector_HD
using realx3x3Vector_HD = VectorDual<realx3x3>
Definition at line 47 of file VectorDuals.hpp.
int8Vector_D
typedef VectorSingle<int8> int8Vector_D
Definition at line 33 of file VectorSingles.hpp.
int8Vector_H
typedef VectorSingle<int8, HostSpace> int8Vector_H
Definition at line 35 of file VectorSingles.hpp.
int32Vector_D
typedef VectorSingle<int32> int32Vector_D
Definition at line 37 of file VectorSingles.hpp.
int32Vector_H
typedef VectorSingle<int32, HostSpace> int32Vector_H
Definition at line 39 of file VectorSingles.hpp.
int64Vector_D
typedef VectorSingle<int64> int64Vector_D
Definition at line 41 of file VectorSingles.hpp.
int64Vector_H
typedef VectorSingle<int64, HostSpace> int64Vector_H
Definition at line 43 of file VectorSingles.hpp.
uint8Vector_D
typedef VectorSingle<uint8> uint8Vector_D
Definition at line 45 of file VectorSingles.hpp.
uint8Vector_H
typedef VectorSingle<uint8, HostSpace> uint8Vector_H
Definition at line 47 of file VectorSingles.hpp.
uint32Vector_D
typedef VectorSingle<uint32> uint32Vector_D
Definition at line 49 of file VectorSingles.hpp.
uint32Vector_H
typedef VectorSingle<uint32, HostSpace> uint32Vector_H
Definition at line 51 of file VectorSingles.hpp.
uint64Vector_D
typedef VectorSingle<uint64> uint64Vector_D
Definition at line 53 of file VectorSingles.hpp.
uint64Vector_H
typedef VectorSingle<uint64, HostSpace> uint64Vector_H
Definition at line 55 of file VectorSingles.hpp.
realVector_D
typedef VectorSingle<real> realVector_D
Definition at line 57 of file VectorSingles.hpp.
realVector_H
typedef VectorSingle<real, HostSpace> realVector_H
Definition at line 59 of file VectorSingles.hpp.
realx3Vector_D
typedef VectorSingle<realx3> realx3Vector_D
Definition at line 61 of file VectorSingles.hpp.
realx3Vector_H
typedef VectorSingle<realx3, HostSpace> realx3Vector_H
Definition at line 63 of file VectorSingles.hpp.
int32x3Vector_D
typedef VectorSingle<int32x3> int32x3Vector_D
Definition at line 65 of file VectorSingles.hpp.
int32x3Vector_H
typedef VectorSingle<int32x3, HostSpace> int32x3Vector_H
Definition at line 67 of file VectorSingles.hpp.
int64x3Vector_D
typedef VectorSingle<int64x3> int64x3Vector_D
Definition at line 69 of file VectorSingles.hpp.
int64x3Vector_H
typedef VectorSingle<int64x3, HostSpace> int64x3Vector_H
Definition at line 71 of file VectorSingles.hpp.
uint32x3Vector_D
typedef VectorSingle<uint32x3> uint32x3Vector_D
Definition at line 73 of file VectorSingles.hpp.
uint32x3Vector_H
typedef VectorSingle<uint32x3, HostSpace> uint32x3Vector_H
Definition at line 75 of file VectorSingles.hpp.
realx3x3Vector_D
typedef VectorSingle<realx3x3> realx3x3Vector_D
Definition at line 77 of file VectorSingles.hpp.
realx3x3Vector_H
typedef VectorSingle<realx3x3, HostSpace> realx3x3Vector_H
Definition at line 79 of file VectorSingles.hpp.
wordVector_H
typedef VectorSingle<word, HostSpace> wordVector_H
Definition at line 81 of file VectorSingles.hpp.
fileSystemList
using fileSystemList = List<fileSystem>
Definition at line 217 of file fileSystem.hpp.
HostSpace
using HostSpace = Kokkos::HostSpace
Host memory space.
Definition at line 41 of file KokkosTypes.hpp.
Serial
using Serial = Kokkos::Serial
Serial execution space.
Definition at line 44 of file KokkosTypes.hpp.
DefaultHostExecutionSpace
using DefaultHostExecutionSpace = Kokkos::DefaultHostExecutionSpace
Default Host execution space, on top of all host execution spaces.
Definition at line 57 of file KokkosTypes.hpp.
DefaultExecutionSpace
using DefaultExecutionSpace = Kokkos::DefaultExecutionSpace
Default execution space, it can be device exe.
space, if a device space is activated.
Definition at line 61 of file KokkosTypes.hpp.
deviceRPolicyStatic
using deviceRPolicyStatic = Kokkos::RangePolicy< Kokkos::DefaultExecutionSpace, Kokkos::Schedule<Kokkos::Static>, Kokkos::IndexType<pFlow::uint32> >
Definition at line 66 of file KokkosTypes.hpp.
hostRPolicyStatic
using hostRPolicyStatic = Kokkos::RangePolicy< Kokkos::DefaultExecutionSpace, Kokkos::Schedule<Kokkos::Static>, Kokkos::IndexType<pFlow::uint32> >
Definition at line 71 of file KokkosTypes.hpp.
deviceRPolicyDynamic
using deviceRPolicyDynamic = Kokkos::RangePolicy< Kokkos::DefaultExecutionSpace, Kokkos::Schedule<Kokkos::Dynamic>, Kokkos::IndexType<pFlow::uint32> >
Definition at line 76 of file KokkosTypes.hpp.
hostRPolicyDynamic
using hostRPolicyDynamic = Kokkos::RangePolicy< Kokkos::DefaultExecutionSpace, Kokkos::Schedule<Kokkos::Dynamic>, Kokkos::IndexType<pFlow::uint32> >
Definition at line 81 of file KokkosTypes.hpp.
Pair
using Pair = Kokkos::pair<T1, T2>
Pair of two variables.
Definition at line 85 of file KokkosTypes.hpp.
ViewTypeScalar
using ViewTypeScalar = Kokkos::View<T, properties...>
View for a scalar.
Definition at line 89 of file KokkosTypes.hpp.
ViewType1D
using ViewType1D = Kokkos::View<T*, properties...>
1D veiw as a vector
Definition at line 93 of file KokkosTypes.hpp.
ViewType2D
using ViewType2D = Kokkos::View<T**, properties...>
2D view as an array
Definition at line 97 of file KokkosTypes.hpp.
ViewType3D
using ViewType3D = Kokkos::View<T***, properties...>
3D view as an array
Definition at line 101 of file KokkosTypes.hpp.
DualViewType1D
using DualViewType1D = Kokkos::DualView<T*, properties...>
1D dual view as a vector
Definition at line 105 of file KokkosTypes.hpp.
unorderedMap
using unorderedMap = Kokkos::UnorderedMap<Key, Value, properties...>
unordered map
Definition at line 109 of file KokkosTypes.hpp.
unorderedSet
using unorderedSet = Kokkos::UnorderedMap<Key, void, properties...>
unordered set
Definition at line 113 of file KokkosTypes.hpp.
deviceViewTypeScalar
using deviceViewTypeScalar = Kokkos::View<T>
Scalar on device.
Definition at line 117 of file KokkosTypes.hpp.
deviceViewType1D
using deviceViewType1D = Kokkos::View<T*>
1D array (vector) with default device (memory space and execution space)
Definition at line 121 of file KokkosTypes.hpp.
deviceViewType2D
using deviceViewType2D = Kokkos::View<T**, Layout, void>
2D view on device as an array on device
Definition at line 125 of file KokkosTypes.hpp.
deviceViewType3D
using deviceViewType3D = Kokkos::View<T***, Layout, void>
3D view on device as an array on device
Definition at line 129 of file KokkosTypes.hpp.
hostViewTypeScalar
using hostViewTypeScalar = Kokkos::View<T, Kokkos::HostSpace>
Definition at line 132 of file KokkosTypes.hpp.
hostViewType1D
using hostViewType1D = Kokkos::View<T*, Kokkos::HostSpace>
1D array (vector with host memeory space)
Definition at line 136 of file KokkosTypes.hpp.
hostViewType2D
using hostViewType2D = Kokkos::View<T**, Layout, Kokkos::HostSpace>
2D array on host
Definition at line 140 of file KokkosTypes.hpp.
hostViewType3D
using hostViewType3D = Kokkos::View<T***, Layout, Kokkos::HostSpace>
3D array on host
Definition at line 144 of file KokkosTypes.hpp.
deviceAtomicViewType1D
using deviceAtomicViewType1D = Kokkos::View< T*, Kokkos::MemoryTraits< std::is_same_v<DefaultExecutionSpace, Serial> ? 0 : Kokkos::Atomic> >
1D vector on device with atomic capabilities
Definition at line 151 of file KokkosTypes.hpp.
deviceAtomicViewType3D
using deviceAtomicViewType3D = Kokkos::View< T***, Kokkos::MemoryTraits< std::is_same_v<DefaultExecutionSpace, Serial> ? 0 : Kokkos::Atomic> >
3D array on device with atomic capabilities
Definition at line 158 of file KokkosTypes.hpp.
range32
using range32 = Range<int32>
Definition at line 139 of file Range.hpp.
range64
using range64 = Range<int64>
Definition at line 141 of file Range.hpp.
rangeU32
using rangeU32 = Range<uint32>
Definition at line 143 of file Range.hpp.
rangeU64
using rangeU64 = Range<uint64>
Definition at line 145 of file Range.hpp.
uniformRandomRealDistribution
typedef RandomReal<uniformRandomReal> uniformRandomRealDistribution
Definition at line 30 of file randomReals.hpp.
int32StridedRagne
using int32StridedRagne = stridedRange<int32>
Definition at line 31 of file ranges.hpp.
int64StridedRange
using int64StridedRange = stridedRange<int64>
Definition at line 32 of file ranges.hpp.
realStridedRange
using realStridedRange = stridedRange<real>
Definition at line 33 of file ranges.hpp.
int32IntervalRange
using int32IntervalRange = intervalRange<int32>
Definition at line 35 of file ranges.hpp.
int64IntervalRange
using int64IntervalRange = intervalRange<int64>
Definition at line 36 of file ranges.hpp.
realIntervalRange
using realIntervalRange = intervalRange<real>
Definition at line 37 of file ranges.hpp.
int32CombinedRange
using int32CombinedRange = combinedRange<int32>
Definition at line 39 of file ranges.hpp.
int64CombinedRange
using int64CombinedRange = combinedRange<int64>
Definition at line 40 of file ranges.hpp.
realCombinedRange
using realCombinedRange = combinedRange<real>
Definition at line 41 of file ranges.hpp.
iIstreamManip
typedef iIstream&(* iIstreamManip) (iIstream &)
Definition at line 228 of file iIstream.hpp.
iOstreamManip
typedef iOstream&(* iOstreamManip) (iOstream &)
An iOstream manipulator.
Definition at line 293 of file iOstream.hpp.
IOstreamManip
typedef IOstream&(* IOstreamManip) (IOstream &)
An IOstream manipulator.
Definition at line 308 of file IOstream.hpp.
tokenList
using tokenList = List<token>
Definition at line 31 of file tokenList.hpp.
tokenTypeList
using tokenTypeList = List<token::tokenType>
Definition at line 32 of file tokenList.hpp.
deviceScatteredFieldAccess
using deviceScatteredFieldAccess = scatteredFieldAccess<T, typename DefaultExecutionSpace::memory_space>
Definition at line 166 of file scatteredFieldAccess.hpp.
hostScatteredFieldAccess
using hostScatteredFieldAccess = scatteredFieldAccess<T,HostSpace>
Definition at line 170 of file scatteredFieldAccess.hpp.
boxRegion
using boxRegion = geometricRegion<box>
Definition at line 32 of file geometricRegions.hpp.
sphereRegion
using sphereRegion = geometricRegion<sphere>
Definition at line 34 of file geometricRegions.hpp.
cylinderRegion
using cylinderRegion = geometricRegion<cylinder>
Definition at line 36 of file geometricRegions.hpp.
pFlagTypeDevice
using pFlagTypeDevice = pointFlag<DefaultExecutionSpace>
Definition at line 387 of file pointFlag.hpp.
pFlagTypeHost
using pFlagTypeHost = pointFlag<DefaultHostExecutionSpace>
Definition at line 389 of file pointFlag.hpp.
subSurfaceList
using subSurfaceList = List<subSurface>
Definition at line 107 of file subSurface.hpp.
real
using real = float
Definition at line 45 of file builtinTypes.hpp.
int8
using int8 = signed char
Definition at line 48 of file builtinTypes.hpp.
int32
using int32 = int
Definition at line 50 of file builtinTypes.hpp.
int64
using int64 = long long int
Definition at line 52 of file builtinTypes.hpp.
uint8
using uint8 = unsigned char
Definition at line 54 of file builtinTypes.hpp.
uint32
using uint32 = unsigned int
Definition at line 56 of file builtinTypes.hpp.
uint64
using uint64 = unsigned long long int
Definition at line 58 of file builtinTypes.hpp.
id_t
using id_t = uint32
Definition at line 60 of file builtinTypes.hpp.
size_t
using size_t = std::size_t
Definition at line 62 of file builtinTypes.hpp.
word
using word = std::string
Definition at line 64 of file builtinTypes.hpp.
int8x3
using int8x3 = triple<int8>
Definition at line 37 of file types.hpp.
int32x3
using int32x3 = triple<int32>
Definition at line 38 of file types.hpp.
int64x3
using int64x3 = triple<int64>
Definition at line 39 of file types.hpp.
uint8x3
using uint8x3 = triple<uint8>
Definition at line 40 of file types.hpp.
uint32x3
using uint32x3 = triple<uint32>
Definition at line 41 of file types.hpp.
uint64x3
using uint64x3 = triple<uint64>
Definition at line 42 of file types.hpp.
realx3
using realx3 = triple<real>
Definition at line 43 of file types.hpp.
int32x3x3
using int32x3x3 = triple<int32x3>
Definition at line 45 of file types.hpp.
uint32x3x3
using uint32x3x3 = triple<uint32x3>
Definition at line 46 of file types.hpp.
realx3x3
using realx3x3 = triple<realx3>
Definition at line 47 of file types.hpp.
realx4
using realx4 = quadruple<real>
Definition at line 49 of file types.hpp.
realx4x3
using realx4x3 = quadruple<realx3>
Definition at line 51 of file types.hpp.
rectMeshField_H
using rectMeshField_H = rectMeshField<T>
Definition at line 30 of file rectMeshFields.hpp.
int8RectMeshField_H
using int8RectMeshField_H = rectMeshField<int8>
Definition at line 32 of file rectMeshFields.hpp.
int32RectMeshField_H
using int32RectMeshField_H = rectMeshField<int32>
Definition at line 34 of file rectMeshFields.hpp.
int64RectMeshField_H
using int64RectMeshField_H = rectMeshField<int64>
Definition at line 36 of file rectMeshFields.hpp.
realRectMeshField_H
using realRectMeshField_H = rectMeshField<real>
Definition at line 38 of file rectMeshFields.hpp.
realx3RectMeshField_H
using realx3RectMeshField_H = rectMeshField<realx3>
Definition at line 40 of file rectMeshFields.hpp.
Enumeration Type Documentation
DataDirection
enum DataDirection strong
Enumerator
MasterToSlave
SlaveToMaster
TwoWay
Definition at line 34 of file boundaryField.hpp.
Function Documentation
intAllActive()
bool pFlow::intAllActive (real dt, realx3Field_D & y, realx3PointField_D & dy, realx3PointField_D & dy1)
Definition at line 36 of file AdamsBashforth2.cpp.
References pointField< T, MemorySpace >::activeRange(), internalField< T, MemorySpace >::deviceView(), VectorSingle< T, MemorySpace >::deviceView(), and LAMBDA_HD.
Referenced by AdamsBashforth2::correct(), and AdamsBashforth2::correctPStruct().
intScattered()
bool pFlow::intScattered (real dt, realx3Field_D & y, realx3PointField_D & dy, realx3PointField_D & dy1)
Definition at line 61 of file AdamsBashforth2.cpp.
References internalField< T, MemorySpace >::activePointsMaskDevice(), pointField< T, MemorySpace >::activeRange(), internalField< T, MemorySpace >::deviceView(), VectorSingle< T, MemorySpace >::deviceView(), and LAMBDA_HD.
Referenced by AdamsBashforth2::correct(), and AdamsBashforth2::correctPStruct().
operator>>() [1/41]
INLINE_FUNCTION iIstream& pFlow::operator>> (iIstream & str, AB3History & ab3)
Definition at line 41 of file AdamsBashforth3.hpp.
References IOstream::check(), AB3History::dy1_, AB3History::dy2_, FUNCTION_NAME, iIstream::readBegin(), and iIstream::readEnd().
operator<<() [1/58]
INLINE_FUNCTION iOstream& pFlow::operator<< (iOstream & str, const AB3History & ab3)
Definition at line 57 of file AdamsBashforth3.hpp.
References token::BEGIN_LIST, IOstream::check(), AB3History::dy1_, AB3History::dy2_, token::END_LIST, FUNCTION_NAME, and token::SPACE.
operator>>() [2/41]
INLINE_FUNCTION iIstream& pFlow::operator>> (iIstream & str, AB4History & ab4)
Definition at line 43 of file AdamsBashforth4.hpp.
References IOstream::check(), AB4History::dy1_, AB4History::dy2_, AB4History::dy3_, FUNCTION_NAME, iIstream::readBegin(), and iIstream::readEnd().
operator<<() [2/58]
INLINE_FUNCTION iOstream& pFlow::operator<< (iOstream & str, const AB4History & ab4)
Definition at line 60 of file AdamsBashforth4.hpp.
References token::BEGIN_LIST, IOstream::check(), AB4History::dy1_, AB4History::dy2_, AB4History::dy3_, token::END_LIST, FUNCTION_NAME, and token::SPACE.
operator>>() [3/41]
INLINE_FUNCTION iIstream& pFlow::operator>> (iIstream & str, AB5History & ab5)
Definition at line 43 of file AdamsBashforth5.hpp.
References IOstream::check(), AB5History::dy1_, AB5History::dy2_, AB5History::dy3_, AB5History::dy4_, FUNCTION_NAME, iIstream::readBegin(), and iIstream::readEnd().
operator<<() [3/58]
INLINE_FUNCTION iOstream& pFlow::operator<< (iOstream & str, const AB5History & ab5)
Definition at line 61 of file AdamsBashforth5.hpp.
References token::BEGIN_LIST, IOstream::check(), AB5History::dy1_, AB5History::dy2_, AB5History::dy3_, AB5History::dy4_, token::END_LIST, FUNCTION_NAME, and token::SPACE.
splitBy3()
INLINE_FUNCTION_HD uint64_t splitBy3 (const uint64_t val)
Definition at line 31 of file contactSearchFunctions.hpp.
Referenced by xyzToMortonCode64().
xyzToMortonCode64()
INLINE_FUNCTION_HD uint64_t xyzToMortonCode64 (uint64_t x, uint64_t y, uint64_t z)
Definition at line 42 of file contactSearchFunctions.hpp.
References splitBy3().
getThirdBits()
INLINE_FUNCTION_HD uint64_t getThirdBits (uint64_t x)
Definition at line 49 of file contactSearchFunctions.hpp.
Referenced by mortonCode64Toxyz().
mortonCode64Toxyz()
INLINE_FUNCTION_HD void mortonCode64Toxyz (uint64_t morton, uint64_t & x, uint64_t & y, uint64_t & z)
Definition at line 62 of file contactSearchFunctions.hpp.
References getThirdBits().
indexToCell() [1/2]
INLINE_FUNCTION_HD void pFlow::indexToCell (const indexType idx, const triple< cellIndexType > & extent, triple< cellIndexType > & cell)
Definition at line 71 of file contactSearchFunctions.hpp.
References triple< T >::x(), triple< T >::y(), and triple< T >::z().
Referenced by cellsWallLevel0::findPairsElementRangeCount(), and indexToCell().
boxExtent()
INLINE_FUNCTION_HD triple<cellIndexType> pFlow::boxExtent (const iBox< cellIndexType > & box)
Definition at line 82 of file contactSearchFunctions.hpp.
References box::maxPoint(), box::minPoint(), triple< T >::x(), triple< T >::y(), and triple< T >::z().
Referenced by cellsWallLevel0::findPairsElementRangeCount(), and indexToCell().
indexToCell() [2/2]
INLINE_FUNCTION_HD void pFlow::indexToCell (const indexType idx, const iBox< cellIndexType > & box, triple< cellIndexType > & cell)
Definition at line 92 of file contactSearchFunctions.hpp.
References boxExtent(), indexToCell(), and box::minPoint().
operator<<() [4/58]
iOstream& pFlow::operator<< (iOstream & os, const conveyorBelt & obj) inline
Definition at line 93 of file conveyorBelt.hpp.
operator>>() [4/41]
iIstream& pFlow::operator>> (iIstream & is, conveyorBelt & obj) inline
Definition at line 99 of file conveyorBelt.hpp.
operator<<() [5/58]
iOstream& pFlow::operator<< (iOstream & os, const rotatingAxis & ax) inline
Definition at line 154 of file rotatingAxis.hpp.
References fatalExit, and rotatingAxis::write().
operator>>() [5/41]
iIstream& pFlow::operator>> (iIstream & is, rotatingAxis & ax) inline
Definition at line 163 of file rotatingAxis.hpp.
References fatalExit, and rotatingAxis::read().
rotate() [1/4]
INLINE_FUNCTION_HD pFlow::realx3 rotate (const realx3 & p, const line & ln, real theta)
Definition at line 74 of file rotatingAxisI.hpp.
References cos(), line::point1(), sin(), line::unitVector(), triple< T >::x(), triple< T >::x_, triple< T >::y(), triple< T >::y_, triple< T >::z(), and triple< T >::z_.
Referenced by rotatingAxis::transferPoint(), and multiRotatingAxis::transferPoint().
rotate() [2/4]
INLINE_FUNCTION_HD pFlow::realx3 rotate (const realx3 & p, const rotatingAxis & ax, real dt)
Definition at line 39 of file rotatingAxisI.hpp.
References cos(), timeInterval::inTimeRange(), rotatingAxis::omega(), line::point1(), sin(), line::unitVector(), triple< T >::x(), triple< T >::x_, triple< T >::y(), triple< T >::y_, triple< T >::z(), and triple< T >::z_.
rotate() [3/4]
INLINE_FUNCTION_HD void rotate (realx3 * p, uint32 n, const line & ln, real theta)
Definition at line 107 of file rotatingAxisI.hpp.
References cos(), n, line::point1(), sin(), line::unitVector(), triple< T >::x(), triple< T >::x_, triple< T >::y(), triple< T >::y_, triple< T >::z(), and triple< T >::z_.
rotate() [4/4]
INLINE_FUNCTION_HD void rotate (realx3 * p, uint32 n, const rotatingAxis & ax, real dt)
Definition at line 143 of file rotatingAxisI.hpp.
References cos(), timeInterval::inTimeRange(), n, rotatingAxis::omega(), line::point1(), sin(), line::unitVector(), triple< T >::x(), triple< T >::x_, triple< T >::y(), triple< T >::y_, triple< T >::z(), and triple< T >::z_.
operator<<() [6/58]
iOstream& pFlow::operator<< (iOstream & os, const stationary & obj) inline
Definition at line 89 of file stationary.hpp.
operator>>() [6/41]
iIstream& pFlow::operator>> (iIstream & is, stationary & obj) inline
Definition at line 95 of file stationary.hpp.
operator<<() [7/58]
iOstream& pFlow::operator<< (iOstream & os, const timeInterval & obj) inline
Definition at line 96 of file timeInterval.hpp.
References fatalExit, and timeInterval::write().
operator>>() [7/41]
iIstream& pFlow::operator>> (iIstream & is, timeInterval & obj) inline
Definition at line 105 of file timeInterval.hpp.
References fatalExit, and timeInterval::read().
operator<<() [8/58]
iOstream& pFlow::operator<< (iOstream & os, const vibrating & obj) inline
Definition at line 147 of file vibrating.hpp.
References fatalExit, and vibrating::write().
operator>>() [8/41]
iIstream& pFlow::operator>> (iIstream & is, vibrating & obj) inline
Definition at line 156 of file vibrating.hpp.
References fatalExit, and vibrating::read().
setOneEntry()
bool pFlow::setOneEntry (const twoPartEntry & tpEntry, anyList & varList)
Definition at line 32 of file insertionRegion.cpp.
References anyList::emplaceBack(), twoPartEntry::firstPart(), twoPartEntry::keyword(), and twoPartEntry::secondPartVal().
readOneEtrty()
bool pFlow::readOneEtrty (const dataEntry & entry, anyList & varList)
Definition at line 44 of file insertionRegion.cpp.
References endl(), fatalErrorInFunction, and twoPartEntry::firstPart().
Referenced by insertionRegion::readSetFieldDict().
operator>>() [9/41]
iIstream& pFlow::operator>> (iIstream & is, Field< T, MemorySpace > & ifld) inline
Definition at line 214 of file Field.hpp.
References fatalExit, ioErrorInFile, IOstream::lineNumber(), IOPattern::MasterProcessorOnly, IOstream::name(), and Field< T, MemorySpace >::read().
operator<<() [9/58]
iOstream& pFlow::operator<< (iOstream & os, const Field< T, MemorySpace > & ofld) inline
Definition at line 225 of file Field.hpp.
References IOPattern::AllProcessorsDifferent, fatalExit, ioErrorInFile, IOstream::lineNumber(), IOstream::name(), and Field< T, MemorySpace >::write().
operator<<() [10/58]
iOstream& pFlow::operator<< (iOstream & os, const List< T > & lst)
operator>>() [10/41]
iIstream& pFlow::operator>> (iIstream & is, List< T > & lst)
printKeys() [1/11]
iOstream& pFlow::printKeys (iOstream & os, const wordHashMap< T > & m) inline
Referenced by randomReal::create(), boundarySphereParticles::create(), boundaryGrainParticles::create(), peakableRegion::create(), particleIdHandler::create(), boundaryIntegration::create(), pStructSelector::create(), interaction::create(), includeMask::create(), boundaryContactSearch::create(), Wall::create(), positionParticles::create(), dataIO< T >::create(), integration::create(), processField::create(), boundarySphereInteraction< contactForceModel, geometryMotionModel >::create(), boundaryGrainInteraction< contactForceModel, geometryMotionModel >::create(), boundaryField< T, void >::create(), simulationDomain::create(), contactSearch::create(), geometry::create(), and boundaryBase::create().
printKeys() [2/11]
iOstream& pFlow::printKeys (iOstream & os, const uint64HashMap< T > & m) inline
printKeys() [3/11]
iOstream& pFlow::printKeys (iOstream & os, const uint32HashMap< T > & m) inline
printKeys() [4/11]
iOstream& pFlow::printKeys (iOstream & os, const int64HashMap< T > & m) inline
printKeys() [5/11]
iOstream& pFlow::printKeys (iOstream & os, const int32HashMap< T > & m) inline
printKeys() [6/11]
iOstream& pFlow::printKeys (iOstream & os, const wordMap< T > & m) inline
printKeys() [7/11]
iOstream& pFlow::printKeys (iOstream & os, const uint64Map< T > & m) inline
printKeys() [8/11]
iOstream& pFlow::printKeys (iOstream & os, const uint32Map< T > & m) inline
printKeys() [9/11]
iOstream& pFlow::printKeys (iOstream & os, const int32Map< T > & m) inline
printKeys() [10/11]
iOstream& pFlow::printKeys (iOstream & os, const int64Map< T > & m) inline
printKeys() [11/11]
iOstream & printKeys (iOstream & os, const wordHashMapPtr< T > & m) inline
Definition at line 240 of file MapPtr.hpp.
References endl(), and m.
operator<<() [11/58]
iOstream& pFlow::operator<< (iOstream & os, const internalField< T, MemorySpace > & ifeild) inline
Definition at line 210 of file internalField.hpp.
References IOPattern::AllProcessorsDifferent, fatalExit, ioErrorInFile, IOstream::lineNumber(), and IOstream::name().
min() [1/15]
T pFlow::min (const internalField< T, MemorySpace > & iField) inline
Definition at line 28 of file internalFieldAlgorithms.hpp.
References internalField< T, MemorySpace >::activePointsMaskDevice(), internalField< T, MemorySpace >::activePointsMaskHost(), pointFlag< ExecutionSpace >::activeRange(), internalField< T, MemorySpace >::field(), and LAMBDA_HD.
Referenced by cells::bound(), cylinder::calculateParams(), collisionCheck::checkPoint(), cells::extendBox(), dictionary::getValMin(), dictionary::getValOrSetMin(), indexContainer< IndexType >::indexContainer(), VectorDual< multiRotatingAxis >::insertSetElement(), max(), min(), min_serial(), sphereShape::minBoundingSphere(), grainShape::minBoundingSphere(), sortedContactList< valueType, executionSpace, idType >::operator()(), pFlow::pointStructureKernels::scanPointFlag(), selectorStridedRange::selectorStridedRange(), and indexContainer< IndexType >::syncViews().
max() [1/15]
T pFlow::max (const internalField< T, MemorySpace > & iField) inline
Definition at line 79 of file internalFieldAlgorithms.hpp.
References internalField< T, MemorySpace >::activePointsMaskDevice(), internalField< T, MemorySpace >::activePointsMaskHost(), pointFlag< ExecutionSpace >::activeRange(), internalField< T, MemorySpace >::field(), and LAMBDA_HD.
Referenced by geometry::afterIteration(), Timer::averageTime(), cells::bound(), wallBoundaryContactSearch::broadSearch(), ppwBndryContactSearch::broadSearchPP(), cells::calculate(), cylinder::calculateParams(), collisionCheck::checkPoint(), cells::extendBox(), dictionary::getValMax(), dictionary::getValOrSetMax(), indexContainer< IndexType >::indexContainer(), regularParticleIdHandler::initialIdCheck(), VectorDual< multiRotatingAxis >::insertSetElement(), max(), max_serial(), maxActive(), maxActive_serial(), maxActiveD(), maxActiveH(), sphereShape::maxBoundingSphere(), grainShape::maxBoundingSphere(), sortedContactList< valueType, executionSpace, idType >::operator()(), cellsWallLevel0::particleWallFindPairs(), positionRandom::positionRandom(), pFlow::pointStructureKernels::scanPointFlag(), selectorStridedRange::selectorStridedRange(), and indexContainer< IndexType >::syncViews().
minMax()
Pair<T,T> pFlow::minMax (const internalField< T, MemorySpace > & iField) inline
Definition at line 132 of file internalFieldAlgorithms.hpp.
References internalField< T, MemorySpace >::activePointsMaskDevice(), internalField< T, MemorySpace >::activePointsMaskHost(), pointFlag< ExecutionSpace >::activeRange(), internalField< T, MemorySpace >::field(), and LAMBDA_HD.
Referenced by grainParticles::initializeParticles(), and sphereParticles::initializeParticles().
fillSequence() [1/4]
void pFlow::fillSequence (internalField< T, MemorySpace > & iField, const T & startVal) inline
Definition at line 198 of file internalFieldAlgorithms.hpp.
References internalField< T, MemorySpace >::activePointsMaskDevice(), internalField< T, MemorySpace >::activePointsMaskHost(), pointFlag< ExecutionSpace >::activeRange(), exclusiveScan(), internalField< T, MemorySpace >::field(), and LAMBDA_HD.
Referenced by fillSequence(), particleIdHandler::hearChanges(), indexContainer< IndexType >::indexContainer(), and regularParticleIdHandler::initialIdCheck().
operator<<() [12/58]
iOstream& pFlow::operator<< (iOstream & os, const pointField< T, MemorySpace > & pF)
Definition at line 175 of file pointField.hpp.
References IOPattern::AllProcessorsDifferent, fatalExit, ioErrorInFile, IOstream::lineNumber(), IOstream::name(), and pointField< T, MemorySpace >::write().
operator>>() [11/41]
iIstream& pFlow::operator>> (iIstream & is, pointField< VectorField, T, MemorySpace > & pF)
Definition at line 166 of file pointField_old.hpp.
References fatalExit, ioErrorInFile, IOstream::lineNumber(), and IOstream::name().
operator<<() [13/58]
iOstream& pFlow::operator<< (iOstream & os, const pointField< VectorField, T, MemorySpace > & pF)
Definition at line 179 of file pointField_old.hpp.
References fatalExit, ioErrorInFile, IOstream::lineNumber(), and IOstream::name().
maxActive_serial()
T pFlow::maxActive_serial (const Kokkos::View< T *, properties... > & view, const Kokkos::View< int8 *, Kokkos::LayoutLeft, Kokkos::HostSpace > & flag, size_t start, size_t end)
Definition at line 28 of file pointFieldAlgorithms.hpp.
References ActivePoint, and max().
Referenced by maxActive().
maxActiveH()
INLINE_FUNCTION_H T pFlow::maxActiveH (const Kokkos::View< T *, properties... > & view, const Kokkos::View< int8 *, Kokkos::LayoutLeft, Kokkos::HostSpace > & flag, size_t start, size_t end)
Definition at line 46 of file pointFieldAlgorithms.hpp.
References ActivePoint, LAMBDA_HD, and max().
Referenced by maxActive().
maxActiveD()
INLINE_FUNCTION_H T pFlow::maxActiveD (const Kokkos::View< T *, properties... > & view, const Kokkos::View< int8 *, Kokkos::LayoutLeft > & flag, size_t start, size_t end)
Definition at line 74 of file pointFieldAlgorithms.hpp.
References ActivePoint, LAMBDA_HD, and max().
Referenced by maxActive().
maxActive() [1/2]
T pFlow::maxActive (const pointField< VectorSingle, T, MemorySpace > & pField)
Definition at line 99 of file pointFieldAlgorithms.hpp.
References pointField< T, MemorySpace >::allActive(), internalField< T, void >::deviceViewAll(), max(), maxActive_serial(), maxActiveD(), maxActiveH(), pointField< T, MemorySpace >::pointFlag(), internalField< T, void >::size(), and sizeToSerial__.
maxActive() [2/2]
T pFlow::maxActive (const pointField< VectorDual, T, MemorySpace > & pField)
Definition at line 139 of file pointFieldAlgorithms.hpp.
References pointField< T, MemorySpace >::allActive(), internalField< T, void >::deviceViewAll(), max(), maxActive_serial(), maxActiveD(), maxActiveH(), pointField< T, MemorySpace >::pointFlag(), internalField< T, void >::size(), and sizeToSerial__.
charSpan() [1/2]
span<char> pFlow::charSpan (span< T > s) inline
Definition at line 177 of file span.hpp.
References span< T >::data(), and span< T >::size().
Referenced by regularSimulationDomain::initialTransferBlockData(), simulationDomain::initialTransferBlockData(), and writeDataAsciiBinary().
charSpan() [2/2]
span<const char> pFlow::charSpan (span< const T > s) inline
Definition at line 187 of file span.hpp.
References span< T >::data(), and span< T >::size().
SWAP()
INLINE_FUNCTION_HD void pFlow::SWAP (Type & x, Type & y)
Definition at line 37 of file symArrayHD.hpp.
Referenced by symArray< nonLinearProperties >::operator()().
operator>>() [12/41]
iIstream& pFlow::operator>> (iIstream & is, symArray< T, MemorySpace > & iArr) inline
Definition at line 251 of file symArrayHD.hpp.
References fatalExit, ioErrorInFile, IOstream::lineNumber(), IOstream::name(), and symArray< T, MemorySpace >::read().
operator<<() [14/58]
iOstream& pFlow::operator<< (iOstream & os, const symArray< T, MemorySpace > & oArr) inline
Definition at line 262 of file symArrayHD.hpp.
References fatalExit, ioErrorInFile, IOstream::lineNumber(), IOstream::name(), and symArray< T, MemorySpace >::write().
makeSpan() [1/6]
span<T> pFlow::makeSpan (std::vector< T > & container) inline
Definition at line 53 of file stdVectorHelper.hpp.
Referenced by writeStdVector().
makeSpan() [2/6]
span<T> pFlow::makeSpan (const std::vector< T > & container) inline
Definition at line 60 of file stdVectorHelper.hpp.
writeSpan() [1/2]
bool pFlow::writeSpan (iOstream & os, span< T > sp) inline
Definition at line 70 of file stdVectorHelper.hpp.
References writeDataAsciiBinary().
Referenced by VectorSingle< uint32, HostSpace >::write(), and writeStdVector().
writeSpan() [2/2]
bool pFlow::writeSpan (iOstream & os, span< T > sp, const IOPattern & iop) inline
Definition at line 79 of file stdVectorHelper.hpp.
References dataIO< T >::create(), and fatalErrorInFunction.
writeStdVector() [1/2]
bool pFlow::writeStdVector (iOstream & os, const std::vector< T, Allocator > & vec)
Definition at line 103 of file stdVectorHelper.hpp.
References makeSpan(), and writeSpan().
Referenced by operator<<(), and Vector< word >::write().
writeStdVector() [2/2]
bool pFlow::writeStdVector (iOstream & os, const std::vector< T, Allocator > & vec, const IOPattern & iop)
Definition at line 114 of file stdVectorHelper.hpp.
References makeSpan(), and writeSpan().
readStdVector() [1/2]
bool pFlow::readStdVector (iIstream & is, std::vector< T, Allocator > & vec)
Definition at line 126 of file stdVectorHelper.hpp.
References readDataAsciiBinary().
Referenced by operator>>(), Vector< word >::read(), and VectorSingle< uint32, HostSpace >::read().
readStdVector() [2/2]
bool pFlow::readStdVector (iIstream & is, std::vector< T, Allocator > & vec, const IOPattern & iop)
Definition at line 138 of file stdVectorHelper.hpp.
References dataIO< T >::create(), and fatalErrorInFunction.
operator<<() [15/58]
iOstream& pFlow::operator<< (iOstream & os, const std::vector< T, Allocator > & vec)
Definition at line 162 of file stdVectorHelper.hpp.
References fatalErrorInFunction, fatalExit, and writeStdVector().
operator>>() [13/41]
iIstream& pFlow::operator>> (iIstream & is, std::vector< T, Allocator > & vec)
Always assume ASCII is in the input stream.
Definition at line 174 of file stdVectorHelper.hpp.
References fatalErrorInFunction, fatalExit, and readStdVector().
operator>>() [14/41]
iIstream& pFlow::operator>> (iIstream & is, Vector< T, Allocator > & ivec) inline
Definition at line 352 of file Vector.hpp.
References fatalExit, ioErrorInFile, IOstream::lineNumber(), IOstream::name(), and Vector< T, Allocator >::read().
operator<<() [16/58]
iOstream& pFlow::operator<< (iOstream & os, const Vector< T, Allocator > & ovec) inline
Definition at line 363 of file Vector.hpp.
References fatalExit, ioErrorInFile, IOstream::lineNumber(), IOstream::name(), and Vector< T, Allocator >::write().
count() [1/5]
auto pFlow::count (const Vector< T, Allocator > & vec, const T & val) inline
Definition at line 26 of file VectorAlgorithm.hpp.
References count().
Referenced by count(), Istream::getLine(), Timer::pause(), countFields::process(), Istream::read(), masterOstream::write(), Ostream::write(), and processorOstream::write().
count_if()
auto pFlow::count_if (const Vector< T, Allocator > & vec, UnaryPredicate p) inline
Definition at line 32 of file VectorAlgorithm.hpp.
References count_if().
fill_n()
void pFlow::fill_n (Vector< T, Allocator > & vec, size_t n, const T & val) inline
Definition at line 38 of file VectorAlgorithm.hpp.
References fill_n(), and n.
fill() [1/6]
void pFlow::fill (Vector< T, Allocator > & vec, const T & val) inline
Definition at line 44 of file VectorAlgorithm.hpp.
References fill().
Referenced by boundariesMask< 6 >::boundariesMask(), collisionCheck::build(), fill(), rectMeshField< int32 >::fill(), VectorSingle< uint32, HostSpace >::fill(), shapeMixture::getNextShapeName(), ppwBndryContactSearch::nullifyHead(), cellMapper::nullifyHead(), mapperNBS::nullifyHead(), ppwBndryContactSearch::nullifyNext(), cellMapper::nullifyNext(), mapperNBS::nullifyNext(), pointFlag< DefaultHostExecutionSpace >::pointFlag(), and pointFlag< DefaultHostExecutionSpace >::resetFlags().
fillSequence() [2/4]
void pFlow::fillSequence (Vector< T, Allocator > & vec, int32 start, int32 end, const T & startVal) inline
Definition at line 50 of file VectorAlgorithm.hpp.
fillSequence() [3/4]
void pFlow::fillSequence (Vector< T, Allocator > & vec, const T & startVal) inline
Definition at line 56 of file VectorAlgorithm.hpp.
References fillSequence(), and Vector< T, Allocator >::size().
sort() [1/3]
void pFlow::sort (Vector< T, Allocator > & vec) inline
Definition at line 62 of file VectorAlgorithm.hpp.
References sort().
Referenced by sortedPairs< executionSpace, idType >::prepareSorted().
find()
int64 pFlow::find (Vector< T, Allocator > & vec, const T & val) inline
Definition at line 69 of file VectorAlgorithm.hpp.
References ForAll.
Referenced by convertToTriSurfaceComponents(), List< std::any >::find(), List< std::any >::findi(), hashMap< void * >::findIf(), Map< pFlow::IOobject * >::findIf(), MapPtr< pFlow::iEntry >::search(), List< std::any >::search(), MapPtr< pFlow::iEntry >::set(), and subscriber::unsubscribe().
abs() [1/6]
Vector<T, Allocator> pFlow::abs (const Vector< T, Allocator > & v) inline
Definition at line 84 of file VectorMath.hpp.
Referenced by timeControl::checkForOutputToFile(), equal(), timeControl::finalTime(), cellsWallLevel0::findPairsElementRangeCount(), pFlow::grnTriInteraction::isGrainInContactBothSides(), stridedRange< int32 >::isMember(), pFlow::sphTriInteraction::isSphereInContactBothSides(), zAxis::makeTransMatrix(), timeControl::reachedStopAt(), real2Word(), pFlow::triangle::surface(), and Timer::write().
abs() [2/6]
Vector<T, Allocator> pFlow::abs (const Vector< T, Allocator > & v, indexFunc iFn) inline
Definition at line 84 of file VectorMath.hpp.
mod() [1/8]
Vector<T, Allocator> pFlow::mod (const Vector< T, Allocator > & v1, const Vector< T, Allocator > & v2) inline
Definition at line 85 of file VectorMath.hpp.
mod() [2/8]
Vector<T, Allocator> pFlow::mod (const Vector< T, Allocator > & v1, const Vector< T, Allocator > & v2, indexFunc iFn) inline
Definition at line 85 of file VectorMath.hpp.
exp() [1/4]
Vector<T, Allocator> pFlow::exp (const Vector< T, Allocator > & v) inline
Definition at line 86 of file VectorMath.hpp.
Referenced by cGRelativeLinear< limited >::contactForce(), and cGAbsoluteLinear< limited >::contactForce().
exp() [2/4]
Vector<T, Allocator> pFlow::exp (const Vector< T, Allocator > & v, indexFunc iFn) inline
Definition at line 86 of file VectorMath.hpp.
log() [1/4]
Vector<T, Allocator> pFlow::log (const Vector< T, Allocator > & v) inline
Definition at line 87 of file VectorMath.hpp.
Referenced by cGRelativeLinear< limited >::contactForce(), cGAbsoluteLinear< limited >::contactForce(), linear< limited >::readLinearDictionary(), cGAbsoluteLinear< limited >::readLinearDictionary(), cGRelativeLinear< limited >::readLinearDictionary(), and nonLinear< limited >::readNonLinearDictionary().
log() [2/4]
Vector<T, Allocator> pFlow::log (const Vector< T, Allocator > & v, indexFunc iFn) inline
Definition at line 87 of file VectorMath.hpp.
log10() [1/4]
Vector<T, Allocator> pFlow::log10 (const Vector< T, Allocator > & v) inline
Definition at line 88 of file VectorMath.hpp.
log10() [2/4]
Vector<T, Allocator> pFlow::log10 (const Vector< T, Allocator > & v, indexFunc iFn) inline
Definition at line 88 of file VectorMath.hpp.
pow() [1/7]
Vector<T, Allocator> pFlow::pow (const Vector< T, Allocator > & v1, const Vector< T, Allocator > & v2) inline
Definition at line 89 of file VectorMath.hpp.
Referenced by timeControl::checkForOutputToFile(), nonLinearMod< limited >::contactForce(), nonLinear< limited >::contactForce(), linear< limited >::contactForce(), cGRelativeLinear< limited >::contactForce(), cGAbsoluteLinear< limited >::contactForce(), sphereShape::Inertia(), grainShape::Inertia(), sphereShape::mass(), grainShape::mass(), pow(), linear< limited >::readLinearDictionary(), cGAbsoluteLinear< limited >::readLinearDictionary(), cGRelativeLinear< limited >::readLinearDictionary(), and nonLinear< limited >::readNonLinearDictionary().
pow() [2/7]
Vector<T, Allocator> pFlow::pow (const Vector< T, Allocator > & v1, const Vector< T, Allocator > & v2, indexFunc iFn) inline
Definition at line 89 of file VectorMath.hpp.
sqrt() [1/4]
Vector<T, Allocator> pFlow::sqrt (const Vector< T, Allocator > & v) inline
Definition at line 90 of file VectorMath.hpp.
Referenced by cylinder::calculateParams(), nonLinearMod< limited >::contactForce(), nonLinear< limited >::contactForce(), linear< limited >::contactForce(), cGRelativeLinear< limited >::contactForce(), cGAbsoluteLinear< limited >::contactForce(), symArray< nonLinearProperties >::getN(), quadruple< T >::length(), triple< intType >::length(), sphere::radius(), cylinder::radius(), linear< limited >::readLinearDictionary(), cGAbsoluteLinear< limited >::readLinearDictionary(), cGRelativeLinear< limited >::readLinearDictionary(), nonLinear< limited >::readNonLinearDictionary(), sphere::write(), and cylinder::write().
sqrt() [2/4]
Vector<T, Allocator> pFlow::sqrt (const Vector< T, Allocator > & v, indexFunc iFn) inline
Definition at line 90 of file VectorMath.hpp.
cbrt() [1/4]
Vector<T, Allocator> pFlow::cbrt (const Vector< T, Allocator > & v) inline
Definition at line 91 of file VectorMath.hpp.
cbrt() [2/4]
Vector<T, Allocator> pFlow::cbrt (const Vector< T, Allocator > & v, indexFunc iFn) inline
Definition at line 91 of file VectorMath.hpp.
sin() [1/4]
Vector<T, Allocator> pFlow::sin (const Vector< T, Allocator > & v) inline
Definition at line 92 of file VectorMath.hpp.
Referenced by vibrating::calculateVelocity(), cylinderWall::createCylinder(), and rotate().
sin() [2/4]
Vector<T, Allocator> pFlow::sin (const Vector< T, Allocator > & v, indexFunc iFn) inline
Definition at line 92 of file VectorMath.hpp.
cos() [1/4]
Vector<T, Allocator> pFlow::cos (const Vector< T, Allocator > & v) inline
Definition at line 93 of file VectorMath.hpp.
Referenced by cylinderWall::createCylinder(), and rotate().
cos() [2/4]
Vector<T, Allocator> pFlow::cos (const Vector< T, Allocator > & v, indexFunc iFn) inline
Definition at line 93 of file VectorMath.hpp.
tan() [1/4]
Vector<T, Allocator> pFlow::tan (const Vector< T, Allocator > & v) inline
Definition at line 94 of file VectorMath.hpp.
tan() [2/4]
Vector<T, Allocator> pFlow::tan (const Vector< T, Allocator > & v, indexFunc iFn) inline
Definition at line 94 of file VectorMath.hpp.
asin() [1/4]
Vector<T, Allocator> pFlow::asin (const Vector< T, Allocator > & v) inline
Definition at line 95 of file VectorMath.hpp.
asin() [2/4]
Vector<T, Allocator> pFlow::asin (const Vector< T, Allocator > & v, indexFunc iFn) inline
Definition at line 95 of file VectorMath.hpp.
acos() [1/4]
Vector<T, Allocator> pFlow::acos (const Vector< T, Allocator > & v) inline
Definition at line 96 of file VectorMath.hpp.
acos() [2/4]
Vector<T, Allocator> pFlow::acos (const Vector< T, Allocator > & v, indexFunc iFn) inline
Definition at line 96 of file VectorMath.hpp.
atan() [1/4]
Vector<T, Allocator> pFlow::atan (const Vector< T, Allocator > & v) inline
Definition at line 97 of file VectorMath.hpp.
atan() [2/4]
Vector<T, Allocator> pFlow::atan (const Vector< T, Allocator > & v, indexFunc iFn) inline
Definition at line 97 of file VectorMath.hpp.
atan2() [1/4]
Vector<T, Allocator> pFlow::atan2 (const Vector< T, Allocator > & v1, const Vector< T, Allocator > & v2) inline
Definition at line 98 of file VectorMath.hpp.
atan2() [2/4]
Vector<T, Allocator> pFlow::atan2 (const Vector< T, Allocator > & v1, const Vector< T, Allocator > & v2, indexFunc iFn) inline
Definition at line 98 of file VectorMath.hpp.
sinh() [1/4]
Vector<T, Allocator> pFlow::sinh (const Vector< T, Allocator > & v) inline
Definition at line 99 of file VectorMath.hpp.
sinh() [2/4]
Vector<T, Allocator> pFlow::sinh (const Vector< T, Allocator > & v, indexFunc iFn) inline
Definition at line 99 of file VectorMath.hpp.
cosh() [1/4]
Vector<T, Allocator> pFlow::cosh (const Vector< T, Allocator > & v) inline
Definition at line 100 of file VectorMath.hpp.
cosh() [2/4]
Vector<T, Allocator> pFlow::cosh (const Vector< T, Allocator > & v, indexFunc iFn) inline
Definition at line 100 of file VectorMath.hpp.
tanh() [1/4]
Vector<T, Allocator> pFlow::tanh (const Vector< T, Allocator > & v) inline
Definition at line 101 of file VectorMath.hpp.
tanh() [2/4]
Vector<T, Allocator> pFlow::tanh (const Vector< T, Allocator > & v, indexFunc iFn) inline
Definition at line 101 of file VectorMath.hpp.
asinh() [1/4]
Vector<T, Allocator> pFlow::asinh (const Vector< T, Allocator > & v) inline
Definition at line 102 of file VectorMath.hpp.
asinh() [2/4]
Vector<T, Allocator> pFlow::asinh (const Vector< T, Allocator > & v, indexFunc iFn) inline
Definition at line 102 of file VectorMath.hpp.
acosh() [1/4]
Vector<T, Allocator> pFlow::acosh (const Vector< T, Allocator > & v) inline
Definition at line 103 of file VectorMath.hpp.
acosh() [2/4]
Vector<T, Allocator> pFlow::acosh (const Vector< T, Allocator > & v, indexFunc iFn) inline
Definition at line 103 of file VectorMath.hpp.
atanh() [1/4]
Vector<T, Allocator> pFlow::atanh (const Vector< T, Allocator > & v) inline
Definition at line 104 of file VectorMath.hpp.
atanh() [2/4]
Vector<T, Allocator> pFlow::atanh (const Vector< T, Allocator > & v, indexFunc iFn) inline
Definition at line 104 of file VectorMath.hpp.
pow() [3/7]
Vector<T, Allocator> pFlow::pow (const Vector< T, Allocator > & v, T e) inline
Definition at line 116 of file VectorMath.hpp.
References Vector< T, Allocator >::capacity(), Vector< T, Allocator >::name(), and pow().
pow() [4/7]
Vector<T,Allocator> pFlow::pow (const Vector< T, Allocator > & v, T e, indexFunc iFn) inline
Definition at line 127 of file VectorMath.hpp.
References Vector< T, Allocator >::capacity(), Vector< T, Allocator >::name(), pow(), and Vector< T, Allocator >::size().
min() [2/15]
T pFlow::min (const Vector< T, Allocator > & v) inline
Definition at line 145 of file VectorMath.hpp.
References min().
min() [3/15]
T pFlow::min (const Vector< T, Allocator > & v, indexFunc iFn) inline
Definition at line 156 of file VectorMath.hpp.
References min(), and Vector< T, Allocator >::size().
max() [2/15]
T pFlow::max (const Vector< T, Allocator > & v) inline
Definition at line 171 of file VectorMath.hpp.
References max().
max() [3/15]
T pFlow::max (const Vector< T, Allocator > & v, indexFunc iFn) inline
Definition at line 182 of file VectorMath.hpp.
References max(), and Vector< T, Allocator >::size().
sum() [1/2]
T pFlow::sum (const Vector< T, Allocator > & v) inline
Definition at line 197 of file VectorMath.hpp.
Referenced by MatMul(), and shapeMixture::totalInserted().
sum() [2/2]
T pFlow::sum (const Vector< T, Allocator > & v, indexFunc iFn) inline
Definition at line 208 of file VectorMath.hpp.
References Vector< T, Allocator >::size().
operator>>() [15/41]
iIstream& pFlow::operator>> (iIstream & is, VectorDual< T, memory_space > & ivec) inline
Definition at line 977 of file VectorDual.hpp.
References fatalExit, ioErrorInFile, IOstream::lineNumber(), IOstream::name(), and VectorDual< T, MemorySpace >::read().
operator<<() [17/58]
iOstream& pFlow::operator<< (iOstream & os, const VectorDual< T, memory_space > & ovec) inline
Definition at line 988 of file VectorDual.hpp.
References fatalExit, ioErrorInFile, IOstream::lineNumber(), IOstream::name(), and VectorDual< T, MemorySpace >::write().
count() [2/5]
INLINE_FUNCTION_H int64 pFlow::count (const VectorDual< T, MemorySpace > & vec, const T & val)
Definition at line 38 of file VectorDualAlgorithms.hpp.
References count(), VectorDual< T, MemorySpace >::deviceViewAll(), VectorDual< T, MemorySpace >::hostViewAll(), and VectorDual< T, MemorySpace >::size().
count() [3/5]
INLINE_FUNCTION_H int64 pFlow::count (const VectorDual< T, MemorySpace > & vec, const T & val)
Definition at line 55 of file VectorDualAlgorithms.hpp.
min() [4/15]
INLINE_FUNCTION_H int64 pFlow::min (const VectorDual< T, MemorySpace > & vec)
Definition at line 62 of file VectorDualAlgorithms.hpp.
References VectorDual< T, MemorySpace >::deviceViewAll(), VectorDual< T, MemorySpace >::hostViewAll(), min(), and VectorDual< T, MemorySpace >::size().
min() [5/15]
INLINE_FUNCTION_H int64 pFlow::min (const VectorDual< T, MemorySpace > & vec)
Definition at line 79 of file VectorDualAlgorithms.hpp.
max() [4/15]
INLINE_FUNCTION_H int64 pFlow::max (const VectorDual< T, MemorySpace > & vec)
Definition at line 86 of file VectorDualAlgorithms.hpp.
References VectorDual< T, MemorySpace >::deviceViewAll(), VectorDual< T, MemorySpace >::hostViewAll(), max(), and VectorDual< T, MemorySpace >::size().
max() [5/15]
INLINE_FUNCTION_H int64 pFlow::max (const VectorDual< T, MemorySpace > & vec)
Definition at line 103 of file VectorDualAlgorithms.hpp.
operator>>() [16/41]
iIstream& pFlow::operator>> (iIstream & is, VectorSingle< T, MemorySpace > & ivec) inline
Definition at line 477 of file VectorSingle.hpp.
References fatalExit, ioErrorInFile, IOstream::lineNumber(), IOstream::name(), and VectorSingle< T, MemorySpace >::read().
operator<<() [18/58]
iOstream& pFlow::operator<< (iOstream & os, const VectorSingle< T, MemorySpace > & ovec) inline
Definition at line 488 of file VectorSingle.hpp.
References fatalExit, ioErrorInFile, IOstream::lineNumber(), IOstream::name(), and VectorSingle< T, MemorySpace >::write().
count() [4/5]
INLINE_FUNCTION_H size_t pFlow::count (const VectorSingle< T, MemorySpace > & vec, const T & val)
Definition at line 29 of file VectorSingleAlgorithms.hpp.
References count(), VectorSingle< T, MemorySpace >::deviceViewAll(), and VectorSingle< T, MemorySpace >::size().
min() [6/15]
INLINE_FUNCTION_H T pFlow::min (const VectorSingle< T, MemorySpace > & vec)
Definition at line 35 of file VectorSingleAlgorithms.hpp.
References VectorSingle< T, MemorySpace >::deviceViewAll(), min(), and VectorSingle< T, MemorySpace >::size().
max() [6/15]
INLINE_FUNCTION_H T pFlow::max (const VectorSingle< T, MemorySpace > & vec)
Definition at line 44 of file VectorSingleAlgorithms.hpp.
References VectorSingle< T, MemorySpace >::deviceViewAll(), min(), and VectorSingle< T, MemorySpace >::size().
operator>>() [17/41]
iIstream& pFlow::operator>> (iIstream & is, VectorSingle< word, HostSpace > & ivec) inline
Definition at line 492 of file wordVectorHost.hpp.
References fatalExit, ioErrorInFile, IOstream::lineNumber(), IOstream::name(), and VectorSingle< word, HostSpace >::read().
operator<<() [19/58]
iOstream& pFlow::operator<< (iOstream & os, const VectorSingle< word, HostSpace > & ovec) inline
Definition at line 502 of file wordVectorHost.hpp.
References fatalExit, ioErrorInFile, IOstream::lineNumber(), IOstream::name(), and VectorSingle< word, HostSpace >::write().
operator<<() [20/58]
pFlow::iOstream & operator<< (iOstream & os, const iEntry & e)
Definition at line 164 of file iEntry.cpp.
References fatalExit, ioErrorInFile, IOstream::lineNumber(), IOstream::name(), and iEntry::write().
operator>>() [18/41]
pFlow::iIstream & operator>> (iIstream & is, iEntry & e)
Definition at line 175 of file iEntry.cpp.
References fatalExit, ioErrorInFile, IOstream::lineNumber(), IOstream::name(), and iEntry::read().
isTwoPartEntry()
bool isTwoPartEntry (pFlow::dataEntry entry)
Definition at line 56 of file twoPartEntry.cpp.
References twoPartEntry::secondPart(), and iTstream::size().
Referenced by countField::getFieldType(), and processField::getFieldType().
operator<<() [21/58]
iOstream& pFlow::operator<< (iOstream & os, const message & msg) inline
Definition at line 204 of file message.hpp.
References endl(), message::equivalentTo(), and message::size().
operator+() [1/3]
message pFlow::operator+ (message::EVENT evnt1, message::EVENT evnt2) inline
Definition at line 216 of file message.hpp.
References message::add(), and message::Empty().
operator<<() [22/58]
pFlow::iOstream & operator<< (iOstream & os, const fileSystem & fs)
Definition at line 311 of file fileSystem.cpp.
References fileSystem::path_.
operator<<() [23/58]
std::ostream & operator<< (std::ostream & os, const fileSystem & fs)
Definition at line 317 of file fileSystem.cpp.
References fileSystem::path_.
operator/() [1/4]
pFlow::fileSystem operator/ (const fileSystem & fs1, const fileSystem & fs2)
Definition at line 280 of file fileSystem.cpp.
References fileSystem::dirPath(), and fileSystem::path_.
operator/() [2/4]
pFlow::fileSystem operator/ (const fileSystem & fs1, const word & dir2)
Definition at line 292 of file fileSystem.cpp.
operator+() [2/3]
pFlow::fileSystem operator+ (const fileSystem & fs1, const word fName)
Definition at line 301 of file fileSystem.cpp.
CWD()
fileSystem pFlow::CWD () inline
Free function to reture current working directory.
Definition at line 221 of file fileSystem.hpp.
References fileSystem::CWD().
Referenced by IOfileHeader::dummyOutStream(), and main().
isDirectory()
bool isDirectory (const fileSystem & path)
Free function to check if the path is dir path.
Definition at line 324 of file fileSystem.cpp.
References fileSystem::path().
Referenced by containingFiles(), and subDirectories().
isRegularFile()
bool isRegularFile (const fileSystem & path)
free function to check if the path is regular file
Definition at line 331 of file fileSystem.cpp.
References fileSystem::path().
subDirectories()
pFlow::fileSystemList subDirectories (const fileSystem & path)
A list of sub-directories that exist in path.
Definition at line 337 of file fileSystem.cpp.
References isDirectory(), and fileSystem::path().
Referenced by getTimeFolders().
containingFiles()
pFlow::fileSystemList containingFiles (const fileSystem & path)
A list of file paths that exist in the path.
Definition at line 359 of file fileSystem.cpp.
References isDirectory(), and fileSystem::path().
Referenced by pFlow::PFtoVTK::convertTimeFolderPointFields(), pFlow::PFtoVTK::convertTimeFolderPointFieldsSelected(), pFlow::TSFtoVTK::convertTimeFolderTriSurfaceFieldsSeparate(), and pFlow::TSFtoVTK::convertTimeFolderTriSurfaceFieldsSingle().
min() [7/15]
INLINE_FUNCTION_H T pFlow::min (const ViewType1D< T, properties... > & view, size_t start, size_t end)
Definition at line 61 of file baseAlgorithms_.hpp.
References LAMBDA_HD, and min().
max() [7/15]
INLINE_FUNCTION_H T pFlow::max (const ViewType1D< T, properties... > & view, size_t start, size_t end)
Definition at line 82 of file baseAlgorithms_.hpp.
References LAMBDA_HD, and max().
min_serial()
INLINE_FUNCTION_H T pFlow::min_serial (const ViewType1D< T, properties... > & view, size_t start, size_t end)
Definition at line 103 of file baseAlgorithms_.hpp.
References min().
max_serial()
INLINE_FUNCTION_H T pFlow::max_serial (const ViewType1D< T, properties... > & view, size_t start, size_t end)
Definition at line 115 of file baseAlgorithms_.hpp.
References max().
apply_to_each()
void pFlow::apply_to_each (const ViewType1D< T, properties... > & view, size_t start, size_t end, UnaryFunction func)
Definition at line 127 of file baseAlgorithms_.hpp.
References LAMBDA_HD.
insertSetElementH() [1/2]
void pFlow::insertSetElementH (ViewType1D< T, properties... > & view, hostViewType1D< label > & selected, T val)
Definition at line 145 of file baseAlgorithms_.hpp.
insertSetElementH() [2/2]
void pFlow::insertSetElementH (ViewType1D< T, properties... > & view, hostViewType1D< label > & selected, hostViewType1D< T > & vals)
Definition at line 159 of file baseAlgorithms_.hpp.
insertSetElementD() [1/2]
void pFlow::insertSetElementD (ViewType1D< T, properties... > & view, deviceViewType1D< label > & selected, T val)
Definition at line 173 of file baseAlgorithms_.hpp.
References LAMBDA_D.
insertSetElementD() [2/2]
void pFlow::insertSetElementD (ViewType1D< T, properties... > & view, deviceViewType1D< label > & selected, deviceViewType1D< T > & vals)
Definition at line 194 of file baseAlgorithms_.hpp.
References LAMBDA_D.
fill() [2/6]
void pFlow::fill (ViewType3D< T, properties... > & view, range range1, range range2, range range3, T val)
Definition at line 215 of file baseAlgorithms_.hpp.
isHostAccessible()
INLINE_FUNCTION_H constexpr bool pFlow::isHostAccessible () constexpr
Definition at line 35 of file KokkosUtilities.hpp.
isDeviceAccessible()
INLINE_FUNCTION_H constexpr bool pFlow::isDeviceAccessible () constexpr
Definition at line 41 of file KokkosUtilities.hpp.
areAccessible()
INLINE_FUNCTION_H constexpr bool pFlow::areAccessible () constexpr
Is MemoerySpace accessible from ExecutionSpace.
Definition at line 50 of file KokkosUtilities.hpp.
Referenced by exclusiveScan(), fillSelected(), inclusiveScan(), and permuteSort().
reallocInit() [1/3]
INLINE_FUNCTION_H void pFlow::reallocInit (ViewType1D< Type, Properties... > & view, uint32 len)
Definition at line 57 of file KokkosUtilities.hpp.
reallocNoInit() [1/3]
INLINE_FUNCTION_H void pFlow::reallocNoInit (ViewType1D< Type, Properties... > & view, uint32 len)
Definition at line 64 of file KokkosUtilities.hpp.
Referenced by sortedContactList< valueType, executionSpace, idType >::adjustCapacity(), unsortedContactList< valueType, executionSpace, idType >::adjustCapacity(), wallBoundaryContactSearch::allocateArrays(), cellsWallLevel0::allocateArrays(), ppwBndryContactSearch::checkAllocateNext(), cellMapper::checkAllocateNext(), mapperNBS::checkAllocateNext(), sortedPairs< executionSpace, idType >::prepareSorted(), VectorSingle< uint32, HostSpace >::reallocateCapacitySize(), and reallocFill().
reallocFill() [1/3]
INLINE_FUNCTION_H void pFlow::reallocFill (ViewType1D< Type, Properties... > & view, uint32 len, Type val)
Definition at line 71 of file KokkosUtilities.hpp.
References reallocNoInit().
Referenced by cellMapper::allocateArrays(), mapperNBS::allocateArrays(), and pointFlag< DefaultHostExecutionSpace >::resetFlags().
reallocInit() [2/3]
INLINE_FUNCTION_H void pFlow::reallocInit (ViewType2D< Type, Properties... > & view, uint32 len1, uint32 len2)
Definition at line 79 of file KokkosUtilities.hpp.
reallocNoInit() [2/3]
INLINE_FUNCTION_H void pFlow::reallocNoInit (ViewType2D< Type, Properties... > & view, uint32 len1, uint32 len2)
Definition at line 86 of file KokkosUtilities.hpp.
reallocFill() [2/3]
INLINE_FUNCTION_H void pFlow::reallocFill (ViewType2D< Type, Properties... > & view, uint32 len1, uint32 len2, Type val)
Definition at line 93 of file KokkosUtilities.hpp.
References reallocNoInit().
reallocInit() [3/3]
INLINE_FUNCTION_H void pFlow::reallocInit (ViewType3D< Type, Properties... > & view, uint32 len1, uint32 len2, uint32 len3)
Definition at line 106 of file KokkosUtilities.hpp.
reallocNoInit() [3/3]
INLINE_FUNCTION_H void pFlow::reallocNoInit (ViewType3D< Type, Properties... > & view, uint32 len1, uint32 len2, uint32 len3)
Definition at line 118 of file KokkosUtilities.hpp.
reallocFill() [3/3]
INLINE_FUNCTION_H void pFlow::reallocFill (ViewType3D< Type, Properties... > & view, uint32 len1, uint32 len2, uint32 len3, Type val)
Definition at line 130 of file KokkosUtilities.hpp.
References reallocNoInit().
resizeInit()
INLINE_FUNCTION_H void pFlow::resizeInit (ViewType1D< Type, Properties... > & view, uint32 newLen)
Definition at line 144 of file KokkosUtilities.hpp.
Referenced by VectorSingle< uint32, HostSpace >::changeCapacity().
resizeNoInit()
INLINE_FUNCTION_H void pFlow::resizeNoInit (ViewType1D< Type, Properties... > & view, uint32 newLen)
Definition at line 151 of file KokkosUtilities.hpp.
Referenced by VectorSingle< uint32, HostSpace >::changeCapacity().
swapViews()
INLINE_FUNCTION_H void pFlow::swapViews (ViewType & v1, ViewType & v2)
Definition at line 158 of file KokkosUtilities.hpp.
Referenced by sortedContactList< valueType, executionSpace, idType >::beforeBroadSearch(), and unsortedContactList< valueType, executionSpace, idType >::beforeBroadSearch().
operator<<() [24/58]
INLINE_FUNCTION_H iOstream& pFlow::operator<< (iOstream & os, const Pair< T1, T2 > & p)
Definition at line 173 of file KokkosUtilities.hpp.
makeSpan() [3/6]
INLINE_FUNCTION_H span<T> pFlow::makeSpan (ViewType1D< T, properties... > & v)
Definition at line 181 of file KokkosUtilities.hpp.
makeSpan() [4/6]
INLINE_FUNCTION_H span<T> pFlow::makeSpan (ViewType1D< T, properties... > & v, uint32 size)
Definition at line 188 of file KokkosUtilities.hpp.
makeSpan() [5/6]
INLINE_FUNCTION_H span<T> pFlow::makeSpan (const ViewType1D< T, properties... > & v)
Definition at line 195 of file KokkosUtilities.hpp.
makeSpan() [6/6]
INLINE_FUNCTION_H span<T> pFlow::makeSpan (const ViewType1D< T, properties... > & v, uint32 size)
Definition at line 202 of file KokkosUtilities.hpp.
operator<<() [25/58]
INLINE_FUNCTION_H iOstream& pFlow::operator<< (iOstream & os, const ViewType1D< T, properties... > & v)
Definition at line 209 of file KokkosUtilities.hpp.
operator<<() [26/58]
INLINE_FUNCTION_H iOstream& pFlow::operator<< (iOstream & os, const Range< T > & rng)
Definition at line 133 of file Range.hpp.
References Range< T >::end(), and Range< T >::start().
count() [5/5]
INLINE_FUNCTION_H uint32 pFlow::count (const ViewType1D< T, properties... > & view, uint32 start, uint32 end, const T & val)
Definition at line 36 of file ViewAlgorithms.hpp.
fill() [3/6]
INLINE_FUNCTION_H void pFlow::fill (ViewType1D< T, properties... > & view, rangeU32 span, T val)
Definition at line 55 of file ViewAlgorithms.hpp.
References span< T >::end().
fill() [4/6]
void pFlow::fill (ViewType1D< T, properties... > & view, uint32 start, uint32 end, T val)
Definition at line 78 of file ViewAlgorithms.hpp.
References fill().
fill() [5/6]
void pFlow::fill (ViewType3D< T, properties... > & view, rangeU32 range1, rangeU32 range2, rangeU32 range3, const T & val)
Definition at line 85 of file ViewAlgorithms.hpp.
fill() [6/6]
void pFlow::fill (ViewType3D< T, properties... > & view, const T & val)
Definition at line 100 of file ViewAlgorithms.hpp.
fillSequence() [4/4]
void pFlow::fillSequence (ViewType1D< Type, properties... > & view, uint32 start, uint32 end, const Type startVal)
Definition at line 108 of file ViewAlgorithms.hpp.
fillSelected() [1/2]
bool pFlow::fillSelected (ViewType1D< Type, properties... > view, ViewType1D< indexType, indexProperties... > indices, uint32 numElems, Type val)
Definition at line 135 of file ViewAlgorithms.hpp.
References areAccessible(), and LAMBDA_HD.
Referenced by VectorDual< multiRotatingAxis >::insertSetElement().
fillSelected() [2/2]
bool pFlow::fillSelected (ViewType1D< Type, properties... > view, const ViewType1D< indexType, indexProperties... > indices, const ViewType1D< Type, properties... > vals, const uint32 numElems)
Definition at line 173 of file ViewAlgorithms.hpp.
References areAccessible().
min() [8/15]
INLINE_FUNCTION_H T pFlow::min (const ViewType1D< T, properties... > & view, uint32 start, uint32 end)
Definition at line 202 of file ViewAlgorithms.hpp.
max() [8/15]
INLINE_FUNCTION_H T pFlow::max (const ViewType1D< T, properties... > & view, uint32 start, uint32 end)
Definition at line 216 of file ViewAlgorithms.hpp.
copy() [1/2]
INLINE_FUNCTION_H void pFlow::copy (const ViewType1D< dType, dProperties... > & dst, const ViewType1D< sType, sProperties... > & src)
Definition at line 234 of file ViewAlgorithms.hpp.
Referenced by VectorSingle< uint32, HostSpace >::append(), VectorSingle< uint32, HostSpace >::assign(), VectorSingle< uint32, HostSpace >::assignFromDevice(), VectorSingle< uint32, HostSpace >::assignFromHost(), pointFlag< DefaultHostExecutionSpace >::changeCapacity(), pointFlag< DefaultHostExecutionSpace >::clone(), VectorSingle< uint32, HostSpace >::hostView(), VectorSingle< uint32, HostSpace >::hostViewAll(), indexContainer< IndexType >::indexContainer(), VectorSingle< uint32, HostSpace >::insertSetElement(), ListPtr< boundaryIntegration >::ListPtr(), MapPtr< pFlow::iEntry >::MapPtr(), MapPtr< pFlow::iEntry >::operator=(), ListPtr< boundaryIntegration >::operator=(), VectorSingle< uint32, HostSpace >::reorderItems(), VectorDual< multiRotatingAxis >::sortItems(), and VectorSingle< uint32, HostSpace >::VectorSingle().
copy() [2/2]
INLINE_FUNCTION_H void pFlow::copy (const ViewType1D< dType, dProperties... > & dst, uint32 dStart, const ViewType1D< sType, sProperties... > & src, uint32 sStart, uint32 sEnd)
Definition at line 248 of file ViewAlgorithms.hpp.
getNth()
INLINE_FUNCTION_H void pFlow::getNth (Type & dst, const ViewType1D< Type, sProperties... > & src, const uint32 n)
Definition at line 270 of file ViewAlgorithms.hpp.
References n.
Referenced by scatteredFieldAccess< T, MemorySpace >::getFirstCopy(), scatteredFieldAccess< T, MemorySpace >::getLastCopy(), and sortedPairs< executionSpace, idType >::prepareSorted().
sort() [2/3]
INLINE_FUNCTION_H void pFlow::sort (ViewType1D< T, properties... > & view, uint32 start, uint32 end)
Definition at line 281 of file ViewAlgorithms.hpp.
sort() [3/3]
INLINE_FUNCTION_H void pFlow::sort (ViewType1D< T, properties... > & view, uint32 start, uint32 end, CompareFunc compare)
Definition at line 307 of file ViewAlgorithms.hpp.
permuteSort()
void pFlow::permuteSort (const ViewType1D< Type, properties... > & view, uint32 start, uint32 end, ViewType1D< permType, permProperties... > & permuteView, uint32 permStart)
Definition at line 346 of file ViewAlgorithms.hpp.
References areAccessible().
binarySearch_()
INLINE_FUNCTION_HD int32 pFlow::binarySearch_ (const T * array, int32 length, const T & val)
Definition at line 384 of file ViewAlgorithms.hpp.
References length().
Referenced by binarySearch().
binarySearch()
INLINE_FUNCTION_HD uint32 pFlow::binarySearch (const ViewType1D< Type, properties... > & view, uint32 start, uint32 end, const Type & val)
On DEVICE and HOST calls.
Definition at line 416 of file ViewAlgorithms.hpp.
References binarySearch_().
Referenced by sortedContactList< valueType, executionSpace, idType >::operator()().
exclusiveScan()
void pFlow::exclusiveScan (const ViewType1D< Type, properties... > & view, uint32 start, uint32 end, ViewType1D< Type, dProperties... > & dView, uint32 dStart)
Definition at line 439 of file ViewAlgorithms.hpp.
References areAccessible().
Referenced by boundaryReflective::afterIteration(), fillSequence(), and sortedPairs< executionSpace, idType >::prepareSorted().
inclusiveScan()
void pFlow::inclusiveScan (const ViewType1D< Type, properties... > & view, uint32 start, uint32 end, ViewType1D< Type, dProperties... > & dView, uint32 dStart)
Definition at line 467 of file ViewAlgorithms.hpp.
References areAccessible().
ComputationTimer()
pFlow::MPITimer & ComputationTimer ()
Definition at line 85 of file MPITimer.cpp.
References ComputationTimer__.
Referenced by grainInteraction< contactForceModel, geometryMotionModel, contactListType >::iterate(), and sphereInteraction< contactForceModel, geometryMotionModel, contactListType >::iterate().
pFlowProcessors()
pFlow::localProcessors & pFlowProcessors ()
Definition at line 5 of file pFlowProcessors.cpp.
References pFlowProcessors__.
Referenced by MPITimer::averageTimeAllAtoMaster(), MPITimer::averageTimeAllToAll(), boundaryGrainParticles::create(), boundarySphereParticles::create(), particleIdHandler::create(), interaction::create(), boundaryContactSearch::create(), dataIO< T >::create(), simulationDomain::create(), boundaryBase::thisProcessorNo(), MPITimer::totalTimeAllToAll(), and MPITimer::totalTimeAllToMaster().
initialize_pFlowProcessors() [1/2]
void initialize_pFlowProcessors ()
Definition at line 10 of file pFlowProcessors.cpp.
References pFlowProcessors__.
Referenced by main().
initialize_pFlowProcessors() [2/2]
void initialize_pFlowProcessors (const std::vector< int > & ranks)
Definition at line 15 of file pFlowProcessors.cpp.
References pFlowProcessors__.
checkMPI()
bool checkMPI (const char * funcName, int error, bool forceAbort, const char * fileName, int lineNumebr)
Definition at line 165 of file processors.cpp.
References fatalErrorInMessage(), and reportAndExit().
getTimeFolders()
Map< real, fileSystem > getTimeFolders (const fileSystem & path) inline
Definition at line 119 of file timeFolder.hpp.
References endl(), fatalErrorInFunction, fatalExit, Map< Key, T, Compare >::insertIf(), readReal(), subDirectories(), and tailName().
makeUnique()
uniquePtr<T> pFlow::makeUnique (Args &&... args) inline
Definition at line 99 of file uniquePtr.hpp.
Referenced by Insertion< ShapeType >::readInsertionDict().
createDataIO()
uniquePtr<dataIO<T> > pFlow::createDataIO (const word & runType, const IOPattern & iop)
Definition at line 33 of file createDataIO-old.hpp.
References endl(), fatalErrorInFunction, and fatalExit.
writeDataAsciiBinary()
bool writeDataAsciiBinary (iOstream & os, span< T > data)
Definition at line 22 of file dataIO.cpp.
References charSpan(), IOstream::check(), endl(), fatalErrorInFunction, FUNCTION_NAME, IOstream::isBinary(), IOstream::name(), span< T >::size(), iOstream::write(), and writeDataASCII().
Referenced by operator<<(), dataIO< T >::writeData(), and writeSpan().
writeDataASCII()
bool writeDataASCII (iOstream & os, span< T > data)
Definition at line 57 of file dataIO.cpp.
References IOstream::check(), endl(), FUNCTION_NAME, and span< T >::size().
Referenced by dataIO< T >::writeData(), and writeDataAsciiBinary().
readDataAscii()
bool readDataAscii (iIstream & is, std::vector< T > & vec)
Definition at line 120 of file dataIO.cpp.
References endl(), IOstream::fatalCheck(), FUNCTION_NAME, token::int64Token(), token::isInt64(), token::isPunctuation(), iIstream::putBack(), and warningInFunction.
Referenced by readDataAsciiBinary().
readDataAsciiBinary()
bool readDataAsciiBinary (iIstream & is, std::vector< T > & data)
Definition at line 80 of file dataIO.cpp.
References IOstream::check(), endl(), fatalErrorInFunction, FUNCTION_NAME, token::int64Token(), IOstream::isBinary(), token::isInt64(), IOstream::name(), iIstream::read(), and readDataAscii().
Referenced by dataIO< T >::readData(), and readStdVector().
operator<<() [27/58]
iOstream& pFlow::operator<< (iOstream & os, const span< T > & s) inline
Definition at line 124 of file dataIO.hpp.
References fatalExit, ioErrorInFile, IOstream::lineNumber(), IOstream::name(), and writeDataAsciiBinary().
operator>>() [19/41]
iIstream& pFlow::operator>> (iIstream & is, iIstreamManip f) inline
operator>> handling for manipulators without arguments
Definition at line 231 of file iIstream.hpp.
operator>>() [20/41]
iIstream& pFlow::operator>> (iIstream & is, IOstreamManip f) inline
operator>> handling for manipulators without arguments
Definition at line 237 of file iIstream.hpp.
operator>>() [21/41]
pFlow::iIstream & operator>> (iIstream & is, word & w) inline
Definition at line 129 of file iIstreamI.hpp.
References IOstream::check(), fatalExit, FUNCTION_NAME, token::good(), ioErrorInFile, token::isString(), token::isWord(), IOstream::lineNumber(), IOstream::name(), IOstream::setBad(), token::stringToken(), and token::wordToken().
operator>>() [22/41]
pFlow::iIstream & operator>> (iIstream & is, int64 & val) inline
Definition at line 163 of file iIstreamI.hpp.
References IOstream::check(), fatalExit, FUNCTION_NAME, token::good(), ioErrorInFile, token::isNumber(), IOstream::lineNumber(), IOstream::name(), token::number(), and IOstream::setBad().
operator>>() [23/41]
pFlow::iIstream & operator>> (iIstream & is, int32 & val) inline
Definition at line 195 of file iIstreamI.hpp.
operator>>() [24/41]
pFlow::iIstream & operator>> (iIstream & is, int8 & val) inline
Definition at line 204 of file iIstreamI.hpp.
operator>>() [25/41]
pFlow::iIstream & operator>> (iIstream & is, uint64 & val) inline
Definition at line 212 of file iIstreamI.hpp.
operator>>() [26/41]
pFlow::iIstream & operator>> (iIstream & is, uint32 & val) inline
Definition at line 220 of file iIstreamI.hpp.
operator>>() [27/41]
pFlow::iIstream & operator>> (iIstream & is, uint8 & val) inline
Definition at line 228 of file iIstreamI.hpp.
operator>>() [28/41]
pFlow::iIstream & operator>> (iIstream & is, float & val) inline
Definition at line 237 of file iIstreamI.hpp.
References IOstream::check(), fatalExit, FUNCTION_NAME, token::good(), ioErrorInFile, token::isNumber(), IOstream::lineNumber(), IOstream::name(), token::number(), and IOstream::setBad().
operator>>() [29/41]
pFlow::iIstream & operator>> (iIstream & is, double & val) inline
Definition at line 268 of file iIstreamI.hpp.
References IOstream::check(), fatalExit, FUNCTION_NAME, token::good(), ioErrorInFile, token::isNumber(), IOstream::lineNumber(), IOstream::name(), token::number(), and IOstream::setBad().
operator>>() [30/41]
pFlow::iIstream & operator>> (iIstream & is, size_t & val) inline
Definition at line 298 of file iIstreamI.hpp.
References IOstream::check(), fatalExit, FUNCTION_NAME, token::good(), ioErrorInFile, token::isNumber(), IOstream::lineNumber(), IOstream::name(), token::number(), and IOstream::setBad().
operator<<() [28/58]
iOstream& pFlow::operator<< (iOstream & os, iOstreamManip f) inline
operator<< handling for manipulators without arguments
Definition at line 297 of file iOstream.hpp.
operator<<() [29/58]
iOstream& pFlow::operator<< (iOstream & os, IOstreamManip f) inline
operator<< handling for manipulators without arguments
Definition at line 303 of file iOstream.hpp.
indent()
iOstream& pFlow::indent (iOstream & os) inline
Indent stream.
Definition at line 311 of file iOstream.hpp.
References iOstream::indent().
Referenced by iOstream::beginBlock(), iOstream::endBlock(), stlFile::writeFacet(), and iOstream::writeWordKeyword().
incrIndent()
iOstream& pFlow::incrIndent (iOstream & os) inline
Increment the indent level.
Definition at line 318 of file iOstream.hpp.
References iOstream::incrIndent().
Referenced by iOstream::beginBlock().
decrIndent()
iOstream& pFlow::decrIndent (iOstream & os) inline
Decrement the indent level.
Definition at line 325 of file iOstream.hpp.
References iOstream::decrIndent().
Referenced by iOstream::endBlock().
flush()
iOstream& pFlow::flush (iOstream & os) inline
Flush stream.
Definition at line 333 of file iOstream.hpp.
References iOstream::flush().
Referenced by Ostream::endOfBinaryStreaming(), and Ostream::startOfBinaryStreaming().
endl()
iOstream& pFlow::endl (iOstream & os) inline
Add newline and flush stream.
Definition at line 341 of file iOstream.hpp.
References iOstream::endl().
Referenced by fileSystem::absolute(), observer::addEvent(), combinedRange< T >::addRanges(), observer::addToSubscriber(), pFlow::PFtoVTK::addUndstrcuturedGridField(), pointStructure::afterIteration(), boundaryList::afterIteration(), triSurface::append(), symArray< nonLinearProperties >::assign(), baseTimeControl::baseTimeControl(), pointStructure::beforeIteration(), boundaryList::beforeIteration(), sphereShape::boundingDiameter(), grainShape::boundingDiameter(), particleWallContactSearchs< NBS >::broadSearch(), collisionCheck::build(), mapperNBS::build(), fileSystem::canonical(), internalPoints::changePointsFlagPosition(), fileSystem::checkFileName(), setFieldEntry::checkForTypeAndValueAll(), grainShape::coarseGrainFactor(), commandLine::commandLine(), convertRectMeshField(), pFlow::PFtoVTK::convertTimeFolderPointFields(), pFlow::PFtoVTK::convertTimeFolderPointFieldsSelected(), pFlow::TSFtoVTK::convertTimeFolderTriSurfaceFieldsSeparate(), pFlow::TSFtoVTK::convertTimeFolderTriSurfaceFieldsSingle(), readControlDict::convertTimeToName(), convertToTriSurfaceComponents(), conveyorBelt::conveyorBelt(), boundaryIntegrationList::correct(), boundaryIntegrationList::correctPStruct(), boundaryGrainParticles::create(), boundarySphereParticles::create(), boundaryIntegration::create(), boundaryContactSearch::create(), contactSearch::create(), regularSimulationDomain::createBoundaryDicts(), cylinderWall::createCylinder(), createDataIO(), fileSystem::createDirs(), iEntry< Key, T * >::createEntry(), geometry::createPropertyId(), readFromTimeFolder::createUniformPointField_H(), cylinder::cylinder(), dictionary::dataEntryPtr(), dictionary::dataEntryRef(), internalPoints::deletePoints(), dataEntry::dict(), dictionary::dictionary(), dataEntry::dictPtr(), fileSystem::dirExist(), anyList::emplaceBack(), baseTimeControl::endIter(), Ostream::endOfBinaryStreaming(), baseTimeControl::endTime(), fileSystem::exist(), fileDictionary::fileDictionary(), fileSystem::fileName(), fileSystem::fileSystem(), positionOrdered::findAxisIndex(), geometryMotion< MotionModelType >::findMotionIndex(), shape::findPropertyIds(), iIstream::findTokenAndNext(), iIstream::findTokenResume(), geometry::geometry(), includeMask::getFieldType(), countField::getFieldType(), processField::getFieldType(), anyList::getObject(), anyList::getObjectPtr(), sphereParticles::getParticlesInfoFromShape(), grainParticles::getParticlesInfoFromShape(), getTimeFolders(), dictionary::getVal(), IOfileHeader::headerOk(), boundaryGrainInteraction< contactForceModel, geometryMotionModel >::hearChanges(), boundarySphereInteraction< contactForceModel, geometryMotionModel >::hearChanges(), baseTimeControl::iInterval(), NBS::impl_broadSearch(), MotionModel< rotatingAxisMotion, rotatingAxis >::impl_readDictionary(), MotionModel< rotatingAxisMotion, rotatingAxis >::impl_writeDictionary(), multiRotatingAxisMotion::indexToName(), infinitePlane::infinitePlane(), grainParticles::initializeParticles(), sphereParticles::initializeParticles(), regularSimulationDomain::initialTransferBlockData(), Insertion< ShapeType >::insertParticles(), internalPoints::insertPoints(), internalPoints::insertPointsOnly(), IOobject::IOobject(), pointStructure::iterate(), boundaryList::iterate(), grainInteraction< contactForceModel, geometryMotionModel, contactListType >::iterate(), sphereInteraction< contactForceModel, geometryMotionModel, contactListType >::iterate(), ListPtr< boundaryIntegration >::ListPtr(), localProcessors::localProcessors(), Logical::Logical(), repository::lookupObject(), repository::lookupObjectTypeName(), repository::lookupRepository(), main(), collisionCheck::mapLastAddedParticle(), MapPtr< pFlow::iEntry >::MapPtr(), sphereShape::mass(), grainShape::mass(), multiRotatingAxis::multiRotatingAxis(), multiTriSurface::multiTriSurface(), stlFile::name(), iIstream::nextData(), dynamicLinkLibs::open(), vtkFile::operator()(), fileSystem::operator/=(), operator<<(), MapPtr< pFlow::iEntry >::operator=(), ListPtr< boundaryIntegration >::operator=(), dictionary::operator=(), MapPtr< pFlow::iEntry >::operator[](), grainShape::orginalDiameter(), token::parseError(), geometricRegion< GeomType >::peek(), plane::plane(), planeWall::planeWall(), pointField< pFlow::VectorSingle, pFlow::AB3History >::pointField(), readFromTimeFolder::pointFieldFileGetType(), readFromTimeFolder::pointFieldGetType(), pointStructure::pointStructure(), postprocess::postprocess(), simulationDomain::prepareBoundaryDicts(), printKeys(), printKeys(), printTokenInfo(), ProcessField< T >::process(), processors::processors(), postprocess::processTimeFolder(), property::property(), readControlDict::read(), timeInterval::read(), shapeMixture::read(), Istream::read(), line::read(), dataEntry::read(), rotatingAxis::read(), multiTriSurface::read(), pointStructure::read(), Field< uint32x3 >::read(), triSurface::read(), internalPoints::read(), dictionary::read(), iIstream::readBegin(), iIstream::readBeginList(), iIstream::readBeginSquare(), readDataAscii(), readDataAsciiBinary(), Time::readDictionary(), property::readDictionary(), multiRotatingAxisMotion::readDictionary(), iIstream::readEnd(), iIstream::readEndList(), iIstream::readEndSquare(), iIstream::readEndStatement(), shape::readFromDictionary2(), sphereShape::readFromDictionary3(), grainShape::readFromDictionary3(), IOfileHeader::readHeader(), insertionRegion::readInsertionRegion(), IOobject::readObject(), readOneEtrty(), planeWall::readPlaneWall(), pointField< pFlow::VectorSingle, pFlow::AB3History >::readPointField(), readFromTimeFolder::readPointField_D(), readFromTimeFolder::readPointField_H(), stlWall::readSTLWall(), Istream::readVariable(), internalField< realx3, void >::rearrange(), rectangleMesh::rectangleMesh(), boundaryBase::removeIndices(), VectorSingle< uint32, HostSpace >::reorderItems(), reportAndExit(), baseTimeControl::rInterval(), rotatingAxis::rotatingAxis(), selectorRandomPoints::selectAllPointsInRange(), selectedFieldVals(), boundaryList::setExtendedDomain(), setFieldEntry::setPointFieldDefaultValueNewAll(), setFieldEntry::setPointFieldSelectedAll(), boundaryBase::setRemoveKeepIndices(), pointStructure::setupPointStructure(), shapeMixture::shapeMixture(), simulationDomain::simulationDomain(), stlFile::solid(), baseTimeControl::startIter(), Ostream::startOfBinaryStreaming(), baseTimeControl::startTime(), dictionary::subDict(), dictionary::subDictOrCreate(), dictionary::subDictPtr(), symArray< nonLinearProperties >::symArray(), Istream::tell(), boundaryBase::transferPointsToMirror(), triSurfaceField< uint32 >::triSurfaceField(), pFlow::TSFtoVTK::triSurfaceToVTK(), boundaryList::updateNeighborLists(), vibrating::vibrating(), vtkFile::vtkFile(), MPITimer::write(), sphereRegion::write(), conveyorBelt::write(), timeInterval::write(), stationaryWall::write(), conveyorBeltMotion::write(), rotatingAxisMotion::write(), iBox< intType >::write(), vibratingMotion::write(), shapeMixture::write(), sphere::write(), box::write(), insertion::write(), line::write(), vibrating::write(), rotatingAxis::write(), baseShapeNames::write(), cylinder::write(), repository::write(), Field< uint32x3 >::write(), triSurface::write(), dataIO< T >::writeData(), writeDataASCII(), writeDataAsciiBinary(), property::writeDictionary(), multiRotatingAxisMotion::writeDictionary(), stlFile::writeFacet(), insertion::writeInsertionDict(), Insertion< ShapeType >::writeInsertionDict(), IOobject::writeObject(), stlFile::writeSolid(), sphereShape::writeToDict(), shape::writeToDict(), baseShapeNames::writeToDict(), rectangleMesh::writeToVtk(), zAxis::zAxis(), and dynamicLinkLibs::~dynamicLinkLibs().
beginBlock()
iOstream& pFlow::beginBlock (iOstream & os) inline
Write begin block group without a name.
Definition at line 350 of file iOstream.hpp.
References iOstream::beginBlock().
Referenced by iOstream::beginBlock().
endBlock()
iOstream& pFlow::endBlock (iOstream & os) inline
Write end block group.
Definition at line 359 of file iOstream.hpp.
References iOstream::endBlock().
endEntry()
iOstream& pFlow::endEntry (iOstream & os) inline
Write end entry (';') followed by newline.
Definition at line 367 of file iOstream.hpp.
References iOstream::endEntry().
operator<<() [30/58]
iOstream& pFlow::operator<< (iOstream & os, const char c) inline
Definition at line 375 of file iOstream.hpp.
References iOstream::write().
operator<<() [31/58]
iOstream& pFlow::operator<< (iOstream & os, const char * buf) inline
Definition at line 380 of file iOstream.hpp.
References iOstream::write().
operator<<() [32/58]
iOstream& pFlow::operator<< (iOstream & os, const word & w) inline
Definition at line 385 of file iOstream.hpp.
References iOstream::write().
operator<<() [33/58]
iOstream& pFlow::operator<< (iOstream & os, const int64 & val) inline
Definition at line 391 of file iOstream.hpp.
References iOstream::write().
operator<<() [34/58]
iOstream& pFlow::operator<< (iOstream & os, const int32 & val) inline
Definition at line 396 of file iOstream.hpp.
References iOstream::write().
operator<<() [35/58]
iOstream& pFlow::operator<< (iOstream & os, const int8 & val) inline
Definition at line 402 of file iOstream.hpp.
References iOstream::write().
operator<<() [36/58]
iOstream& pFlow::operator<< (iOstream & os, const uint64 & val) inline
Definition at line 407 of file iOstream.hpp.
References iOstream::write().
operator<<() [37/58]
iOstream& pFlow::operator<< (iOstream & os, const uint32 & val) inline
Definition at line 412 of file iOstream.hpp.
References iOstream::write().
operator<<() [38/58]
iOstream& pFlow::operator<< (iOstream & os, const uint8 & val) inline
Definition at line 417 of file iOstream.hpp.
References iOstream::write().
operator<<() [39/58]
iOstream& pFlow::operator<< (iOstream & os, const float & val) inline
Definition at line 422 of file iOstream.hpp.
References iOstream::write().
operator<<() [40/58]
iOstream& pFlow::operator<< (iOstream & os, const double & val) inline
Definition at line 428 of file iOstream.hpp.
References iOstream::write().
operator<<() [41/58]
iOstream& pFlow::operator<< (iOstream & os, const size_t & val) inline
Definition at line 433 of file iOstream.hpp.
References iOstream::write().
dec()
IOstream& pFlow::dec (IOstream & io) inline
Definition at line 311 of file IOstream.hpp.
References hex(), oct(), and IOstream::setf().
Referenced by hex(), oct(), and removeDecimalZeros().
hex()
IOstream& pFlow::hex (IOstream & io) inline
Definition at line 317 of file IOstream.hpp.
References dec(), oct(), and IOstream::setf().
Referenced by dec(), and oct().
oct()
IOstream& pFlow::oct (IOstream & io) inline
Definition at line 323 of file IOstream.hpp.
References dec(), hex(), and IOstream::setf().
Referenced by dec(), and hex().
fixed()
IOstream& pFlow::fixed (IOstream & io) inline
Definition at line 329 of file IOstream.hpp.
References IOstream::setf().
Referenced by readControlDict::convertTimeToName(), and real2Fixed().
scientific()
IOstream& pFlow::scientific (IOstream & io) inline
Definition at line 335 of file IOstream.hpp.
References IOstream::setf().
Referenced by readControlDict::convertTimeToName().
operator<<() [42/58]
pFlow::iOstream & operator<< (iOstream & os, const token & tok)
Definition at line 146 of file tokenIO.cpp.
References IOstream::check(), token::doubleToken(), endl(), token::floatToken(), FUNCTION_NAME, token::int64Token(), token::pToken(), token::stringToken(), token::type_, warningInFunction, token::wordToken(), and iOstream::write().
operator>>() [31/41]
pFlow::iIstream & operator>> (iIstream & is, token & tok)
Definition at line 139 of file tokenIO.cpp.
References iIstream::read(), and token::reset().
operator<<() [43/58]
pFlow::iOstream & operator<< (iOstream & os, const token::punctuationToken & pt)
Definition at line 208 of file tokenIO.cpp.
operator<<() [44/58]
std::ostream & operator<< (std::ostream & os, const token::punctuationToken & pt)
Definition at line 213 of file tokenIO.cpp.
operator<<() [45/58]
std::ostream & operator<< (std::ostream & os, const token & tok)
Definition at line 218 of file tokenIO.cpp.
References printTokenInfo().
endListToken()
token pFlow::endListToken () inline
Definition at line 503 of file token.hpp.
References token::endList().
Referenced by List< std::any >::writeList().
beginListToken()
token pFlow::beginListToken () inline
Definition at line 508 of file token.hpp.
References token::beginList().
Referenced by List< std::any >::readList(), and List< std::any >::writeList().
endStatementToken()
token pFlow::endStatementToken () inline
Definition at line 513 of file token.hpp.
References token::endStatement().
Referenced by dataEntry::dataEntry(), and dataEntry::writeDataEntry().
beginBlockToken()
token pFlow::beginBlockToken () inline
Definition at line 518 of file token.hpp.
References token::beginBlock().
endBlocKToken()
token pFlow::endBlocKToken () inline
Definition at line 523 of file token.hpp.
References token::endBlocK().
spaceToken()
token pFlow::spaceToken () inline
Definition at line 528 of file token.hpp.
References token::space().
Referenced by dataEntry::writeDataEntry(), stlFile::writeFacet(), List< std::any >::writeList(), and stlFile::writeSolid().
newLineToken()
token pFlow::newLineToken () inline
Definition at line 533 of file token.hpp.
References token::newLine().
Referenced by List< std::any >::writeList().
printTokenInfo()
static OS& pFlow::printTokenInfo (OS & os, const token & tok) static
Definition at line 32 of file tokenIO.cpp.
References token::doubleToken(), endl(), token::floatToken(), token::int64Token(), token::lineNumber(), token::pToken(), token::stringToken(), token::type(), warningInFunction, and token::wordToken().
Referenced by operator<<(), and token::printInfo().
validTokenForStream()
bool validTokenForStream (const token tok) inline
Is tok a valid token for this stream?
Referenced by oTstream::append(), iTstream::appendToken(), iTstream::appendTokens(), and iTstream::validate().
isBeginToken()
bool isBeginToken (const token & tok) inline
Is tok a begin token?
isEndToken()
bool isEndToken (const token & tok) inline
Is tok an end token?
operator>>() [32/41]
FUNCTION_H pFlow::iIstream & operator>> (iIstream & is, box & b)
Definition at line 107 of file box.cpp.
References fatalExit, ioErrorInFile, IOstream::lineNumber(), IOstream::name(), and box::read().
operator<<() [46/58]
FUNCTION_H pFlow::iOstream & operator<< (iOstream & os, const box & b)
Definition at line 119 of file box.cpp.
References fatalExit, ioErrorInFile, IOstream::lineNumber(), IOstream::name(), and box::write().
equal() [1/10]
INLINE_FUNCTION_HD bool pFlow::equal (const box & b1, const box & b2, real tol = smallValue)
Definition at line 135 of file box.hpp.
References box::maxPoint(), and box::minPoint().
Referenced by pFlow::algorithms::KOKKOS::count(), pFlow::algorithms::STD::count(), equal(), symArray< nonLinearProperties >::getN(), infinitePlane::infinitePlane(), stridedRange< int32 >::isMember(), main(), pFlow::triangle::normal(), equalOp< T >::operator()(), operator==(), token::operator==(), infinitePlane::parallel(), infinitePlane::parallelTouch(), infinitePlane::pointOnPlane(), normalRolling< contactForceModel >::rollingFriction(), grainRolling< contactForceModel >::rollingFriction(), rotatingAxis::setOmega(), vibrating::setTime(), pFlow::triangle::valid(), infinitePlane::validPlane3(), and zAxis::zAxis().
operator==() [1/2]
INLINE_FUNCTION_HD bool pFlow::operator== (const box & b1, const box & b2)
Definition at line 142 of file box.hpp.
References equal().
Referenced by token::operator!=().
extendBox()
INLINE_FUNCTION_HD box pFlow::extendBox (const box & b, const realx3 & dl)
Definition at line 148 of file box.hpp.
References box::maxPoint(), and box::minPoint().
operator>>() [33/41]
FUNCTION_H pFlow::iIstream & operator>> (iIstream & is, cylinder & b)
Definition at line 180 of file cylinder.cpp.
References fatalExit, ioErrorInFile, IOstream::lineNumber(), IOstream::name(), and cylinder::read().
operator<<() [47/58]
FUNCTION_H pFlow::iOstream & operator<< (iOstream & os, const cylinder & b)
Definition at line 192 of file cylinder.cpp.
References fatalExit, ioErrorInFile, IOstream::lineNumber(), IOstream::name(), and cylinder::write().
equal() [2/10]
INLINE_FUNCTION_HD bool pFlow::equal (const domain & d1, const domain & d2, real tol = smallValue)
Definition at line 166 of file domain.hpp.
References domain::domainBox(), and equal().
operator==() [2/2]
INLINE_FUNCTION_HD bool pFlow::operator== (const domain & d1, const domain & d2)
Definition at line 172 of file domain.hpp.
References equal().
operator>>() [34/41]
FUNCTION_H pFlow::iIstream & operator>> (pFlow::iIstream & is, pFlow::domain & d)
Definition at line 63 of file domain.cpp.
operator<<() [48/58]
FUNCTION_H pFlow::iOstream & operator<< (pFlow::iOstream & os, const domain & d)
Definition at line 74 of file domain.cpp.
References domain::domainBox().
operator>>() [35/41]
FUNCTION_H iIstream& pFlow::operator>> (iIstream & is, iBox< intType > & b)
operator<<() [49/58]
FUNCTION_H iOstream& pFlow::operator<< (iOstream & os, const iBox< intType > & b)
operator<<() [50/58]
iOstream& pFlow::operator<< (iOstream & os, const internalPoints & ip) inline
Definition at line 263 of file internalPoints.hpp.
References fatalExit, ioErrorInFile, IOstream::lineNumber(), IOstream::name(), and internalPoints::write().
getSortedIndices()
pFlow::uint32IndexContainer getSortedIndices (box boundingBox, real dx, const ViewType1D< realx3 > & pos, const pFlagTypeDevice & flag)
Definition at line 24 of file mortonIndexing.cpp.
References pointFlag< ExecutionSpace >::activeRange(), indexContainer< IndexType >::deviceView(), pointFlag< ExecutionSpace >::isActive(), LAMBDA_HD, indexContainer< IndexType >::modifyOnDevice(), pointFlag< ExecutionSpace >::numActive(), pFlow::algorithms::STD::permuteSort(), and indexContainer< IndexType >::syncViews().
Referenced by pointSorting::getSortedIndices().
selectedFieldVals()
Vector<T> pFlow::selectedFieldVals (const pStructSelector & selector, const word & name) inline
Definition at line 14 of file fieldSelector.hpp.
References Vector< T, Allocator >::empty(), endl(), fatalErrorInFunction, fatalExit, repository::lookupObject(), repository::lookupObjectName(), repository::lookupObjectTypeName(), pStructSelector::pStruct(), pStructSelector::selectedPoints(), and pointStructure::time().
operator>>() [36/41]
FUNCTION_H pFlow::iIstream & operator>> (iIstream & is, sphere & b)
Definition at line 121 of file sphere.cpp.
References fatalExit, ioErrorInFile, IOstream::lineNumber(), IOstream::name(), and sphere::read().
operator<<() [51/58]
FUNCTION_H pFlow::iOstream & operator<< (iOstream & os, const sphere & b)
Definition at line 133 of file sphere.cpp.
References fatalExit, ioErrorInFile, IOstream::lineNumber(), IOstream::name(), and sphere::write().
operator+() [3/3]
array2D<T, nRow, nCol> pFlow::operator+ (const array2D< T, nRow, nCol > & arr1, const array2D< T, nRow, nCol > & arr2)
Definition at line 47 of file array2D.hpp.
operator-()
array2D<T, nRow, nCol> pFlow::operator- (const array2D< T, nRow, nCol > & arr1, const array2D< T, nRow, nCol > & arr2)
Definition at line 60 of file array2D.hpp.
operator*() [1/2]
array2D<T, nRow, nCol> pFlow::operator* (const array2D< T, nRow, nCol > & arr1, const array2D< T, nRow, nCol > & arr2)
Definition at line 73 of file array2D.hpp.
operator*() [2/2]
array2D<T, nRow, nCol> pFlow::operator* (const T & s, const array2D< T, nRow, nCol > & arr2)
Definition at line 86 of file array2D.hpp.
operator/() [3/4]
array2D<T, nRow, nCol> pFlow::operator/ (const array2D< T, nRow, nCol > & arr1, const array2D< T, nRow, nCol > & arr2)
Definition at line 99 of file array2D.hpp.
operator/() [4/4]
array2D<T, nRow, nCol> pFlow::operator/ (const T & val, const array2D< T, nRow, nCol > & arr2)
Definition at line 112 of file array2D.hpp.
MatMul()
array2D<T, nRow, nCol> pFlow::MatMul (const array2D< T, nRow, nInner > & A, const array2D< T, nInner, nCol > & B)
Definition at line 126 of file array2D.hpp.
References sum().
Referenced by zAxis::transferBackZ(), and zAxis::transferToZ().
transpose()
array2D<T, nCol, nRow> pFlow::transpose (const array2D< T, nRow, nCol > & arr)
Definition at line 150 of file array2D.hpp.
Referenced by zAxis::makeTransMatrix().
operator<<() [52/58]
iOstream& pFlow::operator<< (iOstream & os, const array2D< T, nRow, nCol > & arr)
Definition at line 165 of file array2D.hpp.
operator<<() [53/58]
iOstream& pFlow::operator<< (iOstream & os, const Timer & t) inline
Definition at line 178 of file Timer.hpp.
References Timer::write().
operator>>() [37/41]
iIstream& pFlow::operator>> (iIstream & is, Timer & t) inline
Definition at line 184 of file Timer.hpp.
operator<<() [54/58]
iOstream& pFlow::operator<< (iOstream & os, const Timers & t) inline
Definition at line 109 of file Timers.hpp.
References Timers::write().
operator>>() [38/41]
iIstream& pFlow::operator>> (iIstream & is, Timers & t) inline
Definition at line 115 of file Timers.hpp.
operator<<() [55/58]
iOstream& pFlow::operator<< (iOstream & os, const multiTriSurface & tri) inline
Definition at line 170 of file multiTriSurface.hpp.
References IOPattern::AllProcessorsDifferent, fatalExit, ioErrorInFile, IOstream::lineNumber(), IOstream::name(), and multiTriSurface::write().
operator<<() [56/58]
pFlow::iOstream & operator<< (iOstream & str, const subSurface & sub)
Definition at line 3 of file subSurface.cpp.
References iOstream::beginSquare(), IOstream::check(), subSurface::end_, iOstream::endSquare(), FUNCTION_NAME, subSurface::name_, subSurface::pointEnd_, subSurface::pointStart_, and subSurface::start_.
operator>>() [39/41]
pFlow::iIstream & operator>> (iIstream & str, subSurface & sub)
Definition at line 15 of file subSurface.cpp.
References IOstream::check(), subSurface::end_, FUNCTION_NAME, subSurface::name_, subSurface::pointEnd_, subSurface::pointStart_, iIstream::readBeginSquare(), iIstream::readEndSquare(), and subSurface::start_.
convertToTriSurfaceComponents()
bool pFlow::convertToTriSurfaceComponents (uint32 basePointIndex, span< realx3x3 > tris, realx3Vector & points, uint32x3Vector & vertices, realVector & area, realx3Vector & normal)
Definition at line 33 of file triSurface.cpp.
References triple< T >::comp1(), triple< T >::comp2(), triple< T >::comp3(), endl(), fatalErrorInFunction, find(), pFlow::triangle::normal(), Vector< T, Allocator >::reserve(), span< T >::size(), Vector< T, Allocator >::size(), pFlow::triangle::surface(), and pFlow::triangle::valid().
Referenced by triSurface::append().
operator>>() [40/41]
iIstream& pFlow::operator>> (iIstream & is, triSurface & tri) inline
Definition at line 237 of file triSurface.hpp.
References IOPattern::AllProcessorsDifferent, fatalExit, ioErrorInFile, IOstream::lineNumber(), IOstream::name(), and triSurface::read().
operator<<() [57/58]
iOstream& pFlow::operator<< (iOstream & os, const triSurface & tri) inline
Definition at line 248 of file triSurface.hpp.
References IOPattern::AllProcessorsDifferent, fatalExit, ioErrorInFile, IOstream::lineNumber(), IOstream::name(), and triSurface::write().
whiteSpace()
const word pFlow::whiteSpace (" \t\n\v\f\r") inline
white space
countChar() [1/2]
pFlow::int32 countChar (const word & s, const char c)
Count numer of chars c in a word.
Definition at line 28 of file bTypesFunctions.cpp.
References count().
Referenced by Ostream::write(), and Ostream::writeQuoted().
countChar() [2/2]
pFlow::int32 countChar (const char * s, const char c)
Count numer of chars c in a char string.
Definition at line 34 of file bTypesFunctions.cpp.
References count(), and length().
toUpper()
pFlow::word toUpper (const word & inStr)
convert a word to all caps
Definition at line 43 of file bTypesFunctions.cpp.
Referenced by Logical::evaluteWord(), IOfileHeader::inFileBinary(), isNo(), isYes(), and Time::readDictionary().
firstCapital()
pFlow::word firstCapital (const word & inStr)
Definition at line 51 of file bTypesFunctions.cpp.
isYes()
bool isYes (const word & str)
Check if str equals "Yes", "Y", "True", "Ok", "ON", or "T".
Definition at line 59 of file bTypesFunctions.cpp.
References toUpper().
Referenced by readBoolian_Str().
isNo()
bool isNo (const word & str)
Check if str equals "No", "N", "False", or "Off".
Definition at line 74 of file bTypesFunctions.cpp.
References toUpper().
Referenced by readBoolian_Str().
real2Fixed()
pFlow::word real2Fixed (const real & v, int32 numPrecision = 6)
Convert floating point variable to string with fixed number of precisions.
Definition at line 85 of file bTypesFunctions.cpp.
References fixed().
Referenced by real2FixedStripZeros().
real2Word()
pFlow::word real2Word (const real & v, int32 numPrecision = 6)
Convert floating point variable to string with general format.
Definition at line 94 of file bTypesFunctions.cpp.
References abs(), and verySmallValue.
Referenced by stlFile::readSolid().
int322Word()
pFlow::word int322Word (const int32 & v)
Convert int32 to word.
Definition at line 110 of file bTypesFunctions.cpp.
Referenced by vtkFile::fileName(), and processorOstream::setPrefixNum().
removeDecimalZeros()
pFlow::word removeDecimalZeros (const word & str)
Remove zeros from decimal part of a string number.
Definition at line 119 of file bTypesFunctions.cpp.
References dec(), and n.
Referenced by real2FixedStripZeros().
real2FixedStripZeros()
pFlow::word real2FixedStripZeros (const real & v, int32 numPrecision = 6)
Convert to fixed point variable and remove zeros.
Definition at line 149 of file bTypesFunctions.cpp.
References real2Fixed(), and removeDecimalZeros().
Referenced by timeControl::currentTimeWord().
angleBracketsNames()
pFlow::word angleBracketsNames (const word & w1, const word & w2)
Output <w1,w2>
Definition at line 156 of file bTypesFunctions.cpp.
Referenced by randomReal::create(), peakableRegion::create(), particleIdHandler::create(), pStructSelector::create(), interaction::create(), processField::create(), simulationDomain::create(), contactSearch::create(), geometry::create(), and boundaryBase::create().
angleBracketsNames2()
pFlow::word angleBracketsNames2 (const word & base, const word & w1, const word & w2)
Output base<w1,w2>
Definition at line 162 of file bTypesFunctions.cpp.
Referenced by boundaryGrainParticles::create(), boundarySphereParticles::create(), boundaryIntegration::create(), includeMask::create(), boundaryContactSearch::create(), dataIO< T >::create(), boundarySphereInteraction< contactForceModel, geometryMotionModel >::create(), and boundaryGrainInteraction< contactForceModel, geometryMotionModel >::create().
angleBracketsNames3()
pFlow::word angleBracketsNames3 (const word & base, const word & w1, const word & w2, const word & w3)
Output base<w1,sw2,w3>
Definition at line 168 of file bTypesFunctions.cpp.
Referenced by interaction::create(), boundaryGrainInteraction< contactForceModel, geometryMotionModel >::create(), boundarySphereInteraction< contactForceModel, geometryMotionModel >::create(), and boundaryField< T, void >::create().
groupNames()
pFlow::word groupNames (const word & bw, const word & tw, char sep = '.')
Group words and output bw.tw.
Definition at line 179 of file bTypesFunctions.cpp.
Referenced by pFlow::TSFtoVTK::convertRealx3TypetriSurfaceFieldSeparate(), pFlow::TSFtoVTK::convertTimeFolderTriSurfaceFieldsSeparate(), and boundaryField< T, void >::name().
baseName()
pFlow::word baseName (const word & w, char sep = '.')
Find the base in a group separated by "." and return it.
Definition at line 185 of file bTypesFunctions.cpp.
Referenced by fileSeries::addTimeFile(), integration::create(), and fileSeries::writeOneBaseName().
tailName()
pFlow::word tailName (const word & w, char sep = '.')
Find tail name in a group separated by "." and return it.
Definition at line 198 of file bTypesFunctions.cpp.
References nullWord.
Referenced by getTimeFolders(), and timeFolder::timeName().
validWord() [1/2]
bool validWord (char c)
Is the character valid for a word name?
Definition at line 211 of file bTypesFunctions.cpp.
Referenced by Istream::read(), and validWord().
validWordWithQuote() [1/2]
bool validWordWithQuote (char c)
Is c a valid character including quote?
Definition at line 224 of file bTypesFunctions.cpp.
Referenced by validWordWithQuote().
validWord() [2/2]
bool validWord (const word & w)
Is a valid word?
Definition at line 234 of file bTypesFunctions.cpp.
References validWord().
validWordWithQuote() [2/2]
bool validWordWithQuote (const word & c)
Is a valid word with qoute?
Definition at line 246 of file bTypesFunctions.cpp.
References validWordWithQuote().
readUint32() [1/2]
bool readUint32 (const word & w, uint32 & val)
Convert word to uint32.
Definition at line 258 of file bTypesFunctions.cpp.
Referenced by readUint32(), and readValue().
readUint32() [2/2]
bool readUint32 (const char * buf, uint32 & val)
Convert char string to uint32.
Definition at line 272 of file bTypesFunctions.cpp.
References readUint32().
readInt64() [1/2]
bool readInt64 (const word & w, int64 & val)
Convert word to int64.
Definition at line 279 of file bTypesFunctions.cpp.
Referenced by Istream::read(), readInt64(), and readValue().
readInt64() [2/2]
bool readInt64 (const char * buf, int64 & val)
Convert char string to int64.
Definition at line 293 of file bTypesFunctions.cpp.
References readInt64().
readInt32() [1/2]
bool readInt32 (const word & w, int32 & val)
Convert word to int32.
Definition at line 300 of file bTypesFunctions.cpp.
Referenced by readInt32(), and readValue().
readInt32() [2/2]
bool readInt32 (const char * buf, int32 & val)
Convert char string to int32.
Definition at line 314 of file bTypesFunctions.cpp.
References readInt32().
readInt8() [1/2]
bool readInt8 (const word & w, int8 & val)
Convert word to int8.
Definition at line 321 of file bTypesFunctions.cpp.
Referenced by readInt8(), and readValue().
readInt8() [2/2]
bool readInt8 (const char * buf, int8 & val)
Convert char string to int8.
Definition at line 335 of file bTypesFunctions.cpp.
References readInt8().
readReal() [1/2]
bool readReal (const word & w, real & val)
Convert word to real.
Definition at line 343 of file bTypesFunctions.cpp.
Referenced by getTimeFolders(), Istream::read(), and readValue().
readReal() [2/2]
bool readReal (const char * buf, real & val)
Convert char string to real.
Definition at line 361 of file bTypesFunctions.cpp.
readBoolian_Str() [1/2]
bool readBoolian_Str (const word & w, bool & val)
Convert word to bool.
Definition at line 381 of file bTypesFunctions.cpp.
References isNo(), and isYes().
Referenced by readBoolian_Str(), and readValue().
readBoolian_Str() [2/2]
bool readBoolian_Str (const char * buf, bool & val)
Convert char string to bool.
Definition at line 397 of file bTypesFunctions.cpp.
References readBoolian_Str().
readValue() [1/6]
bool pFlow::readValue (const word & w, real & val) inline
Definition at line 191 of file bTypesFunctions.hpp.
References readReal().
Referenced by combinedRange< T >::addIndividual(), intervalRange< T >::parseRange(), and stridedRange< int32 >::parseRange().
readValue() [2/6]
bool pFlow::readValue (const word & w, uint32 & val) inline
Definition at line 197 of file bTypesFunctions.hpp.
References readUint32().
readValue() [3/6]
bool pFlow::readValue (const word & w, int64 & val) inline
Definition at line 203 of file bTypesFunctions.hpp.
References readInt64().
readValue() [4/6]
bool pFlow::readValue (const word & w, int32 & val) inline
Definition at line 209 of file bTypesFunctions.hpp.
References readInt32().
readValue() [5/6]
bool pFlow::readValue (const word & w, int8 & val) inline
Definition at line 215 of file bTypesFunctions.hpp.
References readInt8().
readValue() [6/6]
bool pFlow::readValue (const word & w, bool & val) inline
Definition at line 221 of file bTypesFunctions.hpp.
References readBoolian_Str().
equal() [3/10]
INLINE_FUNCTION_HD bool pFlow::equal (const real & s1, const real & s2, real tol = smallValue)
Definition at line 228 of file bTypesFunctions.hpp.
References abs().
equal() [4/10]
INLINE_FUNCTION_HD bool pFlow::equal (const int64 & s1, const int64 & s2)
Definition at line 235 of file bTypesFunctions.hpp.
equal() [5/10]
INLINE_FUNCTION_HD bool pFlow::equal (const int32 & s1, const int32 & s2)
Definition at line 242 of file bTypesFunctions.hpp.
equal() [6/10]
INLINE_FUNCTION_HD bool pFlow::equal (const int8 & s1, const int8 & s2)
Definition at line 249 of file bTypesFunctions.hpp.
equal() [7/10]
INLINE_FUNCTION_HD bool pFlow::equal (const uint32 & s1, const uint32 & s2)
Definition at line 256 of file bTypesFunctions.hpp.
equal() [8/10]
INLINE_FUNCTION bool pFlow::equal (const word & s1, const word & s2)
Are two words equal (host only)?
Definition at line 264 of file bTypesFunctions.hpp.
degree2Radian()
INLINE_FUNCTION_HD real pFlow::degree2Radian (const real & theta)
Convert degree to radians.
Definition at line 272 of file bTypesFunctions.hpp.
References Pi.
radian2Degree()
INLINE_FUNCTION_HD real pFlow::radian2Degree (const real & phi)
Convert radians to degree.
Definition at line 280 of file bTypesFunctions.hpp.
References Pi.
floatingPointDescription()
word pFlow::floatingPointDescription () inline
Definition at line 69 of file builtinTypes.hpp.
References floatingPointType__.
Referenced by commandLine::commandLine(), and main().
operator>>() [41/41]
pFlow::iIstream & operator>> (iIstream & is, Logical & L)
Definition at line 111 of file Logical.cpp.
References fatalExit, and Logical::read().
operator<<() [58/58]
pFlow::iOstream & operator<< (iOstream & os, const Logical & L)
Definition at line 121 of file Logical.cpp.
References fatalExit, and Logical::write().
abs() [3/6]
INLINE_FUNCTION_HD real pFlow::abs (real x)
Definition at line 46 of file math.hpp.
abs() [4/6]
INLINE_FUNCTION_HD int64 pFlow::abs (int64 x)
Definition at line 57 of file math.hpp.
References abs().
abs() [5/6]
INLINE_FUNCTION_HD int32 pFlow::abs (int32 x)
Definition at line 67 of file math.hpp.
Referenced by abs().
mod() [3/8]
INLINE_FUNCTION_HD real pFlow::mod (real x, real y)
Definition at line 77 of file math.hpp.
mod() [4/8]
INLINE_FUNCTION_HD int64 pFlow::mod (int64 x, int64 y)
Definition at line 88 of file math.hpp.
mod() [5/8]
INLINE_FUNCTION_HD int32 pFlow::mod (int32 x, int32 y)
Definition at line 94 of file math.hpp.
mod() [6/8]
INLINE_FUNCTION_HD int64 pFlow::mod (uint64 x, uint64 y)
Definition at line 100 of file math.hpp.
mod() [7/8]
INLINE_FUNCTION_HD auto pFlow::mod (uint32 x, uint32 y)
Definition at line 106 of file math.hpp.
remainder()
INLINE_FUNCTION_HD real pFlow::remainder (real x, real y)
Definition at line 112 of file math.hpp.
exp() [3/4]
INLINE_FUNCTION_HD real pFlow::exp (real x)
Definition at line 124 of file math.hpp.
log() [3/4]
INLINE_FUNCTION_HD real pFlow::log (real x)
Definition at line 136 of file math.hpp.
log10() [3/4]
INLINE_FUNCTION_HD real pFlow::log10 (real x)
Definition at line 148 of file math.hpp.
pow() [5/7]
INLINE_FUNCTION_HD real pFlow::pow (real x, real y)
Definition at line 159 of file math.hpp.
sqrt() [3/4]
INLINE_FUNCTION_HD real pFlow::sqrt (real x)
Definition at line 171 of file math.hpp.
cbrt() [3/4]
INLINE_FUNCTION_HD real pFlow::cbrt (real x)
Definition at line 184 of file math.hpp.
sin() [3/4]
INLINE_FUNCTION_HD real pFlow::sin (real x)
Definition at line 195 of file math.hpp.
cos() [3/4]
INLINE_FUNCTION_HD real pFlow::cos (real x)
Definition at line 206 of file math.hpp.
tan() [3/4]
INLINE_FUNCTION_HD real pFlow::tan (real x)
Definition at line 219 of file math.hpp.
asin() [3/4]
INLINE_FUNCTION_HD real pFlow::asin (real x)
Definition at line 230 of file math.hpp.
acos() [3/4]
INLINE_FUNCTION_HD real pFlow::acos (real x)
Definition at line 241 of file math.hpp.
atan() [3/4]
INLINE_FUNCTION_HD real pFlow::atan (real x)
Definition at line 252 of file math.hpp.
atan2() [3/4]
INLINE_FUNCTION_HD real pFlow::atan2 (real y, real x)
Definition at line 262 of file math.hpp.
sinh() [3/4]
INLINE_FUNCTION_HD real pFlow::sinh (real x)
Definition at line 273 of file math.hpp.
cosh() [3/4]
INLINE_FUNCTION_HD real pFlow::cosh (real x)
Definition at line 284 of file math.hpp.
tanh() [3/4]
INLINE_FUNCTION_HD real pFlow::tanh (real x)
Definition at line 295 of file math.hpp.
asinh() [3/4]
INLINE_FUNCTION_HD real pFlow::asinh (real x)
Definition at line 305 of file math.hpp.
acosh() [3/4]
INLINE_FUNCTION_HD real pFlow::acosh (real x)
Definition at line 315 of file math.hpp.
atanh() [3/4]
INLINE_FUNCTION_HD real pFlow::atanh (real x)
Definition at line 326 of file math.hpp.
min() [9/15]
INLINE_FUNCTION_HD real pFlow::min (real x, real y)
Definition at line 337 of file math.hpp.
min() [10/15]
INLINE_FUNCTION_HD int64 pFlow::min (int32 x, int32 y)
Definition at line 348 of file math.hpp.
References min().
min() [11/15]
INLINE_FUNCTION_HD int64 pFlow::min (int64 x, int64 y)
Definition at line 360 of file math.hpp.
References min().
min() [12/15]
INLINE_FUNCTION_HD uint64 pFlow::min (uint64 x, uint64 y)
Definition at line 373 of file math.hpp.
References min().
min() [13/15]
INLINE_FUNCTION_HD uint32 pFlow::min (uint32 x, uint32 y)
Definition at line 385 of file math.hpp.
Referenced by min().
max() [9/15]
INLINE_FUNCTION_HD real pFlow::max (real x, real y)
Definition at line 396 of file math.hpp.
max() [10/15]
INLINE_FUNCTION_HD int64 pFlow::max (int64 x, int64 y)
Definition at line 406 of file math.hpp.
References max().
max() [11/15]
INLINE_FUNCTION_HD int32 pFlow::max (int32 x, int32 y)
Definition at line 418 of file math.hpp.
References max().
max() [12/15]
INLINE_FUNCTION_HD uint64 pFlow::max (uint64 x, uint64 y)
Definition at line 428 of file math.hpp.
References max().
max() [13/15]
INLINE_FUNCTION_HD uint32 pFlow::max (uint32 x, uint32 y)
Definition at line 438 of file math.hpp.
Referenced by max().
largestNegative()
constexpr T pFlow::largestNegative () constexpr
Definition at line 39 of file numericConstants.hpp.
epsilonValue()
constexpr T pFlow::epsilonValue () constexpr
Definition at line 46 of file numericConstants.hpp.
References pFlow::algorithms::KOKKOS::min().
largestPositive()
constexpr T pFlow::largestPositive () constexpr
Definition at line 54 of file numericConstants.hpp.
References pFlow::algorithms::KOKKOS::max().
equal() [9/10]
bool INLINE_FUNCTION_HD equal (const triple< T > & opr1, const triple< T > & opr2)
Definition at line 341 of file tripleI.hpp.
References equal(), triple< T >::x(), triple< T >::y(), and triple< T >::z().
equal() [10/10]
bool INLINE_FUNCTION_HD pFlow::equal (const triple< real > & opr1, const triple< real > & opr2, real tol)
Definition at line 307 of file triple.hpp.
References equal(), triple< T >::x(), triple< T >::y(), and triple< T >::z().
abs() [6/6]
INLINE_FUNCTION_HD triple<T> pFlow::abs (const triple< T > & v)
Definition at line 52 of file tripleMath.hpp.
mod() [8/8]
INLINE_FUNCTION_HD triple<T> pFlow::mod (const triple< T > & arg1, const triple< T > & arg2)
Definition at line 53 of file tripleMath.hpp.
exp() [4/4]
INLINE_FUNCTION_HD triple<T> pFlow::exp (const triple< T > & v)
Definition at line 54 of file tripleMath.hpp.
log() [4/4]
INLINE_FUNCTION_HD triple<T> pFlow::log (const triple< T > & v)
Definition at line 55 of file tripleMath.hpp.
log10() [4/4]
INLINE_FUNCTION_HD triple<T> pFlow::log10 (const triple< T > & v)
Definition at line 56 of file tripleMath.hpp.
pow() [6/7]
INLINE_FUNCTION_HD triple<T> pFlow::pow (const triple< T > & arg1, const triple< T > & arg2)
Definition at line 57 of file tripleMath.hpp.
sqrt() [4/4]
INLINE_FUNCTION_HD triple<T> pFlow::sqrt (const triple< T > & v)
Definition at line 58 of file tripleMath.hpp.
cbrt() [4/4]
INLINE_FUNCTION_HD triple<T> pFlow::cbrt (const triple< T > & v)
Definition at line 59 of file tripleMath.hpp.
sin() [4/4]
INLINE_FUNCTION_HD triple<T> pFlow::sin (const triple< T > & v)
Definition at line 60 of file tripleMath.hpp.
cos() [4/4]
INLINE_FUNCTION_HD triple<T> pFlow::cos (const triple< T > & v)
Definition at line 61 of file tripleMath.hpp.
tan() [4/4]
INLINE_FUNCTION_HD triple<T> pFlow::tan (const triple< T > & v)
Definition at line 62 of file tripleMath.hpp.
asin() [4/4]
INLINE_FUNCTION_HD triple<T> pFlow::asin (const triple< T > & v)
Definition at line 63 of file tripleMath.hpp.
acos() [4/4]
INLINE_FUNCTION_HD triple<T> pFlow::acos (const triple< T > & v)
Definition at line 64 of file tripleMath.hpp.
atan() [4/4]
INLINE_FUNCTION_HD triple<T> pFlow::atan (const triple< T > & v)
Definition at line 65 of file tripleMath.hpp.
atan2() [4/4]
INLINE_FUNCTION_HD triple<T> pFlow::atan2 (const triple< T > & arg1, const triple< T > & arg2)
Definition at line 66 of file tripleMath.hpp.
sinh() [4/4]
INLINE_FUNCTION_HD triple<T> pFlow::sinh (const triple< T > & v)
Definition at line 67 of file tripleMath.hpp.
cosh() [4/4]
INLINE_FUNCTION_HD triple<T> pFlow::cosh (const triple< T > & v)
Definition at line 68 of file tripleMath.hpp.
tanh() [4/4]
INLINE_FUNCTION_HD triple<T> pFlow::tanh (const triple< T > & v)
Definition at line 69 of file tripleMath.hpp.
asinh() [4/4]
INLINE_FUNCTION_HD triple<T> pFlow::asinh (const triple< T > & v)
Definition at line 70 of file tripleMath.hpp.
acosh() [4/4]
INLINE_FUNCTION_HD triple<T> pFlow::acosh (const triple< T > & v)
Definition at line 71 of file tripleMath.hpp.
atanh() [4/4]
INLINE_FUNCTION_HD triple<T> pFlow::atanh (const triple< T > & v)
Definition at line 72 of file tripleMath.hpp.
min() [14/15]
INLINE_FUNCTION_HD triple<T> pFlow::min (const triple< T > & arg1, const triple< T > & arg2)
Definition at line 73 of file tripleMath.hpp.
max() [14/15]
INLINE_FUNCTION_HD triple<T> pFlow::max (const triple< T > & arg1, const triple< T > & arg2)
Definition at line 74 of file tripleMath.hpp.
pow() [7/7]
INLINE_FUNCTION_HD triple<T> pFlow::pow (const triple< T > & t3, T e)
Definition at line 81 of file tripleMath.hpp.
References pow(), triple< T >::x_, triple< T >::y_, and triple< T >::z_.
min() [15/15]
INLINE_FUNCTION_HD T pFlow::min (const triple< T > & t3)
Definition at line 89 of file tripleMath.hpp.
References min(), triple< T >::x_, triple< T >::y_, and triple< T >::z_.
max() [15/15]
INLINE_FUNCTION_HD T pFlow::max (const triple< T > & t3)
Definition at line 97 of file tripleMath.hpp.
References max(), triple< T >::x_, triple< T >::y_, and triple< T >::z_.
basicTypeName()
word pFlow::basicTypeName () inline
Definition at line 62 of file typeInfo.hpp.
basicTypeName< word >()
word pFlow::basicTypeName< word > () inline
Definition at line 73 of file typeInfo.hpp.
basicTypeName< int64 >()
word pFlow::basicTypeName< int64 > () inline
Definition at line 79 of file typeInfo.hpp.
basicTypeName< int32 >()
word pFlow::basicTypeName< int32 > () inline
Definition at line 85 of file typeInfo.hpp.
basicTypeName< int8 >()
word pFlow::basicTypeName< int8 > () inline
Definition at line 91 of file typeInfo.hpp.
basicTypeName< uint64 >()
word pFlow::basicTypeName< uint64 > () inline
Definition at line 97 of file typeInfo.hpp.
basicTypeName< uint32 >()
word pFlow::basicTypeName< uint32 > () inline
Definition at line 103 of file typeInfo.hpp.
basicTypeName< uint8 >()
word pFlow::basicTypeName< uint8 > () inline
Definition at line 109 of file typeInfo.hpp.
basicTypeName< real >()
word pFlow::basicTypeName< real > () inline
Definition at line 115 of file typeInfo.hpp.
getTypeName() [1/2]
word pFlow::getTypeName () inline
Definition at line 122 of file typeInfo.hpp.
Referenced by anyList::emplaceBack(), and setFieldEntry::setPointFieldSelected().
getTypeName() [2/2]
word pFlow::getTypeName (const T &) inline
Definition at line 136 of file typeInfo.hpp.
checkType() [1/2]
bool pFlow::checkType (Type2 * object)
Definition at line 151 of file typeInfo.hpp.
checkType() [2/2]
bool pFlow::checkType (Type2 & object)
Definition at line 157 of file typeInfo.hpp.
applySelector()
bool pFlow::applySelector (systemControl & control, const pointStructure & pStruct, const dictionary & selDict)
Definition at line 34 of file setFields.hpp.
References pStructSelector::create(), pStruct, dictionary::subDict(), and systemControl::time().
Referenced by main().
sumOp()
uniquePtr<rectMeshField_H<T> > pFlow::sumOp (pointField_H< T > & field, pointRectCell & pointToCell)
Definition at line 34 of file fieldOperations.hpp.
References internalField< T, void >::deviceView(), pointRectCell::getCellIterator(), pointRectCell::mesh(), n, and cellMapper::NoPos.
Referenced by ProcessField< T >::process().
sumMaksOp()
uniquePtr<rectMeshField_H<T> > pFlow::sumMaksOp (pointField_H< T > & field, pointRectCell & pointToCell, const incMask & mask)
Definition at line 66 of file fieldOperations.hpp.
References internalField< T, void >::deviceView(), pointRectCell::getCellIterator(), pointRectCell::mesh(), n, and cellMapper::NoPos.
Referenced by ProcessField< T >::process().
convertRectMeshField() [1/4]
bool pFlow::convertRectMeshField (iOstream & os, const rectMeshField_H< T > & field)
Definition at line 29 of file rectMeshFieldToVTK.hpp.
References endl(), fatalErrorInFunction, fatalExit, and IOobject::typeName().
Referenced by ProcessField< T >::writeToVTK().
convertRectMeshField() [2/4]
bool pFlow::convertRectMeshField (iOstream & os, const rectMeshField_H< real > & field)
Definition at line 39 of file rectMeshFieldToVTK.hpp.
References endl(), rectMeshField< T >::name(), rectMeshField< T >::nx(), rectMeshField< T >::ny(), rectMeshField< T >::nz(), and rectMeshField< T >::size().
convertRectMeshField() [3/4]
bool pFlow::convertRectMeshField (iOstream & os, const rectMeshField_H< realx3 > & field)
Definition at line 58 of file rectMeshFieldToVTK.hpp.
References endl(), rectMeshField< T >::name(), rectMeshField< T >::nx(), rectMeshField< T >::ny(), rectMeshField< T >::nz(), and rectMeshField< T >::size().
convertRectMeshField() [4/4]
bool pFlow::convertRectMeshField (iOstream & os, const rectMeshField_H< int32 > & field)
Definition at line 77 of file rectMeshFieldToVTK.hpp.
References endl(), rectMeshField< T >::name(), rectMeshField< T >::nx(), rectMeshField< T >::ny(), rectMeshField< T >::nz(), and rectMeshField< T >::size().
badInput()
bool pFlow::badInput (iIstream & is, token & tok) inline
Definition at line 29 of file stlFile.cpp.
References IOstream::bad(), and token::good().
Referenced by checkNumberToken(), checkWordToken(), and stlFile::readSolid().
checkWordToken()
bool pFlow::checkWordToken (iIstream & is, token & tok, const word & check) inline
Definition at line 34 of file stlFile.cpp.
References badInput(), IOstream::eof(), token::isWord(), and token::wordToken().
Referenced by stlFile::readFacet(), and stlFile::readSolid().
checkNumberToken()
bool pFlow::checkNumberToken (iIstream & is, token & tok, real & val) inline
Definition at line 42 of file stlFile.cpp.
References badInput(), IOstream::eof(), token::isNumber(), and token::number().
Referenced by stlFile::readFacet().
checkNormalVec()
bool checkNormalVec (const realx3 & p1, const realx3 & p2, const realx3 & p3, realx3 & norm)
Definition at line 88 of file Wall.cpp.
References cross(), length(), and smallValue.
Referenced by cylinderWall::createCylinder().
byteSwaper()
T pFlow::byteSwaper (const T & p) inline
Definition at line 81 of file vtkByteSwapper.hpp.
References pFlow::NBSLevel0Kernels::Swap().
Referenced by pFlow::PFtoVTK::addIntPointField(), pFlow::PFtoVTK::addRealPointField(), pFlow::PFtoVTK::addRealx3PointField(), and pFlow::PFtoVTK::addUndstrcuturedGridField().
Variable Documentation
BASE_MIRROR_WALL_INDEX
const uint32 BASE_MIRROR_WALL_INDEX = 1000000 inline
Definition at line 37 of file contactSearchGlobals.hpp.
Referenced by wallBoundaryContactSearch::broadSearch().
ActivePoint
const auto ActivePoint = pointStructure::ACTIVE inline
Definition at line 25 of file pointFieldAlgorithms.hpp.
Referenced by maxActive_serial(), maxActiveD(), and maxActiveH().
settingsFolder__
const char* const settingsFolder__ = "settings" inline
Definition at line 28 of file vocabs.hpp.
settingsRepository__
const char* const settingsRepository__ = "settings" inline
Definition at line 29 of file vocabs.hpp.
caseSetupFolder__
const char* const caseSetupFolder__ = "caseSetup" inline
Definition at line 30 of file vocabs.hpp.
caseSetupRepository__
const char* const caseSetupRepository__ = "caseSetup" inline
Definition at line 31 of file vocabs.hpp.
geometryFolder__
const char* const geometryFolder__ = "geometry" inline
Definition at line 32 of file vocabs.hpp.
Referenced by main().
geometryRepository_
const char* const geometryRepository_ = "geometry" inline
Definition at line 33 of file vocabs.hpp.
integrationRepository__
const char* const integrationRepository__ = "integration" inline
Definition at line 34 of file vocabs.hpp.
integrationFolder__
const char* const integrationFolder__ = "integration" inline
Definition at line 35 of file vocabs.hpp.
Referenced by Time::integrationFolder().
settingsFile__
const char* const settingsFile__ = "settingsDict" inline
Definition at line 38 of file vocabs.hpp.
domainFile__
const char* const domainFile__ = "domainDict" inline
Definition at line 39 of file vocabs.hpp.
Referenced by positionParticles::positionParticles().
insertionFile__
const char* const insertionFile__ = "particleInsertion" inline
Definition at line 40 of file vocabs.hpp.
Referenced by insertion::insertion().
shapeFile__
const char* const shapeFile__ = "shapes" inline
Definition at line 41 of file vocabs.hpp.
Referenced by main().
pointStructureFile__
const char* const pointStructureFile__ = "pStructure" inline
Definition at line 42 of file vocabs.hpp.
Referenced by readFromTimeFolder::checkForPointStructure(), pFlow::PFtoVTK::convertTimeFolderPointFields(), pFlow::PFtoVTK::convertTimeFolderPointFieldsSelected(), readFromTimeFolder::createUniformPointField_H(), main(), readFromTimeFolder::readPointField_D(), and readFromTimeFolder::readPointField_H().
triSurfaceFile__
const char* const triSurfaceFile__ = "triSurface" inline
Definition at line 43 of file vocabs.hpp.
Referenced by pFlow::TSFtoVTK::convertTimeFolderTriSurfaceFields(), and main().
createParticles__
const char* const createParticles__ = "createParticles" inline
Definition at line 44 of file vocabs.hpp.
motionModelFile__
const char* const motionModelFile__ = "motionModel" inline
Definition at line 45 of file vocabs.hpp.
Referenced by geometry::create(), multiRotatingAxisMotion::read(), and multiRotatingAxisMotion::write().
contactSearchFile__
const char* const contactSearchFile__ = "contactSearch" inline
Definition at line 46 of file vocabs.hpp.
propertyFile__
const char* const propertyFile__ = "interaction" inline
Definition at line 47 of file vocabs.hpp.
interactionFile__
const char* const interactionFile__ = "interaction" inline
Definition at line 48 of file vocabs.hpp.
Referenced by interaction::create().
postprocessFile__
const char* const postprocessFile__ = "postprocessDict" inline
Definition at line 49 of file vocabs.hpp.
uniform__
const char* const uniform__ = "uniform" inline
Definition at line 51 of file vocabs.hpp.
nonUniform__
const char* const nonUniform__ = "nonUniform" inline
Definition at line 52 of file vocabs.hpp.
tab
constexpr char tab = '\t' constexpr
Definition at line 439 of file iOstream.hpp.
nl
constexpr char nl = '\n' constexpr
Definition at line 440 of file iOstream.hpp.
Referenced by pFlow::PFtoVTK::convertTimeFolderPointFields(), pFlow::PFtoVTK::convertTimeFolderPointFieldsSelected(), Istream::read(), and Istream::readVariable().
output
pFlow::Ostream output
Referenced by pFlow::PFtoVTK::convertTimeFolderPointFields(), pFlow::PFtoVTK::convertTimeFolderPointFieldsSelected(), pFlow::TSFtoVTK::convertTimeFolderTriSurfaceFieldsSeparate(), pFlow::TSFtoVTK::convertTimeFolderTriSurfaceFieldsSingle(), main(), and postprocess::processTimeFolder().
mOutput
pFlow::masterOstream mOutput
Referenced by commandLine::commandLine(), processors::initProcessors(), and systemControl::operator++().
pOutput
pFlow::processorOstream pOutput
Referenced by boundaryGrainParticles::create(), boundarySphereParticles::create(), boundaryIntegration::create(), interaction::create(), boundaryContactSearch::create(), boundaryGrainInteraction< contactForceModel, geometryMotionModel >::create(), boundarySphereInteraction< contactForceModel, geometryMotionModel >::create(), contactSearch::create(), boundarySphereInteraction< contactForceModel, geometryMotionModel >::hearChanges(), boundaryGrainInteraction< contactForceModel, geometryMotionModel >::hearChanges(), processors::initProcessors(), internalPoints::insertPoints(), and internalPoints::insertPointsOnly().
input
pFlow::Istream input
errReport
pFlow::processorOstream errReport
Referenced by processors::initProcessors().
zero
const real zero = 0.0 inline
Zero real variable.
Definition at line 37 of file bTypesFunctions.hpp.
one
const real one = 1.0 inline
one real variable
Definition at line 40 of file bTypesFunctions.hpp.
zero32
const int32 zero32 = 0 inline
zero int32 variable
Definition at line 43 of file bTypesFunctions.hpp.
one32
const int32 one32 = 1 inline
one int32 variable
Definition at line 46 of file bTypesFunctions.hpp.
nullWord
const word nullWord inline
null/empty word
Definition at line 49 of file bTypesFunctions.hpp.
Referenced by token::stringToken(), tailName(), and token::wordToken().
floatingPointType__
const char* floatingPointType__ = "float" inline
Definition at line 37 of file builtinTypes.hpp.
Referenced by floatingPointDescription().
usingDouble__
const bool usingDouble__ = false inline
Definition at line 38 of file builtinTypes.hpp.
numBytesForReal__
const int numBytesForReal__ = sizeof(real) inline
Definition at line 66 of file builtinTypes.hpp.
Pi
const real Pi = real(3.1415926535897932384626433832) inline
Definition at line 30 of file numericConstants.hpp.
Referenced by nonLinearMod< limited >::contactForce(), nonLinear< limited >::contactForce(), linear< limited >::contactForce(), cGRelativeLinear< limited >::contactForce(), cGAbsoluteLinear< limited >::contactForce(), cylinderWall::createCylinder(), degree2Radian(), sphereShape::mass(), grainShape::mass(), radian2Degree(), linear< limited >::readLinearDictionary(), cGRelativeLinear< limited >::readLinearDictionary(), cGAbsoluteLinear< limited >::readLinearDictionary(), and nonLinear< limited >::readNonLinearDictionary().
smallValue
const real smallValue = 1.0e-15 inline
Definition at line 31 of file numericConstants.hpp.
Referenced by geometry::afterIteration(), cylinder::calculateParams(), checkNormalVec(), Wall::checkTrianlge(), zAxis::makeTransMatrix(), quadruple< T >::normalize(), and Timer::write().
verySmallValue
const real verySmallValue = 1.0e-30 inline
Definition at line 32 of file numericConstants.hpp.
Referenced by triple< intType >::normalize(), and real2Word().
largeValue
const real largeValue = 1.0e15 inline
Definition at line 33 of file numericConstants.hpp.
Referenced by baseTimeControl::baseTimeControl(), and timeInterval::read().
veryLargeValue
const real veryLargeValue = 1.0e30 inline
Definition at line 34 of file numericConstants.hpp.
largestNegInt32
const int32 largestNegInt32 = largestNegative<int32>() inline
Definition at line 59 of file numericConstants.hpp.
largestPosInt32
const int32 largestPosInt32 = largestPositive<int32>() inline
Definition at line 60 of file numericConstants.hpp.
Referenced by baseTimeControl::baseTimeControl().
largestNegInt64
const int64 largestNegInt64 = largestNegative<int64>() inline
Definition at line 62 of file numericConstants.hpp.
largestPosInt64
const int64 largestPosInt64 = largestPositive<int64>() inline
Definition at line 63 of file numericConstants.hpp.
largestNegREAL
const real largestNegREAL = largestNegative<real>() inline
Definition at line 65 of file numericConstants.hpp.
largestPosREAL
const real largestPosREAL = largestPositive<real>() inline
Definition at line 66 of file numericConstants.hpp.
epsilonREAL
const real epsilonREAL = epsilonValue<real>() inline
Definition at line 67 of file numericConstants.hpp.
zero3
const realx3 zero3
Definition at line 137 of file types.hpp.
Referenced by AdamsBashforth3::AdamsBashforth3(), AdamsBashforth4::AdamsBashforth4(), AdamsBashforth5::AdamsBashforth5(), particles::zeroForce(), geometry::zeroForce(), and particles::zeroTorque().
one3
const realx3 one3
Definition at line 138 of file types.hpp.
zero33
const realx3x3 zero33
Definition at line 140 of file types.hpp.
one33
const realx3x3 one33
Definition at line 141 of file types.hpp.
zero4
const realx4 zero4
Definition at line 143 of file types.hpp.