PhasicFlow: pFlow::triangle Namespace Reference
pFlow::triangle Namespace Reference
Functions
INLINE_FUNCTION_HD real surface (const realx3 &p1, const realx3 &p2, const realx3 &p3)
INLINE_FUNCTION_HD realx3 normal (const realx3 &p1, const realx3 &p2, const realx3 &p3)
INLINE_FUNCTION_HD bool valid (const realx3 &p1, const realx3 &p2, const realx3 &p3)
Function Documentation
surface()
INLINE_FUNCTION_HD real pFlow::triangle::surface (const realx3 & p1, const realx3 & p2, const realx3 & p3)
Definition at line 30 of file triangleFunctions.hpp.
References pFlow::abs(), cross(), and length().
Referenced by pFlow::triSurfaceKernels::calculateArea(), pFlow::TSFtoVTK::convertTimeFolderTriSurfaceFieldsSeparate(), pFlow::TSFtoVTK::convertTimeFolderTriSurfaceFieldsSingle(), pFlow::convertToTriSurfaceComponents(), and main().
normal()
INLINE_FUNCTION_HD realx3 pFlow::triangle::normal (const realx3 & p1, const realx3 & p2, const realx3 & p3)
Definition at line 38 of file triangleFunctions.hpp.
References cross(), pFlow::equal(), n, and normalize().
Referenced by triSurface::append(), pFlow::triSurfaceKernels::calculateNormals(), and pFlow::convertToTriSurfaceComponents().
valid()
INLINE_FUNCTION_HD bool pFlow::triangle::valid (const realx3 & p1, const realx3 & p2, const realx3 & p3)
Definition at line 49 of file triangleFunctions.hpp.
References cross(), pFlow::equal(), and length().
Referenced by pFlow::convertToTriSurfaceComponents().