PhasicFlow: src/phasicFlow/types/quadruple/quadrupleFwd.hpp File Reference
quadrupleFwd.hpp File Reference
Functions
template<typename T >
INLINE_FUNCTION_HD T dot (const quadruple< T > &oprnd1, const quadruple< T > &oprnd2)
template<typename T >
INLINE_FUNCTION_HD quadruple< T > operator+ (const quadruple< T > &oprnd1, const quadruple< T > &oprnd2)
template<typename T >
INLINE_FUNCTION_HD quadruple< T > operator+ (const quadruple< T > &oprnd1, const T &oprnd2)
template<typename T >
INLINE_FUNCTION_HD quadruple< T > operator+ (const T &oprnd2, const quadruple< T > &oprnd1)
template<typename T >
INLINE_FUNCTION_HD quadruple< T > operator- (const quadruple< T > &oprnd1, const quadruple< T > &oprnd2)
template<typename T >
INLINE_FUNCTION_HD quadruple< T > operator- (const quadruple< T > &oprnd1, const T &oprnd2)
template<typename T >
INLINE_FUNCTION_HD quadruple< T > operator- (const T &oprnd1, const quadruple< T > &oprnd2)
template<typename T >
INLINE_FUNCTION_HD quadruple< T > operator* (const quadruple< T > &oprnd1, const quadruple< T > &oprnd2)
template<typename T >
INLINE_FUNCTION_HD quadruple< T > operator* (const quadruple< T > &oprnd1, const T &oprnd2)
template<typename T >
INLINE_FUNCTION_HD quadruple< T > operator* (const T &oprnd1, const quadruple< T > &oprnd2)
template<typename T >
INLINE_FUNCTION_HD quadruple< T > operator/ (const quadruple< T > &oprnd1, const quadruple< T > &oprnd2)
template<typename T >
INLINE_FUNCTION_HD quadruple< T > operator/ (const quadruple< T > &oprnd1, const T &oprnd2)
template<typename T >
INLINE_FUNCTION_HD quadruple< T > operator/ (const T &oprnd1, const quadruple< T > &oprnd2)
template<typename T >
INLINE_FUNCTION_HD bool operator== (const quadruple< T > &opr1, const quadruple< T > &opr2)
template<typename T >
INLINE_FUNCTION_H iOstream & operator<< (iOstream &str, const quadruple< T > &ov)
template<typename T >
INLINE_FUNCTION_H iIstream & operator>> (iIstream &str, quadruple< T > &iv)
template<typename T >
INLINE_FUNCTION_H void readIstream (iIstream &str, quadruple< T > &iv)
Function Documentation
dot()
INLINE_FUNCTION_HD T dot (const quadruple< T > & oprnd1, const quadruple< T > & oprnd2)
Referenced by cylinder::calculateParams(), nonLinearMod< limited >::contactForce(), nonLinear< limited >::contactForce(), linear< limited >::contactForce(), sphere::isInside(), cylinder::isInside(), triple< intType >::length(), quadruple< T >::length(), triWall::makeWall(), triWall::nearestPointOnWall(), triWall::normalDistFromWall(), pFlow::sphTriInteraction::pointInPlane(), positionOrdered::positionPointsOrdered(), line::projectNormalizedLength(), and pLine::projectNormLength().
operator+() [1/3]
INLINE_FUNCTION_HD quadruple<T> operator+ (const quadruple< T > & oprnd1, const quadruple< T > & oprnd2)
operator+() [2/3]
INLINE_FUNCTION_HD quadruple<T> operator+ (const quadruple< T > & oprnd1, const T & oprnd2)
operator+() [3/3]
INLINE_FUNCTION_HD quadruple<T> operator+ (const T & oprnd2, const quadruple< T > & oprnd1)
operator-() [1/3]
INLINE_FUNCTION_HD quadruple<T> operator- (const quadruple< T > & oprnd1, const quadruple< T > & oprnd2)
operator-() [2/3]
INLINE_FUNCTION_HD quadruple<T> operator- (const quadruple< T > & oprnd1, const T & oprnd2)
operator-() [3/3]
INLINE_FUNCTION_HD quadruple<T> operator- (const T & oprnd1, const quadruple< T > & oprnd2)
operator*() [1/3]
INLINE_FUNCTION_HD quadruple<T> operator* (const quadruple< T > & oprnd1, const quadruple< T > & oprnd2)
operator*() [2/3]
INLINE_FUNCTION_HD quadruple<T> operator* (const quadruple< T > & oprnd1, const T & oprnd2)
operator*() [3/3]
INLINE_FUNCTION_HD quadruple<T> operator* (const T & oprnd1, const quadruple< T > & oprnd2)
operator/() [1/3]
INLINE_FUNCTION_HD quadruple<T> operator/ (const quadruple< T > & oprnd1, const quadruple< T > & oprnd2)
operator/() [2/3]
INLINE_FUNCTION_HD quadruple<T> operator/ (const quadruple< T > & oprnd1, const T & oprnd2)
operator/() [3/3]
INLINE_FUNCTION_HD quadruple<T> operator/ (const T & oprnd1, const quadruple< T > & oprnd2)
operator==()
INLINE_FUNCTION_HD bool operator== (const quadruple< T > & opr1, const quadruple< T > & opr2)
Referenced by token::operator!=().
operator<<()
INLINE_FUNCTION_H iOstream& operator<< (iOstream & str, const quadruple< T > & ov)
operator>>()
INLINE_FUNCTION_H iIstream& operator>> (iIstream & str, quadruple< T > & iv)
readIstream()
INLINE_FUNCTION_H void readIstream (iIstream & str, quadruple< T > & iv)