PhasicFlow: Range< T > Struct Template Reference
Range< T > Struct Template Reference
Range for elements in an vector [start,end)
Public Types
using Pair = Kokkos::pair< T, T >
Public Member Functions
TypeInfoTemplateNV11 ("Range", T) INLINE_FUNCTION_HD Range()=default
Default.
INLINE_FUNCTION_HD Range (const T &e)
From end, set start to 0.
INLINE_FUNCTION_HD Range (const T &s, const T &e)
From componeents.
INLINE_FUNCTION_HD Range (const Range::Pair &src)
From pair.
INLINE_FUNCTION_HD Range (const Range &)=default
Copy.
INLINE_FUNCTION_HD Range (Range &&)=default
Move.
INLINE_FUNCTION_HD Range & operator= (const Range &)=default
Copy assignment.
INLINE_FUNCTION_HD Range & operator= (Range &&)=default
Move assignment.
INLINE_FUNCTION_HD ~Range ()=default
Destructor.
INLINE_FUNCTION_HD T & start ()
Start.
INLINE_FUNCTION_HD T & end ()
End.
const INLINE_FUNCTION_HD T & start () const
const INLINE_FUNCTION_HD T & end () const
INLINE_FUNCTION_HD T numElements ()
INLINE_FUNCTION_HD auto getPair () const
Detailed Description
template<typename T>
struct pFlow::Range< T >
Range for elements in an vector [start,end)
Definition at line 38 of file Range.hpp.
Member Typedef Documentation
Pair
using Pair = Kokkos::pair<T, T>
Definition at line 40 of file Range.hpp.
Constructor & Destructor Documentation
Range() [1/5]
INLINE_FUNCTION_HD Range (const T & e) inline explicit
From end, set start to 0.
Definition at line 51 of file Range.hpp.
Range() [2/5]
INLINE_FUNCTION_HD Range (const T & s, const T & e) inline
From componeents.
Definition at line 58 of file Range.hpp.
Range() [3/5]
INLINE_FUNCTION_HD Range (const Range< T >::Pair & src) inline
From pair.
Definition at line 65 of file Range.hpp.
Range() [4/5]
INLINE_FUNCTION_HD Range (const Range< T > &) default
Copy.
Range() [5/5]
INLINE_FUNCTION_HD Range (Range< T > &&) default
Move.
~Range()
INLINE_FUNCTION_HD ~Range () default
Destructor.
Member Function Documentation
TypeInfoTemplateNV11()
TypeInfoTemplateNV11 ("Range< T >" , T) default
Default.
operator=() [1/2]
INLINE_FUNCTION_HD Range& operator= (const Range< T > &) default
Copy assignment.
operator=() [2/2]
INLINE_FUNCTION_HD Range& operator= (Range< T > &&) default
Move assignment.
start() [1/2]
INLINE_FUNCTION_HD T& start () inline
Start.
Definition at line 94 of file Range.hpp.
Referenced by VectorSingle< word, HostSpace >::fill(), pFlow::AB2Kernels::intAllActive(), Range< uint32 >::numElements(), and pFlow::operator<<().
end() [1/2]
INLINE_FUNCTION_HD T& end () inline
End.
Definition at line 101 of file Range.hpp.
Referenced by cellMapper::checkAllocateNext(), mapperNBS::checkAllocateNext(), VectorSingle< uint32, HostSpace >::fill(), VectorSingle< word, HostSpace >::fill(), pFlow::AB2Kernels::intAllActive(), Range< uint32 >::numElements(), pFlow::operator<<(), and internalPoints::size().
start() [2/2]
const INLINE_FUNCTION_HD T& start () const inline
Definition at line 107 of file Range.hpp.
end() [2/2]
const INLINE_FUNCTION_HD T& end () const inline
Definition at line 113 of file Range.hpp.
numElements()
INLINE_FUNCTION_HD T numElements () inline
Definition at line 119 of file Range.hpp.
Referenced by pointFlag< DefaultHostExecutionSpace >::resetFlags(), multiTriSurface::subSurfaceNumPoints(), and multiTriSurface::subSurfaceSize().
getPair()
INLINE_FUNCTION_HD auto getPair () const inline
Definition at line 125 of file Range.hpp.
The documentation for this struct was generated from the following file:
src/phasicFlow/Kokkos/Range.hpp