PhasicFlow: src/phasicFlow/types/triple/tripleFwd.hpp File Reference
tripleFwd.hpp File Reference
Functions
template<typename T >
INLINE_FUNCTION_HD T dot (const triple< T > &oprnd1, const triple< T > &oprnd2)
template<typename T >
INLINE_FUNCTION_HD triple< T > cross (const triple< T > &v1, const triple< T > &v2)
template<typename T >
INLINE_FUNCTION_HD T length (const triple< T > &v1)
template<typename T >
INLINE_FUNCTION_HD triple< T > normalize (const triple< T > &v1)
template<typename T >
INLINE_FUNCTION_HD triple< T > operator+ (const triple< T > &oprnd1, const triple< T > &oprnd2)
template<typename T >
INLINE_FUNCTION_HD triple< T > operator+ (const triple< T > &oprnd1, const T &oprnd2)
template<typename T >
INLINE_FUNCTION_HD triple< T > operator+ (const T &oprnd2, const triple< T > &oprnd1)
template<typename T >
INLINE_FUNCTION_HD triple< T > operator- (const triple< T > &oprnd1, const triple< T > &oprnd2)
template<typename T >
INLINE_FUNCTION_HD triple< T > operator- (const triple< T > &oprnd1, const T &oprnd2)
template<typename T >
INLINE_FUNCTION_HD triple< T > operator- (const T &oprnd1, const triple< T > &oprnd2)
template<typename T >
INLINE_FUNCTION_HD triple< T > operator* (const triple< T > &oprnd1, const triple< T > &oprnd2)
template<typename T >
INLINE_FUNCTION_HD triple< T > operator* (const triple< T > &oprnd1, const T &oprnd2)
template<typename T >
INLINE_FUNCTION_HD triple< T > operator* (const T &oprnd1, const triple< T > &oprnd2)
template<typename T >
INLINE_FUNCTION_HD triple< T > operator/ (const triple< T > &oprnd1, const triple< T > &oprnd2)
template<typename T >
INLINE_FUNCTION_HD triple< T > operator/ (const triple< T > &oprnd1, const T &oprnd2)
template<typename T >
INLINE_FUNCTION_HD triple< T > operator/ (const T &oprnd1, const triple< T > &oprnd2)
template<typename T >
INLINE_FUNCTION_HD bool operator== (const triple< T > &opr1, const triple< T > &opr2)
template<typename T >
INLINE_FUNCTION_HD bool operator> (const triple< T > &opr1, const triple< T > &opr2)
template<typename T >
INLINE_FUNCTION_HD bool operator< (const triple< T > &opr1, const triple< T > &opr2)
template<typename T >
INLINE_FUNCTION_HD bool operator<= (const triple< T > &opr1, const triple< T > &opr2)
template<typename T >
INLINE_FUNCTION_HD bool operator>= (const triple< T > &opr1, const triple< T > &opr2)
template<typename T >
INLINE_FUNCTION iOstream & operator<< (iOstream &str, const triple< T > &ov)
template<typename T >
INLINE_FUNCTION iIstream & operator>> (iIstream &str, triple< T > &iv)
template<typename T >
INLINE_FUNCTION void readIstream (iIstream &str, triple< T > &iv)
Function Documentation
dot()
INLINE_FUNCTION_HD T dot (const triple< T > & oprnd1, const triple< T > & oprnd2)
cross()
INLINE_FUNCTION_HD triple<T> cross (const triple< T > & v1, const triple< T > & v2)
Referenced by pFlow::checkNormalVec(), Wall::checkTrianlge(), cylinder::isInside(), rotatingAxis::linTangentialVelocityPoint(), triWall::makeWall(), ppInteractionFunctor< ContactForceModel, ContactListType >::operator()(), pwInteractionFunctor< ContactForceModel, ContactListType, TraingleAccessor, MotionModel >::operator()(), pFlow::triangleFunctions::triangleSurface(), and stlFile::writeFacet().
length()
INLINE_FUNCTION_HD T length (const triple< T > & v1)
Referenced by pFlow::algorithms::binarySearch(), InsertionRegion< ShapeType >::checkForContact(), pFlow::checkNormalVec(), nonLinearMod< limited >::contactForce(), nonLinear< limited >::contactForce(), linear< limited >::contactForce(), pFlow::countChar(), positionRandom::inCollision(), zAxis::length(), line::length(), pLine::lineSphereCheck(), triWall::makeWall(), triple< intType >::normalize(), quadruple< T >::normalize(), ppInteractionFunctor< ContactForceModel, ContactListType >::operator()(), normalRolling< contactForceModel >::rollingFriction(), pFlow::sphereSphereCheck(), pFlow::triangleFunctions::triangleSurface(), and zAxis::zAxis().
normalize()
INLINE_FUNCTION_HD triple<T> normalize (const triple< T > & v1)
Referenced by line::unitVector().
operator+() [1/3]
INLINE_FUNCTION_HD triple<T> operator+ (const triple< T > & oprnd1, const triple< T > & oprnd2)
operator+() [2/3]
INLINE_FUNCTION_HD triple<T> operator+ (const triple< T > & oprnd1, const T & oprnd2)
operator+() [3/3]
INLINE_FUNCTION_HD triple<T> operator+ (const T & oprnd2, const triple< T > & oprnd1)
operator-() [1/3]
INLINE_FUNCTION_HD triple<T> operator- (const triple< T > & oprnd1, const triple< T > & oprnd2)
operator-() [2/3]
INLINE_FUNCTION_HD triple<T> operator- (const triple< T > & oprnd1, const T & oprnd2)
operator-() [3/3]
INLINE_FUNCTION_HD triple<T> operator- (const T & oprnd1, const triple< T > & oprnd2)
operator*() [1/3]
INLINE_FUNCTION_HD triple<T> operator* (const triple< T > & oprnd1, const triple< T > & oprnd2)
operator*() [2/3]
INLINE_FUNCTION_HD triple<T> operator* (const triple< T > & oprnd1, const T & oprnd2)
operator*() [3/3]
INLINE_FUNCTION_HD triple<T> operator* (const T & oprnd1, const triple< T > & oprnd2)
operator/() [1/3]
INLINE_FUNCTION_HD triple<T> operator/ (const triple< T > & oprnd1, const triple< T > & oprnd2)
operator/() [2/3]
INLINE_FUNCTION_HD triple<T> operator/ (const triple< T > & oprnd1, const T & oprnd2)
operator/() [3/3]
INLINE_FUNCTION_HD triple<T> operator/ (const T & oprnd1, const triple< T > & oprnd2)
operator==()
INLINE_FUNCTION_HD bool operator== (const triple< T > & opr1, const triple< T > & opr2)
operator>()
INLINE_FUNCTION_HD bool operator> (const triple< T > & opr1, const triple< T > & opr2)
operator<()
INLINE_FUNCTION_HD bool operator< (const triple< T > & opr1, const triple< T > & opr2)
operator<=()
INLINE_FUNCTION_HD bool operator<= (const triple< T > & opr1, const triple< T > & opr2)
operator>=()
INLINE_FUNCTION_HD bool operator>= (const triple< T > & opr1, const triple< T > & opr2)
operator<<()
INLINE_FUNCTION iOstream& operator<< (iOstream & str, const triple< T > & ov)
operator>>()
INLINE_FUNCTION iIstream& operator>> (iIstream & str, triple< T > & iv)
readIstream()
INLINE_FUNCTION void readIstream (iIstream & str, triple< T > & iv)