PhasicFlow: src/phasicFlow/containers/Vector/VectorFwd.hpp File Reference
VectorFwd.hpp File Reference
Functions
template<typename T , typename Allocator >
Vector< T, Allocator > operator+ (const Vector< T, Allocator > &op1, const T &op2)
template<typename T , typename Allocator >
Vector< T, Allocator > operator+ (const T &op1, const Vector< T, Allocator > &op2)
template<typename T , typename Allocator >
Vector< T, Allocator > operator+ (const Vector< T, Allocator > &op1, const Vector< T, Allocator > &op2)
template<typename T , typename Allocator >
Vector< T, Allocator > operator- (const Vector< T, Allocator > &op1, const T &op2)
template<typename T , typename Allocator >
Vector< T, Allocator > operator- (const T &op1, const Vector< T, Allocator > &op2)
template<typename T , typename Allocator >
Vector< T, Allocator > operator- (const Vector< T, Allocator > &op1, const Vector< T, Allocator > &op2)
template<typename T , typename Allocator >
Vector< T, Allocator > operator* (const Vector< T, Allocator > &op1, const T &op2)
template<typename T , typename Allocator >
Vector< T, Allocator > operator* (const T &op1, const Vector< T, Allocator > &op2)
template<typename T , typename Allocator >
Vector< T, Allocator > operator* (const Vector< T, Allocator > &op1, const Vector< T, Allocator > &op2)
template<typename T , typename Allocator >
Vector< T, Allocator > operator/ (const Vector< T, Allocator > &op1, const T &op2)
template<typename T , typename Allocator >
Vector< T, Allocator > operator/ (const T &op1, const Vector< T, Allocator > &op2)
template<typename T , typename Allocator >
Vector< T, Allocator > operator/ (const Vector< T, Allocator > &op1, const Vector< T, Allocator > &op2)
template<typename T , typename Allocator >
auto count (const Vector< T, Allocator > &vec, const T &val)
template<typename T , typename Allocator , typename UnaryPredicate >
auto count_if (const Vector< T, Allocator > &vec, UnaryPredicate p)
template<typename T , typename Allocator >
void fill_n (Vector< T, Allocator > &vec, size_t n, const T &val)
template<typename T , typename Allocator >
void fill (Vector< T, Allocator > &vec, const T &val)
template<typename T , typename Allocator >
void sort (Vector< T, Allocator > &vec)
Function Documentation
operator+() [1/3]
Vector<T, Allocator> operator+ (const Vector< T, Allocator > & op1, const T & op2) inline
operator+() [2/3]
Vector<T, Allocator> operator+ (const T & op1, const Vector< T, Allocator > & op2) inline
operator+() [3/3]
Vector<T, Allocator> operator+ (const Vector< T, Allocator > & op1, const Vector< T, Allocator > & op2) inline
operator-() [1/3]
Vector<T, Allocator> operator- (const Vector< T, Allocator > & op1, const T & op2) inline
operator-() [2/3]
Vector<T, Allocator> operator- (const T & op1, const Vector< T, Allocator > & op2) inline
operator-() [3/3]
Vector<T, Allocator> operator- (const Vector< T, Allocator > & op1, const Vector< T, Allocator > & op2) inline
operator*() [1/3]
Vector<T, Allocator> operator* (const Vector< T, Allocator > & op1, const T & op2) inline
operator*() [2/3]
Vector<T, Allocator> operator* (const T & op1, const Vector< T, Allocator > & op2) inline
operator*() [3/3]
Vector<T, Allocator> operator* (const Vector< T, Allocator > & op1, const Vector< T, Allocator > & op2) inline
operator/() [1/3]
Vector<T, Allocator> operator/ (const Vector< T, Allocator > & op1, const T & op2) inline
operator/() [2/3]
Vector<T, Allocator> operator/ (const T & op1, const Vector< T, Allocator > & op2) inline
operator/() [3/3]
Vector<T, Allocator> operator/ (const Vector< T, Allocator > & op1, const Vector< T, Allocator > & op2) inline
count()
auto count (const Vector< T, Allocator > & vec, const T & val) inline
Referenced by pFlow::count(), pFlow::countChar(), List< word >::countElement(), commandLine::parse(), intervalRange< T >::parseRange(), and stridedRange< real >::parseRange().
count_if()
auto count_if (const Vector< T, Allocator > & vec, UnaryPredicate p) inline
Referenced by pFlow::algorithms::STD::count(), and pFlow::count_if().
fill_n()
void fill_n (Vector< T, Allocator > & vec, size_t n, const T & val) inline
Referenced by pFlow::fill_n().
fill()
void fill (Vector< T, Allocator > & vec, const T & val) inline
Referenced by pFlow::fill(), pFlow::algorithms::STD::fill(), Vector< word, vecAllocator< word > >::fill(), pointField< T >::pointField(), and triSurfaceField< VectorField, T, MemorySpace >::triSurfaceField().
sort()
void sort (Vector< T, Allocator > & vec) inline
Referenced by Vector< word, vecAllocator< word > >::deleteElement(), multiRotatingAxisMotion::readDictionary(), pFlow::sort(), pFlow::algorithms::STD::sort(), and positionParticles::sortByMortonCode().